### ISSUE TITLE
Ready?

### ISSUE THREAD

**Issue by brettz9** [naptha/tesseract.js#1]
Hi,

Does "Nothing to see here" in your project description mean that your project is not ready yet? If not, will this be the correct repo to watch for a version of Tesseract that will work in the browser (via Emscripten)?

**Comment by bijection** [comment]
Yes it's not quite ready, and yes that's the correct repo.


Best,
Guillermo


---- On Fri, 14 Aug 2015 13:21:03 -0400 Brett Zamir &lt;notifications@github.com&gt; wrote ---- 

Hi,
 Does "Nothing to see here" in your project description mean that your project is not ready yet? If not, will this be the correct repo to watch for a version of Tesseract that will work in the browser (via Emscripten)?

**Comment by brettz9** [comment]
Thanks!
