### ISSUE TITLE
Cannot enlarge memory arrays error after trying to run recognize on a second image

### ISSUE THREAD

**Issue by davidworkman9** [naptha/tesseract.js#100]
This works great the first time a user uploads an image, but the second time on the same session, the following error is thrown:

```
Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 100663296, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
```

Even if I pick the same image twice in a row I get this error.

**Comment by ashokkumarjuly** [comment]
@davidworkman9, hi had you got any solution.

**Comment by davidworkman9** [comment]
@ashokkumarjuly unfortunately no, I never found a way around this.

**Comment by rmadisonhaynie** [comment]
Hello @ashokkumarjuly I am getting the same error for files that are too large. My main issue is this error doesn't get caught in the catch function. Should this be a separate issue?

@davidworkman9 do you mind sharing your work around?

**Comment by davidworkman9** [comment]
@rmadisonhaynie sorry if I wasn't clear, I never found a workaround for this. It was only for a pet project that I haven't worked on since I ran into this.

**Comment by ryanfb** [comment]
I ran into the same issue and found two ways around it.

1. The hard way: recompile https://github.com/naptha/tesseract-emscripten with `-s ALLOW_MEMORY_GROWTH=1` and use the resulting core for the `corePath` when initializing Tesseract.js (as described [here](https://github.com/naptha/tesseract.js#local-installation)). Unfortunately I wanted to use this on iOS devices and this allowed memory growth beyond what MobileSafari would support, so the resulting core would crash when trying to do recognition on mobile. Which lead me to...
2. The easy way: download the `dist` version of `worker.js` corresponding to your Tesseract.js version, e.g. https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/worker.js. Increase the `MIN_MEMORY` amount e.g. here: https://github.com/naptha/tesseract.js/blob/master/dist/worker.js#L8928. Use the resulting modified `worker.js` for the `workerPath` when initializing Tesseract.js (as described [here](https://github.com/naptha/tesseract.js#local-installation)). You may need to do a few rounds of this to experimentally determine what the minimum amount of memory you can get away with for a particular training file/image/browser is.

**Comment by yurymuski** [comment]
@ryanfb could you be more specific how to compile with '-s ALLOW_MEMORY_GROWTH=1' ?
CFLAGS="ALLOW_MEMORY_GROWTH=1" ./configure ?

**Comment by jeromewu** [comment]
ALLOW_MEMORY_GROWTH=1 is now added to the CMakeLists.txt (https://github.com/jeromewu/tesseract/blob/4.1.0-tesseract.js/CMakeLists.txt#L468), hope it helps.
