### ISSUE TITLE
Working with Tesseract.js with custom language and without internet connection

### ISSUE THREAD

**Issue by caspx** [naptha/tesseract.js#101]
Hey, 

Wonder if it's possible to use tesseract.js on a mobile app using a custom traineddata file? 
In addition, is it possible to use it offline? locally from the mobile device without an internet connection. 

Thanks.

**Comment by joarb** [comment]
I second that. Custom traineddata would be an awesome addition to a already great piece of software!

**Comment by tartinesKiller** [comment]
Actually this is already possible: [https://github.com/naptha/tesseract.js#langpath](url)

**Comment by evolutionxbox** [comment]
@tartinesKiller your URL is broken (the text is correct, but the href results in a 404).

Also I'm not really sure what your solution is...

**Comment by tartinesKiller** [comment]
The anchor have been renamed, here's the now-correct link : [https://github.com/naptha/tesseract.js#local-installation](url)

I'll explain here, in case it gets renamed once again:
You can override default values for the CDN of the language files, and so provide an URL to your own data. For example, in ASP.NET:
`window.Tesseract = Tesseract.create({
    langPath: "@(new Uri(Request.Url, Url.Content("~/tessdata/")))"
});`
which will be replaced in execution-time by:
`window.Tesseract = Tesseract.create({
    langPath: "http://localhost:50337/tessdata/"
});`
..where tessdata is a local directory which contains my custom trained data, in .gz format.

**Comment by krsyoung** [comment]
@caspx  did you end up getting this to work?  I'm stuck in the same situation for needing a local installation for a mobile (Cordova) app.

Any chance you can share how you referenced the the `workerPath`, `langPath`,  and `corePath`?

I'm trying this with no luck:
```
      let scanner = Tesseract.create({
        workerPath: '../../lib/worker.js',
        langPath: '../../lib/',
        corePath: '../../lib/tsseract-core.js'
      })
```

I've been trying to follow the [README](https://github.com/naptha/tesseract.js#local-installation) however haven't had any luck :(

**Comment by wideweide** [comment]
@tartinesKiller 
Hi,I want to use tesseract in node.js,just as a serviceto ocr the images,I am not sure how to  set the workerPath:nodejs\node_modules\tesseract.js\src\node\worker.js  ?
corePath:nodejs\node_modules\tesseract.js\src\node\index.js?
langPath:C:\Tesseract-OCR\tessdata\ -- I user 4.0,but truaned data is not .gz format ..,just eng.traineddata 

So how to use  locally?

**Comment by tartinesKiller** [comment]
Hello @wideweide, I've never worked with node.js, but I guess since workerPath and corePath points to the correct FILE, and that langPath points to the correct DIRECTORY, it'll be fine. In order to create a .gz version of the .traineddata, use this command:
On Linux: gzip <file.traineddata>
On Windows: download and install gzip from here: http://gnuwin32.sourceforge.net/packages/gzip.htm and then locate gzip.exe and: 
gzip.exe <file.traineddata>
(For windows, this is only a guess, can't check right now)

**Comment by wideweide** [comment]
@tartinesKiller thanks for reply

I put *.traineddata at test.js ,it will be worked fine

another question：https://github.com/naptha/tesseract.js/issues/133

**Comment by albertytau** [comment]
I have same challenge with @caspx @krsyoung  as I cannot refer those link in my cordova application. It works well without changing the default values, but it is so slow. I wonder I can improve the performance if I can place those files locally.

**Comment by katossi** [comment]
I have the same problem. Can someone explain how to use local languages in a node.js environment?

**Comment by KashifAhmed** [comment]
@krsyoung  
give path like this its work for me.
      workerPath: 'file:///android_asset/www/assets/tesseract/dist/worker.js',
      langPath: 'file:///android_asset/www/assets/tesseract/langs/eng.traineddata.gz',
      corePath: 'file:///android_asset/www/assets/tesseract/core/index.js'

**Comment by Joey-996** [comment]
> @krsyoung
> give path like this, its work for me.
> workerPath: 'file:///android_asset/www/assets/tesseract/dist/worker.js',
> langPath: 'file:///android_asset/www/assets/tesseract/langs/eng.traineddata.gz',
> corePath: 'file:///android_asset/www/assets/tesseract/core/index.js'

With Worker, you have to access remote links but not local ones.

**Comment by jeromewu** [comment]
Here is a full example for offline version: https://github.com/jeromewu/tesseract.js-offline

**Comment by fgroupindonesia** [comment]
> I have the same problem. Can someone explain how to use local languages in a node.js environment?

have you solved it out on nodejs?

**Comment by celesteMaciass** [comment]
Alguien sigue trabajando en esto? que me asesore
