### ISSUE TITLE
Kazakh language support

### ISSUE THREAD

**Issue by arsenanai** [naptha/tesseract.js#103]
Hello, how can I contribute and add Kazakh language support

**Comment by sanathko** [comment]
I would like to contribute and add support for sinhaleese language support.

**Comment by maxotov** [comment]
Hello! I would like contribute to Kazakh language support too. How can we do this?

**Comment by jeromewu** [comment]
Supported in tesseract.js v2 with language code `kaz`, feel free to try :smile:
