### ISSUE TITLE
Node v4.3 support for AWS Lambda

### ISSUE THREAD

**Issue by tetreault** [naptha/tesseract.js#105]
AWS lambda is pegged to Node v4.3 right now.

**Comment by antimatter15** [comment]
Does it not work on Lambdas currently?

**Comment by tetreault** [comment]
Correct, in the docs it says "Note: Tesseract.js currently requires node v6.8.0 or greater."

**Comment by ironprice91** [comment]
@tetreault  @antimatter15  - Looks like aws can use Node.js versions – v4.3.2 and 6.10 now

http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

**Comment by tetreault** [comment]
Awesome thanks for the update @ironprice91 !
