### ISSUE TITLE
add makebox flag?

### ISSUE THREAD

**Issue by michaelMinar** [naptha/tesseract.js#106]
Fantastic port and api for getting this up and running in the browser/worker. I was wondering if there was a way to produce the boxfile (for further refinement of tesseract's learned recognition). This can be useful when the auto training misses a few characters, or mislabels them.

cheers.

**Comment by jeromewu** [comment]
Not sure about the boxfile, but we do have bbox in the recognition result, you can check [official website](https://tesseract.projectnaptha.com/) for the demo.
