### ISSUE TITLE
Enforcing a pattern when applying OCR

### ISSUE THREAD

**Issue by seme1** [naptha/tesseract.js#108]
Is it possible to force a text pattern when performing OCR on an image? For example, if I want to scan an alphanumeric number that is always of fixed length (length is 15 alphanumeric characters) and the characters are always in capital (no small letter characters). Also, I know that some letters/numbers will never appear in the scanned text. 

This text also has a checkdigit which (through a math formula) can be used to tell whether it was read correctly.

What's the best way for feeding the above info to tesseract.js to allow for a potential higher accuracy ?

**Comment by bijection** [comment]
Have you checked out [the parameters page](https://github.com/naptha/tesseract.js/blob/master/docs/tesseract_parameters.md)?

In particular, tessedit_char_whitelist and tessedit_char_blacklist seem like they might do what you want. Hope this helps!

**Comment by seme1** [comment]
Thanks. I am actually using tessedit_char_whitelist and tessedit_dump_choices . However, the possible choices are provided per character and I have to build a list of possible terms by iterating through all of the provided choices and checking whether any of them is valid. No optimal, but it does the job for now. Accuracy is still far from good and I still need to figure out how it can be improved.
