### ISSUE TITLE
getting top N results with their confidence level

### ISSUE THREAD

**Issue by seme1** [naptha/tesseract.js#109]
Is it possible to get the top N results along with their confidence level ? In this way, I may be able to apply my verification algorithm on each of the top results one by one to select the correct one.

**Comment by antimatter15** [comment]
The results object provided includes all the available top choices that Tesseract emits and their associated confidence at the word and symbol level. If you head over to the demo page (http://tesseract.projectnaptha.com/) and open up your web inspector, you'll be able to play around with the results object.

Words and symbols have a `choices` field, which is an object containing the fields `text` and `confidence`.
