### ISSUE TITLE
How to determine Page segmentation method ?

### ISSUE THREAD

**Issue by seme1** [naptha/tesseract.js#111]
Using the tesseract command line in linux, one can do so with the -psm parameter. 
How to achieve the same with tesseract.js ?? I need to tell tesseract that the image contains only a fixed number of characters in a single word with no spaces.

Also, is there a way, method to tell tesseract that the number of characters is always fixed ??

**Comment by JulianKnodt** [comment]
![screen shot 2017-02-27 at 9 13 47 pm](https://cloud.githubusercontent.com/assets/7675847/23392597/b11cb0f6-fd31-11e6-90b3-809582fad61d.png)

Rather than input a number, I think you have to input the string like "auto+osd", but it doesn't seem to actually change the output. This is supposed to work, but I don't think it does.

**Comment by seme1** [comment]
Based on the provided description, the value for tessedit_pageseg_mode should be a digit. Also the default value is 6. However, it doesn't seem to work !! Perhaps a bug ?

**Comment by IllusionPerdu** [comment]
In function handleRecognize(req, res) `tesseract.js/src/common/worker.js` you can add base.SetPageSegMode(Module.PSM_...); after base.Init(null, req.options.lang); but it don't load the osd language file the segmode osd, auto+osd don't work the other it's seen to be good...
(sorry for my bad english)

**Comment by kayazinc** [comment]
It also seem to me the parameters pass in not working.  Anyone experiencing the same issue?
```
    const TesseractOptions = {
        lang: 'eng',
        tessedit_pageseg_mode: 3,
    }
...
    Tesseract.recognize(image, TesseractOptions)
```

**Comment by royjkim** [comment]
@kayazinc 
did you solve it ? 
I'm faced at same problem that parameters doesn't work.

**Comment by chadmwest** [comment]
This is particularly an issue when dealing with Asian characters. In the command-line version of Tesseract 3.04, I use -psm 10 for single character. Otherwise a single kanji may be recognized as multiple characters.

**Comment by chadmwest** [comment]
You have to put the number in quotation marks. However, it appears the documentation at [https://github.com/naptha/tesseract.js/blob/master/docs/tesseract_parameters.md](https://github.com/naptha/tesseract.js/blob/master/docs/tesseract_parameters.md) is incorrect for the parameter `tessedit_pageseg_mode`. 

The correct PSM values are numbers 1-10 at [the official Tesseract documentation](https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage) (the remaining three options on that page are Tesseract 4.0 options, but tesseract.js uses 3.04). For instance,`tessedit_pageseg_mode: '10',` actually maps to `SINGLE_CHAR`, not 7 (which is actually `SINGLE_LINE`) as stated in the docs here.

The following works for me to analyze a single character in Japanese:

```(JavaScript)
var myImage = document.getElementById('someImage');

Tesseract.recognize(myImage, {
    lang: 'jpn',
    tessedit_pageseg_mode: '10',
})
.then(function(result){
    console.log(result)
})
```

**Comment by koosg** [comment]
So, I understand you've got it to work?
I haven't. Whenever I set a mode which is not '6', tesseract.js abort's
Well, tested it a bit more... '10' apparently, it fails on 1-5. 
And I have a picture with columns (possibly)

> C:\code\code\kop\app\node_modules\tesseract.js-core\index.js:4
function f(a){throw a;}var h=void 0,i=!0,j=null,k=!1;function aa(){return function(){}}function ba(a){return function(){return a}}var n,Module;Module||(Module=eval("(function() { try { return TesseractCore || {} } catch(e) { return {} } })()"));var ca={},da;for(da in Module)Module.hasOwnProperty(da)&&(ca[da]=Module[da]);var ea=i,fa=!ea&&i;
              ^
abort() at Error
    at Na (C:\code\code\kop\app\node_modules\tesseract.js-core\index.js:32:26)
    at Object.ka [as abort] (C:\code\code\kop\app\node_modules\tesseract.js-core\index.js:507:108)
    at _abort (C:\code\code\kop\app\node_modules\tesseract.js-core\index.js:373:173)
    at VFa (C:\code\code\kop\app\node_modules\tesseract.js-core\index.js:396:63403)
    at Object.Lr [as _ptaDestroy] (C:\code\code\kop\app\node_modules\tesseract.js-core\index.js:384:100728)
    at DumpLiterallyEverything (C:\code\code\kop\app\node_modules\tesseract.js\src\common\dump.js:27:24)
    at C:\code\code\kop\app\node_modules\tesseract.js\src\common\worker.js:121:22
    at C:\code\code\kop\app\node_modules\tesseract.js\src\common\worker.js:92:9
    at C:\code\code\kop\app\node_modules\tesseract.js\src\node\lang.js:14:25
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by EvgenyKislyy** [comment]
Same for me
All the values of tessedit_pageseg_mode: '6' doesn't work

```
Error opening data file ./tessdata/osd.traineddata
index.js:10 Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
index.js:10 Failed loading language 'osd'
index.js:10 Tesseract couldn't load any languages!
index.js:10 Warning: Auto orientation and script detection requested, but osd language failed to load
```


```
{status: "recognizing text", progress: 0.9857142857142858}
demo-2.html:79 {status: "recognizing text", progress: 1}
index.js:8 Uncaught abort() at Error
    at Na (https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:36:26)
    at Object.ka [as abort] (https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:511:108)
    at _abort (https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:377:173)
    at VFa (https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:400:63403)
    at Lr (https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:388:100728)
    at DumpLiterallyEverything (http://127.0.0.1:7355/dist/worker.dev.js?nocache=v6d3kok0j:8661:24)
    at http://127.0.0.1:7355/dist/worker.dev.js?nocache=v6d3kok0j:8925:22
    at http://127.0.0.1:7355/dist/worker.dev.js?nocache=v6d3kok0j:8895:9
    at http://127.0.0.1:7355/dist/worker.dev.js?nocache=v6d3kok0j:8518:13
    at http://127.0.0.1:7355/dist/worker.dev.js?nocache=v6d3kok0j:2114:12
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by helensantosdesign** [comment]
+1

**Comment by jeromewu** [comment]
You can do it by using Worker.setParameters() in the latest version, please check here for details: https://github.com/naptha/tesseract.js/blob/master/docs/api.md#worker-set-parameters
