### ISSUE TITLE
[question] is there any way to identify and classify the scanned data?

### ISSUE THREAD

**Issue by jonathanpalma** [naptha/tesseract.js#112]
Hey everybody,

I would like to know if there is any way to do a natural language processing with the scanned data to identify and classify things as the name, surname, email, phone number, etc. 

I attached an image that I found on internet.

![image](https://cloud.githubusercontent.com/assets/12414771/23328565/e6e12072-fae9-11e6-99cf-e3ee0e3e387e.png)

In case it is necessary to use an extra library I would be grateful if you give me your recommendations to achieve what I comment.

Thank you

**Comment by bijection** [comment]
Unfortunately, tesseract.js only provides OCR, not natural language processing. If you're trying to detect if a string returned my tesseract.js is an address for example, the first thing you might try is a [regular expression](https://developer.mozilla.org/enUS/docs/Web/JavaScript/Guide/Regular_Expressions).

If that doesn't suit you needs, you might try googling around for javascript nlp libraries, or (shameless plug) you could try writing a natural language parser with the [Nearley.js Parser Generator](https://github.com/Hardmath123/nearley) using the [Nearley Parser Playground](omrelli.ug/nearley-playground/).

Good luck!
