### ISSUE TITLE
Which trainingdata-versions are supported?

### ISSUE THREAD

**Issue by joarb** [naptha/tesseract.js#113]
From the little experience I have with tesseract.js, it seems as though the default traineddata-format is compatible with tesseract 3.02. Can anyone confirm this? Does tesseract.js support other tesseract traineddata-formats?

**Comment by joarb** [comment]
Ok, so from my experiment, it seems as though it works with 3.04/3.05 traineddata-files. At least I get sensible results by hosting the language-appropriate [traineddata-file](https://github.com/tesseract-ocr/tessdata/tree/3.04.00). Just remeber to gzip the downloaded file first. I haven't had time to check 4.0-compatibility yet, but as far as I can understand, 4.0 is pretty different format and I suspect it won't work.

**Comment by jeromewu** [comment]
For tesseract.js v1, you can only use traineddata 3.04 as it is a port of tesseract-ocr v3.
And for tesseract.js v2, it is recommended to use traineddata 4.0 to get the best result, although it is possible to use 3.04, you may encounter some extra warning message or error.
