### ISSUE TITLE
How to stop the recognition process?

### ISSUE THREAD

**Issue by Dimatokis** [naptha/tesseract.js#116]
Sometimes it is necessary to stop recognition during protracted operations.
It would be very useful method ".stop" or ".cancel"

**Comment by ianrose14** [comment]
@Dimatokis https://github.com/naptha/tesseract.js/issues/93 seems to address this, although I don't fully understand it

**Comment by bowersj** [comment]
@Dimatokis I don't know if you're still interested but here's a solution I stumbled on to.

Disclaimer, I am still learning and there might be a  better approach but this is what worked for me.

Note: I am running on windows 7 node version 8.11.2

```javascript
const Tesseract = require('tesseract.js');

const imgPath = "D:\\some\\path\\to\\an\\image.PNG";

Tesseract.recognize( imgPath )
    .catch( err => console.error( err ) )
    .then( function( res ){ console.log( res ) } )
    .catch( err => console.error( err ) )
    .finally( msg => {
        // console.log( msg );
       Tesseract.terminate();
    });
```

The key is the `Tesseract.terminate();` statement on the finally event. 

Hope this helps.

On a side note, if anyone has a better approach, do share!

**Comment by jeromewu** [comment]
Close for now as no more replies.
