### ISSUE TITLE
What options can I change to improve the symbols recognition?

### ISSUE THREAD

**Issue by Vasile-Peste** [naptha/tesseract.js#117]
I am interested only in recognizing the alphabet symbols in a picture, what options can I change to improve this process?

**Comment by FlanGrande** [comment]
Maybe is too late for you.
You can use this:

var tesseractOptions = {
    tessedit_char_whitelist: "ABCDEFGHIJKLMNOPQRSTUVWYZ"
};

As far as I know, this is case sensitive (in case you want lowercase letters, add "abcd..." to the string above.
