### ISSUE TITLE
performance when recognize a few images

### ISSUE THREAD

**Issue by ZinkevychSergii** [naptha/tesseract.js#119]
hi. i have some issue with performance. below i provide timing when try to recognize 5 images
```javascript
    static ParseImage(image, options = {}) {
        console.time('parse image' + image)
        return Tesseract
                .recognize(image, options)
                .then(result => {
                    console.timeEnd('parse image' + image);
                    return result.text;
                })
    }
```

logs
```
parse image/home/incognito/projects/test/screenshots/1.png: 1845.146ms
parse image/home/incognito/projects/test/screenshots/2.png: 2723.008ms
parse image/home/incognito/projects/test/screenshots/3.png: 3267.928ms
parse image/home/incognito/projects/test/screenshots/4.png: 3719.227ms
parse image/home/incognito/projects/test/screenshots/5.png: 4148.500ms
```

if i will parse only the last images i got

```
parse image/home/incognito/projects/test/screenshots/5.png: 1721.617ms
```

**Comment by Sirvasile** [comment]
What is the size of these images? You can try to scale all the images before calling Tesseract.

**Comment by ZinkevychSergii** [comment]
actually different. the biggest one is about 350*100px and 24kb.
but i just wondering why if i run recognize only for one image (the last one) it's takes 1721ms. and if i run all of them, the same image recognize takes 4148.

if matter i run them via Promise.all

**Comment by jeromewu** [comment]
You can speed up using multiple workers, please check example here: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-multiple-workers-to-speed-up-200-beta1
