### ISSUE TITLE
Support real Promises

### ISSUE THREAD

**Issue by osdiab** [naptha/tesseract.js#120]
It seems that I can't use `async`/`await` with this library since it has it's own modified version of promises—it would be cool if `TesseractJob` extended `Promise` or maybe acted as a generator function in some form, though with the progress handlers it does seem a little tricky.

Some promise libs like when.js provide progress support for promises, so it's probably possible (without including that as a dep); but I'm not sure what a good form of that would look like for this library. I'll try some stuff in my own side project and read up on the topic :)

**Comment by peonmodel** [comment]
hi, just wanted to share my my very crude wrapper that uses web streams API that is compatible with async-await

https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream


```js
let tj = null;
    const tesseractStream = new ReadableStream({
      start(controller) {
        tj = Tesseract.recognize(canvas);
        tj.progress((p) => {
          controller.enqueue(p)
        });
        tj.then((p) => {
          controller.enqueue(p);
          controller.close();
        });
        tj.catch((p) => {
          controller.error(p);
        });
        tj.finally(() => {
          controller.close();
        });
      },
      pull(controller) {},
      cancel(reason) {}
    });

    const reader = tesseractStream.getReader();
    let done = false;
    let final = null;
    while (!done) {
      const result = await reader.read();
      done = result.done;
      console.log(result)
      if (done) { break; }
      final = result.value;
    }
    console.log('final', final)
```
the code can be cleaned up much more

**Comment by BigChief45** [comment]
This is greatly needed. Any plans for this?

**Comment by hammeiam** [comment]
Agreed that it's very confusing to try and chain the result of `.then()` and just have the original result returned to me.

**Comment by jeromewu** [comment]
In 2.0.0-beta.1, we totally support Promise (async/await) now! Close this issue.
