### ISSUE TITLE
Large image = hang

### ISSUE THREAD

**Issue by osdiab** [naptha/tesseract.js#121]
Node.js 6.4.0, tesseract.js 1.0.10

I tried testing this out to see what would happen with a relatively large image that didn't have text, and it just hung and didn't give any progress, error, or result.

The image in question is this:
![garlic_siracha](https://cloud.githubusercontent.com/assets/1890926/24972555/cfffee64-1f89-11e7-8cbb-d64f46a3c8df.png)

just hung forever. When I resized the image to be small then the process completed.

**Comment by jeromewu** [comment]
I just try it with the latest version, I think it won't hang in tesseract.js@2.0.0-beta.1, close for now.
