### ISSUE TITLE
Poor accuracy

### ISSUE THREAD

**Issue by alexlegg1992** [naptha/tesseract.js#125]
It failed to interpret size 12/14 text from a png. So I thought I'd take it to the extreme and test it on a much bigger font size and still it failed to interpret the letter M.

Please see screenshot http://imgur.com/a/TRHZQ

**Comment by jeromewu** [comment]
I think you can assign the part of image to recognize, that might help. See example here: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-only-part-of-the-image-200-beta1
