### ISSUE TITLE
Location to Save Training Data

### ISSUE THREAD

**Issue by slothropbodine** [naptha/tesseract.js#126]
I want to save the training data to the /tmp/ directory for use with aws lamda, is this possible?

**Comment by BigChief45** [comment]
You can save the training data to `/tmp/` but once the Lambda execution is finished, the data inside `/tmp/` is disposed.

**Comment by jeromewu** [comment]
Good answer :smile:

**Comment by laggingreflex** [comment]
Is it still possible to store it elsewhere? I want to store it somewhere other than current-dir. I have a cli-app that when run from different dirs it downloads the training data every time.

**Comment by timstrasser** [comment]
I'd be interested to know this as well.
