### ISSUE TITLE
Incorrect header check at Zlib._handle.onerror (zlib.js:363:17)

### ISSUE THREAD

**Issue by abhisheksett** [naptha/tesseract.js#130]
I'm trying to process an image which is saved locally in my node server. I'm getting following error:

> 2017-06-17T16:12:45.087797+00:00 app[web.1]: File write complete-- /app/sample.png
> 2017-06-17T16:12:46.065537+00:00 app[web.1]: pre-main prep time: 61 ms
> 2017-06-17T16:12:46.114192+00:00 app[web.1]: events.js:154
> 2017-06-17T16:12:46.114195+00:00 app[web.1]:       throw er; // Unhandled 'error' event
> 2017-06-17T16:12:46.114196+00:00 app[web.1]:       ^
> 2017-06-17T16:12:46.114197+00:00 app[web.1]: 
> 2017-06-17T16:12:46.114198+00:00 app[web.1]: Error: incorrect header check
> 2017-06-17T16:12:46.114201+00:00 app[web.1]:     at Zlib._handle.onerror (zlib.js:363:17)

Here is my code:

```
Tesseract.recognize(completeFilePath)
   .then(function(data) {
   		console.log('Job completed');
   	})
   	.catch(function(err){
        console.log('catch\n', err);
     })
   	.finally(function(e){
        console.log('Finally');
        //cleanup temp file
     });
```

**Comment by 6160** [comment]
i've got the same problem when i try to set a language.

this is my code:
`Tesseract.recognize(myImage,{lang: 'ita'})
    .progress(message => console.log(message))
    .catch(err => console.error(err))
    .then(result => console.log(result))
    .finally(resultOrError => console.log(resultOrError))`

**Comment by abhisheksett** [comment]
I'm facing the issue without using language option as well.

**Comment by robomotic** [comment]
This happens to me as well but only in a Heroku app container (it works fine when I run it locally):

2017-07-23T13:34:23.587299+00:00 app[web.1]: { status: 'loading tesseract core' }
2017-07-23T13:34:23.954816+00:00 app[web.1]: { status: 'loaded tesseract core' }
2017-07-23T13:34:23.955561+00:00 app[web.1]: { status: 'initializing tesseract', progress: 0 }
2017-07-23T13:34:24.483124+00:00 app[web.1]: pre-main prep time: 78 ms
2017-07-23T13:34:24.487849+00:00 app[web.1]: { status: 'initializing tesseract', progress: 1 }
2017-07-23T13:34:24.804306+00:00 app[web.1]: { status: 'downloading eng.traineddata.gz',
2017-07-23T13:34:24.804320+00:00 app[web.1]:   loaded: 116,
2017-07-23T13:34:24.804321+00:00 app[web.1]:   progress: 0.000012270517521770119 }
2017-07-23T13:34:24.809222+00:00 app[web.1]: events.js:160
2017-07-23T13:34:24.809224+00:00 app[web.1]:       throw er; // Unhandled 'error' event

**Comment by robomotic** [comment]
Is there a way to pass the path to the eng.trainneddata.gz? I am wondering if somehow the file doesn't get downloaded fully and then it attempts to extract.

**Comment by agentcooper** [comment]
Had the same problem, solved by manually downloading [`eng.traineddata`](https://github.com/tesseract-ocr/tessdata/blob/master/eng.traineddata).

**Comment by robomotic** [comment]
Cool where do I put it though? I don't see any info for the NPM version where is the default data dict?

**Comment by agentcooper** [comment]
@robomotic for me it the same directory where my `index.js` is:

```
.
├── eng.traineddata
├── images
├── index.js
├── node_modules
├── ocr.js
├── package-lock.json
└── package.json
```

**Comment by mikewesthad** [comment]
Re: local paths - looks like there are a couple issues open related to that. Cross referencing: #136 where a similar solution came up, but with the option of placing the local files anywhere.

**Comment by katossi** [comment]
I have the same problem. Tesseractjs is useless in node.js until this issue is solved

**Comment by BigChief45** [comment]
Still experiencing this issue...

**Comment by noor92** [comment]
I am also experiencing the same issue

**Comment by Jo-ravar** [comment]
Experiencing the same issue.

**Comment by NoobDoesMC** [comment]
I got this right now:

```js
const Jimp = require('jimp');
const Tesseract = require('tesseract.js');

function pullText(url, callback) {
  Jimp.read(url)
  .then(image => {
    image.getBuffer(Jimp.MIME_PNG, (err, data) => {
      if (err) return callback(err);

      Tesseract.recognize(data, {
        lang: 'eng'
      })
      .then(result => {
        callback(null, result);
      })
      .catch(err => callback(err));
    });
  })
  .catch(err => callback(err));
};

const url = 'https://cdn.discordapp.com/attachments/401856302290042883/401892405365964801/Screen_Shot_2018-01-13_at_16.51.06.png';

pullText(url, (err, result) => {
  if (err) throw err;

  console.log(result);
});
```

above code errors for me with 

```
Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:355:17)
```

**Comment by NoobDoesMC** [comment]
I get this error with online urls

**Comment by colshacol** [comment]
I was able to fix this issue by downloading [eng.traineddata](https://github.com/tesseract-ocr/tessdata/blob/master/eng.traineddata) and placing it in my root directory.

![fixx](https://user-images.githubusercontent.com/19484365/35189011-902baff0-fe07-11e7-8d2b-ea488597a3c8.PNG)

**Comment by NoobDoesMC** [comment]
me too ^^

**Comment by tborychowski** [comment]
works for me only when I run `node ./index.js` (in the same directory).
If I run the script from a different path - the error still occurs.
