### ISSUE TITLE
Zonal OCR

### ISSUE THREAD

**Issue by w32gold** [naptha/tesseract.js#131]
Hi,
How do I OCR a specific region of the image?
Thanks.

**Comment by jarodium** [comment]
You can try pre-processing the image with imagemagick for example before feeding it to tesseract.

**Comment by NeboSky42** [comment]
Is there any way to use uzn file? 
https://github.com/OpenGreekAndLatin/greek-dev/wiki/uzn-format

**Comment by jeromewu** [comment]
Please check here for example of recognizing part of image: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-only-part-of-the-image-200-beta1
