### ISSUE TITLE
tesseract-core not found

### ISSUE THREAD

**Issue by crazylxr** [naptha/tesseract.js#132]
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src='https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js'></script>

  </head>
  <body>
    <img style='width:100px' id='img' src="./img/timg.jpeg" alt="">
    <script type="text/javascript">
    window.onload = function(){
      var img = document.getElementById('img');
      console.log(img.naturalWidth);
          Tesseract.recognize(img,{
            lang:'chi_sim'
          }).then((res)=>{
            console.log(res);
          }).catch((err)=>{
            console.log(err);
          })
    }
    </script>
  </body>
</html>

```
I am a Chinese ,my English is poor . 
this is my code,when i run my code in nginx ,running in chrome,but this is a error .

GET https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js net::ERR_CONNECTION_TIMED_OUT

worker.js:8474 Uncaught DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': DOMException object could not be cloned.

**Comment by titan52** [comment]
in local
u can use # npm install
in the node_modules/tesseract.js-core/
