### ISSUE TITLE
how to use more than one languange?

### ISSUE THREAD

**Issue by wideweide** [naptha/tesseract.js#133]
In commandline: tesseract test2.jpg  -l eng+chi_sim out pdf
But in .js: Tesseract.recognize(image, {lang:'chi_sim+eng',out:'pdf'})  --- seems wrong...

btw: tesseract  seems too slow than abbyy finereader ?
One A4 paper: tesseract needs 20s to out pdf --- chinese words

**Comment by jeromewu** [comment]
Please check example here for using multiple languages: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-multiple-languages-separate-by-
