### ISSUE TITLE
What is your default settings for Tesseract

### ISSUE THREAD

**Issue by korcanergun** [naptha/tesseract.js#137]
Hi,

When i tried to recognize this image 
![temp_no](https://user-images.githubusercontent.com/3787276/28503364-d81b37e6-700d-11e7-9200-0d67f7e66c3b.png)

Tesseract never recognizes. I almost tried everything. In some settings some digits works but others are not. (btw maximum 2 digit images in same resolution)

But when i upload this image to tesseract.js demo page it recognizes immediatly. Can you tell us which command line options you are using ? Because whenever tesseract command line not recognized, your system recognizes them all. For that reason can you give me your default options ?

Best,
Korcan

**Comment by judenaveenraj** [comment]
Same here, can we have the default settings you guys use for the demo?

**Comment by mikewesthad** [comment]
@korcanergun, this works for me on my node setup using the default settings. How are you loading the image? Is the code erroring out? For the latter, you might want to look at #136

**Comment by Hedva** [comment]
```
Tesseract.recognize(image, {
            lang: 'eng',
            tessedit_char_whitelist: '0123456789'
          })
```

should do the trick if you only want to recognize 0-9.
However; the better the resolution, the better results you get.
