### ISSUE TITLE
spatial information of recognised text

### ISSUE THREAD

**Issue by peonmodel** [naptha/tesseract.js#143]
does tesseract return the position of the recognised text relative to the image? it will be essential to do some sort of text overlay for the image

**Comment by deejbee** [comment]
I believe so.  When you call Tesseract.recognise() it returns a huge amount of data when it has finished.  Look for the bbox (bounding box) fields for each recognised object,  it has 4 fields (x0,y0,x1,y1) that relate to the pixel positions.

**Comment by jeromewu** [comment]
Yes, bbox is the information you need.
