### ISSUE TITLE
Browser-end Tesseract couldn't load 

### ISSUE THREAD

**Issue by albertytau** [naptha/tesseract.js#144]
I would like to use Tesseract.js on my cordova app. It works well with the online / default options to create the Tesseract. However, in order improve the speed, payload, we would like to store the core-js / worker.js and the traineddata locally on the device.

core/index.js is referring tesseract-core.js
langs is the folder to store both zip and unzip eng.traineddata

According to the console, the eng.traineddata is loaded ... but language 'eng' cannot be loaded in the api initialization which it can not perform text recognition.

Here is my code

    var tesspath = (function() { //absolute path
    var pathArray = window.location.pathname.split( '/' );
    pathArray.pop(); //Remove the last ("**.html")
    return window.location.origin + pathArray.join("/");
    })();    
    
    $scope.tesseract_defaultOptions = {
    workerPath: 'https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/worker.js',
    langPath: 'https://cdn.rawgit.com/naptha/tessdata/gh-pages/3.02/',
    corePath: 'https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js'     
    };
    
    $scope.tesseract_offlineOptions = {
    workerPath: tesspath + '/lib/tesseract.js-master/dist/worker.js',
    langPath: tesspath + '/lib/tesseract.js-master/langs/',
    corePath: tesspath + '/lib/tesseract.js-master/core/index.js',
    }; 

        window.Tesseract = Tesseract.create($scope.tesseract_offlineOptions);     
        
        Tesseract.recognize(imageData, {
            lang: "eng"
        }).progress(function  (p) {
            console.log('progress', p);
            $scope.ocr_percent = $scope.completeness(p.progress);
            $scope.ocr_result = p.status;
        })
        .then(function (result) {
            console.log('result', result);
            $scope.ocr_result = result.text;
            $scope.ocr_confidence = result.confidence;
            $scope.toLUIS();
        });

<img width="1001" alt="screen shot 2017-08-15 at 11 47 06 pm" src="https://user-images.githubusercontent.com/6008471/29324548-048cdc42-8217-11e7-844e-813b3dfa18cb.png">
<img width="999" alt="screen shot 2017-08-15 at 11 46 39 pm" src="https://user-images.githubusercontent.com/6008471/29324549-0490012e-8217-11e7-811d-697105445510.png">

**Comment by sabanad** [comment]
How can I install Tesseract.js in my ionic v1 project?

**Comment by jeromewu** [comment]
Sorry Cordova is not supported so far.
