### ISSUE TITLE
Portuguese Brazil

### ISSUE THREAD

**Issue by gabrielcantarin** [naptha/tesseract.js#145]
How can I help you improving it to Portuguese Brazil? What can I do?

**Comment by isaacguerreir** [comment]
I don't know exactly if you already tested this possibilite, but you can change the language supported by default (english, in that case) to portuguese using:

`Tesseract.recognize(img, { lang: 'por' })
    .then(yourfunction)`

**Comment by jeromewu** [comment]
Good answer :smile:
