### ISSUE TITLE
Uncaught abort() Error displays when using Arabic language  

### ISSUE THREAD

**Issue by abutalal93** [naptha/tesseract.js#146]
unable to recognition Arabic characters 
![image](https://user-images.githubusercontent.com/26893368/29741903-53a9320c-8a7e-11e7-9e34-26f19e85ad6e.png)

**Comment by valerius21** [comment]
You'll have to change the CDN-URIs in the tesseract.js component. That can be achieved by either changing the URIs to raw git URLs or by hosting them on your own.

**Comment by jeromewu** [comment]
Yes, that should be the CDN issue, you can try it again with the latest version.
