### ISSUE TITLE
Failed loading language 'eng'

### ISSUE THREAD

**Issue by frontalnh** [naptha/tesseract.js#147]
because i couldn't get traineddate from cdn 
l downloaded data in my repository and tried to load it
but failed...

i used langPath to load from my local storage and i don't know why

this is my javascript code
```
var Tesseract = require('tesseract.js')
  const path = require("path");
  var imagePath= path.join(__dirname,"jake.jpg");

  Tesseract.create({
    langPath: path.join(__dirname, "langs")
  }).recognize(imagePath, {lang: "eng"}) 
      .then((result) => console.log(result.text));
```
my traineddata is in 'langs' folder which is in the same repository with javascript file

![image](https://user-images.githubusercontent.com/25814035/29999898-ba997fce-9093-11e7-8183-52a32ff7a686.png)
and lang folder is in the same repository with javascript file above.

**Comment by ForcedUnknown** [comment]
@frontalnh you should check out https://github.com/naptha/tesseract.js/issues/136

It solved the problem for me.

**Comment by jjyyxx** [comment]
Faced with the problem too

**Comment by FlorianKoerner** [comment]
Same issue here.

**Comment by Superpencil** [comment]
Use the master branch.

**Comment by fsiaonma** [comment]
Faced with the problem too

**Comment by Hedva** [comment]
Same problem

**Comment by NoobDoesMC** [comment]
I just did `npm install --save tesseract.js`

Now every time I try to use tesseract I get

```
Failed loading language 'eng'
Tesseract couldn't load any languages!
AdaptedTemplates != NULL:Error:Assert failed:in file ../classify/adaptmatch.cpp, line 190
```

Even though `tesseract` command works at command line

**Comment by NoobDoesMC** [comment]
@Hedva where are you meant to put the language files?

**Comment by Hedva** [comment]
You can put the language files where ever you want. As long you refer to them. In your example you used `langPath: path.join(__dirname, "langs")`. In this case I you need to put them in a folder called 'langs' in your dir. You can get the language files [here](https://github.com/naptha/tessdata/tree/gh-pages/3.02).

If you know what language the image contains, you can set which specific language and black/whitelist characters. [Here](https://github.com/naptha/tesseract.js/blob/master/docs/tesseract_parameters.md) is a list of parameters

```
Tesseract.recognize(myImage, {
    lang: 'eng',
    tessedit_char_blacklist: '0123456789!?',
    tessedit_char_whitelist: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
})
.then(function(result){
    console.log(result)
})
```

**Comment by HasanAliKaraca** [comment]
Running a simple code and having same problem in node / express.
In a new express project, in app.js:

var Tesseract = require('tesseract.js')

Tesseract.recognize("test.png")
  .progress(message => console.log(message))
  .catch(err => console.error(err))
  .then(result => console.log(result))
  .finally(resultOrError => console.log(resultOrError));

**Comment by Nassiesde** [comment]
I've got the same problem.
 has someone a solution?

**Comment by joel99** [comment]
Hi guys,
Ran into the same issue, the problem for me was a corrupted `eng.traineddata`. Try extracting a zip, the ones mentioned by Hedva hosted [here](https://github.com/naptha/tessdata/tree/gh-pages/3.02) worked for me.

**Comment by jeromewu** [comment]
More like network issue, please also check here for offline setup: https://github.com/jeromewu/tesseract.js-offline
