### ISSUE TITLE
Too slow 20.9 seconds end to end

### ISSUE THREAD

**Issue by thatsmekaustubh** [naptha/tesseract.js#148]
Hi I am new to tesseract and just have implemented a small demonstration about its features for an internal discussion with colleagues. So far only one concern is bothering me, that

From the time i call tesseract.recognize till its ocr is completed it has taken me approx 18-21 seconds everytime.

Is there any possible way or reference i am missing out in order to optimize this timing.
I have been going through many issues in other tesseract repo as well. Some have reported the result timing as low as 3 seconds.

Help is appreciated. 
Ty

**Comment by mtford90** [comment]
Agreed

On my machine:

- 10 images using `tesseract.js`: 471.671 seconds
- Same 10 images using `node-tesseract`: 19.909 seconds

If it's this slow on node on pumped up macbook pro, I can only assume it will be super painful in the browser and on mobile devices e.g. with react native. Shame as I was hoping to save some cash by offsetting OCR onto the client ;)

**Comment by thatsmekaustubh** [comment]
@mtford90 agreed 

Will updated my result again after testing latest release if there are any performance changes

**Comment by jeromewu** [comment]
JavaScript has its limit and node-tesseract is actually using the C version to complete the task. I think it is normal to take more time in tesseract.js comparing the the native one.
