### ISSUE TITLE
How to recognize tables content?

### ISSUE THREAD

**Issue by tradescantia** [naptha/tesseract.js#150]
I would like extract text from a table, but with this code it doesn't work.

function runOCR(myImage) {
                Tesseract.recognize(myImage, {
                    // english traindata
                    lang: 'eng'
                })
                    .then(function(result) {
                       document.getElementById("ocr_results")
                        .innerText = result.text;
                    }) 
                    .progress(function(result) {
                        document.getElementById("ocr_status")
                                .innerText = result["status"] + " (" +
                                    (result["progress"] * 100) + "%)";
                    })
                    .finally(resultOrError => console.log(resultOrError));
            }
            document.getElementById("go_button")
            .addEventListener("click", function(e) {
                var myImage = document.getElementById("myImage").src;
                runOCR(myImage);
            });

Do you have any hints?

**Comment by alicantutumlu** [comment]
Same issue that I have. Any recommendation?

**Comment by jeromewu** [comment]
Close for now, feel free to reopen with sample images, thanks.
