### ISSUE TITLE
Wrong recognition in case of words containing both characters and digits.

### ISSUE THREAD

**Issue by avi9839** [naptha/tesseract.js#151]
I have been trying to recognize sample data containing words which is mixture of characters and digits.
Unfortunately in some cases characters are getting converted to digits.
Example:

![download 26](https://user-images.githubusercontent.com/7263446/30594171-bfbf2e34-9d6a-11e7-9116-e3f409d4217a.png)
Output for this image : '83b'
In the above image attached 'S' is getting recognized to  '8'.
Similarily in some cases '2' gets recognized as 'Z'.
But passing individual characters works fine.
I guess this might happen because of following issues.
Dictionary word match in postprocessing step by tesseract So i tried to disable dictionary model use and other parameters as shown below but it did not work for me.

              Tesseract.recognize(imgforocr,{
			    tessedit_enable_doc_dict : 0,
			    load_system_dawg : 0,
			    load_freq_dawg : 0,
			   load_punc_dawg : 0,	
		    }).then(function(result){
		         console.log(result);
	            });

Am i using wrong parameters in here or Is there any other way to resolve this issue?

**Comment by jeromewu** [comment]
In the latest version (2.0.0-beta.1), the recognition is correct, please try and feel free to reopen with more information.
