### ISSUE TITLE
How to initialize without image analysis?

### ISSUE THREAD

**Issue by thEpisode** [naptha/tesseract.js#152]
Hi, first of all, this library is amazing!

I'm developing an app with Ionic 3.x and works perfectly, but how to load languages, API, an so on without image analysis? because my users needs to take a photo with camera and start analyze it. The idea is load Tesseract API before user take a photo. Is possible?

**Comment by magorismagor** [comment]
Hi thEpisode, 

have you find out how to initialize Tesseract.js?

**Comment by thEpisode** [comment]
Nope

**Comment by sabanad** [comment]
Hi thEpisode

how did you add this lib in your ionic project? I have a similar requirement but ionic v1 project.

**Comment by jeromewu** [comment]
In 2.0.0-beta.1, it is now possible to initialize tesseract.js without analysis, please check documents for more details.
