### ISSUE TITLE
AdaptedTemplates != NULL:Error

### ISSUE THREAD

**Issue by ganny26** [naptha/tesseract.js#153]
@zenners @hidace @kostasx @Hedva @mtford90 
Getting error **AdaptedTemplates != NULL:Error:Assert failed:in file ../classify/adaptmatch.cpp, line 190**
even after configuring language data and core path

**To reproduce error :**
λ node -v
v6.9.0
Tesseract Version: "tesseract.js": "^1.0.10"

**Code Snippet:**
`var Tesseract = require('tesseract.js');
var image = require('path').resolve(__dirname, 'cosmic.png');
console.log(image);
Tesseract.create({
    langPath: 'https://cdn.rawgit.com/naptha/tessdata/gh-pages/3.02/',
    corePath: 'https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js',
}).recognize(image, {
        lang: 'eng'
    })
    .then(data => {
        console.log('then\n', data.text)
    })
    .catch(err => {
        console.log('catch\n', err);
    })
    .finally(e => {
        console.log('finally\n');
        process.exit();
    });
`

pre-main prep time: 74 ms
Failed loading language 'eng'
Tesseract couldn't load any languages!
AdaptedTemplates != NULL:Error:Assert failed:in file ../classify/adaptmatch.cpp, line 190

D:\Work\mail-example\node_modules\tesseract.js-core\index.js:4
function f(a){throw a;}var h=void 0,i=!0,j=null,k=!1;function aa(){return function(){}}function ba(a){return function(){return a}}var n,Module;Module||(Module=eval("(function() { try { return TesseractCore || {} } catch(e) { return {} } })()"));var ca={},da;for(da in Module)Module.hasOwnProperty(da)&&(ca[da]=Module[da]);var ea=i,fa=!ea&&i;
              ^
abort() at Error
    at Error (native)
    at Na (D:\Work\mail-example\node_modules\tesseract.js-core\index.js:32:26)
    at Object.ka [as abort] (D:\Work\mail-example\node_modules\tesseract.js-core\index.js:507:108)
    at _abort (D:\Work\mail-example\node_modules\tesseract.js-core\index.js:373:173)
    at $L (D:\Work\mail-example\node_modules\tesseract.js-core\index.js:383:55709)
    at jpa (D:\Work\mail-example\node_modules\tesseract.js-core\index.js:388:22274)
    at lT (D:\Work\mail-example\node_modules\tesseract.js-core\index.js:387:80568)
    at mT (D:\Work\mail-example\node_modules\tesseract.js-core\index.js:387:80700)
    at Array.BS (D:\Work\mail-example\node_modules\tesseract.js-core\index.js:387:69011)
    at bP (D:\Work\mail-example\node_modules\tesseract.js-core\index.js:383:110121)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by zenners** [comment]
+1 getting the same error on 
node 6.11.3
tesseract.js 1.0.10

**Comment by hidace** [comment]
Hi, also getting the same error. I'm on:

tesseract.js: 1.0.10
Node: 8.1.2

**Comment by kostasx** [comment]
+1 getting the same error on
node v7.7.1
tesseract.js 1.0.10

**Comment by Hedva** [comment]
I got the same problem. 

node v9.0.0
tesseract.js 1.0.10

**Comment by mtford90** [comment]
Same error

node v8.7.0
tesseract.js 1.0.10

**Comment by Hedva** [comment]
@mtford90 please check here for a solution:
https://github.com/naptha/tesseract.js/issues/164#issuecomment-345984952

**Comment by standayweb** [comment]
+1 getting the same error on
node v8.9.1
tesseract.js 1.0.10

**Comment by bonzinho** [comment]
+1 getting the same error on
node v8.9.1
tesseract.js 1.0.10

**Comment by webbuilderkel** [comment]
+1. I also got this error. node -v 6.11.0

**Comment by jeromewu** [comment]
Please try 2.0.0-beta.1 to see if it works, feel free to reopen with more information.
