### ISSUE TITLE
Can I Use this component offline?

### ISSUE THREAD

**Issue by bay1ts** [naptha/tesseract.js#155]
can I use this as a offline service?for example :workerPath,langPath,etc. Use a local js worker and core,then download all lang resource from 'https://cdn.rawgit.com/naptha/tessdata/gh-pages/3.02/' .can this work? can this work well with tesseract-ocr/tesseract 's tranied language data?

**Comment by yorrd** [comment]
I think if you apply [this](https://github.com/naptha/tesseract.js#local-installation) and change the path to a local one, it should work. of course you'll have to download all the files. Disclaimer: Haven't tried

**Comment by bay1ts** [comment]
sorry for bothering,in China,I can't access this site:'https://cdn.rawgit.com/naptha/tessdata/gh-pages/3.02/'.Can I use https://github.com/tesseract-ocr/tessdata  instead？

**Comment by mtaa** [comment]
@bay1ts 
```
const path = require('path');

let tesseract = Tesseract.create({
  workerPath: 'file://' + path.join(__dirname, './tesseract/worker.js'),
  langPath: 'file://' + path.join(__dirname, './tesseract/langs/'),
  corePath: 'file://' + path.join(__dirname, './tesseract/core.js')
});
```

**Comment by jeromewu** [comment]
Please here for local installation: https://github.com/naptha/tesseract.js/blob/master/docs/local-installation.md
