### ISSUE TITLE
Exception executing file_input/basic in Chrome 61 on Windows (works in Firefox)

### ISSUE THREAD

**Issue by LO-RAN** [naptha/tesseract.js#157]
worker.js:8474 Uncaught DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': DOMException object could not be cloned.
    at https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/worker.js:8474:16
    at Object.respond (https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/worker.js:8706:9)
    at Object.dispatchHandlers (https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/worker.js:8726:17)
    at https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/worker.js:8473:17

**Comment by leaving123** [comment]
I met the same problem as you. How did you deal with it?

**Comment by jeromewu** [comment]
Please try again with the latest version (2.0.0-beta.1), feel free to reopen with more information, thanks.
