### ISSUE TITLE
Use tesseract.js in node to report an error

### ISSUE THREAD

**Issue by messi1991** [naptha/tesseract.js#160]
pre-main prep time: 74 ms
events.js:182
  throw er; // Unhandled 'error' event
  ^
Error: connect ETIMEDOUT 31.13.85.1:80
  at Object.exports._errnoException (util.js:1024:11)
  at exports._exceptionWithHostPort (util.js:1047:20)
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)

**Comment by BigChief45** [comment]
Having the same issue. Any ideas...?

**Comment by andrew0213** [comment]
Me too,How to solve this ?

**Comment by MagnifierSun** [comment]
the same issue with me ...

**Comment by samcsf** [comment]
I met the same issue today, any one can help? thanks.

**Comment by zhouzhili** [comment]
me too, How to solve this?

**Comment by hezhii** [comment]
+1

**Comment by OPY-bbt** [comment]
+1

**Comment by jeromewu** [comment]
In 2.0.0-beta.1, this issue should be fixed. Close for now, feel free to reopen if needed.
