### ISSUE TITLE
Tesseract process not ending

### ISSUE THREAD

**Issue by wlwl2** [naptha/tesseract.js#161]
Hi,

I was wondering if this is normal and the reason behind this. I have to press ctrl-c twice to end the process on Windows 10. I ran `node this-file.js`. The english training data and `myImage.png` is in the same folder as `this-file.js`. I would think that once the entire job is done, the process can end?

Contents of `this-file.js`:

```
var Tesseract = require('tesseract.js')
var image = 'myImage.png'
Tesseract.recognize(image)
  .progress(function (p) { console.log('progress', p) })
  .then(function (result) { console.log(result) })
```

**Comment by BigChief45** [comment]
See #88

**Comment by updesktop** [comment]
it's really frustrating. how to stop it? I'm going back to ocrad!
