### ISSUE TITLE
module is not defined could not be cloned.

### ISSUE THREAD

**Issue by dawning321** [naptha/tesseract.js#162]
Hi. this is my error:
worker.js:8664 Uncaught DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': Error: Uncaught ReferenceError: module is not defined could not be cloned.
    at http://localhost:7355/dist/worker.js:8664:16
    at Object.respond (http://localhost:7355/dist/worker.js:8898:9)
    at Object.dispatchHandlers (http://localhost:7355/dist/worker.js:8918:17)
    at http://localhost:7355/dist/worker.js:8663:17

**Comment by leaving123** [comment]
Local Installation.
this is my codes：

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <script src="/dist/tesseract.dev.js"></script>
    <script type="text/javascript">
        function road() {
            tesseract = Tesseract.create({
                workerPath: 'http://localhost:7355/dist/worker.js',
                langPath: 'http://localhost:7355/tessdata/gh-pages/3.02/',
                corePath: 'http://localhost:7355/node_modules/_tesseract.js-core@1.0.2@tesseract.js-core/index.js',
            })    
           tesseract.recognize('http://localhost:7355/dist/pic.jpg')       
        }
    </script>
</head>
<body>
<img id='img' src="http://localhost:7355/dist/pic.jpg" alt="">
<button onclick="road()">click me!</button>
</body>
</html>

And all the Status of Network are 200.

**Comment by arthurdayton116** [comment]
change tesseract = Tesseract.create... too tesseract2 = Tesseract.create(

**Comment by HuubSmit** [comment]
> I was having same problem trying to use local and browserify.
> 
> I couldn't get this to ever reference local code -
> Tesseract.create({
> workerPath: './dist/worker.js',
> langPath: 'http://localhost:3000/',
> corePath: 'http://localhost:3000/tesseract.js-core/index.js',
> })
> 
> So I tried changing the default settings,which got it pointing to the right stuff but gave me the same error you have -
> (function (process){
> var defaultOptions = {
> // workerPath: 'https://cdn.rawgit.com/naptha/tesseract.js/0.2.0/dist/worker.js',
> // corePath: 'https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js',
> // langPath: 'https://cdn.rawgit.com/naptha/tessdata/gh-pages/3.02/',
> corePath: 'http://localhost:3000/tesseract.js-core/index.js',
> langPath: 'http://localhost:3000/',
> 
> }
> 
> if (process.env.NODE_ENV === "development") {
> console.debug('Using Development Configuration')
> defaultOptions.workerPath = location.protocol + '//' + location.host + '/dist/worker.dev.js?nocache=' + Math.random().toString(36).slice(3)
> }else{
> var version = require('../../package.json').version;
> defaultOptions.workerPath = 'http://localhost:3000/tesseract.js/dist/worker.js'
> }
> 
> So then I downloaded the index.js file from https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js and replaced version from git and it worked for me.
> 
> -Hope it helps

I am using this is well but it seems to me that the local urls are getting ignored this way... I have the traineddata locally but it seems to not work.. IT doesn't load it locally.

**Comment by jeromewu** [comment]
Please check here for [local-installation](https://github.com/naptha/tesseract.js/blob/master/docs/local-installation.md), feel free to reopen with more information.
