### ISSUE TITLE
Unable to determine the domain name

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [naptha/tesseract.js#164]
Hello.

I have just installed this lib and wrote code like this:

    const Tesseract = require('tesseract.js').create({
        langPath: './data/3.02/',
        corePath: './data/core/index.js'
    });

    Tesseract.recognize('./examples/1.jpg', {
        lang: 'chi_sim'
    }).then(result => {
        console.log(result);
    });

I have downloaded `chi_sim.traineddata.gz` file into my `./data/3.02/` folder and `index.js` core file to `./data/core` folder

When I try to launch this code it throws me this error:

    pre-main prep time: 50 ms
    _http_client.js:53
          throw new Error('Unable to determine the domain name');
          ^

    Error: Unable to determine the domain name
        at new ClientRequest (_http_client.js:53:13)
        at Object.request (http.js:26:10)
        at Object.get (http.js:30:21)
        at ReadFileContext.callback (D:\node-ocr\node_modules\tesseract.js\src\node\lang.js:16:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:358:13)

Why this is happening? Is it bug?

**Comment by BigChief45** [comment]
Same issue here...

**Comment by BigChief45** [comment]
It seems (although I am not sure) that the issue is with the **worker**. Downloading the [worker file](https://github.com/naptha/tesseract.js/blob/master/dist/worker.js) and specifying it in the `workerPath` gives me a different error 👎  :

```
global.addEventListener('message', function (e) {
       ^

TypeError: global.addEventListener is not a function
```

**Comment by dmichelin** [comment]
I'm also having this issue

**Comment by voisinv** [comment]
Having the same issue

**Comment by Hedva** [comment]
I fixed this by the following:

```js
Tesseract.create({
          workerPath: path.join(__dirname, '../tesseract/src/node/worker.js'),
          langPath: path.join(__dirname, '../tesseract/langs/'),
          corePath: path.join(__dirname, '../tesseract/src/index.js')
        }).recognize('saveimages/top'+timecode+'.jpg', {
          lang: 'eng'
        })
        .then(function(result){
            console.log(result)
        });
      }
```

I downloaded the tesseract.js [master](https://github.com/naptha/tesseract.js/archive/master.zip), unzipped it, renamed the folder to _tesseract_, and placed it somewhere in my project. 

I also downloaded the language files I needed from [here](https://github.com/naptha/tessdata/tree/gh-pages/3.02). Unzipped those files and placed it in a folder called _langs_. 

As you can see:
`workerPath: path.join(__dirname, '../tesseract/src/node/worker.js'),` is the worker from the _node folder_ from tesseract.
`corePath: path.join(__dirname, '../tesseract/src/index.js')` is the standard index.js file from the _src folder_.

`langPath: path.join(__dirname, '../tesseract/langs/')` is the folder containing the languages.

Then I tell what image to recognize (in my case an image from the folder 'saveimages') `recognize('saveimages/top'+timecode+'.jpg'`

If you copy all of tesseract.js files locally, it should work. Afterwards you can always remove files which aren't used. You can't just only copy index.js. As you can see in the files, it requires other files
```
index.js
const adapter = require('./node/index.js')
const circularize = require('./common/circularize.js')
const TesseractJob = require('./common/job');
const version = require('../package.json').version;
```

and those require more files on their own

**Comment by BigChief45** [comment]
@Hedva Great comment! Thank you. But doesn't copying the whole repository defeat the purpose of installing TesseractJS with `npm` in the NodeJS server?

**Comment by khrice** [comment]
`let tesseract = require('tesseract.js');
const path = require('path');
const image = path.resolve(__dirname, 'test.jpg')

tesseract.create({
	workerPath: path.join(__dirname, 'tesseract/src/node/worker.js'),
	langPath: path.join(__dirname, 'tesseract/langs/'),
	corePath: path.join(__dirname, 'tesseract/src/index.js')
}).recognize(image, {
	lang: 'eng'
}).then(function (result) {
	console.log(result)
});`

Above is my code, I followed exactly what @Hedva said and I am getting an error of:

`pre-main prep time: 48 ms
_http_client.js:86
      throw new errors.Error('ERR_INVALID_DOMAIN_NAME');
      ^

Error [ERR_INVALID_DOMAIN_NAME]: Unable to determine the domain name
    at new ClientRequest (_http_client.js:86:13)
    at request (http.js:38:10)
    at Object.get (http.js:42:13)
    at ReadFileContext.callback (/Users/Keegan/projects/grocery/tesseract/src/node/lang.js:22:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)`

**Comment by fortil** [comment]
Hi guys
It work for me the this way.
https://github.com/naptha/tesseract.js/issues/136#issuecomment-373228094

**Comment by Asma-Projects** [comment]
try this 👍 it works for me 
just you need to copy the files of this repository into your project  https://github.com/naptha/tesseract.js/tree/master/src

const Tesseract = require('tesseract.js').create({
    workerPath: path.join(__dirname, '../src/node/worker.js'),
    langPath: path.join(__dirname, '../src/langs'),
    corePath: path.join(__dirname, '../src/node/index.js')
});

Tesseract.recognize('./tmp/myimage.png', {
    lang: 'eng'
}).then(result => {
    console.log(result.text);
});

**Comment by kvvsatyasunil** [comment]
Followed same steps, but still getting same error. 
Any suggestion on this please

TypeError [ERR_INVALID_DOMAIN_NAME]: Unable to determine the domain name
    at request (https.js:265:13)
    at Object.get (https.js:284:15)
    at ReadFileContext.callback (D:\ws\rnd\nodews\tesseract\src\node\lang.js:25:23)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)

**Comment by NemoAlex** [comment]
@kvvsatyasunil Same issue.
Check this:
https://github.com/naptha/tesseract.js/blob/master/src/node/lang.js#L18
Turns out if langPath is a local path, lang files should not be gziped.
Just unzip your .traineddata.gz files to .traineddata and problem solved.
