### ISSUE TITLE
connect ETIMEDOUT 69.171.247.32:80

### ISSUE THREAD

**Issue by fox19920726** [naptha/tesseract.js#165]
![image](https://user-images.githubusercontent.com/7921911/33061667-8ccae116-ce62-11e7-8d4a-ced1c6d1ee27.png)
![image](https://user-images.githubusercontent.com/7921911/33061685-9fdbbc12-ce62-11e7-98e7-4e1ccb99872f.png)

**Comment by Imcodingcc** [comment]
作者把服务器关了， 图片识别不了了，这个并不是纯的图片识别，应该是要把图片上传到服务器，让服务器识别然后再回传文字的。

**Comment by Pandorym** [comment]
並不是 @Imcodingcc 說的機制，而是需要從網路上下載代碼和語言包。

**Comment by Imcodingcc** [comment]
@Pandorym 哦，没看npm里面的源码，瞎猜的，不够严谨，sorry。

**Comment by andrew0213** [comment]
那么报这个错误是什么原因呢?又该如何解决呢?

**Comment by loliconer** [comment]
同问，这样的话是不是说国内就用不了了？

**Comment by jeromewu** [comment]
Close as this issue no longer exits
