### ISSUE TITLE
Returning random strings of characters when Image contains Large heading with different font  

### ISSUE THREAD

**Issue by sparkhill** [naptha/tesseract.js#166]
Returning random strings of characters when Image contains large heading with a different font than main body text. 

![capturebad](https://user-images.githubusercontent.com/866402/33343621-e92b3f8e-d47d-11e7-842c-01fc693b5800.PNG)

Result:

Coronation Street spoilers: Anna
Windass’ exit plot REVEALED in
cruel Pat Phelan twist?

$273213?$255123f2”:ZiZVEE‘iiZSJZfiLZQZfZYESZLgehiéZﬂiyggffiy‘T:STE;

**Comment by jeromewu** [comment]
I try the latest version and the issue still exists, I think the quick solution is to split the image and recognize them one by one.
