### ISSUE TITLE
Performance with multiple runs

### ISSUE THREAD

**Issue by yorrd** [naptha/tesseract.js#167]
I want to run Tesseract on very small snippets of text within parts of a second. Therefore, every millisecond counts. I've noticed you're loading a lot of basics for the library which takes some hundred milliseconds every time I `recognize`. Is there a possibility to do this once and then re-run the recognition a couple of times with different images?

Thanks a lot

EDIT: here's a log of what I'm doing. The first number is the millisecond-difference, the second number is the absolute number of milliseconds since my script started (there's some stuff happening before). I'm wondering if anything above `recognizing text` can be done once and never again until I close the app?

![image](https://user-images.githubusercontent.com/1191486/33581620-d3a7c604-d951-11e7-9bd3-b6644a02322f.png)

**Comment by yorrd** [comment]
specifically, I'm looking at [line 8991 in the worker](https://github.com/naptha/tesseract.js/blob/8e9f7861ac2a13197cd49dd251fdfbf58e29553f/dist/worker.js#L8991). Is it necessary to call this on every scan? Couldn't we just do this on the first load?

Sorry if I misunderstand how the library works, I'd be really happy to see this go though :D

**Comment by jeromewu** [comment]
In v2.0.0-beta.1, the performance issue has been addressed and fixed, please check this medium post for more information: https://medium.com/@jeromewus/why-i-refactor-tesseract-js-v2-50f750a9cfe2
