### ISSUE TITLE
Add instructions for building the worker with Emscripten

### ISSUE THREAD

**Issue by tocttou** [naptha/tesseract.js#17]
Can you please add instructions on how you used emscripten to compile the project from tesseract-ocr/tesseract? I am working on a project like this and this can be very informative. Thanks.

**Comment by bijection** [comment]
You should check out https://github.com/naptha/tesseract.js-core!

**Comment by tocttou** [comment]
I was looking at [1](https://github.com/naptha/tesseract-emscripten/tree/master/javascript) but there are no instructions :( anywhere on how you were actually able to compile it. Looks like there is no straightforward way and you had to make wrappers/modifications - but I don't understand it. Perhaps a blog post for the community?

**Comment by bijection** [comment]
Perhaps!
