### ISSUE TITLE
WebAssembly port

### ISSUE THREAD

**Issue by abdulhannanali** [naptha/tesseract.js#170]
Hello, Is it possible to have a Web Assembly port of Tesseract.JS, I suppose that'd be faster?

**Comment by jeromewu** [comment]
Starting from v2, we support WebAssembly, feel free to try 😄

**Comment by MonsieurMan** [comment]
@jeromewu Can you please clarify what you mean by supporting WebAssembly ?  

Does it mean you use emscripten to compile to WebAssembly instead of asm.js in v2 ?

Thanks.

**Comment by jeromewu** [comment]
@MonsieurMan Yes, I have configured emscripten to output WebAssembly version and asm.js version. By default tesseract.js v2 will use WebAssembly version, and fallback to asm.js when the browser is not supported.

Some more information here: https://github.com/naptha/tesseract.js/blob/master/docs/local-installation.md

**Comment by MonsieurMan** [comment]
@jeromewu This is nice ! I'll write a small PWA using it for saving my book quotes in the next few weeks. I'll keep you updated. ☺️

Maybe you should mention WebAssembly and the fallback to asm.js in the readme upfront ? It's a good selling point !
