### ISSUE TITLE
Error Implementing on Angular 4

### ISSUE THREAD

**Issue by zearaez** [naptha/tesseract.js#171]
I tried to implement tesseract.js on angular 4 with Dotnet core 2.0.
Here is my sample code:
`
<script src='https://cdn.rawgit.com/naptha/tesseract.js/a01d2a2/dist/tesseract.js'></script>

declare function tesseract(): any;

tesseract.recognize(image, {
            lang: 'en-US'
        })
            .progress(function (packet) {
                console.log(packet)
            })
            .then(function (data) {
                console.log(data)
            })
`
But it says recognize doesnot exist on type ()=> any.
How can i solve it?

**Comment by Hedva** [comment]
Some time ago there where some problems with the cdn. Look for issue 164. I've posted a solution (for nodejs) but maybe it can also work for you.
