### ISSUE TITLE
Multiple Training Data

### ISSUE THREAD

**Issue by hdsmob** [naptha/tesseract.js#172]
Not able to add multiple language (.trainingdata) in Tesseract.recognize function? Any solution?

**Comment by LauraSophieM** [comment]
Someone pleaaaaaaaaase comment a solution here

**Comment by jeromewu** [comment]
Multiple language is now supported in v2, check [HERE](https://github.com/naptha/tesseract.js/blob/master/docs/examples.md) for examples.
