### ISSUE TITLE
Error running examples

### ISSUE THREAD

**Issue by glidenz** [naptha/tesseract.js#174]
Hi

Just starting to try out tesseract. When running either example file (basic.js or detect.js), I getting errors thrown.

Detect is more verbose so I've included the output below. Seems to be failing when it unpacks some files it sucks down.

Any ideas??

JUCEBOXWS2:node marklloyd$ node detect.js 
{ status: 'loading tesseract core' }
{ status: 'loaded tesseract core' }
{ status: 'initializing tesseract', progress: 0 }
pre-main prep time: 56 ms
{ status: 'initializing tesseract', progress: 1 }
{ status: 'downloading osd.traineddata.gz',
  loaded: 116,
  progress: 0.000027136730992415984 }
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Gunzip.zlibOnError (zlib.js:152:15)
JUCEBOXWS2:node marklloyd$

**Comment by Hedva** [comment]
Load the language files locally instead of trying to get them from the internet. You can get them here: https://github.com/naptha/tessdata/tree/gh-pages/3.02

**Comment by syzer** [comment]
the probl;em is with get reqest send by tesseract.
it should not accept `deflate` method header.
you can grab those files manually here: https://github.com/tesseract-ocr/tessdata
