### ISSUE TITLE
How do we train it ourselves?

### ISSUE THREAD

**Issue by NoobDoesMC** [naptha/tesseract.js#176]
I want to work on a super specific set of input files.

Can I train it myself?

**Comment by Scotthorn0** [comment]
@NoobDoesMC 
I'm not a contributor, but I don't think Tesseract currently supports that. 

The best bet might be to make use of the black/white list parameters. See all the parameters [here](https://github.com/naptha/tesseract.js/blob/master/docs/tesseract_parameters.md). 

You could run your own data collection and add/remove characters to those lists as you process items and find better results.

The other option is to build a full data set of the results and start processing that data with your own machine learning or something similar.

**Comment by NoobDoesMC** [comment]
I know Tesseract supports this.

I did research since this question and it looks like I might be able to create my own language data files right?

**Comment by mwh1te** [comment]
Yes, you can just train using the regular Tesseract engine (the one tesseract.js uses) and create your .traineddata file to be used within tesseract.js.

**Comment by NoobDoesMC** [comment]
Sounds perfect. Sounds tricky to create those though, I saw an online tutorial and it looks like a lot of manual work is also required.

**Comment by mwh1te** [comment]
@NoobDoesMC Yeah I made one with text in a seven segment font (digital font) and it was not very fun. Hardest part was obtaining data to train on, what type of text are you planning on using?

**Comment by NoobDoesMC** [comment]
@mwh1te I want to train it to extract the text from screenshots of minecraft games, e.g. to turn this image:

![screen shot 2018-01-14 at 00 33 43](https://user-images.githubusercontent.com/29206206/35401942-f23b0a58-01f2-11e8-842a-71407c6c9fd9.png)

Into this text:

> NoobDoesMC's Stats  
> Super Smash Mobs  
> Wins: 856  
> Games Played: 2455  
> SO SUPER!  
> MLG Pro  
> ...  
> Click for more details!

**Comment by Quiesan** [comment]
Did you succed with train tesseract please ?

**Comment by pratham2003** [comment]
@mwh1te Which version of the training files can be use? 3 / 4..?

Off-topic @NoobDoesMC Doing it as your own Java plugin for Minecraft might be easier and give better results than training an OCR.

**Comment by jeromewu** [comment]
To train it yourself, please check [FAQ](https://github.com/naptha/tesseract.js/blob/master/docs/faq.md#how-can-i-train-my-own-traineddata)
