### ISSUE TITLE
Language "ben" (Bengali) is not working.

### ISSUE THREAD

**Issue by jabedbd** [naptha/tesseract.js#177]
Hi found that this library can support Bengali also. But when i use "ben" as language code my code fallback to default language (English) and not recognize any Bengali character.

**Comment by jeromewu** [comment]
Maybe you call it in the wrong way, check [HERE](https://github.com/naptha/tesseract.js/blob/master/docs/examples.md) for examples.

**Comment by putnik** [comment]
I started using this library a few days ago, and made a script that works great with different languages. But specifically with Bengali is really some kind of problem.

The console displays the following messages:
> Fetch finished loading: GET "https://tessdata.projectnaptha.com/4.0.0/ben.traineddata.gz".
> Failed loading language 'ben'

If only Bengali is used (`ben`), then recognition does not work. If Bengali and English are used (`ben+eng`), then recognition works but only in English.

I am sure that I am adding the language correctly, since for all other languages this works fine.

@jeromewu May you reopen this task?

**Comment by putnik** [comment]
I now tried to recognize the same image locally with Tesseract v4.0.0. I used the same ben.traindata file, and everything works perfectly. So probably this is not a problem in the traindata file (unless maybe with gz), but a problem with its loading.

**Comment by jeromewu** [comment]
@putnik 

I do test with following configuration:

- Environment: Node.js v10.14.2
- Image:
![image](https://user-images.githubusercontent.com/5723124/58069350-7c8f8680-7bc7-11e9-9765-76b9da5a48bc.png)
- Code:
```javascript
const { TesseractWorker } = require('tesseract.js');
const worker = new TesseractWorker();
const imgName = __dirname + '/image/ben.png';

worker.recognize(imgName, 'ben', {
})
  .progress(p => console.log(p))
  .then(function (result) {
    console.log(result.text);
    worker.terminate();
  })
```
- Output:
```
{ status: 'loading tesseract core', progress: 0 }
{ status: 'loaded tesseract core', progress: 1 }
{ status: 'initializing tesseract', progress: 0 }
{ status: 'initialized tesseract', progress: 1 }
{ status: 'loading language traineddata', progress: 0 }
{ status: 'loaded language traineddata', progress: 1 }
{ status: 'initializing api', progress: 0 }
Failed loading language 'ben'
Tesseract couldn't load any languages!
{ status: 'initializing api', progress: 0.5 }
{ status: 'initializing api', progress: 1 }
{ status: 'recognizing text', progress: 0 }
{ status: 'recognizing text', progress: 0.7142857142857143 }
{ status: 'recognizing text', progress: 1 }
বাংলা
```

Although you can see there is an error message, still the answer is right, I will check the error message part first.
I think Tesseract.js works OK, and from the console message you provided:

> Fetch finished loading: GET "https://tessdata.projectnaptha.com/4.0.0/ben.traineddata.gz".
> Failed loading language 'ben'

It is more like that there is a network issue which makes you unable to download the gz file, I think you can try it again to see if it is the same.

If the problem still exists, please provide more information about your environment and anything related.

**Comment by putnik** [comment]
I tried some different examples. And it seems that the issue occurs when multiple languages are used. And since an error occurs with Bengali, it is excluded from those used. E. g. if in the example above, replace `ben` with `ben+eng`, the result will be `QU]`. Same as using only `eng`.

**Comment by putnik** [comment]
Now I use traindata files that I gzipped on my own, and it looks like the problem has disappeared. Perhaps there is no problem with the traindata files, but there is a problem with the traindata.gz files that are located on http://tessdata.projectnaptha.com

**Comment by jeromewu** [comment]
Please try tesseract.js v2.0.0-alpha.11 to see if the issue still exists, we have done some enhancement for this issue.
Feel free to reopen the issue with more information. :smile:
