### ISSUE TITLE
Recognising characters in real time via a canvas video feed

### ISSUE THREAD

**Issue by cosmo-naut** [naptha/tesseract.js#179]
Has anybody attempted this before?
How fast is tesseract?
I would assume this is possible but I was hoping to see if anybody has experimented with it and could point me in the right direction.

**Comment by tom-s** [comment]
Hi @cosmo-naut . I'm actually investigating the same thing and built this jsfiddle where you can see it.
I think the canvas image may need some processing to optimize the OCR (i dunno if tesseract does it already under the hood ?)

https://jsfiddle.net/f5L38emf/4/

**Comment by tom-s** [comment]
I also recommend this article :https://yoric.github.io/post/extracting-text-from-images/

**Comment by cosmo-naut** [comment]
I gotta hand it to you that's pretty interesting!
I believe the Stroke Width Transform algorithm could be useful for what I intend to do, which is more along the lines of real time character detection as opposed to recognition.

**Comment by zocheyado** [comment]
@tom-s Any details on how you actually did this? I cannot for the life of me replicate this. I see your fiddle working but every-time I try this I get "TypeError: path must be a string or Buffer" from tesseractworker.

**Comment by jeromewu** [comment]
I make an example here, feel free to check: https://github.com/jeromewu/tesseract.js-video
