### ISSUE TITLE
Can currently only create a Blob from other Blobs

### ISSUE THREAD

**Issue by uendar** [naptha/tesseract.js#180]
Hi everyone,

I am trying to use tesseract.js in android. I use react-native-image-crop-picker to get the image and than i past the image name(myImage) into a function that calles 
```
 redImg(myImage){
  Tesseract.recognize(myImage)
  .progress(function  (p) { console.log('progress', p)    })
  .then(function (result) { console.log('result', result) })
 }
```
but  i get an worning and nothing works
The error is:
 Possible Unhandled Promise Rejection (id: 0):
 ReactNativeJS: Invariant Violation: Can currently only create a Blob from other Blobs

**Comment by socialcode-rob1** [comment]
what is your 'image-like' type being passed ?

**Comment by jeromewu** [comment]
Close for now, feel free to reopen with more information.
