### ISSUE TITLE
Data clone error with Tesseract JS local-installation on Internet Explorer 11

### ISSUE THREAD

**Issue by suyogpargaonkar** [naptha/tesseract.js#182]
I am using Tesseract Js OCR, Referring tesseract.js In that local-installation approach `Below` is my Code
```
<script src="~/Scripts/tessaract.js">
</script> 
   TesseractObj = Tesseract.create({
                                 workerPath: 'http://localhost:14180/scripts/worker.js',  
                                 langPath: 'http://localhost:14180/scripts/', 
                              corePath: 'http://localhost:14180/scripts/index.js', }); 

  TesseractObj.recognize(file)
                      .progress(function (p) { console.log(p); })
                      .then(function (result) {
                           // my remaining code on result }  
                         });
```
All required js and eng.traineddata.gz files I have downloaded and referring from my solutionOn Chrome browser it processing correclty but On Internet Explorer 11 it is throwing below

![image](https://user-images.githubusercontent.com/35335303/36013197-f0881b28-0d88-11e8-8e46-6dfe1ad72b4e.png)

In worker.js file when postMessage function is called then getting this error

```
global.addEventListener('message', function (e) {
    var packet = e.data;
    workerUtils.dispatchHandlers(packet, function (obj) {
        return postMessage(obj);
    });
});
```
Note: When I was referring cdn file then working on IE browser
Please help on this  @antimatter15 
Thanks in advance

**Comment by avi9839** [comment]
@suyogpargaonkar did you get any solution to this issue?

**Comment by jeromewu** [comment]
Close this issue as it is a v1 issue. If it happens in v2 as well, feel free to reopen with more information, thanks.
