### ISSUE TITLE
Scanning Fix Position in the image

### ISSUE THREAD

**Issue by glenngsanchez** [naptha/tesseract.js#183]
Hi, Is there a way to scan fix position in the images?  

`
Tesseract.recognize(myImage, {startx:10,starty:10, endx:90,endy:10})
         .progress(function  (p) { console.log('progress', p)    })
         .then(function (result) { console.log('result', result) })
`

**Comment by armin77** [comment]
Hi
Why don't you crop the image beforehand to that rect!?

**Comment by jeromewu** [comment]
Hi, we now support this feature!

Check here: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-only-part-of-the-image-200-alpha12
