### ISSUE TITLE
Can't find variable: location

### ISSUE THREAD

**Issue by uendar** [naptha/tesseract.js#184]
I get this error after installing tesseract.js in react-native. It is located on 
                ` tesseract.js/scr/browser/index.js `

Any idea how to solve it?

**Comment by jeromewu** [comment]
For react-native, maybe you can try [react-native-tesseract-ocr](https://github.com/jonathanpalma/react-native-tesseract-ocr), for resource intensive task like OCR, it is better to use native approach.

**Comment by jeromewu** [comment]
Related to #55
