### ISSUE TITLE
Continue the maintenance of this repository

### ISSUE THREAD

**Issue by jeromewu** [naptha/tesseract.js#185]
Judge from the issues and PR, looks like this repository is not under a good maintenance status. I am willing to help but my PR is not accepted after few days (not to mention other PRs).

Is there any good method we can continue this repo?

**Comment by antimatter15** [comment]
Are you interested in taking over maintenance of the project?

**Comment by jeromewu** [comment]
Yes, I am interested, thanks for making me the contributor :)
