### ISSUE TITLE
MRZ Scanning

### ISSUE THREAD

**Issue by supportreq** [naptha/tesseract.js#186]
Can we use tesseract.js to scan MRZ code present under Passports and visa??

how do we do that... please advice..

**Comment by jeromewu** [comment]
It should be possible to scan the MRZ code, can you provide some sample data you are using? Maybe we can do some tests.

**Comment by supportreq** [comment]
i dont have a test set.. google would be a best source for passports and visas :)

**Comment by jeromewu** [comment]
Well, if your case is not so complicated, I just do a google for you and here is the result:

Googled MRZCodeExample:

![mrzcodeexample](https://user-images.githubusercontent.com/5723124/36259270-a712d658-1298-11e8-9561-5b877b4bcef6.jpg)

Result:

![image](https://user-images.githubusercontent.com/5723124/36259246-95d01a0e-1298-11e8-89cc-4a5119b35af4.png)

To do a quick test, you can use [the example described in our README](https://github.com/naptha/tesseract.js#development), it is simple and takes few commands to complete the task.
