### ISSUE TITLE
Using latest HEAD (tesseract 4)

### ISSUE THREAD

**Issue by donmb1** [naptha/tesseract.js#187]
Thanks for this great repo - we're using it in our Cordova app with success.
However, we're wondering if it is possible to include the latest tesseract HEAD (which is tesseract 4.0.0 alpha) in the repo without too much hazzle? As tesseract 4 uses a LSTM it delivers much better results and this could be a great advantage. I understand that it is still in ALPHA but I believe that more people could be interested in that.

**Comment by jeromewu** [comment]
I think it is possible but there are lots of works to do, includes (maybe more):
1. Use emscripten to convert the tesseract 4
2. Update tesseract.js-core
3. Integrate tesseract.js-core with tesseract.js

I will put this in the roadmap and plan for a specific timing for resolving this issue.

**Comment by jeromewu** [comment]
After trying for few days, I found it hard to upgrade to 4.0+, for the next step we may only have a version for 3.05.01 before official release of 4.0.0.

**Comment by janis91** [comment]
@jeromewu any updates on this?

**Comment by ricardomga** [comment]
First, thank you for the amazing project!
@jeromewu where can we found the roadmap?
Thanks

**Comment by jeromewu** [comment]
Hello folks,

Sorry I have been super busy lately and unable to do any updates...
I will try to figure out how to move forward and any help from the community is highly welcome :smile:

**Comment by tomkos** [comment]
Dear @jeromewu, thanks for your work, just checking if you had any luck with 4.0.0 version?

**Comment by jeromewu** [comment]
Right now tesserat.js v2 has released alpha version and its core has upgraded to tesseract v4.
Feel free to try and leave comments. 😄
