### ISSUE TITLE
Custom traineddata

### ISSUE THREAD

**Issue by kiralikbeyin** [naptha/tesseract.js#189]
I have a custom traineddata, this is not a lang pack. It is for reading some special id under a qr barcode.

I tried examples in the repo but it is trying to download from web "http://.../3.0.2/custom.traineddata.gz"

Changed paths in this but didn't work.
```
window.Tesseract = Tesseract.create({
    workerPath: '/path/to/worker.js',
    langPath: 'https://cdn.rawgit.com/naptha/tessdata/gh-pages/3.02/',
    corePath: 'https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js',
})
````

Please can anyone show me correct code and how to work locally?

**Comment by jeromewu** [comment]
Please check [local-installation](https://github.com/naptha/tesseract.js/blob/master/docs/local-installation.md) for more details.
