### ISSUE TITLE
Can name recognition be improved? 

### ISSUE THREAD

**Issue by tugend** [naptha/tesseract.js#191]
Hi. I'm trying to learn ocr using Tesseract.js and my webcam, right now I'm experimenting with reading the name of my identity card.

I think I've gotten rather far, but now I'm stuck on improving the quality of the character recognition. 
Though Tesseract 4.0 handles my case much better than tesseract.js (ported from 3.05 I think), I still think it should be possible to get usuable results -  if I could just figure out where to tweak the options correctly! 

So far I haven't really manage to improve anything beyond setting the correct language (including the special characters. Do you have any suggestions for improvement?

My best configuration so far seems to be simply { lan: 'dan' }, with which I get a consistently good results on numbers (a confidence around 80%), but a name like Mads Wårlich keeps getting read as mm, MW and other similar unusable matches.

I have tried different values of psm, and even user specific word file input, I've also considered trying build a new set of training data because the font might be weird but it seems a lot of work for something that might not make a difference.

![download](https://user-images.githubusercontent.com/1878092/36985615-0c4ddcc2-2098-11e8-914c-9200581b577d.png) (the image is truncated, since I'd prefer not to include my full name here ^_^)

Do you have any good suggestions for what I could do to improve my results in a case like this?
Any input would be appriciated.

**Comment by minalmeg** [comment]
You may want to try using a desaturation file with higher accuracy than the current desaturate.js. This will help in the preprocessing step to convert the image into black and white. Further, you may want to use more sophisticated binarization algorithm to increase resolution of your input image. 
I have just started working on this so I am not a pro! but I do think playing with preprocessing algos would increase accuracy more likely than building a new training dataset.

**Comment by tugend** [comment]
Duely noted, though it's a bit far from memory now. ^_^
By thank you for the answer , and good luck with your own ml journey.
