### ISSUE TITLE
how can i see the recognized result???

### ISSUE THREAD

**Issue by pol2edo** [naptha/tesseract.js#192]
first , i add tesseract js in browser html through : 

var script = document.createElement("script");
script.type = "text/javascript";
script.src="https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js";
document.body.appendChild(script);

second,  I write code to recognize image ,  like this : 

Tesseract.recognize(document.getElementsByTagName('img')[1], {
    lang: "eng"
})
.then(function(data){
    console.log(data);
});

but, it always not ouput data log , just output these:

TesseractJob {id: "Job-22-46209", _instance: TesseractWorker, _resolve: Array(1), _reject: Array(0), _progress: Array(0), …}

why?  how can I see the recognized result????? ths

**Comment by jeromewu** [comment]
You not using the right way to call the API, please follow the format as below:

```javascript
Tesseract.recognize(myImage)
       .progress(function  (p) { console.log('progress', p)    })
       .then(function (result) { console.log('result', result) })
```

**Comment by pradeepbatchu** [comment]
I am new to tesseract.js with latest version I am facing issue :
TypeError: Tesseract.recognize(...).progress is not a function, 
Can someone please help.?

**Comment by Shiv-2712** [comment]
I am still getting the same issue **TypeError: Tesseract.recognize(...).progress is not a function**
