### ISSUE TITLE
How can I read the image which is on my local machine??

### ISSUE THREAD

**Issue by rajatgang786** [naptha/tesseract.js#193]

**Comment by rajatgang786** [comment]
Tesseract.recognize('mGHPI.png').then((res: any) => {
            console.log(res.text ,"res.text");
            this.setState({
                imageData: res.text
            });
        })


I am getting an error  "You need to enable JavaScript to run this app."

**Comment by jeromewu** [comment]
Can you provide more details about your environment?

It is executed in browser, node.js or other runtime?

Thanks

**Comment by rajatgang786** [comment]
i want to pass the image in recognition (), and in-browser i want the data written over that image...

**Comment by jeromewu** [comment]
A quick guess is that you are developing a react app with create-react-app, maybe this issue can help you:

https://github.com/facebook/create-react-app/issues/2888

And I think this is not a tesseract.js issue.

**Comment by rajatgang786** [comment]
Thanx
