### ISSUE TITLE
Failed loading language 'eng' while trying Tesseract.js

### ISSUE THREAD

**Issue by jSquaredSolutions** [naptha/tesseract.js#194]
var Tesseract = require("tesseract.js");
Tesseract.recognize('5421482431.jpg')
.progress(function  (p) { console.log('progress', p)    })
.then(function (result) { console.log('result', result) })

/* Im using the above code to try tesseract. However, when I run the nodejs script from my bash shell in Windows I get the following:
progress { status: 'loading tesseract core' }
progress { status: 'loaded tesseract core' }
progress { status: 'initializing tesseract', progress: 0 }
pre-main prep time: 51 ms
progress { status: 'initializing tesseract', progress: 1 }
progress { status: 'loading eng.traineddata', progress: 0 }
progress { status: 'loading eng.traineddata', progress: 1 }
progress { status: 'initializing api', progress: 0 }
**Failed loading language 'eng'**

**Comment by jinhwanee93** [comment]
I had this issue before; try replacing your old eng.traineddate file 

download a new eng.traineddata file here: 
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files 

or here:
https://github.com/tesseract-ocr/tessdata

Hope this helps

**Comment by user883311** [comment]
@jinhwanee93 Thank you - this solved it for me: 
- download the new `eng.traineddata` file from https://github.com/tesseract-ocr/tesseract/wiki/Data-Files
- paste the `eng.traineddata` file into the root folder of my node app (replacing the old file)

**Comment by BATspock** [comment]
@jinhwanee93 Thanks, this worked for me as well

**Comment by danielsnider** [comment]
BTW, the traineddata file that finally worked for me is from:
https://github.com/tesseract-ocr/tessdata/blob/master/eng.traineddata

On Ubuntu 16.04 I put it here `/usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata`.

This fixes the error:
```
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.
```

**Comment by jeromewu** [comment]
Close as resolved.
