### ISSUE TITLE
Modify the number of symbol choice ?

### ISSUE THREAD

**Issue by Inglebard** [naptha/tesseract.js#197]
Hi,
Is there a way to modify the number of symbol choice ?

![choice](https://user-images.githubusercontent.com/8203903/37778767-0e6416c4-2deb-11e8-9915-007905540dd4.jpg)

By default, it returns 10 choices, it is possible to have 15 or 20 ?

**Comment by jeromewu** [comment]
We don't have plan for this feature as we are not sure about the scenario, feel free to reopen the issue with more details about the scenario, thanks.
