### ISSUE TITLE
None of this works in Node.js

### ISSUE THREAD

**Issue by virus2016** [naptha/tesseract.js#199]
Hi all,

Can someone please help me with an example of running this in node?

Many thanks,

**Comment by Coronal-Halo** [comment]
What error messages did you get???

**Comment by user883311** [comment]
It works for me.. Have you tried the example/demos on the project github?

**Comment by berrytechnics** [comment]
https://gist.github.com/berrytechnics/3d4942d3335e036c9d11294d2409fd1c

This is the most basic example I got to work

**Comment by jeromewu** [comment]
Should be working at this moment, close for now, feel free to reopen if it still doesn't work.
