### ISSUE TITLE
Completely locally-based deployment with trained data

### ISSUE THREAD

**Issue by aebadirad** [naptha/tesseract.js#2]
When trying to keep everything local, especially when no internet access is available, for the externally hosted traineddata language packs, things do not function (obviously).

If we pull the tessdata, where do we include it in order for it to be preloaded without having the call go out? There is a mention of an environment variable, (tessdata_prefix) but that appears to be a leave-over from the original c.

Where can we stick the tessdata relative and specify that in the worker.js file?

edit: Well, I've found a way via web worker messaging and attaching a new parameter (rootURL) to the base tesseractinit object, then modifying the xhr connect string to take the rooturl as the base of the path. It works really well and really makes this flexible.

Not sure if it'd be something you want me to fork and pull request back to you though.

**Comment by antimatter15** [comment]
This is a feature we've been planning to add for a while.

**Comment by aebadirad** [comment]
So I've modified the library to be object-based, to be easier to configure and save some memory if this has to be done thousands of times, not to mention tesseract has so many features under the hood it might help with feature development against that.

I've added some config options to set paths for both worker.js and the tessdata folder, lot more to add including flushing/reinstantiating the worker on demand, as well as some additional functionality.

You can check it out in my fork, I've added some additional examples as well. At some point I'd like to break out worker.js a bit more and isolate the low level from the supporting JS wrappers to make things more clean.

**Comment by lihan** [comment]
@aebadirad Nice work!
