### ISSUE TITLE
Unable to load local worker without full url path

### ISSUE THREAD

**Issue by Inglebard** [naptha/tesseract.js#200]
Hi,

I try to use a local worker as described in the doc. However, I got : "Failed to load worker script at ...".
I only suceeded with a full url path. A relative or an absolute (beginning with "/") is not working.

I notice in the spawnWorker, it uses a blob to load script.
```javascript
exports.spawnWorker = function spawnWorker(instance, workerOptions) {
    if (window.Blob && window.URL) {
        var blob = new Blob(['importScripts("' + workerOptions.workerPath + '");']);
        var worker = new Worker(window.URL.createObjectURL(blob));
    } else {
        var worker = new Worker(workerOptions.workerPath);
    }
```

**Comment by jeromewu** [comment]
In tesseract.js v2, we leverage resolve-url package to check the URL, it should be working properly now.

Close for now, feel free to reopen this issue if needed.
