### ISSUE TITLE
string.match is not a function

### ISSUE THREAD

**Issue by ejvelasco** [naptha/tesseract.js#202]
I attempted to follow the example in the docs, but I keep getting the following error.
![screenshot from 2018-03-25 20-13-33](https://user-images.githubusercontent.com/20133794/37882452-0bb87ca0-3069-11e8-83c9-b93ec8ba7121.png)

**Comment by faisalarkan21** [comment]
what i do is delete this code from the library node_modules and it's works, take a look this images
![selection_713](https://user-images.githubusercontent.com/10622747/37882628-24a356de-30cf-11e8-8177-72527509e2a8.png)

they has solving this problem actually
https://github.com/naptha/tesseract.js/pull/196#pullrequestreview-106753491

**Comment by BigChief45** [comment]
@faisalarkan21 I started experiencing the same issue today, yet everything worked before.

You can see this in the stack trace:

```
isUrl (/var/task/node_modules/is-url/index.js:27:22
```

It seems that it is failing on that node module?

**Comment by jeromewu** [comment]
Fix by #196
