### ISSUE TITLE
digits only

### ISSUE THREAD

**Issue by dcharbonnier** [naptha/tesseract.js#203]
`tesseract imagename outputbase digits`

https://github.com/tesseract-ocr/tesseract/wiki/FAQ#tesseract-3

Is it possible to use this with the js version ? The initialization is too slow, especially when you only need digits

**Comment by etienne-martin** [comment]
```javascript
Tesseract.recognize(image, {
    lang: 'eng',
    tessedit_char_whitelist: '0123456789'
})
```

Should do the trick if you only want to recognize 0-9.

**Comment by jeromewu** [comment]
BTW, in tesseract.js v2, you need to write it in this way:

```javascript
const worker = Tesseract.TesseractWorker();

worker.recognize(image, 'eng', {
    tessedit_char_whitelist: '0123456789'
})
```

**Comment by webgoto** [comment]
Even if I write like this, there are other characters.
No options have been applied.

```HTML
<script src='https://unpkg.com/tesseract.js@v2.0.0-alpha.3/dist/tesseract.min.js'></script>
<script>
	var worker = new Tesseract.TesseractWorker();

	worker.recognize('./img/tesseract.jpg', 'eng', {
		tessedit_char_whitelist: '0123456789',
	})
	.progress(function(p){
		console.log(p);
	})
	.then(function(result){
		console.log(result);
	});
</script>
```
result object
{text: "IRILF— 137kcal↵lehiE<E 7.3g↵fEE 3.2g↵RAKALH 19.8g↵FhUDL 774mg↵", ...}

**Comment by jeromewu** [comment]
After some research, I found that `tessedit_char_whitelist` is not available in tesseract v4. So we need to use tesseract v3 engine to make it work.

```html
<script src='https://unpkg.com/tesseract.js@v2.0.0-alpha.4/dist/tesseract.min.js'></script>
<script>
	var worker = new Tesseract.TesseractWorker();
        var OEM = Tesseract.OEM;

	worker.recognize('./img/tesseract.jpg', 'eng', {
                init_oem: OEM.TESSERACT_ONLY,
		tessedit_char_whitelist: '0123456789',
	})
	.progress(function(p){
		console.log(p);
	})
	.then(function(result){
		console.log(result);
	});
</script>
```

More information: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-whitelist-chars-200-alpha4

**Comment by HoldYourWaffle** [comment]
Do we really need to switch engine versions for a trivial feature like this? Can't we just filter the output from Tesseract and remove any words that contain non-whitelisted characters?

**Comment by webgoto** [comment]
It worked using tesseract v3 engine.
Thank you.

**Comment by QimatLuo** [comment]
> After some research, I found that `tessedit_char_whitelist` is not available in tesseract v4. So we need to use tesseract v3 engine to make it work.
> 
> ```
> <script src='https://unpkg.com/tesseract.js@v2.0.0-alpha.4/dist/tesseract.min.js'></script>
> <script>
> 	var worker = new Tesseract.TesseractWorker();
>         var OEM = Tesseract.OEM;
> 
> 	worker.recognize('./img/tesseract.jpg', 'eng', {
>                 init_oem: OEM.TESSERACT_ONLY,
> 		tessedit_char_whitelist: '0123456789',
> 	})
> 	.progress(function(p){
> 		console.log(p);
> 	})
> 	.then(function(result){
> 		console.log(result);
> 	});
> </script>
> ```
> 
> More information: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-whitelist-chars-200-alpha4

Is this code still work for v2.1.1?
This is my code
```js
Tesseract.recognize(
  filename,
  'eng',
  {
    init_oem: Tesseract.OEM.TESSERACT_ONLY,
    tessedit_char_whitelist: '01',
  }
)
.then(({ data: { text } }) => console.log(text))
```
But I still get other result, not only '0' or '1'.

**Comment by QimatLuo** [comment]
Never mind, I follow https://github.com/winderica/DailyReport/issues/4 example to make it work.
By the way, can we use `Tesseract.recognize` without manually setup the worker to do the same thing?

**Comment by JerryGreen** [comment]
Both examples mentioned here doesn't seem to work in `"tesseract.js": "2.1.4"` :\
