### ISSUE TITLE
Can not visit cdn.rawgit.com in China

### ISSUE THREAD

**Issue by yeernet** [naptha/tesseract.js#206]
I am sorry, but I can not visit `cdn.rawgit.com` in China because of the closed-door policy.

**Comment by hktalent** [comment]
@yeernet 
···
1、vps + shadowsocks
2、or static all resource
···

**Comment by otizis** [comment]
@yeernet using ss, but can't use in cmd.
    set http_proxy=http://127.0.0.1:1080
    set https_proxy=http://127.0.0.1:1080

**Comment by zengxs** [comment]
@yeernet 

import tesseract.js 1.0.13 from jsDelivr, you can request tessdata from cdn

`https://cdn.jsdelivr.net/npm/tesseract.js@1.0.13/dist/tesseract.min.js`

**Comment by jeromewu** [comment]
Close as this issue should be resolved using cd like jsDelivr or unpkg.
