### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by DarKWinGTM** [naptha/tesseract.js#207]
I have make this project working on offline and sometime i found issue message "out of memory" i cleared all cahce cookie refresh page trying to load and check on online version but it show "out of memory" 

Online Versions
Successfully compiled asm.js code (loaded from cache in 55ms)  index.js
out of memory  tesseract.js:571:48
	_handle https://cdn.rawgit.com/naptha/tesseract.js/1.0.7/dist/tesseract.js:571:48
	_recv https://cdn.rawgit.com/naptha/tesseract.js/1.0.7/dist/tesseract.js:693:5
	spawnWorker/worker.onmessage https://cdn.rawgit.com/naptha/tesseract.js/1.0.7/dist/tesseract.js:342:9

![image](https://user-images.githubusercontent.com/8704185/38479710-1c11a008-3beb-11e8-95b2-ef8720b44318.png)

Offliine Versions

![image](https://user-images.githubusercontent.com/8704185/38479748-5d82cdd2-3beb-11e8-9a47-89a61031ddb6.png)

Successfully compiled asm.js code (loaded from cache in 31ms)  index.js
out of memory  tesseract.js:571:48
	_handle file:///C:/Users/VMWARE/Documents/iMacros/Datasources/tesseract.projectnaptha.com/tesseract.projectnaptha.com/cdn.rawgit.com/naptha/tesseract.js/1.0.7/dist/tesseract.js:571:48
	_recv file:///C:/Users/VMWARE/Documents/iMacros/Datasources/tesseract.projectnaptha.com/tesseract.projectnaptha.com/cdn.rawgit.com/naptha/tesseract.js/1.0.7/dist/tesseract.js:693:5
	spawnWorker/worker.onmessage file:///C:/Users/VMWARE/Documents/iMacros/Datasources/tesseract.projectnaptha.com/tesseract.projectnaptha.com/cdn.rawgit.com/naptha/tesseract.js/1.0.7/dist/tesseract.js:342:9

**Comment by jeromewu** [comment]
In tesseract.js v2, we double the memory quota, hope it helps.

Feel free to reopen this issue with more information.
