### ISSUE TITLE
How can i add Urdu language in this application

### ISSUE THREAD

**Issue by ProDev72** [naptha/tesseract.js#209]
Hello guys! 
I want to know how can I add the Urdu language in this application. You just need to point me out, I can develop myself and want to contribute to this application. I will be really thankful if you help me in this thing. Thanks

**Comment by jeromewu** [comment]
tesseract.js v2 now supports urdu, you can use it like this:

```javascript
import Tesseract from 'tesseract.js';

const { TesseractWorker } = Tesseract;
const worker = new TesseractWorker();

worker
  .recognize(
    'http://jeroen.github.io/images/testocr.png',
    'urd'
  )
  .progress((p) => {
    console.log('progress', p);
  })
  .then((result) => {
    console.log(result);
  });
```
