### ISSUE TITLE
Tesseract local installation

### ISSUE THREAD

**Issue by tradescantia** [naptha/tesseract.js#210]
Dear all, 
I have a request to use tesseract.js locally. I'm writing an app and I'm inserting all the methods into a js controller file.

For test purposes I am still loading langPath and corePath from the cdn. Later I want to insert also there the local path.
When I try to create the global variable of Tesseract I get following error: "Tesseract is not defined".
Do I miss some previous declaration on my file?

```
// load Tesseract locally
window.Tesseract = Tesseract.create ({
workerPath: "libs/tesseract/dist/worker.js",
langPath: "https://cdn.rawgit.com/naptha/tessdata/gh-pages/3.02/",
corePath: "https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js"
});

// if tesseract is defined continue 
if (! (window.Tesseract === undefined)) {
window.Tesseract.recognize (imageData) (...)
}
```

Thank you for any hint!

Best Regards
Chiara

**Comment by b4dnewz** [comment]
Hi @tradescantia probably you are missing the require/import of the tesseract module:
```js
import Tesseract from 'tesseract.js'
```
See the [usage](https://github.com/naptha/tesseract.js#usage) section of the readme

**Comment by jeromewu** [comment]
You can check here for a local installation example: https://github.com/jeromewu/tesseract.js-offline
