### ISSUE TITLE
tessedit_pageseg_mode: "1" does not work

### ISSUE THREAD

**Issue by konstantin-dzreev** [naptha/tesseract.js#211]
Hi,

I'm trying to use "Automatic page segmentation with OSD" feature, and it does not seem to be working.

Here is my setup:
 - Ubuntu 16.04;
 - node 8.9.4
```
Tesseract.recognize(imgPath, {tessedit_pageseg_mode: "1"}) 

fails with:
pre-main prep time: 46 ms
Error opening data file ./tessdata/osd.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'osd'
Tesseract couldn't load any languages!
Warning: Auto orientation and script detection requested, but osd language failed to load
```

I do have ```eng.traineddata``` and ```osd.traineddata``` in the root folder of my project. ```Tesseract.recognize()``` and ```Tesseract.detect()``` require them to be there, and both work fine without ```tessedit_pageseg_mode``` option, or with ```tessedit_pageseg_mode: "6"```. But ```tessedit_pageseg_mode: "1"``` (or ```"0"```) blows it up with the error above.

I tried placing ```eng.traineddata``` and ```osd.traineddata``` into ```./tessdata```, but this did not help. Providing ```TESSDATA_PREFIX``` to my script did not help either.

In theory I can use ```Tesseract.detect(imgPath)``` to get page orientation, then call image magic to rotate it, and then use ```Tesseract.recognize(imgPath)``` to get HOCR data. But ```Tesseract.recognize(imgPath,{tessedit_pageseg_mode: "1"})``` should automatically do all the above, it just fails for me because of the reason I'm not getting.

Thank you.

**Comment by vasuneet** [comment]
Any update on this?

**Comment by jeromewu** [comment]
Please install the next version of tesseract.js and try the example [HERE](https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-different-pageseg-mode-200-alpha5)

Installation:

```
$ npm install tesseract.js@next
```

**Comment by gblikas** [comment]
@jeromewu I am experiencing the same or similar issue on 

```
"tesseract.js-core": "^2.0.0-beta.10",
 "tesseract.js-utils": "^1.0.0-beta.8" 
```

my output looks slightly different, however:
![image](https://user-images.githubusercontent.com/13577108/62474552-fc090c80-b757-11e9-9ff8-a03097d499ba.png)

Here is the modification I made to the pageseg mode: 

```
function recognize_img(url_to_img){

	var worker = new TesseractWorker(); 	
	var f = GetImageFromDatabase(url_to_img); 
	if(f === null) return;
	console.log('found image', f);
	worker 
		.recognize(f, 'eng', 
			{
				tessedit_pageseg_mode: '3' 
			})
		.progress((p) => { console.log('progress', p); })
		.then( (result) => { 
					console.log(result.text); 
					worker.terminate(); })
		.catch(error => { console.log(error); });
}
```


Do you have any thoughts on why this is? The err message is not helpful either... I do have `osd.traineddata`, and `eng.traineddata` in my current working directory, as well as `TESS_DATAPREFIX` set to said directory.

**Comment by gblikas** [comment]
@konstantin-dzreev Did upgrading work for you?

**Comment by jarodsmk** [comment]
Happening for me on: `tesseract.js@2.0.0-alpha.15`

Code:
`var result = await worker.recognize("test_image.jpg", "eng", {
      tessedit_pageseg_mode: '1'
    });`

Response:
`... "osd":null ...`

**Comment by gblikas** [comment]
@jeromewu Could you please, re-open this issue?

**Comment by torava** [comment]
I second re-opening this issue. This is a critical issue to be examined. Suggested workaround of doing detect and recognize separately adds unnecessary overhead and complexity compared to just running recognize. It seems like tesseract.js is trying to look for osd.traineddata from a wrong place. Could it be solved by simply fixing the path?

**Comment by innerop** [comment]
ping

**Comment by mortezaataiy** [comment]
Happening to me on `"tesseract.js": "^2.1.1"` same error about `eng.traineddata`
I remove this file and it has no problem for a few days, but it gives the error again :/

**Comment by pppn9595** [comment]
I had the same error but this solved it:
`let worker = Tesseract.createWorker();`
`await worker.load();`
`await worker.loadLanguage('eng+osd');`
`await worker.initialize('eng+osd');`
