### ISSUE TITLE
Which version of tesseract-ocr-chi-sim is showcased on http://tesseract.projectnaptha.com/?

### ISSUE THREAD

**Issue by jchan698** [naptha/tesseract.js#212]
Hello,

This is not really an issue but I was really impressed by the results on the website above; however, when I use the original C++ program tesseract-ocr-chi-sim ver 3.04 it has inferior results. Can anyone tell me which version the website uses?

Many thanks in advance!

**Comment by b4dnewz** [comment]
judging from the last commit dates, around 2/3 years ago, I guess it's the 3.04, but I'm just guessing.
[naptha/tesseract.js/commits/gh-pages](https://github.com/naptha/tesseract.js/commits/gh-pages)

**Comment by jeromewu** [comment]
Yes, it is version 3.04 in the demo page.
