### ISSUE TITLE
Best options for Car Plate

### ISSUE THREAD

**Issue by jfoclpf** [naptha/tesseract.js#213]
Hi, thanks for the free tool

I was reading the [options default object](https://github.com/naptha/tesseract.js/blob/master/docs/tesseract_parameters.md), but I couldn't clearly get my point.

Which options would you suggest, for example to car plates like this, to optimize the recognition process?

Just capital letters and numbers, embedded with a small dash symbol in it.

![matricula_portugal_zorate](https://user-images.githubusercontent.com/3984909/39887513-ac8f3194-5492-11e8-85e3-6673a6393f9b.jpg)

Thank you

**Comment by jeromewu** [comment]
I think default options should be good enough, some people try to use page seg mode of "SINGLE_CHAR", maybe you can try it:

```javascript
import Tesseract from 'tesseract.js';

const { TesseractWorker, PSM } = Tesseract;
const worker = new TesseractWorker();

worker
  .recognize(
    'http://jeroen.github.io/images/testocr.png',
    'eng',
    {
      'tessedit_pageseg_mode': PSM.SINGLE_CHAR,
    }
  )
  .progress((p) => {
    console.log('progress', p);
  })
  .then((result) => {
    console.log(result);
  });
```

**Comment by Duologic** [comment]
I used `tessedit_char_whitelist` for this with this content: https://gist.github.com/Duologic/27f9185a565b3f32721850298db1811f#file-tesseract_poc-html-L131
