### ISSUE TITLE
Tesseract.detect cannot get the result.text

### ISSUE THREAD

**Issue by theodore3131** [naptha/tesseract.js#218]
I tried the demo
`Tesseract.detect(file).then(function (result) {
       alert(result.text);
    });
`
But I only got the alert ("undefined" )
Quite Confusing. Please Help, thanks a lot!

**Comment by Riyaz0001** [comment]
same problem here. any idea?

**Comment by julioBesse** [comment]
Result is a complex object, try result.words (array of words)

**Comment by jeromewu** [comment]
@theodore3131 

There is no `text` field in the result of detect(), I think the function you want to use is recognize(), like this:

```javascript
Tesseract
  .recognize(file)
  .then(function (result) { alert(result.text); }); 
```
