### ISSUE TITLE
Tesseract JS in Android

### ISSUE THREAD

**Issue by jarodium** [naptha/tesseract.js#219]
Hello 

I am experiencing some issues getting Tesseract JS in an Android default webview ( e.g Chrome ).
I keep getting this error:

> Uncaught securityerror: failed to construct 'worker' : access to the script at 'blobl:file:///.....' is denied by the documents content security policy.

My CSP in my page is as following:

`<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">`

Should I try a different CSP? If so, can provide an example so that Tesseract works with an image?

Thanks in advance

**Comment by SwagatRanjit84** [comment]
@jarodium Have you solved the problem? How did you implement on android? I wanted to use on react native

**Comment by jarodium** [comment]
@SwagatRanjit84 haven't figured it out yet.

**Comment by jeromewu** [comment]
You can use workerBlobURL to solve the issue, more details in this PR: https://github.com/naptha/tesseract.js/pull/322
