### ISSUE TITLE
Need help to run tesseractjs locally in offline mode.

### ISSUE THREAD

**Issue by ikismail** [naptha/tesseract.js#220]
Hello, I need to run the tesseract locally in offline mode.

I'm getting **Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': Error: Uncaught SyntaxError: Unexpected end of input could not be cloned**

Downloaded the worker.js, index.js and data.
My project structure : 
![Project_Structure](https://image.ibb.co/eqefa8/file_Structure.png)

Injected the tesseract.js in my index.html and modified the workerOption

![html_file](https://preview.ibb.co/nuN0a8/script_Code.png)

This is how I'm calling recognize funtion

![html](https://preview.ibb.co/d3t6F8/sample_Code.png)

When I run this application using [Chrome Web Server](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en)

Error Img:
![error](https://preview.ibb.co/iCLE2o/error.png)

Can anyone know how to fix this ?

**Comment by jeromewu** [comment]
For offline mode, please check here for an example: https://github.com/jeromewu/tesseract.js-offline
