### ISSUE TITLE
how to detect Send in following image

### ISSUE THREAD

**Issue by srigaurav1986** [naptha/tesseract.js#221]
![myimage0](https://user-images.githubusercontent.com/15980342/41510044-81ca37a4-727b-11e8-9790-cc0ab77ebce4.png)

How to detect "Send" in attached image? It fails everytime.

**Comment by avi9839** [comment]
You can try OCR with inverting the image.

**Comment by jeromewu** [comment]
I think @avi9839 's suggestion is a good solution, close this issue for now.
