### ISSUE TITLE
Tesseract.js doesn't work on arabic language?

### ISSUE THREAD

**Issue by ameurbc** [naptha/tesseract.js#222]
I'm using tesseract.js with nodeJs to recognize arabic text from an image but, unfortunately, it gives me a text which is not compliant with the text of the input image.

the input: العربية

the output:  سوعدعسعة

Here is my Code:

`var tesseract = require('tesseract.js')
var request = require('request')
var fs = require('fs')
var util = require('util');
var path = 'C:/Users/Lenovo/Desktop/projet'
var log_file = fs.createWriteStream(path + '/arab.txt', {flags : 'w'});
var log_stdout = process.stdout;
var filename = 'capture.PNG'
tesseract.create({ langPath: "ara.cube.fold"  })
       .recognize(filename, 'ara')
       .progress(function  (p) { console.log('progress', p)  })
       .catch(err => console.error(err))
       .then(function (result) {
    console.log = function(result) {
      log_file.write(util.format(result) + '\n');
      log_stdout.write(util.format(result) + '\n');
     };
    console.log(result.text)
    process.exit(0)
})`

any solution please!!
Thank you

**Comment by sstubbs** [comment]
I am also having this issue.

**Comment by f4r4zas** [comment]
@ameurbc  i am facing this issue 
Uncaught abort(5) at Error
    at Na (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:36:26)
    at ka (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:511:108)
    at LHa (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:406:25912)
    at Qpa (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:392:44877)
    at kpa (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:392:23029)
    at jpa (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:392:22303)
    at lT (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:391:80568)
    at mT (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:391:80700)
    at BS (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:391:69011)
    at bP (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:387:110121)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

Any solution

**Comment by f4r4zas** [comment]
when reading arabic

**Comment by Riyaz0001** [comment]
sam problem.

**Comment by hanibhat** [comment]
> @ameurbc i am facing this issue
> Uncaught abort(5) at Error
> at Na (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:36:26)
> at ka (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:511:108)
> at LHa (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:406:25912)
> at Qpa (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:392:44877)
> at kpa (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:392:23029)
> at jpa (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:392:22303)
> at lT (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:391:80568)
> at mT (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:391:80700)
> at BS (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:391:69011)
> at bP (https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:387:110121)
> If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
> 
> Any solution

Having the same issue! Any solutions?

**Comment by jeromewu** [comment]
With the next version of tesseract.js, it should work now.

```
$ npm install tesseract.js@next
```

I tried this image: http://mesas.emory.edu/home/images/interior-slideshow/Arabic%20Poem%20Excerpt.jpg

Code:
```javascript
const { TesseractWorker } = require('tesseract.js');
const worker = new TesseractWorker();
const imgName = __dirname + '/image/3.jpg';

worker.recognize(imgName, 'ara')
.then(function (result) {
    console.log('result', result.text)
})
```

**Comment by moda20** [comment]
Hey @jeromewu 
I used your code, upgraded to the last version and got this error 
```Error: LSTM requested, but not present!! Loading tesseract.
mgr->GetComponent(TESSDATA_INTTEMP, &fp):Error:Assert failed:in file /src/src/classify/adaptmatch.cpp, line 538
trap!
trap!
(node:38748) UnhandledPromiseRejectionWarning: #<Object>
(node:38748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```
