### ISSUE TITLE
How to load lang and startup without Extract(Unzip)

### ISSUE THREAD

**Issue by DarKWinGTM** [naptha/tesseract.js#223]
How to load lang and startup without Extract(Unzip)
Trying to make script working on local and reduce CPU usage fo extract lang files, I trying to make it working on python via Flask Module this is script on template

		<script src="{{ url_for('static', filename='tesseract/dist/tesseract.js') }}" onload="TesseractQuery();">
			function TesseractQuery(){
				if(typeof Tesseract != 'undefined'){
					console.log('TESSERACT LOADED ');
					window.Tesseract = Tesseract.create({
						workerPath: "{{ url_for('static', filename='tesseract/dist/worker.js') }}",
						langPath: "{{ url_for('static', filename='tesseract/lang/') }}",
						corePath: "{{ url_for('static', filename='tesseract/index.js') }}",
					});
					Tesseract.recognize('{{ base64 }}', {lang: "eng", classify_bln_numeric_mode: 1 }).progress(function (packet){
						document.querySelector('p').innerHTML = document.querySelector('p').innerHTML + packet;
					}).then(function (data){
						console.log(data.text);
						document.querySelector('img[id*="base64"]').innerHTML = data.text;
					});
				}else{
					setTimeout(function(){TesseractQuery()}, 2000);
				}
			}
		</script>

**Comment by jeromewu** [comment]
@DarKWinGTM 

It is necessary for tesseract.js to work with extracted traineddata, so it is impossible now.

BTW, the *.traineddata used by tesseract.js actually cached in the browser indexedDB, it is slow for the first time, but should be pretty fast afterward.

**Comment by HoldYourWaffle** [comment]
@jeromewu What's stopping you from downloading these files yourself and providing the path to this library?

**Comment by jeromewu** [comment]
@HoldYourWaffle 

Thanks for bringing this question, actually you can totally download these files and host by your own.

Check here for more details: https://github.com/naptha/tesseract.js/blob/master/docs/local-installation.md
