### ISSUE TITLE
How to import Opencv or Imagemagick for ionic 3 before using tesseract

### ISSUE THREAD

**Issue by doantutai** [naptha/tesseract.js#224]
Hi everyone.
How to import Opencv or Imagemagick for ionic before using tesseract. I can't know import it.
You can help me.
Thanks you.

**Comment by jeromewu** [comment]
Not sure about your issue and I don't think importing opencv or imagemagick is related to tesseract.js.

I will close issue for now, you can reopen the issue after providing more details.
