### ISSUE TITLE
Need help to generate PDF document using Tesseract.recognize(image: ImageLike[, options])

### ISSUE THREAD

**Issue by hitendraapatel** [naptha/tesseract.js#226]
Hi,

I am able to get text from image document using Tesseract.recognize(image: ImageLike[, options]) function. When I override the Tesseract.recognize function by passing options parameter like {tessedit_create_pdf : 1},,  it is not generating the PDF document. 

As a reference i have used following link to override parameters

https://github.com/naptha/tesseract.js/blob/master/docs/tesseract_parameters.md

Need help to get PDF document as an output from Tesseract.recognize(image: ImageLike[, options]) function. 

Thanks,

**Comment by douglasjunior** [comment]
Same here. If the PDF is being generated, I do not know where.

**Comment by ManAnRuck** [comment]
I think it doesn't work with this package.
I started to create a new (server-side) Tesseract package with the new n-api Addon feature.
in the tests all works fine, but in my projects there are sometimes problems. if u want to try it or have experience with n-api (or c++) u can help to improve the new package

https://github.com/ManAnRuck/napi-typescript-tesseract

**Comment by jeromewu** [comment]
@hitendraapatel 

With the latest version of tesseract.js, you can now get pdf output.

Install:
```shell
$ npm install tesseract.js@next
```

Check example here: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-pdf-output-200-alpha5

**Comment by janis91** [comment]
> @hitendraapatel
> 
> With the latest version of tesseract.js, you can now get pdf output.
> 
> Install:
> 
> ```shell
> $ npm install tesseract.js@next
> ```
> 
> Check example here: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-pdf-output-200-alpha5

I tried the example and it works very nice. But I still have a question: As my browser always wants to download the pdf directly after the tesseract worker finished ocr, I can't handle the output within JavaScript. Is this possible somehow?
My idea is to integrate it tesseract.js into a file browser app. So I would use the resulting pdf file data and upload it again via ajax directly after the worker has finished.

@jeromewu Is this possible somehow?

**Comment by jeromewu** [comment]
@janis91 

I have added this future in 2.0.0-alpha.7

Check example here: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-pdf-output-200-alpha7

**Comment by janis91** [comment]
@jeromewu this is really cool! Thank you. Btw. a little bit off topic but anyway:
I try to get deeper into the web assembly topic and therefore I am very interested in the how to's etc. But this project is the only REAL project I know so far, that makes a lot of sense. If you plan to write something about the steps and the effort you've made so far in order to show others what they'd have to consider when they try to do similar things. This would be a perfect basis for a blog post :-)
Just in case you didn't thought about it before. Because the material I found so far is not the best imho.

**Comment by jeromewu** [comment]
@janis91 

Thanks for the idea, actually I have plan to write some posts to share experience. Hopefully I can have time to do so in near future. 😄
