### ISSUE TITLE
Testsuite ✅

### ISSUE THREAD

**Issue by zzarcon** [naptha/tesseract.js#23]
I guys, I really the idea of this library, how powerful it is and easy to use. But I was taking a look at the codebase and I realised that there's no current testsuite.

So I think will be great if we can setup an initial testsuite, we can discuss the tools to use on it, Im pretty much happy which any runner or assertion library but since this has to work both in Node.js and in the browser, maybe [Karma-runner](https://github.com/karma-runner/karma) will be a good fit for it? Also a lot of developers are used to work with it and gives you some cool things out of the box :).

Also I think it's important for other developers that want to contribute to the project, because right now they don't know if their changes are actually breaking any of the current behaviours.

Later we can easily integrate the testsuite in Travis and have fast feedback on any change 🚀.

What do you think? Thanks!

**Comment by bijection** [comment]
Thanks! We'd definitely like to have tests — I'll take a look at karma etc this evening.

**Comment by okcoker** [comment]
Since there are no tests currently. I'd highly recommend [AVA](https://github.com/avajs/ava) instead. It's easier to install and simpler to configure than Karma. I'd also like to say it's faster although I have no proof to back that up. 

FWIW I also feel Karma requires you to install so many packages to get started.  I've recently moved from Karma to AVA for all my projects and went from installing like 10 packages (karma, mocha, launchers, coverage, etc) to about 3 or so (AVA, nyc, tap-diff)

**Comment by zzarcon** [comment]
@okcoker good point, I have never tried AVA but I agree with you in all the points you have listed. Based on that I think will be a better choice if we go with AVA instead of Karma.

And also I will learn how to use it 😸

**Comment by bijection** [comment]
We like AVA as well! We're working on getting a few preliminary tests up.

**Comment by skc93** [comment]
AVA

**Comment by jeromewu** [comment]
Right now we use mocha to do unit test, and more testing to work on. close this for now.

**Comment by okcoker** [comment]
Woah this is old. It probably doesn't matter to you guys now but I use jest for testing everything now :P

**Comment by jeromewu** [comment]
In fact I tried jest in fhe first but ran into some performance issue, that's why I switch fo mocha. I know jest is popular now, maybe we will do an update one day.
