### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Anujmoglix** [naptha/tesseract.js#230]
Hi ,
  I am using same code as example but getting nothing from the response in recognise function .What i am doing wrong ? My Recognise function is as following :- 

```
   Tesseract.recognize(this.selectedImage)
            .progress(message => {
                if (message.status === 'recognizing text')
                    console.log("recognizing some text");
            })
            .catch(err => console.error(err))
            .then(result => {
                this.imageText = result.text;
            })
            .finally(resultOrError => {
                console.log("recognizing done");
            });
```

Function is not going in then or even finally . So please have a look into it .

**Comment by JakubRuzicka** [comment]
In my opinion tesseract cant load resources . 
https://cdn.rawgit.com/naptha/tessdata/gh-pages/3.02/ is down.

Is there any solution?

**Comment by JakubRuzicka** [comment]
i tried make tesseract offline but it doesn't work :-(
```
tesseract;
ngOnInit() {
        this.tesseract = Tesseract.create({
            workerPath: './assets/tesseractjs/worker.js',
            langPath: './assets/tesseractjs/lang/',
            corePath: './assets/tesseractjs/index.js',
        });
    }
```
in assets floders 
index.js = https://raw.githubusercontent.com/naptha/tesseract.js-core/master/index.js
worker.js = https://github.com/naptha/tesseract.js/blob/master/dist/worker.js
lang floder = https://github.com/naptha/tessdata/tree/gh-pages/3.02

error message: ERROR TypeError: Cannot read property 'create' of undefined
 What am I doing wrong?

**Comment by Anujmoglix** [comment]
It is working with local images. When i am using file from assets then it is working but with capture image which convert it into base 64 format it doesnot work .

**Comment by Riyaz0001** [comment]
same problem here.

**Comment by jeromewu** [comment]
In the README, there is a session about [ImageLike](https://github.com/naptha/tesseract.js#imagelike).

Right now we don't support base64 format and you need to convert it to any ImageLike object described in the link above.
