### ISSUE TITLE
Quality of OCR - Example.

### ISSUE THREAD

**Issue by KKHAN1991** [naptha/tesseract.js#233]
I am trying to extract data from a driving license or passport.

I have an example here. https://jsfiddle.net/8aL31upr/105 and i am using the following image https://www.eufakes.com/products/uk-unionflag.jpg.

I think the quality of the image is quite good however the result is not good.

    nmvms Luczucz I. $23133 1:“;73"*W m a a 1' “tyiﬁmwmmn Vii—x! ) w! Mk

What can i do to improve this?

**Comment by valerius21** [comment]
I am trying to reproduce the issue.

1. Going to image link to download it
2. Opening the DevTools in Chrome
3. Going to jsfiddle and upload the image
4. Getting the following result:
```json
{"text:" : "it’g DRIVING LICENCE
”K 1 SMITH
z. WILL
3. 25.09.1968 PHILADELPHIA. USA
43.24.09.2017 4c.DVLA K 74
4». 23.09.2027 +
\ 7 5. SMITH609258W99iM17 VA LV
7
WM ~5WI‘M
23. 2 /
ﬁ" ) 8. 25MADDEN ROAD
’ TANDRAGEE
BTSZZDG
5. AM/AZ/A/B‘llB/f/k/q"}
```

Doesn't look that bad to me.

**Comment by KayHS** [comment]
@valerius21 Ye youre right it is working better today. Am i able to improve that result at all?

**Comment by valerius21** [comment]
If it's always the same size and type of document, you can autocrop it somehow and feed only the text parts to the tesseract.js part.

**Comment by valerius21** [comment]
> @valerius21 Ye youre right it is working better today. Am i able to improve that result at all?

If it's always the same size and type of document, you can autocrop it somehow and feed only the text parts to the tesseract.js part.

**Comment by Slapbox** [comment]
I'd guess it has trouble with the font combined with the background. Look at the E, A, and R characters in particular.

**Comment by jeromewu** [comment]
Close as no further discussion.
