### ISSUE TITLE
Will this repository be maintained in the near future?

### ISSUE THREAD

**Issue by valerius21** [naptha/tesseract.js#234]
The last commit was on Feb. 7th (?), and tesseract-OCR is releasing the 4.0 beta. Furthermore, there is no indication that planned features, like the searchable-pdf export, are actively developed.

IMHO, this looks like its maintainers may have abandoned this project. - Or am I missing any information regarding this matter?

**Comment by jeromewu** [comment]
Hi, right now I will continue maintaining this repository. I am planning to upgrade to tesseract-ocr 4.0.0 (will be used in tesseract.js v2) while fixing some know bugs in tesseract.js v1. As there is only me working on this project, the progress may not be fast... Please be patient and I will let you know when there are any updates, also please feel free to report any issues you encountered here and I will try to fix when possible. 😃
