### ISSUE TITLE
update this module in npmjs.com

### ISSUE THREAD

**Issue by rombu** [naptha/tesseract.js#235]
on npmjs.com contained old version. there is an error when specifying langPath.
just update library

**Comment by rombu** [comment]
ok! i created https://www.npmjs.com/package/rombu-tesseract.js

**Comment by douglasjunior** [comment]
this repository seems to be abandoned.

**Comment by jeromewu** [comment]
@rombu 

Sorry for the long waiting, now we have publish a new version v1.0.12 to npmjs.
