### ISSUE TITLE
Loading Tesseract.js in a Cordova / Phonegap application

### ISSUE THREAD

**Issue by HuubSmit** [naptha/tesseract.js#237]
Hello,

I have some serious trouble getting this to work in the Cordova / Phonegap application. I can let it work in the browser version of Cordova but the iOS and Android version don't work. I get the following errors:

TypeError: undefined is not a function (evaluating 'Object.assign({}, adapter.defaultOptions, workerOptions)')

I get this in loading the tesseract.js file locally. It's on the following line:

```
function create() {
	var workerOptions = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};

	THIS LINE > var worker = new TesseractWorker(Object.assign({}, adapter.defaultOptions, workerOptions));
	worker.create = create;
	worker.version = version;
	return worker;
}
```

Anyone has an idea why this isn't working in my Cordova application? 

I want to use this thing offlien because when I try to load it online I cannot get the data back due to Cross Origin. Cannot get that to work, so I want it offline. It's also way faster if I use it offline.

**Comment by HuubSmit** [comment]
Does anyone got this working locally?

I tried it on the server but the only solution seems to be to copy the index.js from the CDN:

https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js

But with this index.js it seems to me that everything is done online and not with the local data. Also the traineddata is always loaded online, it doesn't make any sense. Is the Github page still up to date?

**Comment by shirakaba** [comment]
I got this working locally ([proof](https://twitter.com/LinguaBrowse/status/1059427821452443650)).

See this example project for reference: https://github.com/cyanzhong/xTeko/tree/master/extension-demos/tesseract/www

**Comment by jeromewu** [comment]
@shirakaba great example, thanks for resolving this issue. 😃
