### ISSUE TITLE
cdn.rawgit.com is now 404

### ISSUE THREAD

**Issue by melorzhang** [naptha/tesseract.js#239]
{ status: 'loading tesseract core' }
{ status: 'loaded tesseract core' }
{ status: 'initializing tesseract', progress: 0 }
pre-main prep time: 42 ms
{ status: 'initializing tesseract', progress: 1 }
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_FAIL cdn.rawgit.com:80

error occur when using the default config as rawgit is no longer available.

**Comment by jeromewu** [comment]
@melorzhang 

We are now using jsDelivr as our default CDN, thanks for reporting and please check #244 for details.
