### ISSUE TITLE
Get this working in a chrome extension

### ISSUE THREAD

**Issue by btm1** [naptha/tesseract.js#240]
I'm having trouble getting this to work in a chrome extension. I've installed it via npm and I'm trying to use recognize but just get an error "uncaught" in the console.

Any ideas?

**Comment by jesshyl** [comment]
met this problem too, not solved yet

**Comment by KingRial** [comment]
Same problem; with a little effort I just saw that launching the recognize procedure tries to load a new javascript in the DOM:
http://127.0.0.1:9000/dist/worker.dev.js?nocache=63ialyl5bfq

Which is (obviousy) not available.

Maybe we need to include a builded library instead of simply using "npm i" and importing the Tesseract Class ?

**Comment by jesshyl** [comment]
i downloaded the worker.js index.js and traineddata i need via vpn and placed these files in my custom path ，and change the conf in tesseract.create({conf})，and it worked

**Comment by jeromewu** [comment]
@btm1 

Please kindly check whether the replies above help and I will close this issue for now. 😃

**Comment by alaa137** [comment]
Can someone clarify this please?
I downloaded all files locally, and initialized `Tesseract` like this:
```
const worker = Tesseract.create({
    workerPath: 'path/to/local/browser/worker/worker.js',
    langPath: 'https://tessdata.projectnaptha.com/4.0.0',
    corePath: 'https://unpkg.com/tesseract.js-core@v2.0.0-beta.10/tesseract-core.wasm.js'
});
```
I'm getting the following error:

> worker.js:11 Uncaught ReferenceError: require is not defined at worker.js:11

I need to work locally because I'm developing a chrome extension...

**Comment by jeromewu** [comment]
Please check link below for a chrome extension example:

https://github.com/jeromewu/tesseract.js-chrome-extension
