### ISSUE TITLE
broken link in README.md to cdn script download path

### ISSUE THREAD

**Issue by eddo888** [naptha/tesseract.js#245]
Should read
https://cdnjs.cloudflare.com/ajax/libs/tesseract.js/1.0.10/tesseract.min.js

**Comment by jeromewu** [comment]
In fact is not a typo but we are waiting for cdnjs to approve the changes. 🙏 

Please check here for the progress: https://github.com/cdnjs/cdnjs/pull/13098

**Comment by jeromewu** [comment]
Solved by using other 3rd party services.
