### ISSUE TITLE
Tesseract is less accurate when run via NodeJS vs when run directly in the command line

### ISSUE THREAD

**Issue by FrankieIRL** [naptha/tesseract.js#251]
I am trying to extract text from local PNG images. I'm using Tesseract and running JS files from the command line via node.

If I run Tesseract from the command line it works perfectly, if I run it via Javascript, it does not.

I have read a lot of posts about tips on how to improve accuracy of OCR but that is not the issue here. The issue here is in the fact that the text from the png file I am using CAN be extracted perfectly accurately, but the accuracy varies dramatically depending on which method I use to run Tesseract.

When I run Tesseract directly from the command line using the command `tesseract.exe manual.png usingcommandline` (manual.png is the file I am extracting from and I am saving it to usingcommandline.txt) - the returned file is very accurate.

However, when I run my Javascript file from the command line using node ocr.js (which runs the code below) on the exact same file, it is far less accurate. It is unusable. (The code below creates a vianodejs.txt file with results.text (the text from manual.png in it)

`var Tesseract = require('tesseract.js');
var filename = 'manual.png';
var fs = require('fs');

Tesseract.recognize(filename)
  .then(function (result) {fs.writeFileSync('vianodejs.txt', result.text, function(err) {
        if (err) {
            console.log(err);
        } else {
            console.log("file written successfully");
            }
        })
    process.exit(0)
  })`

It is the exact same manual.png file I am using in both instances but it is far less accurate when I run Tesseract via the Javascript program. Ultimately I need to run it through the Javascript program for my application to work, and I need the level of accuracy that I get with the other method.

I have redownloaded the eng.traineddata file and replaced the old one and it does not help. Also, if I run the same file through http://tesseract.projectnaptha.com/ - I get inaccurate results as I do as when I run the Javascript programme, although the output results are slightly different. The projectnaptha link is also meant to be translating English, the text in my file is English. 

Any help would be much appreciated. Thanks 

I have attached the manual.png file that is being read in both instances.

In case it helps, I have also attached the manual.txt file, which is the output of running tesseract via NodeJS. Also, I've attached the viacmdline.txt file, which is created by running tesseract directly from the command line.

![manual](https://user-images.githubusercontent.com/44464227/49104001-c29d0a80-f274-11e8-8050-758a15648163.PNG)
[viacmdline.txt](https://github.com/naptha/tesseract.js/files/2621420/viacmdline.txt)
[manual.txt](https://github.com/naptha/tesseract.js/files/2621421/manual.txt)

**Comment by jeromewu** [comment]
Can you kindly provide manual.png for our reference? Thanks.

**Comment by FrankieIRL** [comment]
> Can you kindly provide manual.png for our reference? Thanks.

Hi Jerome, thank you very much for your interest. I have attached to this comment the manual.png file that is being read in both instances. 

In case it helps, I have also attached the manual.txt file, which is the output of running tesseract via NodeJS. Also, I've attached the viacmdline.txt file, which is created by running tesseract directly from the command line.

Thanks

![manual](https://user-images.githubusercontent.com/44464227/49103830-515d5780-f274-11e8-8dd6-d14d3c8f1a00.PNG)

[viacmdline.txt](https://github.com/naptha/tesseract.js/files/2621401/viacmdline.txt)

[manual.txt](https://github.com/naptha/tesseract.js/files/2621407/manual.txt)

**Comment by jeromewu** [comment]
I have tried to use the latest version of tesseract.js (in develop branch), so far the best I can get is the result below:

tesseract.js (with tesseract 4.0 as its core)
```
 19:00

View 10+ more

Know this place? Answer quick questions

Que_s_tluns & answers Aska question

Qs tjust Farmers, that go here 7 Lt

A: No, there’s no farmers in the ciy! If they are they're on tourist status,

theyll be starting calving season this week or next so there wil be even.

(4 more answers)

See all questions (6)

Popular times @ Thursdays 3

2.9 pm. Usually not busy
< >
_—_ millm

s 3 & % 22 3:

Plan your visit

People typically spend 1.5-3 hours here
```

tesseract 4.0 commandline
```
19:00

View 10+ more

Know this place? Answer q



questions

Questions & answers

Q: Is it just Farmers, that go here ? ere

‘A: No, there’s no farmers in the city! If they are they're on tourist status,
they'll be starting calving season this week or next so there will be even.

(4 more answers)
See all questions (6)

Popular times @ ‘Thursdays >

8.9 p.m: Usually not busy



9a 12p 3p & 9p 128 3a

Plan your visit
People typically spend 1.5-3 hours here
```

I think the differences is caused by the fact we transpile C to JavaScript by emscripten, and it makes the algorithm is somehow less precise compare to the original version.

**Comment by FrankieIRL** [comment]
Hi Jerome, sorry I am just getting ack to the project. Thanks for your time. Do you have any thoughts on why the first version you have is far more accurate than mine? When I run it via the js program with tesseract v4.0.0.20181030 I am still getting the strange results as in the manual.txt file above. Thanks

**Comment by geoyws** [comment]
I'm getting irregular results as well. Sometimes it's spot on and sometimes it's just giving me weird letters. :(

![Screenshot 2020-05-22 at 2 24 19 AM](https://user-images.githubusercontent.com/1738396/82593151-9c8bc880-9bd4-11ea-93b2-cbb6e9a4bb45.png)

This results in:
```
Text: Barrington Publishers
17 Great St et
London SE1 NS

Uritd Kngdom
```
