### ISSUE TITLE
How do I output the conents to a text file?

### ISSUE THREAD

**Issue by ShadeLinux** [naptha/tesseract.js#256]
Hello. I need to save the contents that are displayed in the console to a text file. I tried using FileSync but keep getting "[object Object]" in my text file. Can I output it to a text file? Thanks!

**Comment by jeromewu** [comment]
@ShadeLinux 

Can you provide sample code for this case?

**Comment by jeromewu** [comment]
Close for now, feel free to reopen with more information.
