### ISSUE TITLE
Unable to ocr a large png file.

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [naptha/tesseract.js#257]
When I attempt to do so via an img element (whose image is loaded and visible), I get partial progress up through intiialization, then it throws this error:

```
/somepath/node_modules/tesseract.js/src/common/desaturate.js:22
    } else { throw 'Invalid ImageData' }
             ^
Invalid ImageData
```

The image is large, 300 dpi and about 10 inches tall. It's in color (do I need to bust these down to monochrome?). I've only just now started using this, so I'm afraid that I'm missing something simple, but the same image is processed by command-line tesseract without any errors or warnings.

**Comment by jeromewu** [comment]
Can you kindly help to provide the image you tried? It will be easier for us to find out the root cause.

**Comment by jeromewu** [comment]
Close due to no further responses.
