### ISSUE TITLE
Multi-language recognition

### ISSUE THREAD

**Issue by HoldYourWaffle** [naptha/tesseract.js#260]
Is it possible to use multiple language dictionaries at the same time?
I know [it's possible](https://stackoverflow.com/questions/24379781/tesseract-how-to-run-tesseract-with-multiple-languages-one-time) using commandline tesseract, I just can't figure out how to do it in tesseract.js.

I tried the following:
```js
Tesseract.recognize(input, { lang: 'eng+deu' }) ...
Tesseract.recognize(input, { lang: ['eng', 'deu'] }) ...
```

Both options give similar errors:
```
Error downloading language https://tessdata.projectnaptha.com/3.02/eng+deu.traineddata.gz
```

Is it possible to use multiple languages while recognizing using tesseract.js? If not, what could be possible workarounds? I'd love to implement this on my own and create a pr, but I know close to nothing about tesseract or this specific project.

Any help would be greatly appreciated!

**Comment by jeromewu** [comment]
Right now tesseract.js v1 doesn't support multiple, it is a planned feature for v2 (which is work in progress).

**Comment by HoldYourWaffle** [comment]
That's unfortunate, how long will it be until v2 is released?
Are there any possible workarounds like merging dictionary files or something?

**Comment by shinnthantminn** [comment]
Pls show me how can I do multi-language with tesseract.js

**Comment by ChathuraGH** [comment]
It is now possible to use multiple languages.
Like below.
`Tesseract.recognize(input, { lang: 'eng+deu' })`
