### ISSUE TITLE
Failed to find module: "isomorphic-fetch"

### ISSUE THREAD

**Issue by SethaVa** [naptha/tesseract.js#262]
I have some troubles using tesseract.js with native-script-vue on android:

> import Tesseract from "../tesseract.js";

    export default {
        data() {
            return {};
        },
        created(){
            this._getTranslate()
        },
        methods: {
            _getTranslate() {
                const native_img ="https://upload.wikimedia.org/wikipedia/en/3/33/Hello_world%21.png";
                Tesseract.recognize(native_img).then(function(result) {
                    console.log(result);
                });
            }
        }
    };

===============================================
but got this error in console:

> Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "isomorphic-fetch", relative to: app/tns_modules/
com.tns.Module.resolvePathHelper(Module.java:146)
com.tns.Module.resolvePath(Module.java:55)
com.tns.Runtime.runModule(Native Method)
com.tns.Runtime.runModule(Runtime.java:553)
com.tns.Runtime.run(Runtime.java:545)
com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
android.app.ActivityThread.-wrap3(ActivityThread.java)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:154)
android.app.ActivityThread.main(ActivityThread.java:6682)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tesseract.js/src/node/index.js', line: 3, column: 13
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tesseract.js/src/index.js', line: 7, column: 15
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/components/HelloWorld.js', line: 7, column: 18
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.js', line: 7, column: 19
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "isomorphic-fetch", relative to: app/tns_modules/
com.tns.Module.resolvePathHelper(Module.java:146)
com.tns.Module.resolvePath(Module.java:55)
com.tns.Runtime.runModule(Native Method)
com.tns.Runtime.runModule(Runtime.java:553)
com.tns.Runtime.run(Runtime.java:545)
com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
android.app.ActivityThread.-wrap3(ActivityThread.java)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:154)
android.app.ActivityThread.main(ActivityThread.java:6682)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tesseract.js/src/node/index.js', line: 3, column: 13
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tesseract.js/src/index.js', line: 7, column: 15
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/components/HelloWorld.js', line: 7, column: 18
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.js', line: 7, column: 19
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "isomorphic-fetch", relative to: app/tns_modules/
com.tns.Module.resolvePathHelper(Module.java:146)
com.tns.Module.resolvePath(Module.java:55)
com.tns.Runtime.runModule(Native Method)
com.tns.Runtime.runModule(Runtime.java:553)
com.tns.Runtime.run(Runtime.java:545)
com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
android.app.ActivityThread.-wrap3(ActivityThread.java)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:154)
android.app.ActivityThread.main(ActivityThread.java:6682)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tesseract.js/src/node/index.js', line: 3, column: 13
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tesseract.js/src/index.js', line: 7, column: 15
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/components/HelloWorld.js', line: 7, column: 18
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.js', line: 7, column: 19
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "isomorphic-fetch", relative to: app/tns_modules/
com.tns.Module.resolvePathHelper(Module.java:146)
com.tns.Module.resolvePath(Module.java:55)
com.tns.Runtime.runModule(Native Method)
com.tns.Runtime.runModule(Runtime.java:553)
com.tns.Runtime.run(Runtime.java:545)
com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
android.app.ActivityThread.-wrap3(ActivityThread.java)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:154)
android.app.ActivityThread.main(ActivityThread.java:6682)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tesseract.js/src/node/index.js', line: 3, column: 13
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tesseract.js/src/index.js', line: 7, column: 15
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/components/HelloWorld.js', line: 7, column: 18
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.js', line: 7, column: 19
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "isomorphic-fetch", relative to: app/tns_modules/
com.tns.Module.resolvePathHelper(Module.java:146)
com.tns.Module.resolvePath(Module.java:55)
com.tns.Runtime.runModule(Native Method)
com.tns.Runtime.runModule(Runtime.java:553)
com.tns.Runtime.run(Runtime.java:545)
com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
android.app.ActivityThread.-wrap3(ActivityThread.java)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:154)
android.app.ActivityThread.main(ActivityThread.java:6682)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tesseract.js/src/node/index.js', line: 3, column: 13
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tesseract.js/src/index.js', line: 7, column: 15
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/components/HelloWorld.js', line: 7, column: 18
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/app.js', line: 7, column: 19
Frame: function:'require', file:'', line: 1, column: 266

at com.tns.Runtime.runModule(Native Method)
at com.tns.Runtime.runModule(Runtime.java:553)
at com.tns.Runtime.run(Runtime.java:545)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
at android.app.ActivityThread.-wrap3(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by jeromewu** [comment]
Looks like the isomorphic-fetch is not installed, have you tried to install it following command?

```
$ npm install --save isomorphic-fetch
```

**Comment by jeromewu** [comment]
Close this issue for no further responses.
