### ISSUE TITLE
why is OCR slower on my macbook pro than the online demo?

### ISSUE THREAD

**Issue by whatsdis** [naptha/tesseract.js#264]
It was working great for two lines of text but I bumped it up to a 8 lines of text and now it's just taking forever to OCR (~1min).

But when I upload the same image in the online teressact.js demo, it works almost instantly.

Why does this discrepancy exist, how can I make terresact respond faster?

is this normal when you have more verbose texts to analyze? I didn't think it was too heavy either. these are no more than 60 or less words.

when I test it with only one line of text, it works within seconds.

so is there anyway to split up the image and have it run in parallel somehow with the right order so the lines don't get jumbled up?

**Comment by jeromewu** [comment]
@whatsdis 

Can you provide an example image?

**Comment by jeromewu** [comment]
Close for now, feel free to reopen with more information.
