### ISSUE TITLE
no result after detection ?

### ISSUE THREAD

**Issue by crapthings** [naptha/tesseract.js#268]
{tesseract_script_id: 5, script: "NULL", script_confidence: 0.8333334922790527, orientation_degrees: 0, orientation_confidence: 0.23003005981445312}
orientation_confidence: 0.23003005981445312
orientation_degrees: 0
script: "NULL"
script_confidence: 0.8333334922790527
tesseract_script_id: 5

```
window.Tesseract = Tesseract.create({
  workerPath: '/dist/worker.dev.js',
  langPath: 'https://tessdata.projectnaptha.com/3.02/',
  corePath: 'https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js',
})
```

```
Tesseract.detect(img, { lang: 'eng' })
      .progress(function(message) { console.log(message) })
      .then(function(a){
        console.log(a)
      })

```

![image](https://user-images.githubusercontent.com/1147704/53286671-eeb12480-37ac-11e9-85e9-0d0324390ec4.png)

i m trying to detect image after crop, but i only got above json

**Comment by HoldYourWaffle** [comment]
You probably want to use [Tesseract.recognize](https://github.com/naptha/tesseract.js#tesseractrecognizeimage-imagelike-options---tesseractjob) instead of [Tesseract.detect](https://github.com/naptha/tesseract.js#tesseractdetectimage-imagelike---tesseractjob).

**Comment by crapthings** [comment]
ooops
