### ISSUE TITLE
Read line by line

### ISSUE THREAD

**Issue by Mr0Inka** [naptha/tesseract.js#273]
Hey,  

If I understand tesseract correctly, it first reads the image, applies some changes, filters etc to make it more readable, detect the lines and then it starts recognizing the text in those lines.  

Is there any way how I could get those lines before it finishes recognizing the whole document or would I need to literally split the image and then pass each line as an image to tesseract?

To try this, I split a test image by hand and ran those through tesseract. This speeds up the process (for my specific use-case) by a lot.

Result: https://gyazo.com/3e50e40bb7b2f07190c4a2377b65c92d

Is there a built-in way to output each line or would I need to detect the lines and split the image outside of tesseract?

Thanks in advance!

**Comment by jeromewu** [comment]
Hi, in the latest version of the tesseract.js, we introduce a new feature to assign the range of image you want to recognize, it can fix this issue.

Check here: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-only-part-of-the-image-200-alpha12

**Comment by jeromewu** [comment]
Close for now, feel free to reopen with more information.
