### ISSUE TITLE
Internal working of the library

### ISSUE THREAD

**Issue by ShadabFaiz** [naptha/tesseract.js#274]
How does tesseract internally detect character from an image? Does it use Machine learning /OpenCV or their trained models?

**Comment by jeromewu** [comment]
Starting from tesseract ocr v4 (which maps to tesseract.js v2), it uses LSTM as it core engine. So I think it belongs to Machine Learning approaches.

More deitals: http://colah.github.io/posts/2015-08-Understanding-LSTMs/
