### ISSUE TITLE
initialization doesn't return on Windows 10 Edge browser

### ISSUE THREAD

**Issue by bowang01** [naptha/tesseract.js#275]
While it works on Windows Explore 11 browser, the initialization process doesn't return on Windows 10 Edge browser.
For example, load main web site http://tesseract.projectnaptha.com/ in Edge and notice demo can't continue.

**Comment by jeromewu** [comment]
The quick solution will be using some polyfill in edge browser, but right now I haven't found out which polyfill(s) to use...

**Comment by HoldYourWaffle** [comment]
Shouldn't the choice of polyfill lie with the user?

**Comment by jeromewu** [comment]
After some primary research, I think the issue is caused not only by tesseract.js, but from some of its dependencies (like zlib.js), it involves a lot of changes to make, so I will keep it pending for now.

Of course, any PR is highly welcome. 😄

**Comment by jeromewu** [comment]
Great! thanks for reporting.
