### ISSUE TITLE
Always Failed to detect OS

### ISSUE THREAD

**Issue by zhaochy1990** [naptha/tesseract.js#277]
I'm using mac osx Mojave 10.14.4
my code is like the following:

```
  const img = path.resolve(__dirname, 'name.jpeg');
  Tesseract.detect(img)
    .progress(function (info) {
      console.log(info);
    })
    .then(function (data) {
      console.log('done', data);
      process.exit();
    })
    .catch((e) => {
      console.log(e);
    })
```

always failed by "Failed to detect OS"

can anyone help me?

**Comment by jeromewu** [comment]
Can you provide the image you input? It will be helpful for debugging.

**Comment by jeromewu** [comment]
Close for now, feel free to reopen with more information 😄
