### ISSUE TITLE
Demo page is not working on Chrome 54

### ISSUE THREAD

**Issue by Agnostic** [naptha/tesseract.js#28]
![screen shot 2016-10-13 at 11 38 35 am](https://cloud.githubusercontent.com/assets/1162988/19358004/ad74a3a0-9139-11e6-9db2-2c77971ba0bc.png)

**Comment by bijection** [comment]
What OS? Does that happen every time? I'm on chrome 54 on OSX 10.11 and it's working for me.
![image](https://cloud.githubusercontent.com/assets/8824442/19363104/18df7990-9157-11e6-99bd-8b0bfc7bc816.png)
![image](https://cloud.githubusercontent.com/assets/8824442/19363129/3b0ccb76-9157-11e6-9666-fd07549e49af.png)

**Comment by Agnostic** [comment]
OS X 10.12

**Comment by bijection** [comment]
Ok I'll try test that out on 10.12 this evening. Does that error happen for you every time?

**Comment by Agnostic** [comment]
It's working now, I don't know what happened =/

**Comment by bijection** [comment]
Ok closing this for now, feel free to open another issue if you reproduce the bug!
