### ISSUE TITLE
Website code available?

### ISSUE THREAD

**Issue by howardroark2018** [naptha/tesseract.js#281]
hi,
Is the code of the working website at : https://tesseract.projectnaptha.com/ also included in the repo?  I was searching for a simple online solution for OCR that I can host on my server and use it as easily as it's done on the main website, which is just draggin' and droppin and then clicking a button to translate. by the way, this is a fabulous piece of work and I really love it!  

Thanks!

**Comment by jeromewu** [comment]
The code of the website is here: https://github.com/naptha/tesseract.js/tree/gh-pages

Feel free to take a look. 😄
