### ISSUE TITLE
Specify path to .wasm file in v2.0.0-beta.5

### ISSUE THREAD

**Issue by ryan-codingintrigue** [naptha/tesseract.js#282]
**Problem.**
In the latest version of `tesseract.js-core@v2.0.0-beta.5` the `.wasm` file is embedded within the file as a Base64 Data URI.

Any workers which have an appropriately strict [`connect-src`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src) `Content-Security-Policy` header in place will fail to load.

In addition to the above, it might be nice to be able to cache the `.wasm` separately from the worker `.js`

**Describe the solution you'd like**
It would be great if we could optionally specify a path to the `.wasm` file for the worker to fetch from. If that path isn't specified, then the worker may download from Base64 as a fallback

**Comment by jeromewu** [comment]
@ryan-codingintrigue 

Is there any side effect if we choose to provide only non-embedded version? I am not quiet sure about how to do both with fallback capability.

**Comment by ryan-codingintrigue** [comment]
It does mean that you must specify some form of `wasmPath` to locate the file which is unfortunately another parameter.

I think the usual thing to do is, if a path is provided use that, otherwise fallback to the current directory + wasm filename.
```js
if(options.wasmPath) {
    fetch(options.wasmPath)
} else {
    fetch("tesseract.wasm");
}
```

If you wanted to avoid that, you could provide two distinct core bundles which can be used for `corePath` if desired:
- `tesseract-core.js` - Default. Contains `fetch("data:application/octet-stream...)`
- `tesseract.js-core-external.js` - Optional. Contains `fetch(options.wasmPath)`

**Comment by jeromewu** [comment]
I have upgrade tesseract-core.js to [2.0.0-beta.8](https://github.com/naptha/tesseract.js-core/tree/v2.0.0-beta.8) which contains 3 versions of tesseract-core:

- ASM version: https://unpkg.com/tesseract.js-core@2.0.0-beta.8/tesseract-core.asm.js
- WASM version (embedded): https://unpkg.com/tesseract.js-core@2.0.0-beta.8/tesseract-core.wasm.js
- WASM version:
  - javascript: https://unpkg.com/tesseract.js-core@2.0.0-beta.8/tesseract-core.js
  - wasm: https://unpkg.com/tesseract.js-core@2.0.0-beta.8/tesseract-core.wasm

Right now ASM version and WASM version (embedded) and it works fine, but I actually cannot get WASM version working. I leave it there for now, and feel free to send PR 😃 

BTW, you can try it using code below (in browser):

```javascript
const { TesseractWorker } = Tesseract;
const worker = new TesseractWorker({
  corePath: 'https://unpkg.com/tesseract.js-core@2.0.0-beta.8/tesseract-core.js',
});

worker
  .recognize(image)
  .then(result => console.log(result.text));
```

**Comment by WebReflection** [comment]
FWIW, this is how I managed to make it work via an extension:

```js
const worker = createWorker({
  errorHandler: console.error,
  workerBlobURL: false,
  workerPath: extension.getURL("js/worker.js"),
  corePath: extension.getURL("js/tesseract-core.wasm.js"),
  langPath: extension.getURL("tessdata")
});
```

At least in Firefox, this doesn't result into loading anything embedded, and the `js/tesseract-core.wasm.js` path is retrieved without issues.

**Comment by Balearica** [comment]
Closing the issue as the existing solution (embedded js/wasm) seems to work fine.  Feel free to reopen if there's a compelling reason for pursuing this further.
