### ISSUE TITLE
Module much slower than syscall to tesseract

### ISSUE THREAD

**Issue by GuiJordao21** [naptha/tesseract.js#283]
**Describe the bug**
ocr of a page takes 3 to 4 times longer using the module than with a sys call to tesseract using child process.

**To Reproduce**
const Tesseract = require('tesseract.js'),
    fs = require('fs'),
    path = require('path');

const tesseractjsMod = () => {

    let myImage = fs.readFileSync("./temp-img-folder/Pic-1.png");

    console.log(myImage);

    console.log(process.hrtime());

    Tesseract.recognize(myImage, {
        lang: 'por',
    })
        .then(function (result) {
            console.log(`package call ->>>`, process.hrtime());
            return 0;
        });
};

const syscall = () => {
    const { exec } = require('child_process');
    exec('tesseract ./temp-img-folder/Pic-1.png stdout -l por', (err, stdout, stderr) => {
        if (err) {
            // node couldn't execute the command
            return;
        }

        // the *entire* stdout and stderr (buffered)
        console.log(`stdout: ${stdout}`);
        console.log(`stderr: ${stderr}`);
        console.log(`syscall ->>>`, process.hrtime());
    });
};

console.log(`init ->>>`, process.hrtime());
tesseractjsMod();
syscall();

package - 1.0.16
tesseract-ocr - 4

**Comment by jeromewu** [comment]
I think it is quiet normal for tesseract being faster than tesseract.js, after all tesseract is native C built and should get the maximum possible.

This is not a bug, so I will close for now.
