### ISSUE TITLE
Fetch API cannot load URL scheme "file" is not supported.

### ISSUE THREAD

**Issue by whistlerman** [naptha/tesseract.js#285]
Hi, I tried to use tesseract.js v2 into mine project. when running on real android device, the method "t.fetch(`${e}/${f}.traineddata.gz`)" in worker.min.js fails because of the following error: "Fetch API cannot load file:///storage/emulated/0/Android/data/..../js/ocr_v2/customize.traineddata.gz. URL scheme "file" is not supported."

Here is my code:
`

       new Tesseract.TesseractWorker({
	     workerPath: plus.io.convertLocalFileSystemURL( '/js/ocr_v2/worker.min.js' ),
	     langPath :  plus.io.convertLocalFileSystemURL( '/js/ocr_v2' ),
	     corePath :  plus.io.convertLocalFileSystemURL( '/js/ocr_v2/tesseract-core.wasm.js' )						
	   })...
`

Is there any solutions can resolve this problem?Thanks a lot.

**Comment by jeromewu** [comment]
Right now we don't support `file://` url, but relative path like './foo/bar/worker.min.js' is supported in node.js. I haven't try it in android environment, so right now it will hard for me to help.

BTW, are you using frameworks like cordova to use tesseract.js?

**Comment by whistlerman** [comment]
Thank you for your patient reply, jerome.I am using  h5 to use tesseract.js instead of any frameworks. I have 
 already integrated tesseract.js v1 into my app project, it works well !  Now i am looking forward to upgrading tesseract.js from v1 to v2.  Thank u for your outstanding contributions once more.

**Comment by jeromewu** [comment]
After some survey, I believe you are using HBuilder to build the application (from the API in the sample code above), I think the issue here is that you need to read the *.traineddata by yourself, please check tesseract.js-cordova as a reference to solve the issue.

https://github.com/jeromewu/tesseract.js-cordova/blob/master/www/js/main.js
