### ISSUE TITLE
How to generate TSV and HOCR output

### ISSUE THREAD

**Issue by hezjing** [naptha/tesseract.js#287]
Hi,

[Tesseract 4's command line](https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage) is able to generate TSV and HOCR output.

May I know if it is possible to generate TSV and HOCR output from an image using tesseract.js?

**Comment by jeromewu** [comment]
For TSV and HOCR, you get them from result object, check link below for more details:

https://github.com/naptha/tesseract.js/blob/master/docs/faq.md#how-can-i-get-hocr-tsv-box-unlv-osd
