### ISSUE TITLE
cann't get language package eng.traineddata.gz 

### ISSUE THREAD

**Issue by andyhx** [naptha/tesseract.js#29]
hi, I met with this problem 
![image](https://cloud.githubusercontent.com/assets/7508723/19374734/a6b4aeee-9200-11e6-920b-55ddf419c758.png)

**Comment by andyhx** [comment]
can i use the trained data to  my local filefolders

**Comment by zhangmin510** [comment]
can download with https://github.com/naptha/tessdata/tree/gh-pages/3.02

**Comment by andyhx** [comment]
thank u!
