### ISSUE TITLE
Cannot manually save pdf using 'pdf_bin' option. PDF bin data has weird format

### ISSUE THREAD

**Issue by ev45ive** [naptha/tesseract.js#291]
**Describe the bug**
Enabling pdf options ( pdf_bin ) creates result.files.pdf as some weird object that is not a buffer nor TypedArray nor Stream, just some weird Object that wont convert to anything I can write back to disk as workiing PDF

https://github.com/naptha/tesseract.js/blob/master/docs/tesseract_parameters.md
```
pdf_bin | boolean | false | whether to include pdf binary array in the result object (result.files.pdf)
```

**To Reproduce**
Follow steps From documentation
```js
import Tesseract from 'tesseract.js';

const { TesseractWorker } = Tesseract;
const worker = new TesseractWorker();

worker
  .recognize(
    'https://tesseract.projectnaptha.com/img/eng_bw.png',
    'eng',
    {
      'tessedit_create_pdf': '1',
      'pdf_auto_download': false, // disable auto download
      'pdf_bin': true,            // add pdf file bin array in result
    }
  )
  .progress((p) => {
    console.log('progress', p);
  })
  .then(({ text, files }) => {
    console.log(text);
    files.pdf // << what type is this?
   fs.writeFileSync('somepath/some.pdf', files.pdf) // Doesn`t work
   fs.writeFileSync('somepath/some.pdf', Buffer.from(files.pdf)) // Doesn`t work
   fs.writeFileSync('somepath/some.pdf', Uint8Array.from(files.pdf)) // Doesn`t work
  });
```

**Expected behavior**
```
 recognise('somepath/test.png', 'eng', {
        tessedit_create_pdf: "1",
        pdf_auto_download: false, // disable auto download
        pdf_bin: true // add pdf file bin array in result.files.pdf
}).then( result => 
   fs.writeFileSync('somepath/some.pdf', result.files.pdf) // Should just work
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: NodeJS v10.13.0
 - Version:  "^2.0.0-alpha.7", 

**Additional context**
Documentation is showing options but missing example how to use the result of that option. Would be great is we could add one line where we saving pdf ourselves. :-)

**Comment by ev45ive** [comment]
Ok. I found it! :D 
```
        fs.writeFileSync(
          "temp/test.pdf",  Buffer.from(Object.values(  page.files.pdf  ), 'binary'), )
```
It works, but its CRAZY. I wasted 2 hours on it. :-( 

Should work like this:

```
        fs.writeFileSync( "temp/test.pdf",    page.files.pdf  )
```
So - turining options:
```
        tessedit_create_pdf: "1",
        pdf_auto_download: false, // disable auto download
        pdf_bin: true // add pdf file bin array in result.files.pdf
```
Should have result with:

result.files.pdf as a binary buffer

Currently its and Object in a form :
{ '65032': 314, ... }

Which is NOT ArrayLike because keys are strings, so AnyArray.from(result.files.pdf) returns empty

Should be buffer, or at least TypedArray / ArrayLike object with keys as numbers so Array.from works.

And docs needs to be updated

Version:
    "tesseract.js": "^2.0.0-alpha.7",

**Comment by jeromewu** [comment]
We have enhanced the document to address this issue, thanks for the solution.

Link: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-pdf-output-200-alpha7
