### ISSUE TITLE
Tesseract worker threads

### ISSUE THREAD

**Issue by chocolatetoothpaste** [naptha/tesseract.js#293]
I didn't know whether to file this as a bug or feature request. I am trying to run tesseract in worker threads, but it is either not possible or maybe I'm doing it wrong. I get the following error after the first couple of threads start running:

Error opening data file ./eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!

I suspect the threads are all trying to open eng.traineddata at the same time and corrupting the file. Is there a way to run tesseract in threads without causing conflicts over eng.traineddata?

**Comment by chocolatetoothpaste** [comment]
I replaced the eng.traineddata file with one from the repo, I am able to avoid this error in most instances. I am now getting out of memory errors as well as this output:

./node_modules/tesseract.js-core/tesseract-core.js:8
var Module=typeof TesseractCoreWASM!=="undefined"?TesseractCoreWASM:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=(function(status,toThrow){throw toThrow});Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}else{return scriptDirectory+path}}if(ENV
abort("abort(\"trap!\"). Build with -s ASSERTIONS=1 for more info."). Build with -s ASSERTIONS=1 for more info.
progress { status: 'recognizing text', progress: 0 }
AdaptedTemplates != nullptr:Error:Assert failed:in file /src/src/classify/adaptmatch.cpp, line 197
trap!
trap!
abort("trap!"). Build with -s ASSERTIONS=1 for more info.
abort("trap!"). Build with -s ASSERTIONS=1 for more info.

Is there any method that can be used to clear out memory on each iteration?

**Comment by jeromewu** [comment]
Can you provide a minial example to reproduce the issue? That will be very helpful, thanks.

**Comment by jeromewu** [comment]
Close due to inactivity, free feel to open again with more information.
