### ISSUE TITLE
Feature request: whitelist chars to parse.

### ISSUE THREAD

**Issue by QimatLuo** [naptha/tesseract.js#298]
In my use case, I'm parsing numbers only, which no need to parse a-zA-Z.
When I provide an image which only contains numbers and (, ), +, -, %
But the result will have some English chars.

I want to fill in a whitelist of chars, so the result will be more correct.
Like an array of chars ['0', '1', '2',......'-', '+']
Or a regex will be good /[0-9-+]

Hope this feature can let the parse result more correct.

**Comment by QimatLuo** [comment]
I saw https://github.com/naptha/tesseract.js/blob/master/docs/tesseract_parameters.md support `tessedit_char_whitelist`, but looks not works for me, it still shows English on the result.

**Comment by jeromewu** [comment]
Please check the example here: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-whitelist-char-200-alpha5

This feature is supported after v2.0.0-alpha.5
