### ISSUE TITLE
Lacking documentation

### ISSUE THREAD

**Issue by AlexGustafsson** [naptha/tesseract.js#3]
This library seems promising and very capable. The demo page is great but the documentation is severely lacking - so lacking that I've wondered if it even works.

It's a shame that such a good library risk not getting used by people since they won't understand it without looking through code.

**Comment by rishantagarwal** [comment]
:+1:

**Comment by gamecubate** [comment]
Books and covers... commitment to a project is not a function of its front page, sadly.

**Comment by antimatter15** [comment]
Fixed

**Comment by AlexGustafsson** [comment]
Nice to see that the "relaunch" brought this repo up to trending today. Well deserved!
