### ISSUE TITLE
Doesn't work for Arabic

### ISSUE THREAD

**Issue by antimatter15** [naptha/tesseract.js#30]
Sample image:

![image](https://cloud.githubusercontent.com/assets/30054/19374895/4fb3eaf0-919d-11e6-8124-390af3f4c32d.png)

Error:

![image](https://cloud.githubusercontent.com/assets/30054/19374907/6ddb7b2e-919d-11e6-9733-a82f9b0a05fc.png)

Code

```
Tesseract.recognize(myImageA2,{lang: 'ara'})
    .then(function(result){console.log(result); alert(result.text);})
```

**Comment by amitdo** [comment]
Arabic uses the 'Cube' engine. All the ara cube files are needed.

**Comment by f4r4zas** [comment]
@amitdo How do i use the cub engine

**Comment by f4r4zas** [comment]
and where do i please the ara files

**Comment by jeromewu** [comment]
Should work lang code `ara` now, feel free to reopen with more information.
