### ISSUE TITLE
English Characters even when English isn't chosen?

### ISSUE THREAD

**Issue by DataRogue** [naptha/tesseract.js#300]
I'm trying to get it Tesseract to read Chinese (Simplified) text. However it when dealing with particularly hard to read text, Tesseract starts throwing out English characters despite this being my setting.
```
            loadLang({ langs: "chi_sim", langPath: worker.options.langPath })
            .then(() => {
                worker
                .recognize("./current.png", "chi_sim")
                .progress(p => console.log(p))
                .then(({ text }) => {
                    console.log(text);
```

I had even removed the local eng.traindata.

**Comment by jeromewu** [comment]
Can you provide the image you used? It will be easier for us to debug.

**Comment by jeromewu** [comment]
Close for now, feel free to reopen with more information :smile:
