### ISSUE TITLE
Allow user to do axios request for image

### ISSUE THREAD

**Issue by arifmahmudrana** [naptha/tesseract.js#301]
**Is your feature request related to a problem? Please describe.**
Currently I am requesting for an image where I need to pass some extra headers but as I am doing the ajax request there is no way to pass the response. I have to save the file locally then again pass the path to recognize function

**Describe the solution you'd like**
I don't about the solution yet

**Describe alternatives you've considered**
I save the file to local storage & then serve to recognize function

**Additional context**
No

My question https://stackoverflow.com/q/56742191/1025130 for more details.

**Comment by jeromewu** [comment]
@andrewthehan 

After checking the issue and stackoverflow, I am not sure about your requirement, can you elaborate more details?

**Comment by arifmahmudrana** [comment]
Currently in ```recognize``` function you can only pass paths if it's an URL tesseract but what if I had to pass some other extra header I didn't found any way. As a result I had to save the file. But seems it's resolved as now it's possible to send data:image as source for loadImage function or buffer https://github.com/naptha/tesseract.js/blob/5dd382a67a88bca399e39d792bce7b237c0e5682/src/node/index.js#L33-L50

So @andrewthehan & @jeromewu I am closing this.

Thanks for such an awesome package.
