### ISSUE TITLE
Memory Access out of Bounds when ruunning PSM mode 0 using CDN

### ISSUE THREAD

**Issue by tehtea** [naptha/tesseract.js#303]
**Describe the bug**

I tried to run `worker.recognize` on an usual 'transactions summary' image in English which is 960x1280 pixels big. The tesseract config used for this was:
```
    tessedit_pageseg_mode: "0",
    tessedit_char_whitelist: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
```
Then, these warnings started to show up on the console:
```
Error opening data file ./osd.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'osd'
Warning: Auto orientation and script detection requested, but osd language failed to load
```
and finally this error showed up:
```
Uncaught (in promise) RuntimeError: memory access out of bounds
    at wasm-function[76]:59
    at wasm-function[537]:116
    at Object._ptaDestroy (https://unpkg.com/tesseract.js-core@2.0.0-beta.10/tesseract-core.wasm.js:8:3186926)
    at t.exports (https://unpkg.com/tesseract.js@2.0.0-alpha.10/dist/worker.min.js:16:34950)
    at https://unpkg.com/tesseract.js@2.0.0-alpha.10/dist/worker.min.js:8:47122
```
**To Reproduce**
Run worker.recognize using Tesseract.js using CDN, with the above configuration.

**Expected behavior**
An exception should be thrown (see screenshots)

**Screenshots**
![image](https://user-images.githubusercontent.com/24218271/60559854-678a4380-9d80-11e9-8fcf-274d9fa3e583.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.100 (Official Build) (64-bit)
--

**Comment by tehtea** [comment]
This might not be a PSM problem either, because I've been facing this issue with other PSMs as well, namely PSMs 3 and 11.

**Comment by jeromewu** [comment]
Thanks for reporting the bug, we will take a look and apply a fix soon.

**Comment by maciekmaciello** [comment]
What is the status of the problem?

**Comment by jeromewu** [comment]
This issue is fixed in tesseract.js@^2.0.0-alpha.15, please install with following command

```
$ npm install tesseract.js@next
```
