### ISSUE TITLE
Possibility to have test result in array by section?

### ISSUE THREAD

**Issue by burton666** [naptha/tesseract.js#306]
Is it possible or would it be possible to have the resulting text returned in an array or similar ? When scanning invoices where I live there is some specific info in the top left, some other in the top right and so on.

**Comment by jeromewu** [comment]
Many you can check our latest version with new parameters to recognize only part of the image, check here: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-only-part-of-the-image-200-alpha12

**Comment by burton666** [comment]
Great, if I want several sections to be analyzed how do I do that? I tried adding another rectangle after the first one but that did not work.

**Comment by jeromewu** [comment]
Hi @burton666,

Below is a sample code for recognizing multiple rectangles at a time:

```javascript
const Tesseract = require('tesseract.js');

const { TesseractWorker } = Tesseract;
const worker = new TesseractWorker();

const params = [
  {
    tessjs_image_rectangle_left: 0,
    tessjs_image_rectangle_top: 0,
    tessjs_image_rectangle_width: 500,
    tessjs_image_rectangle_height: 300,
  },
  {
    tessjs_image_rectangle_left: 500,
    tessjs_image_rectangle_top: 0,
    tessjs_image_rectangle_width: 500,
    tessjs_image_rectangle_height: 300,
  },
];

Promise.all(
  params.map(param => (
    worker
      .recognize(
        'https://tesseract.projectnaptha.com/img/eng_bw.png',
        'eng',
        param
      )
      .then(({ text }) => text)
  ))
).then((texts) => {
  console.log(texts);
  worker.terminate();
});
```

**Comment by burton666** [comment]
Thank you for all the useful help. Last question that I hope you/someone can answer. Is there some other "simple" alternative to be able to detect logos in a document?
I want to be able to store pictures of 50-500 company logos that are used in invoices and when I get a match I also know how the locations of all fields that I need to use tesseract on

**Comment by jeromewu** [comment]
As the last question you asked is out of the scope of tesseract.js, I will close the issue for now.

**Comment by cquanu** [comment]
> Hi @burton666,
> 
> Below is a sample code for recognizing multiple rectangles at a time:
> 
> ```js
> const Tesseract = require('tesseract.js');
> 
> const { TesseractWorker } = Tesseract;
> const worker = new TesseractWorker();
> 
> const params = [
>   {
>     tessjs_image_rectangle_left: 0,
>     tessjs_image_rectangle_top: 0,
>     tessjs_image_rectangle_width: 500,
>     tessjs_image_rectangle_height: 300,
>   },
>   {
>     tessjs_image_rectangle_left: 500,
>     tessjs_image_rectangle_top: 0,
>     tessjs_image_rectangle_width: 500,
>     tessjs_image_rectangle_height: 300,
>   },
> ];
> 
> Promise.all(
>   params.map(param => (
>     worker
>       .recognize(
>         'https://tesseract.projectnaptha.com/img/eng_bw.png',
>         'eng',
>         param
>       )
>       .then(({ text }) => text)
>   ))
> ).then((texts) => {
>   console.log(texts);
>   worker.terminate();
> });
> ```

@jeromewu Hi, may I know if this is still valid for v2.0.0-beta.2.
Thanks :)

**Comment by jeromewu** [comment]
In v2.0.0-beta.2, we have updated the API, please check below for example:

https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-only-part-of-the-image-200-beta1

**Comment by cquanu** [comment]
I meant the code for multiple rectangles. Current doc doesn’t have an example for multiple rectangles.

**Comment by cquanu** [comment]
Sorry to hijack this thread. Should I create a new issue @jeromewu?

**Comment by jeromewu** [comment]
Yes, please create a new issue to track this issue, thanks.
