### ISSUE TITLE
PSM object it's outdated

### ISSUE THREAD

**Issue by penovi17** [naptha/tesseract.js#311]
On the V4 a new PSM mode has been added and the object hasn't been updated:

Previous version:
`{ OSD_ONLY: '0',
  AUTO_OSD: '1',
  AUTO_ONLY: '2',
  AUTO: '3',
  SINGLE_COLUMN: '4',
  SINGLE_BLOCK_VERT_TEXT: '5',
  SINGLE_BLOCK: '6',
  SINGLE_LINE: '7',
  SINGLE_WORD: '8',
  SINGLE_CHAR: '9',
  SPARSE_TEXT: '10',
  SPARSE_TEXT_OSD: '11',
  RAW_LINE: '12',
  COUNT: '13' 
}`

New version:
`{ OSD_ONLY: '0',
  AUTO_OSD: '1',
  AUTO_ONLY: '2',
  AUTO: '3',
  SINGLE_COLUMN: '4',
  SINGLE_BLOCK_VERT_TEXT: '5',
  SINGLE_BLOCK: '6',
  SINGLE_LINE: '7',
  SINGLE_WORD: '8',
  CIRCLE_WORD: '9',
  SINGLE_CHAR: '10',
  SPARSE_TEXT: '11',
  SPARSE_TEXT_OSD: '12',
  RAW_LINE: '13',
  COUNT: '14' 
}`

**Comment by jeromewu** [comment]
Thanks for reporting the issue.
Currently the tesseract version we are using is 4.0.0, and you can find it here: https://github.com/jeromewu/tesseract

I think the new version you mentioned should be 4.1.0 which is newer with new PSM object, we will update it as long as we upgrade to 4.1.0, thanks.

**Comment by jeromewu** [comment]
Close for now as we won't upgrade to 4.1.0 soon.
