### ISSUE TITLE
Multiline Digital Detection

### ISSUE THREAD

**Issue by zocheyado** [naptha/tesseract.js#317]
I am trying to figure out the best settings / options for the engine to parse a digital text log. It is digital so I would think giving that information to the engine might be helpful if possible (consistent character size, spacing etc). The reason I cannot just access the data directly is it will be part of a video stream. 

The second issue is with line detection. If I use PSM_SINGLE_LINE it works great if my sample image is just one single line, but if it has multiples like in this screenshot https://puu.sh/E2pm7/d6c9ffaefc.png it falls apart pretty quickly. 

Last issue is with contrast detection, this one I imagine would be part of training but I am not sure, the green text in my screenshot for instance never gets parsed. Is there a way to run this in detailed mode or something that would catch something like that?

So 1, is there a way to increase the performance of tesseract in any meaningful way because this is a digital format. 2, is there a way for tesseract to detect lines and separate text into lines somehow so I at least can handle line at a time. 3, anyway to run in a more aggressive detection mode or anyway to help with contrast. 

Current config that is the best so far.
```
        'tessedit_ocr_engine_mode': OEM.TESSERACT_ONLY,
        'tessedit_pageseg_mode': PSM.PSM_SPARSE_TEXT_OSD,
```

**Comment by jeromewu** [comment]
Wow, there are lots of good questions, here are my two cents for your reference:

1. As there are only digits, you can try [whitelist](https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-whitelist-char-200-alpha5)

2. Currently it is impossible for tesseract.js to split images to lines of text, but you can assign a rectangle range to recognize, check [HERE](https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-only-part-of-the-image-200-alpha12)

3. For the contrast part, I think you need to rely on other libraries to do image preprocessing, which is not part of tesseract.js roadmap so far

**Comment by jeromewu** [comment]
Close due to inactivity.
