### ISSUE TITLE
extract text from multiple parts of an image

### ISSUE THREAD

**Issue by SamerSalmeh** [naptha/tesseract.js#318]
Sorry for my bad English,
I'm beginner at programming
It there way to extract text from multiple parts of an image in one process?
What I'm trying to do, Is extract text from ten parts of one image using [this code ](https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-only-part-of-the-image-200-alpha12) but it's really take so long to do it with a loop.

**Comment by jeromewu** [comment]
Can you provide a sample image for us to test?
