### ISSUE TITLE
Recommended offline Webpack configuration

### ISSUE THREAD

**Issue by vctls** [naptha/tesseract.js#319]
I'd like to use the library offline in a Webpack setup.
The [offline example](https://github.com/jeromewu/tesseract.js-offline/blob/master/browser/index.html) directly uses paths to the `node_modules` folder.
But that folder is not supposed to be public.

At the moment, I'm using the webpack-copy plugin to simply copy `worker.min.js` and `tesseract-core.wasm.js` from the `node_modules` to my public `dist` folder.

Is there any better way?

**Comment by jeromewu** [comment]
I think using webpack-copy is good enough, another common techniques is [externals](https://webpack.js.org/configuration/externals/) which will make your code cleaner (still need to copy though)

**Comment by karlhadwen** [comment]
Apologies for re-opening this, but @vctls what did you use to solve this? I'm bundling React/Electron together and I can get Tesseract.js to work individually in both, but if I use Electron/React together, I can't get this to work. I've had various different errors (all of which I've searched for in open/closed issues) but the issue you had and solved seem to have solved this. The repo I'm testing this against is: https://github.com/karlhadwen/notes - either I'll get issues with the language data not appearing, or errors trying to get `worker.min.js` or `tesseract-core.wasm.js`.
