### ISSUE TITLE
Hosting on CDNJS

### ISSUE THREAD

**Issue by PeterDaveHello** [naptha/tesseract.js#32]
Hi @antimatter15,

I'm wondering if we could host this lib on CDNJS, looks like there are some static codes point to "https://cdn.rawgit.com/naptha/tesseract.js/", do you have any idea about how we should do? 

Thank.

**Comment by antimatter15** [comment]
Once a repo has been added to CDNJS, does it automatically get new versions when tags are new pushed?

We can switch the static URLs to CDNJS if you give us a URL. You might also consider adding https://github.com/naptha/tesseract.js-core which is also statically linked.

**Comment by PeterDaveHello** [comment]
We have auto-update mechanism, so yes, but I prefer to use npm as auto-update source.

The url would be:
 - https://cdnjs.cloudflare.com/ajax/libs/tesseract.js/1.0.5/tesseract.min.js
 - https://cdnjs.cloudflare.com/ajax/libs/tesseract.js/1.0.5/worker.min.js

Maybe you can also provide offivially minified file so that we don't need to do that part on CDNJS.

**Comment by antimatter15** [comment]
Given that tesseract.js-core is 3MB minified, and each of the language models around 1-23MB, saving a dozen kb minifying the API code isn't really worth the reduced usability of error messages, so we'd prefer to keep the files unminified. 

Keeping NPM as update source is fine.

**Comment by PeterDaveHello** [comment]
Since we'll still preserve the un-minified one, so you can still use it for debug, and generating map file for the minified file will also help, we hope the files are always minified to provide the better performance.

**Comment by jeromewu** [comment]
Close as now it is hosted on CDNs.
