### ISSUE TITLE
Webpack Setup is failing to load languages

### ISSUE THREAD

**Issue by theRubyUnicorn** [naptha/tesseract.js#320]
The format of langs inside of tesseract.js-utils lang-data.js appears to not be an array in some situations, failing to do the map function to unzip the language data.

To be precise, I'm running tesseract.js in browser, using the .js packages npm downloaded from the tesseract-offline repository.

Interestingly enough, I was only able to locate these errors when connecting Netbeans to my chrome browser. Without it or in firefox, I got no error message it at all, Tesseract.js simply wouldn't continue and loading language traineddata progress 1 is never reached.

Full console log:
`{status: "initializing tesseract", progress: 0}
{status: "initialized tesseract", progress: 1}
{status: "loading language traineddata", progress: 0}
loadLang.js:125 Uncaught (in promise) TypeError: (intermediate value)(intermediate value)(intermediate value).map is not a function
    at loadLang.js:125
    at v (workerUtils.js:171)
    at workerUtils.js:195
    at Object.onRuntimeInitialized (tesseract-core.wasm.js:formatted:7895)
    at doRun (tesseract-core.wasm.js:formatted:7936)
    at run (tesseract-core.wasm.js:formatted:7950)
    at runCaller (tesseract-core.wasm.js:formatted:7912)
    at removeRunDependency (tesseract-core.wasm.js:formatted:783)
    at receiveInstance (tesseract-core.wasm.js:formatted:885)
    at receiveInstantiatedSource (tesseract-core.wasm.js:formatted:897)`

**Comment by jeromewu** [comment]
Hi, can you provide the versions of tesseract.js & tesseract.js-utils? It seems to me that the version of the packages may not align, thus cause the issue.

**Comment by jayuton** [comment]
hello, i use tesseract v4 to training self language,  can not load it.
error info is 
"tesseract-core.wasm.js:8 Error opening data file ./num.traineddata"
tesseract-core.wasm.js:8 Failed loading language 'num'.

**Comment by jeromewu** [comment]
Close for now due to inactivity, feel free to reopen with more information.

**Comment by sparkmorry** [comment]
same here, any solutions?
