### ISSUE TITLE
Allow spawning Workers without using a Blob URL

### ISSUE THREAD

**Issue by ThibG** [naptha/tesseract.js#321]
**Is your feature request related to a problem? Please describe.**

I would like to use Tesseract.js without widening my Content Security Policy to allow executing scripts from `blob:` sources.

**Describe the solution you'd like**

A flag to prevent `spawnWorker` from creating a `Blob` would be useful.

**Comment by jeromewu** [comment]
I think we can do it, I have made a PR to rename the variable to make it consistent with others.

**Comment by jeromewu** [comment]
Close as fixed.
