### ISSUE TITLE
preload language files doesn't work !

### ISSUE THREAD

**Issue by seme1** [naptha/tesseract.js#324]
I following the example at this link in an attempt to pre-load the language file and the API preparation for a single worker.

https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-preload-language-data

I intend to use the same worker to OCR a large number of images which all contain text in the same language. By following the steps in the above example, the following progress is always repeated for all the images:

{status: "loading language traineddata", progress: 0}
{status: "loaded language traineddata", progress: 1}
{status: "initializing api", progress: 0} 
{status: "initializing api", progress: 0.5}
{status: "initializing api", progress: 1}
{status: "recognizing text", progress: 0}
{status: "recognizing text", progress: 0.08571428571428572}
{status: "recognizing text", progress: 0.17142857142857143}
{status: "recognizing text", progress: 0.2571428571428571}
{status: "recognizing text", progress: 0.35714285714285715}
{status: "recognizing text", progress: 0.44285714285714284}
{status: "recognizing text", progress: 0.5285714285714286}
{status: "recognizing text", progress: 0.6142857142857143}
{status: "recognizing text", progress: 1}

Unless I'm misunderstanding the purpose of the preload, I was expecting the steps "loading language traineddata" and "initializing api" not to be repeated for each image !!

**Comment by jeromewu** [comment]
"preload" here means to pre-download, so you don't have to waste time download trained data from the Internet. "loading language traineddata" you saw is to copy trained data from indexdb to memory, which doesn't take too much time.

**Comment by seme1** [comment]
Thanks for the response. 
Is it possible to "load the language traineddata" and "initialize api" for all images only once ? Currently, these two steps are repeated for every single image even if the worker is NOT terminated.

**Comment by seme1** [comment]
To clarify, I'm using Tesseract JS in a Cordova Android device and the time it takes for running the following steps is nearly 22 seconds. Perhaps it would be more tolerant if the following steps were executed only once for all images till the worker is terminated ?

{status: "loading tesseract core", progress: 0}
{status: "loading tesseract core", progress: 1}
{status: "initializing tesseract", progress: 0}
{status: "initialized tesseract", progress: 1}
{status: "loading language traineddata", progress: 0}
{status: "initializing api", progress: 0}
{status: "initializing api", progress: 0.5}
{status: "initializing api", progress: 1}

**Comment by jeromewu** [comment]
> Thanks for the response.
> Is it possible to "load the language traineddata" and "initialize api" for all images only once ? Currently, these two steps are repeated for every single image even if the worker is NOT terminated.

It is an enhancement we are thinking about, but haven't started working on this, feel free to send us a PR if you have an idea.

**Comment by jeromewu** [comment]
> To clarify, I'm using Tesseract JS in a Cordova Android device and the time it takes for running the following steps is nearly 22 seconds. Perhaps it would be more tolerant if the following steps were executed only once for all images till the worker is terminated ?
> 
> {status: "loading tesseract core", progress: 0}
> {status: "loading tesseract core", progress: 1}
> {status: "initializing tesseract", progress: 0}
> {status: "initialized tesseract", progress: 1}
> {status: "loading language traineddata", progress: 0}
> {status: "initializing api", progress: 0}
> {status: "initializing api", progress: 0.5}
> {status: "initializing api", progress: 1}
> 
> The area to be OCRed in the image is very small and it doens't normally take more than 2 to 3 seconds for the actual recognition to give final the result (note the progress of the following steps jumping from 0 to 1 with no intermediate numbers)
> {status: "recognizing text", progress: 0}
> {status: "recognizing text", progress: 1}

To our knowledge, using tesseract.js in Cordorva is suffering from very poor performance due to restrictions in WebView, we currently have no active actions to solve the issue, but maybe the modification you mentioned can help.

**Comment by buaazhangfan** [comment]
@seme1 I met issues when using tesseract.js in cordova. It works fine on the simulator but on real device, my tesseract part will get stuck on `loading language traineddata, progress = 0`. Have you meet this problem before?
