### ISSUE TITLE
If an image URL fails to fetch, the TesseractWorker silently fails forever

### ISSUE THREAD

**Issue by nolanlawson** [naptha/tesseract.js#325]
**Describe the bug**

Consider a fake or broken image URL:

```js
  try {
    const response = await worker.recognize('/fake.png')
    console.log('response', response)
  } catch (err) {
    console.error('error', err)
  }
```

You may expect that we'd hit the `console.error` line. Instead, tesseract will silently fail and in fact, any further calls to `worker.recognize()` will also silently fail.

Repro'd in `tesseract.js@2.0.0-alpha.13` with `tesseract.js-core@2.0.0-beta.10`.

**To Reproduce**

I've created a minimal repro here: https://github.com/nolanlawson/repro-tesseract-broken-url

**Expected behavior**

I'd expect an error to be thrown (synchronously or asynchronously) and that further `recognize()` calls would work.

**Desktop (please complete the following information):**

Chrome on Ubuntu.

**Comment by jeromewu** [comment]
Hi, in the latest release (2.0.0-beta.1), tesseract.js is not silent anymore (hopefully), please check and feel free to reopen the issue with more information.
