### ISSUE TITLE
Add Ethereum address to FUNDING.yml

### ISSUE THREAD

**Issue by lastmjs** [naptha/tesseract.js#328]
I'd like to see an Ethereum address added to the `custom` property of the `FUNDING.yml` file for GitHub Sponsors. This would allow a canonical address to send funds to. For example, projects could parse out the address and provide donation capabilities to the user.

**Comment by jeromewu** [comment]
Added, thanks for the proposal :smile: 

It will be great if FUNDING.yml can support the bitcoin and etherum directly, just like what you mentioned in your repo: https://github.com/lastmjs/enable-cryptocurrency-in-funding-yml
