### ISSUE TITLE
How to make worker preload and persist?

### ISSUE THREAD

**Issue by Neuroforge** [naptha/tesseract.js#330]
Hello,

I have an application and want to try tesseract on the client side. The worker appears to require creation on every call when preloading language data. Is it possible to save time and preload the data and call the worker multiple times?

This was the closest info i could find, but appears to run multiple images in parallel.
https://github.com/naptha/tesseract.js/issues/323

Here is my code. It works on the first run, but cannot be called again. Worker needs recreation.

Any idea how to get it to work for multiple calls?
```
var worker = null;
 const { TesseractWorker, utils: { loadLang } } = Tesseract;
        worker = new TesseractWorker({
          workerPath: '../node_modules/tesseract.js/dist/worker.min.js',
          langPath: '/tesseract/langs',
          corePath: '../node_modules/tesseract.js-core/tesseract-core.wasm.js',
        });

        loadLang({ langs: 'eng', langPath: worker.options.langPath })
                .then(() => {
                    worker
                      .recognize('/images/testocr.png')
                      .progress((info) => {
                        console.log(info);
                      })
                      .then((result) => {
                        console.log(result)
                      });
                });

    function recognizeFile(){
        worker
          .recognize('/images/testocr.png')
          .progress((info) => {
            console.log(info);
          })
          .then((result) => {
            
            console.log(result)

          });
    }
    <button onclick="recognizeFile('/tesseract/simple.png')">Sample Image</button>
```

On clicking the button the page seems to refresh, no error is shown.

**Comment by jeromewu** [comment]
In v2.0.0-beta.1, it is possible to preload and use multiple workers at a time, please reference to this example: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-multiple-workers-to-speed-up-200-beta1
