### ISSUE TITLE
Detect Font Color

### ISSUE THREAD

**Issue by zocheyado** [naptha/tesseract.js#331]
Is it possible to detect font color with tesseract? I think for my particular use case I could probably use exact hex matching on my source image outside of tesseract. But is it possible to detect the color of the font in addition to the character?

Edit for more context. I am trying to separate out the white text from the green text in this sample image. 
https://i.imgur.com/jDA0CzI.png

**Comment by jeromewu** [comment]
I think you need to some image pre-processing to cut or remove the part you don't need, tesseract.js cannot help in detecting font color.
