### ISSUE TITLE
tesseract v4.1

### ISSUE THREAD

**Issue by xumx** [naptha/tesseract.js#332]
https://github.com/tesseract-ocr/tesseract/wiki/ReleaseNotes#tesseract-release-notes-jul-07-2019---v410

- Backward compatible release with 4.0.0
- Added a new output option formatted in the ALTO standard. Command line usage: tessaract imagename outputbase alto. This output is experimental and might be changed a bit before the next release.
- Added new renders LSTMBox, WordStrBox to simplify training
- Added character boxes in hOCR output.
- Added Python training scripts (experimental) as alternative shell scripts.
- Better support AVX / AVX2 / SSE.
- Disable OpenMP support by default (see e.g. #1171, #1081).
- Fix for bounding box problem.
- **Implemented support for whitelist/blacklist in LSTM engine.**
- Improved CMake configuration.
- Code modernization and improvements.
- A lot of bug fixes...

**Comment by jeromewu** [comment]
Now you can use tesseract v4.1 with v2.0.0-beta.1 or v2.0.0-alpha.16.
