### ISSUE TITLE
Option to disable local IndexedDB storage

### ISSUE THREAD

**Issue by nolanlawson** [naptha/tesseract.js#334]
**Is your feature request related to a problem? Please describe.**

When using tesseract.js, it stores a 23.4MB Uint8Array (blob) in IndexedDB.

**Describe the solution you'd like**

Although I understand why this is the default behavior, it would be nice to have an option to disable it. In some scenarios, an app may already be using lots of IndexedDB storage, so adding an extra 23.4MB puts pressure on the browser's available storage quota.

When IndexedDB storage is disabled, though, the app could decide itself whether or not to cache the `.gz` file (e.g. in Service Worker cache or the regular HTTP cache, as desired). An additional benefit is that this stores the gzipped content (~11MB) rather than the ungzipped content (23.4MB), although at the cost of having to ungzip it later.

**Describe alternatives you've considered**

I've considered writing code to manually clear the blob from IndexedDB, but this seems error-prone and awkward.

**Additional context**

Here is what the blob looks like in the Chrome Dev Tools "Application" tab, under IndexedDB.

![Screenshot from 2019-09-15 10-17-16](https://user-images.githubusercontent.com/283842/64925214-0defbd80-d7a2-11e9-833b-4ee1b0dd7abd.png)

**Comment by jeromewu** [comment]
You can use an option of "cacheMethod" to prevent tesseract.js to write cache, in your scenario, maybe "none" is the option you will choose.

More details here: https://github.com/naptha/tesseract.js/blob/master/docs/api.md#create-worker
