### ISSUE TITLE
can't load self traineddata language

### ISSUE THREAD

**Issue by jayuton** [naptha/tesseract.js#337]
hello, i use tesseract v4 to training self language, can not load it.
error info is
"tesseract-core.wasm.js:8 Error opening data file ./num.traineddata"
tesseract-core.wasm.js:8 Failed loading language 'num'.

**Comment by jeromewu** [comment]
Have you tried to use your self-trained model with tesseract v4?
If it works in tesseract v4, please kindly provide your traineddata to me for testing, thanks.

**Comment by jeromewu** [comment]
Close for inactivity, feel free to open with more information.
