### ISSUE TITLE
How do I use my own created traineddata language in a web app using the CDN?

### ISSUE THREAD

**Issue by iclipsvideo** [naptha/tesseract.js#338]
Hey. I have a http web app and I'm using the tesseract cdn like so:

`<script src='https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js'></script>`

and to point to the location of the traineddata language I use the following code: 

`window.Tesseract = Tesseract.create({
                    // Path of folder where the language trained data is located
                    langPath: 'https://iclips.co.za/images/usr/local/share/tessdata/',
                });`

and finally I call the recognize method like so:

`Tesseract.recognize(image, 'cus')
                        .progress(function(result){
                            console.log('Status: ' + result['status'] + '           ' + parseInt(result['progress'] * 100) + '%');
                        })
                        .then(function(result){
                            console.log(result.text);
                        })
                        .catch(function(err){
                            console.error("ERROR: " + err);
                        });`

but this doesn't work because I get the following error:

Failed loading language 'cus'
index.js:10:298
Tesseract couldn't load any languages!
index.js:10:298
AdaptedTemplates != NULL:Error:Assert failed:in file ../classify/adaptmatch.cpp, line 190
index.js:10:298
uncaught exception: abort() at Na@https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:36:26
ka@https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:511:108
_abort@https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:377:166
$L@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:387:1
jpa@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:392:1
lT@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:391:1
mT@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:391:1
BS@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:391:1
bP@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:387:1
jT@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:391:1
RJ@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:387:1
QJ@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:387:1
zI@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:403:1
tw@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:401:1
rw@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:401:1
lw@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:401:1
_v@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:401:1
aw@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:401:1
cw@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:401:1
oj@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:386:1
Og@https://cdn.jsdelivr.net/gh/naptha/tesseract.js-core@0.1.0/index.js:386:1
TesseractCore/$.prototype.Recognize@https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js:558:386
handleRecognize/<@https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/worker.js:8811:9
loadLanguage/<@https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/worker.js:8786:9
saveDataFile@https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/worker.js:8403:13
fetchLanguageData/xhr.onload@https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/worker.js:8456:9

If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
cached cus undefined

I need help here. How would I fix this? Thanks.

**Comment by jeromewu** [comment]
As v1 is deprecated, if you are new to tesseract.js, I would highly recommend to use v2, please install v2 with

```
$ npm install tesseract.js@next
```

**Comment by jeromewu** [comment]
Here is a sample repository for your reference: https://github.com/jeromewu/tesseract.js-custom-traineddata
