### ISSUE TITLE
Checking instanceof DOMException in node environment

### ISSUE THREAD

**Issue by codeclown** [naptha/tesseract.js#339]
**Describe the bug**
When an error is thrown from `loadLanguage` in workerUtils.js, there is a check for `DOMException`:

https://github.com/naptha/tesseract.js/blob/b76b7b83834b568f716df9a12c38d071956e936e/src/common/workerUtils.js#L233

In node-environment this causes another exception because `DOMException` is undefined.

**To Reproduce**

```js
const tesseract = new TesseractWorker({
  langPath: '/usr/share/tesseract-ocr/tessdata'
});

tesseract.recognize(path.join(__dirname, '../test/fixtures/word.png'), 'eng');
```

Results in error:

```
ReferenceError: DOMException is not defined
    at loadLanguage.catch (/path/to/project/node_modules/tesseract.js/src/common/workerUtils.js:233:28)
    at <anonymous>
```

**Expected behavior**
Should throw the actual exception about what went wrong when loading traineddata.

**Comment by jeromewu** [comment]
Hi, I think there are 2 sub-issues in this issue:

1. DOMException

DOMException only exists in browser environment and it totally mess up the exception handling in node environment, I have committed a fix to resolve this issue, you can check it here: https://github.com/naptha/tesseract.js/commit/740f2cab0cd390d5b7e8a70b6211090f891207e2

2. Read traineddata from tesseract-ocr

I have done a check in my environment (Ubuntu) and following configuration will work (with some magic options):

```javascript
const tessWorker = new TesseractWorker({
  langPath: '/usr/share/tesseract-ocr/4.00/tessdata',
  cacheMethod: 'none',
  gzip: false,
});
```

Hope it helps.

**Comment by codeclown** [comment]
@jeromewu I haven't tested the fix, but it should work. Closing.

I ended up making a wrapper for node-only environment, with some tests as well:
https://github.com/codeclown/tesseract.js-node

Do you have any objection to the name of the repository/package? I am not trying to imply it is part of the tesseract.js family of packages, but I couldn't come up with anything else.

**Comment by jeromewu** [comment]
Don't worry about the naming, just pick up the one you like. It is open source, feel free to create and share :smile:
