### ISSUE TITLE
Reusing worker for multiple images not working

### ISSUE THREAD

**Issue by Shiuyin** [naptha/tesseract.js#340]
Using: alpha15

I am trying to initialize a TesseractWorker only ONCE and then reuse it for every consecutive recognition attempt. This is my code:

```
var worker =
            window.OCRWorker ||
            new Tesseract.TesseractWorker({
                workerPath: workerPath,
                langPath: langPath,
                corePath: corePath
            });
        window.OCRWorker = worker;
        worker.recognize(image, 'eng', options).then(onSuccess);
```

During the first image recognition, i can see that a job 'Job-1-0a1a0' is created, processed and the correct result returns. During the second image recognition, i can see that a job is added to the worker queue but the currentJob id stays at the same 'Job-1-0a1a0' and nothing is executed. I don't get any result and no error. I would think that since the old recognition job was finished long ago, i can reuse the worker instance and simply call worker.recognize() again.

Being able to reuse a worker instance saves A LOT of processing time on older devices. In particular on an old Moto G 5 on Android the complete process was taking about 25s with 22s just being the startup of TesseractJS and 3s for the actual recognition part. If i could reuse the already instantiated TesseractWorker instance, that would save a lot of time on each recognition request.

I also had a look at your tests and found

```describe('should be able to recognize multiple images with 1 worker', () => {
    [3, 10, 20].forEach(num => (
      it(`recognize ${num} images with 1 worker`, (done) => {
        const worker = getWorker();
        Promise.all(
          Array(num).fill(0).map(() => worker.recognize(`${IMAGE_PATH}/simple.png`)),
        ).then((results) => {
          results.forEach(({ text }) => {
            expect(text).to.be(SIMPLE_TEXT);
          });
          worker.terminate();
          done();
        });
      }).timeout(60000)
    ));
  });
```

so in theory this should already be working. What am I doing wrong?

Thank you for your help.

**Comment by Shiuyin** [comment]
After more googling i found https://github.com/naptha/tesseract.js/issues/323 and https://github.com/naptha/tesseract.js/issues/324 and https://github.com/naptha/tesseract.js/issues/330.

I debugged TesseractJS and found out that during delay() the currentJob STILL is set, even though it is finished. I added

`worker._currentJob = null;`

before the recognize() call and now i can reuse the worker instance for multiple calls. The speedup is quite something. On an old Moto G5 ionic view, i went down from 25s total to 8s total because of this.

I still think this is a bug and i should not have to set the currentJob to null manually, but its a successfull workaround at least.

On a side note:

On the first TesseractWorker call, it starts with Loading tesseract core, initializing tesseract, ... when i reuse the worker instance it starts with loading language traineddata, initializing api, ... Maybe this is a target for future optimization for you, as there is no need to reload the data and init the api again when the worker instance itself is already fully initialized.

Thanks for the great lib!

**Comment by jeromewu** [comment]
Actually I do have a plan to improve the performance recently and there is a lot of work, I will let you know when it is done.

**Comment by Shiuyin** [comment]
Thank you very much!

**Comment by trinhpham** [comment]
I have the same concern and Google gets me here.
@Shiuyin has done a very good job to figure out the improvement points. I have to say thanks for your workaround as it saves my app performance as well 😄 
Waiting for the team to do the improvement and thanks for this great lib!

**Comment by jeromewu** [comment]
Right now we have a new version v2.0.0-beta.1 with brand new API and multiple workers scheduling working, you can check this [story](https://medium.com/@jeromewus/why-i-refactor-tesseract-js-v2-50f750a9cfe2) and this [example](https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-multiple-workers-to-speed-up-200-beta1)
