### ISSUE TITLE
Tesseract not recognizing pre defined image

### ISSUE THREAD

**Issue by lwardlegit** [naptha/tesseract.js#341]
I want to use Tesseract on an image that is already included inside my project on a button click:
When I try the following:

<button onclick=()=>{
let img = new Image()
img.src= filepath of my file

when I call:
  var Tesseract = window.Tesseract;
              Tesseract.recognize(img.src)

}>DEMO<button>

Nothing happens, there is no error there is also no output in the console. 

However if I use <input type='file'/> tag instead of button, it works fine.
Can someone please explain why this happens?

my img filepath is' resanote/src/demoImages.png'
and I am passing the variable 'host' as the filepath in the button onclick function

`  <button className="demoButton" onClick = {
                (e, props, state, location) => {
                    let img = new Image()

                    var host = window.location.protocal + "//" + window.location.hostname + ":" + window.location.port + "/resanote/src/demoImages.png";
                    img.src = host
                        //send image to tesseract
                    var Tesseract = window.Tesseract;
                    Tesseract.recognize(img.src)
                        .progress(function(p) {
                            console.log('progress', p)
                        })
                        .then(function(props, result) {
                            console.log('result', result)
                        })
                        //  .then((result)=> { document.body.append('result', result.text)})
                        .then((result, props) => {

                            console.log("result console log", result)
                            this.props.getTextFromBody(result.text.split(","))
                            console.log(this.props.documentText)
                        }).then(
                            () => { this.rundemo() })
                        .catch(function(error) {
                            console.log('Looks like there was a problem: \n', error);
                        })

                }
            } > Demo </button>`

**Comment by jeromewu** [comment]
Maybe the issue is at "filepath of my file", which may cause some unexpected result, can you share an example of "filepath of my file" here?

**Comment by lwardlegit** [comment]
certainly I have updated it to show the filepath

**Comment by jeromewu** [comment]
Hi, I have create a working example in the link below for your reference:

https://gist.github.com/jeromewu/44bdc2c686899775596e981b416a196e

// I know you are working in react, but I think it should work in general

**Comment by jeromewu** [comment]
Close for now.
