### ISSUE TITLE
How to improve speed of ocr ?

### ISSUE THREAD

**Issue by burton666** [naptha/tesseract.js#342]
I want to use tesseract on "easy" sources like pdf-invoices and do not need any fancy handwriting recoqnintion. Is there any good practices that I can use to improve the speed of the ocr process? like adjusting the resolution or anything else?

**Comment by jeromewu** [comment]
You can reference this issue: https://github.com/tesseract-ocr/tesseract/issues/263

**Comment by jeromewu** [comment]
I think it is kind of normal as the performance of tesseract.js (WebAssembly version) is not as good as tesseract-ocr (C version) due to its environmental differences. Although I haven't done any benchmark so far.

**Comment by jeromewu** [comment]
Close for now, feel free to reopen.
