### ISSUE TITLE
request lang data by a customized URL

### ISSUE THREAD

**Issue by donotlb** [naptha/tesseract.js#343]
**Is your feature request related to a problem? Please describe.**

I have a app based on corodva, and i want to install tesseract.js (core/worker/lang-data) locally, with the help of [jeromewu/tesseract.js-offline](https://github.com/jeromewu/tesseract.js-offline), everything is ok, but when i build (android) app, all files with '.gz' extension will be renamed to a name without '.gz' extension, e.g.,   
**eng.traineddata.gz => build => eng.traineddata**,  
some details can be found here: [gzip'ed js file in dist/ breaks AAPT · Issue #347 · sweetalert2/sweetalert2](https://github.com/sweetalert2/sweetalert2/issues/347)  

the problem is: request .../eng.traineddata.gz results in a 404 response

**Describe the solution you'd like**

I found a **gzip (default:true)** lang-data load option, but there doesn't seem to have a way (or API) to config it, so i think we need a way to custmize the lang-data URL

thanks for your time.

**Comment by donotlb** [comment]
I make it work: 

```
import Tesseract from 'tesseract.js'
import corePath from 'file-loader?name=tesseract-local/[name].[ext]!tesseract.js-core/tesseract-core.wasm.js'
import workerPath from 'file-loader?name=tesseract-local/[name].[ext]!tesseract.js/dist/worker.min.js'
import langPath from 'file-loader?name=tesseract-local/[name].[ext]!./lang-data/eng.traineddata'

const { TesseractWorker, utils : { loadLang } } = Tesseract
const worker = new TesseractWorker({
  corePath,
  workerPath,
  langPath: langPath.substring(0, langPath.lastIndexOf('/'))
})

loadLang({ langs: 'eng', langPath: worker.options.langPath, gzip: false })
```

**Comment by dineshrabara** [comment]
For the new version, use it like below 

````
const worker = createWorker({
        workerPath: '/tesseract/worker.min.js',
        corePath: '/tesseract/tesseract-core-simd.wasm.js',
        langPath: '/tesseract/lang-data/',
        gzip: false,
        logger: m => console.log(m)
      });
````

The asset folder keeps the lang file without the .gz file.

PS: tested with capacitors and vue 3
