### ISSUE TITLE
Remove the decimals in progress percent 

### ISSUE THREAD

**Issue by ymoc1699** [naptha/tesseract.js#344]
I can't seem to find the solution on how to remove the decimals in percentage progress when displaying, so maybe we can suggest or cite an example re this. Show 1%,2%,3...100% (whole num) instead of 1.1857142..% and so on. Thank you!

**Comment by jeromewu** [comment]
Maybe I am wrong, but I think you can use toPrecision to solve the issue, check reference [HERE](https://www.w3schools.com/jsref/jsref_toprecision.asp)

**Comment by ymoc1699** [comment]
Will try, thanks!
