### ISSUE TITLE
[Bug] tessedit_pageseg_mode prints some debug info

### ISSUE THREAD

**Issue by elderapo** [naptha/tesseract.js#347]
**Describe the bug**
Setting `tessedit_pageseg_mode` to `PSM.SINGLE_LINE(7)` causes `tesseract.js` to write some debug info (I assume) to the console.

**To Reproduce**
```js
const { createWorker, PSM } = require("tesseract.js");

const main = async () => {
  const worker = createWorker({
    logger: m => {}
  });

  await worker.load();
  await worker.loadLanguage("eng");
  await worker.initialize("eng");
  await worker.setParameters({
    tessedit_pageseg_mode: PSM.SINGLE_LINE
  });

  await worker.recognize("https://i.imgur.com/pM8mJ8A.png");
  await worker.terminate();
};

main();
```

**Expected behavior**
Above snippet should not write anything to the console but instead, it writes this:
```bash
$ node ./index.js
Bottom=0, top=15, base=0, x=0

Total count=0
Min=0.00 Really=0
Lower quartile=0.00
Median=0.00, ile(0.5)=0.00
Upper quartile=0.00
Max=0.00 Really=0
Range=1
Mean= 0.00
SD= 0.00
```

**Desktop (please complete the following information):**
 - OS: `Ubuntu 14.04`
 - Version `^2.0.0-beta.1`

**Comment by jeromewu** [comment]
This bug comes from tesseract-ocr, we don't plan to fix it if it doesn't cause any trouble.

**Comment by elderapo** [comment]
Well, it causes trouble. I am using `tesseract` to continuously process screen frames and with this bug, it makes it really hard to analyze logs because most of them are these useless debug messages.

I've tried hooking `console.log`, `process.stdout.write` and `process.stderr.write` to intercept these messages but it doesn't work.

**Comment by jeromewu** [comment]
After some googling, I have found a solution:

```javascript
const { createWorker, PSM } = require("tesseract.js");

const main = async () => {
  const worker = createWorker({
    logger: m => {}
  });

  await worker.load();
  await worker.loadLanguage("eng");
  await worker.initialize("eng");
  await worker.setParameters({
    tessedit_pageseg_mode: PSM.SINGLE_LINE,
    debug_file: '/dev/null',  // Assigning a debug file disables the console output
  });

  await worker.recognize("https://i.imgur.com/pM8mJ8A.png");
  await worker.terminate();
};

main();
```
