### ISSUE TITLE
tesseract.js crashes when running it in multiple instances

### ISSUE THREAD

**Issue by davidlr99** [naptha/tesseract.js#348]
**Bug description**

I just installed the tesseract.js npm module. I am able to run it, everything works fine.
However if i start the same nodejs script multiple times and run e.g. 3 times the same script parallel the scripts are crashing with following error description:

```
Error opening data file ./eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
AdaptedTemplates != nullptr:Error:Assert failed:in file /src/src/classify/adaptmatch.cpp, line 196
trap!
trap!
/Users/david/Desktop/instaBots/node_modules/tesseract.js/src/createWorker.js:135
      throw Error(data);
      ^

Error: abort(trap!). Build with -s ASSERTIONS=1 for more info.
    at ChildProcess.<anonymous> (/Users/david/Desktop/instaBots/node_modules/tesseract.js/src/createWorker.js:135:13)
    at ChildProcess.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

The script does not crash if I only run one instance of it!.

**To Reproduce**

1. Create a nodejs script 
2. Add tes_worker.recognize("image.png") in e.g. setTimeout to repeat the "ocr scanning".
3. Run multiple instances of the script.

**Desktop (please complete the following information):**
 - OS: mac os (osx) 10.14.6 (18G103)
 - Node: v12.11.1
 - tesseract.js version 2.0.0-beta.1

**Additional context**
It would be very cool if this bug could be fixed :D 
Feel free to ask me for further information.

Best Regards,
David

**Comment by jeromewu** [comment]
Hi, can you provide the full sample code, I think you may missing some initialization of Worker.

Also, it is more recommended to use multiple workers instead of multiple instances, check example here: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-multiple-workers-to-speed-up-200-beta1

**Comment by jeromewu** [comment]
Close for now, feel free to reopen with more information.

**Comment by MirzaPayam** [comment]
@jeromewu how can i achieve that if images are coming from server and i don't have a fixed set of images to assign a worker for each of them ?

**Comment by jeromewu** [comment]
Not sure about the scenario, can you elaborate more?
From your description, the scheduler may solve the issue, and you can check the story above for the sample code.

**Comment by dimatter** [comment]
```const { createWorker, createScheduler } = require('tesseract.js');

const scheduler = createScheduler();
const worker1 = createWorker();
const worker2 = createWorker();

async function loop() {
  await worker1.load();
  await worker2.load();
  await worker1.loadLanguage('eng');
  await worker2.loadLanguage('eng');
  await worker1.initialize('eng');
  await worker2.initialize('eng');
  worker1.setParameters({
    user_defined_dpi: '70',
    tessedit_pageseg_mode: t.PSM.PSM_SINGLE_BLOCK
  })
  worker2.setParameters({
    user_defined_dpi: '70',
    tessedit_pageseg_mode: t.PSM.PSM_SINGLE_BLOCK
  })

  scheduler.addWorker(worker1);
  scheduler.addWorker(worker2);
  /** Add 10 recognition jobs */
  const results = await Promise.all(Array(10).fill(0).map(async (i) => {
    let data = await image.getBufferAsync(Jimp.MIME_BMP)
    scheduler.addJob('recognize', data)
    console.log(results);
    await scheduler.terminate(); // It also terminates all workers.
  })
  )
}


loop()
```

**Comment by northamerican** [comment]
My workaround is to make copies of the traineddata file (`eng-1.trainddata`, `eng-2.trainddata`, `eng-3.trainddata`...) and have my workers each use their own. 

```
  await worker1.loadLanguage('eng-1.trainddata');
  await worker2.loadLanguage('eng-2.trainddata');
  await worker1.initialize('eng-1.trainddata');
  await worker2.initialize('eng-2.trainddata');
```
