### ISSUE TITLE
Unable to recognize dotted text

### ISSUE THREAD

**Issue by shivpatel** [naptha/tesseract.js#349]
Anyone had luck using this library to parse images like the following:

<img width="240" alt="Screen Shot 2019-10-09 at 7 36 33 PM" src="https://user-images.githubusercontent.com/1449420/66528401-bd802d00-eacd-11e9-80bc-7230e6f1bb58.png">

![test](https://user-images.githubusercontent.com/1449420/66528418-d4268400-eacd-11e9-84cc-3fcd9b7ec34a.jpg)

**Comment by jeromewu** [comment]
It is hard to recognize these images without extra efforts, there are 2 possible directions to solve the issue:

1. Image Pre-processing
Sharp the image and connect the dots to make it close to typical characters

2. Custom Traineddata
You need to create your own traineddata

Some references:
- https://github.com/tesseract-ocr/tesseract/issues/2342
- https://groups.google.com/forum/#!topic/tesseract-ocr/SgbpCIL1m68

**Comment by shivpatel** [comment]
I was able to get acceptable results using https://github.com/ameera3/OCR_Expiration_Date/blob/master/OCR_Ensemble/LCDDot_FT_500.traineddata.

How can I tell tesseract.js to use this custom `.traineddata`?

**Comment by jeromewu** [comment]
You are close to the answer, just a little modification should work:

```javascript
const Tesseract = require('tesseract.js');
const { createWorker } = Tesseract;

const worker = createWorker({
  langPath: '/usr/local/Cellar/tesseract/4.1.0/share/tessdata',
  gzip: false,
  logger: m => console.log(m)
});

(async () => {
  await worker.load();
  await worker.loadLanguage('LCDDot_FT_500');
  await worker.initialize('LCDDot_FT_500');
  const { data: { text } } = await worker.recognize('http://domain.com/myimg.jpg');
  console.log(text);
  await worker.terminate();
})();
```

**Comment by shivpatel** [comment]
That worked like a charm! Thank you @jeromewu 

I may PR an addition to the examples doc; will be a nice example of how to use custom traineddata and using dotted/LCD text.

**Comment by jeromewu** [comment]
I just did the same thing :smile: 
You can check here: https://github.com/jeromewu/tesseract.js-custom-traineddata
