### ISSUE TITLE
cordova: worker.loadLanguage doesn't work in real device but works in ios simulator

### ISSUE THREAD

**Issue by buaazhangfan** [naptha/tesseract.js#351]
**Describe the bug**
I am using cordova ios with tesseract.js. In ios simulator everything works well but when I run my project in real device, the progress will get stuck in `loading language traineddata, progress 0`. Do you have any ideas related to this? Should it be a problem regarding download the training data?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [iphoneXR]
 - OS: [IOS13.1]

**Additional context**

**Comment by jeromewu** [comment]
I think it is related to the network environment of your real device.
Can you try to access https://tessdata.projectnaptha.com/4.0.0/eng.traineddata.gz with your real device and see if it works?

**Comment by buaazhangfan** [comment]
Yes I tried it in my real device but it downloaded the trained data successfully.

**Comment by buaazhangfan** [comment]
i think I can read the trained data manually like this [repo] (https://github.com/jeromewu/tesseract.js-cordova/blob/master/www/js/main.js), but in the newest lib, how to apply that since initialize tesseract worker is a little bit different.

**Comment by buaazhangfan** [comment]
Also, I see the load language api under `work-script/index.ts`, I noticed there are some log in the load language api but why these logs will not be printed during run time with tesseract after setlogger(true). How can I debug this to see whether it happened during loading language?

**Comment by buaazhangfan** [comment]
Solved by add `cachemethod: 'none'` when creating the worker. I found in the `work-script/index.js`, everytime it will start to load the trained data from cache. However, in cordova ios app, it got stuck somewhere. So I disable the cache read and write so it can directly download the trained data from website. Although takes a little bit longer time to downloading it.
