### ISSUE TITLE
Performance suggestion: remove axios dependency

### ISSUE THREAD

**Issue by nolanlawson** [naptha/tesseract.js#353]
**Describe the bug**

If you look at a WebpackBundleAnalyzer view of `createWorker` from `tesseract.js` (version `2.0.0-beta.1`), you'll see the following structure:

![Screenshot from 2019-10-20 09-47-53](https://user-images.githubusercontent.com/283842/67162989-b3a4c800-f31e-11e9-844f-2cd36e16c56e.png)

(You can repro using [this gist](https://gist.github.com/nolanlawson/7e6e7aafb67aa84a08e899de4de91231)).

Roughly it breaks down to:

- axios: 34KB
- tesseract.js: 17.5KB
- regenerator-runtime: 6.1KB
- (other): 24.4KB

So `axios` is taking up more space than `tesseract.js` itself!

It looks like we are mostly just using `axios` for the `get()` method. Perhaps we can replace it with [node-fetch](https://www.npmjs.com/package/node-fetch), and use `fetch()` in browsers instead?

(It may also be worthwhile to release a build for modern browsers that doesn't include `regenerator-runtime` &ndash; personally I'm only targeting browsers that support async/await, so it's not needed in my case.)

**To Reproduce**

```sh
git clone https://gist.github.com/nolanlawson/7e6e7aafb67aa84a08e899de4de91231 repro
cd repro
npm i
npm run build
# then it will open a browser window with the WebpackBundleAnalyzer view
```

**Expected behavior**

I believe tesseract.js could be much smaller and thus more performant especially on resource-constrained devices such as mobile phones.

**Comment by jeromewu** [comment]
Good suggestion, but I will put this one in low priority right now.
