### ISSUE TITLE
Impossible to catch error

### ISSUE THREAD

**Issue by loderunner** [naptha/tesseract.js#367]
**Describe the bug**

Using Tesseract.js in Node, when launching a `recognize` job on a worker with invalid image data, the child process crashes. This, in turn, is received in the parent process in the `onMessage` handler, which throws an error. This error happens outside my code's call stack and is impossible to catch and handle gracefully, causing my parent process to crash.

**To Reproduce**

The following script causes the crash.

```javascript
const readline = require("readline");
const fs = require("fs");

readline.emitKeypressEvents(process.stdin);
if (process.stdin.isTTY) {
  process.stdin.setRawMode(true);
}

process.stdin.on("keypress", k => {
  if (k === "q") {
    process.exit();
  }
});

const { createWorker, PSM } = require("tesseract.js");
let worker;
try {
  worker = createWorker({ logger: m => console.log(m) });
} catch (err) {
  console.error(err);
}
(async () => {
  await worker.load();
  await worker.loadLanguage("eng");
  await worker.initialize("eng");
  await worker.setParameters({
    tessedit_pageseg_mode: PSM.AUTO_OSD,
    tessjs_create_hocr: "0",
    tessjs_create_tsv: "0"
  });
  try {
    // const data = fs.readFileSync("helloworld.png");
    const res = await worker.recognize(new Buffer("toto"));
    console.log(res.data.text);
  } catch (err) {
    console.log(err);
  }
})();
```

**Expected behavior**

The above program should report the error, wait for the user to type `q` on the keyboard, then exit.

**Screenshots**

There is no screenshot, but here is the program output:

```
{ status: 'loading tesseract core', progress: 0 }
{ status: 'loaded tesseract core', progress: 1 }
{
  workerId: 'Worker-0-8a764',
  status: 'initializing tesseract',
  progress: 0
}
{
  workerId: 'Worker-0-8a764',
  status: 'initialized tesseract',
  progress: 1
}
{
  workerId: 'Worker-0-8a764',
  status: 'loading language traineddata',
  progress: 0
}
{
  workerId: 'Worker-0-8a764',
  status: 'loaded language traineddata',
  progress: 1
}
{ workerId: 'Worker-0-8a764', status: 'initializing api', progress: 0 }
{ workerId: 'Worker-0-8a764', status: 'initialized api', progress: 1 }
(node:16039) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error in pixReadMem: size < 12
Error in pixGetSpp: pix not defined
Error in pixGetDimensions: pix not defined
Error in pixGetColormap: pix not defined
Error in pixCopy: pixs not defined
Error in pixGetDepth: pix not defined
Error in pixGetWpl: pix not defined
Error in pixGetYRes: pix not defined
Error in pixClone: pixs not defined
Please call SetImage before attempting recognition.
21
21
/private/tmp/toto/node_modules/tesseract.js/src/createWorker.js:139
        throw Error(data);
        ^

Error: abort(21). Build with -s ASSERTIONS=1 for more info.
    at ChildProcess.<anonymous> (/private/tmp/toto/node_modules/tesseract.js/src/createWorker.js:139:15)
    at ChildProcess.emit (events.js:200:13)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Desktop (please complete the following information):**
 - OS:
   * macOS 10.14.6 Mojave
   * Linux Debian Stretch (`Linux 4.9.184-linuxkit`)
 - Node.js: v12.4.0
 - Tesseract.js: 2.0.0-beta.2

**Additional context**

As you can see, the `Error` is thrown at `ChildProcess.onMessage (createWorker.js:135:13)` which is called from `processTicksAndRejections (internal/process/task_queues.js:84:9)`, which is not some place I can wrap with a `try`/`catch` block.

My use case is that I'm running OCR as a backend service. The above program waits for a key, similar to how my server waits for requests. A failed OCR for bad user input crashing my server is not acceptable. I should be able to handle Tesseract errors gracefully.

**Comment by mehmetgelmedi** [comment]
As a workaround
This error is caused by the traineddata(for ex. eng.traineddata) file downloaded . When you delete that file, it will update itself again and you will not receive this error, but after a while you will receive the same error again.
I don't understand exactly why this error occurred.

**Comment by jeromewu** [comment]
It is caused by the fact that traineddata is corrupted due to network issues, a file size check is planned to implement in the future but not available now.

**Comment by jeromewu** [comment]
Close for now.

**Comment by ShooreshS** [comment]
Could it be due to an unseen font in the trained data?
