### ISSUE TITLE
Executing nodejs example runs very slowly and takes up a lot of memory

### ISSUE THREAD

**Issue by zg163zp2006** [naptha/tesseract.js#370]
When the image is larger than 500KB, Executing nodejs example runs very slowly and takes up 10GB memory

**Comment by jeromewu** [comment]
Weird, can you provide a similar image for me to test?

**Comment by zg163zp2006** [comment]
> Weird, can you provide a similar image for me to test?

![微信图片_20191108205000](https://user-images.githubusercontent.com/8944964/71152929-c0885e00-2272-11ea-9947-f18ccee7f461.jpg)

**Comment by jeromewu** [comment]
Hi, I have tried to recognize the image you provided, I was able to complete the recognize in around 2 minutes and it didn't take 10 GB memory.
May I know your environment (OS, node version and so on)?

**Comment by markb-trustifi** [comment]
@jeromewu 2 minutes is very slow. The image recognition should take not more than 10 seconds. Are there any parameters to execute it quick with lite search algorithm?

**Comment by jeromewu** [comment]
To my knowledge, the answer is no, you may need to find some alternatives. BTW, as you are using node version, one option is to use tesseract-ocr native version instead.

**Comment by jeromewu** [comment]
Close for now, feel free to reopen with more information.

**Comment by GitMurf** [comment]
> To my knowledge, the answer is no, you may need to find some alternatives. BTW, as you are using node version, one option is to use tesseract-ocr native version instead.

I know this was a few years ago @jeromewu but what do you mean by the tesseract-ocr native version? Is there an "official" tesseract node native module / Node-API / N-API implementation somewhere? I couldn't find it. Thanks a lot!
