### ISSUE TITLE
Wrong detect text B0 -> B0O0

### ISSUE THREAD

**Issue by 0x0a0d** [naptha/tesseract.js#371]
![asin-5a1b70ca2d75a572b7edfa50](https://user-images.githubusercontent.com/32500015/69911283-bdf0d080-144b-11ea-9022-28b6c082e5ce.png)
<img width="291" alt="Screen Shot 2019-12-01 at 15 04 00" src="https://user-images.githubusercontent.com/32500015/69911291-d660eb00-144b-11ea-9c32-4ffddc85dc10.png">
I tried both online and offline and get the same wrong results. 
The correct text is B0 (zero) but the output is B0O0 (B-zero-o-zero)
Please help to fix it. Thanks

**Comment by cquanu** [comment]
@0x0a0d you could whitelist the character 'O' if you’re not using it.
https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-whitelist-char-200-beta1

**Comment by jeromewu** [comment]
Close for now, feel free to reopen with more information.
