### ISSUE TITLE
postMessage loop

### ISSUE THREAD

**Issue by mtj8033** [naptha/tesseract.js#372]
**Describe the bug**
Currently seeing heavy cpu usage, when tracking down exactly what was occurring noticed there was a loop occurring inside https://github.com/naptha/tesseract.js/blob/15da58127d4bebeef25cae61d6b23deb45d60e73/src/worker-script/browser/index.js#L20

It got a message that wasn't from tesseract (pendo in this scenario) and tried to parse it, it then rejected it which sent another postMessage and began an infinite loop.

**Comment by jeromewu** [comment]
Can you provide any snippet to reproduce the issue? Thanks.

**Comment by jeromewu** [comment]
Close for now, feel free to reopen with more information.
