### ISSUE TITLE
Error: InvalidStateError thrown on Firefox

### ISSUE THREAD

**Issue by Kcchouette** [naptha/tesseract.js#375]
Hello,

on your default page https://tesseract.projectnaptha.com/ with Firefox 71.0 and Firefox 72.0, I have this error:

```
Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. createWorker.js:135:12
    exports createWorker.js:135
    onmessage onMessage.js:3
uncaught exception: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.
```

So we can't try the demo on your website

Cheers

**Comment by jeromewu** [comment]
Hi, may I know if you are using **Private Window** in firefox? It might be the root cause of this problem as IndexedDB is not supported in private mode.

**Comment by Kcchouette** [comment]
Yes I am using **Private Mode**.

**Comment by jeromewu** [comment]
Then the only solution is not to use private mode, close the issue.

**Comment by Kcchouette** [comment]
@jeromewu Maybe you can write that something? Or deals with the exception?

**Comment by jeromewu** [comment]
This issue well describes the problem and our discussion has found the solution, I believe here will help people with the same problem, no extra documentation is required.
