### ISSUE TITLE
Allow Explicit Specification whether the environment is Node or Browser

### ISSUE THREAD

**Issue by geo-systems** [naptha/tesseract.js#376]
**Is your feature request related to a problem? Please describe.**

I'm working on an Electron app. In Electron, each window has access to both the Node JS API and  the web view API (e.g. the global `window` and `window.document` variables are defined). 

Currently, `tesseract.js` checks if it's running in a browser and if so it treats all configuration paths as URLs - [see here](https://github.com/naptha/tesseract.js/blob/7b06e0edcb11624f6a5faf5243de1e7beb85b4fc/src/utils/resolvePaths.js). I would like to force `tesseract.js` to work in "Node mode" and to treat the configuration paths as file paths.

**Describe the solution you'd like**

When initialising `tesseract.js` workers, add a new property to specify whether you're working in browser or Node js mode. This property can be optional - if it's not present then use the current logic.

**Comment by jeromewu** [comment]
Hi,
Instead of adding an explicit environment type assignment, I have added electron environment check in [getEnvironment()](https://github.com/naptha/tesseract.js/blob/master/src/utils/getEnvironment.js) which should fix the issue.

**Comment by jeromewu** [comment]
BTW, here is a repo for your reference: https://github.com/jeromewu/tesseract.js-electron
