### ISSUE TITLE
ClassTemplate->ProtoLengths[ActualProtoNum] < MAX_PROTO_INDEX

### ISSUE THREAD

**Issue by markb-trustifi** [naptha/tesseract.js#377]
This file works well in tesseract demo site but fails in Node.js
![chequeman-cheque2](https://user-images.githubusercontent.com/29097494/71323285-1743a100-24da-11ea-96cf-8d7a58d6ed17.jpg)

**Describe the bug**
```
Error: abort(Assertion failed: ClassTemplate->ProtoLengths[ActualProtoNum] < MAX_PROTO_INDEX, at: /src/src/classify/intmatcher.cpp,1155,UpdateSumOfProtoEvidences). Build with -s ASSERTIONS=1 for more info.
    at ChildProcess.onMessage (node_modules/tesseract.js/src/createWorker.js:139:15)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**To Reproduce**
```
const tesseract = require('tesseract.js');
const worker = tesseract.createWorker();
await worker.load();
await worker.loadLanguage('eng');
await worker.initialize('eng');
const result = await worker.recognize(filebuff);
await worker.terminate();
```

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Platform: Node.js v8.11.1
 - Tesseract: ^2.0.0

**Comment by markb-trustifi** [comment]
I run tesseract after the Jimp, so this test can be considered invalid.
I any case most of the images in https://tesseract.projectnaptha.com/ website are processed with better speed and better quality than I can do locally in Node.js.
How is it possible?

**Comment by jeromewu** [comment]
Well, in my own experience the OCR result might be different depends on the version of browser and node.js you use. So it is possible to happen, and I have taken a deep survey for that.

**Comment by jeromewu** [comment]
Close for now, feel free to reopen if needed.
