### ISSUE TITLE
How extract multiple section of an image

### ISSUE THREAD

**Issue by cquanu** [naptha/tesseract.js#378]
Hi,

Current doc doesn’t have an example for extarcting multiple rectangles. I'm trying to extract data from this image using v2.0.0. I would really appreciate for some example.

![card](https://i.imgur.com/9TL9eYp.jpg)

**Extract Into:**

``` js
["value1,"value2"]
```

**What I've tried:**

```js
const Tesseract = require('tesseract.js');

const { TesseractWorker } = Tesseract;
const worker = new TesseractWorker();

const params = [
  {
    left: 280,
    top: 220,
    width: 420,
    height: 145,
  },
  {
    left: 280
    top: 450,
    width: 420,
    height: 145,
  },
];

Promise.all(
  params.map(param => (
    worker
      .recognize(
        'sample.jpg',
        'eng',
        param
      )
      .then(({ text }) => text)
  ))
).then((texts) => {
  console.log(texts);
  worker.terminate();
});
```

**Comment by jeromewu** [comment]
Hi,
It turns out we cannot assign multiple regions at a time, I have updated the API and you can check hrere for examples to recognize multiple regions: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-only-part-of-the-image-201

**Comment by cquanu** [comment]
Thank you very much @jeromewu 😄
