### ISSUE TITLE
Persian language support

### ISSUE THREAD

**Issue by KiarashS** [naptha/tesseract.js#38]
Dear,

Please add **persian** language to supported languages.

Thanks in advance

**Comment by ChristopherA334** [comment]
@-ant 🐜 larvae ? Lice ? Insects ? Maggots? Ticks? Bugs? Prevacid Rolaids nexium Tums Prilosec Milk emetrol Arm&Hammer Baking Soda Acid Reflux, indigestion,heart burn, sour stomach , nausea, abdominal cramps peptic ulcer , septic . I'm going to add what you asked me too . I'm very new to this , next time I will appreciate some of the reasoning for it , if you don't mind helping me alleviate some of my ignorance to this whole process. Please and thank you.

**Comment by Slowtta** [comment]
Persian and Arabic  are based on the same script, Persian uses four additional letters: 
پ [p] 
گ [g] 
چ [tʃ] (ch as in chat) 
ژ [dʒ] or [ʒ] (j as in jump, s as in pleasure)

**Comment by ChristopherA334** [comment]
I learned something new . I'm in your debt . Thank you, sincerely.

**Comment by KiarashS** [comment]
Yes, that is a new feature request.

**Comment by bijection** [comment]
As @Slowtta points out you may be able to use Arabic when we get that fixed (#30), but otherwise we don't plan to support languages that https://github.com/tesseract-ocr/tesseract doesn't support.
