### ISSUE TITLE
Rate exceeded when loading worker

### ISSUE THREAD

**Issue by santosh898** [naptha/tesseract.js#380]
Cannot load [tesseract.min.js](https://unpkg.com/tesseract.js@v2.0.1/dist/tesseract.min.js).

**Comment by jeromewu** [comment]
Wow, look like the unpkg CDN is running out of capacity.
You can use this one instead: https://cdn.jsdelivr.net/npm/tesseract.js@v2.0.1/dist/tesseract.min.js

**Comment by santosh898** [comment]
Thank you!
