### ISSUE TITLE
failed to request url unpkg

### ISSUE THREAD

**Issue by Syntax-J** [naptha/tesseract.js#381]
with the tesseract.js-vue-app i got 
https://unpkg.com/tesseract.js@v2.0.0-beta.1/dist/worker.min.js . 
![image](https://user-images.githubusercontent.com/29221509/71398117-644e8100-265a-11ea-946a-87f3f05aedd4.png) . 
![image](https://user-images.githubusercontent.com/29221509/71398194-9829a680-265a-11ea-85f4-d95f9b2083a0.png)

**Comment by jeromewu** [comment]
Right now unpkg CDN is running of capacity, you can use another CDN:

```html
<script src="https://cdn.jsdelivr.net/npm/tesseract.js@v2.0.1/dist/tesseract.min.js"></script>
```

```javascript

const worker = createWorker({
  workerPath: 'https://cdn.jsdelivr.net/npm/tesseract.js@v2.0.1/dist/worker.min.js',
  corePath: 'https://cdn.jsdelivr.net/npm/tesseract.js-core@v2.0.0/tesseract-core.wasm.js',
});
```

Or you can use offline approach: https://github.com/jeromewu/tesseract.js-offline
