### ISSUE TITLE
How to stop/timeout a Worker

### ISSUE THREAD

**Issue by geo-systems** [naptha/tesseract.js#384]
**Is your feature request related to a problem? Please describe.**
I'm running a tesseract js worker on a number of images in a sequence. I want to timeout an image recognition - e.g. kill the recognition if it's not complete within 1 minute. 

I tried to call `terminate` on the worker while it's running, but this doesn't seem to stop the process. 

**Describe the solution you'd like**
Can you introduce an optional timeout parameter of the `recognize` method? 

Alternatively, can you introduce a new method on the worker called `stop`. The method should stop the current recognition process, but the worker object should not be in an inconsistent state - i.e. you should be able to call `recognize` for another image.

**Comment by jeromewu** [comment]
Hi, I have fixed the bug in worker.terminate() (ref #387 ) and you can use it to abort the recognition process.
Sadly, currently we don't support worker.stop() and I will take a look and see if we can do that.

**Comment by Balearica** [comment]
I'm closing this issue as version 3 significantly improves recognition speed, and as nothing should take a minute to recognize (or close), hopefully a timeout for runaway jobs is no longer necessary.  Feel free to reopen if you experience runaway jobs in the latest version.
