### ISSUE TITLE
Percentage for rectangles

### ISSUE THREAD

**Issue by cquanu** [naptha/tesseract.js#385]
Hi,

Can we use percentage for top, left, width & height for rectangles?
Say we have a few images all are different size but the position and size of the rectangle will be dynamic based on the image size. meaning left will always start from 20% of the image, then 50% width of the image and so on...

``` js
// 400px x 400px image
const rectangle = { left: 20%, top: 20%, width: 50%, height: 50% };

// Which will be translated into
const rectangle = { left: 80, top: 80, width: 200, height: 200 };
```

**Comment by jeromewu** [comment]
As the user can calculate percentage with width and height, we don't plan to add this feature.
