### ISSUE TITLE
Terminate() no longer abort the recognition process

### ISSUE THREAD

**Issue by spike886** [naptha/tesseract.js#387]
I tested the v2.0.0-alpha.16 and when you call worker.terminate() to abort the recognize process, but on the v2.0.0-beta.2 it no longer works.

**Comment by jeromewu** [comment]
Hi, I have fixed this issue with a new commit, it should fix the bug.

**Comment by geo-systems** [comment]
This issue was fixed in version `2.0.1`, but was re-introduced later on.

I just upgraded to `2.1.1` and the worker termination no longer aborts the recognition. I had to change revert back to `2.0.1`.
