### ISSUE TITLE
Adding the parameter `user_defined_dpi`

### ISSUE THREAD

**Issue by olivierpascal** [naptha/tesseract.js#393]
To avoid the `Warning: Invalid resolution 0 dpi. Using 70 instead.` (especially when using a canvas or a video as a source) and help Tesseract with the correct resolution, would be great to be able to pass the variable `user_defined_dpi` to `worker.setParameters()`.

**Is your feature request related to a problem? Please describe.**
The recurrent warning `Invalid resolution 0 dpi. Using 70 instead.` is annoying and may lead Tesseract to less accurate OCR results.

**Describe the solution you'd like**
Pass the variable `user_defined_dpi` to `worker.setParameters()`.

**Describe alternatives you've considered**
Using a third-party lib to create a new buffer from a canvas or a video element with EXIF metadata including the resolution.

**Comment by jeromewu** [comment]
Hi, in fact **user_defined_dpi** is included in the `setParameters()`, but for some reason it doesn't work and I haven't found a solution, it is more like a bug in tesseract-ocr instead of tesseract.js

**Comment by olivierpascal** [comment]
Thanks for the reply. I cannot see `user_defined_dpi` in [the API](https://github.com/naptha/tesseract.js/blob/master/docs/api.md#workersetparametersparams-jobid-promise).

By the way, why do maintain a limited supported parameters list? Would it be possible to support the entire parameters list?

```
$ tesseract --print-parameters | wc -l
636
```

**Comment by jeromewu** [comment]
In fact, all the parameters should be supported, we only list for those verified.

**Comment by olivierpascal** [comment]
So the issue is that the typed API forbid any other parameter: https://github.com/naptha/tesseract.js/blob/5a40559db2aee317215421e25eb47bd9238b99ee/src/index.d.ts#L20

**Comment by jeromewu** [comment]
Hi, this issue has been fixed by 6f8e69206b234711c5cfe6b9b685efd093458d94
