### ISSUE TITLE
Adding Occitan language

### ISSUE THREAD

**Issue by Quenty31** [naptha/tesseract.js#395]
Hello,
I would like to know how to contribute to add the Occitan language to the project.
Can I give you some set of data?
Occitan and Catalan share the same alphabet except that Catalan has the middle dot.

**Comment by jeromewu** [comment]
There are two steps to contribute a new traineddata to tesseract.js.

1. Train your own traineddata with tutorials here: https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00
2. Issue a PR to this repository: https://github.com/naptha/tessdata/tree/gh-pages/4.0.0

It is not easy, but it will be great if you can contribute.

**Comment by jeromewu** [comment]
BTW, I found this traineddata on the Internet, not sure if it fits your requirement.

https://zenodo.org/record/2533877#.XjayyHUzbrc

**Comment by Quenty31** [comment]
Hello and thanks for this answer @jeromewu !
So, if I understand it well, the trainedata building step has already been made.
So what's next :D ?

**Comment by jeromewu** [comment]
The next is to issue a PR, but before that we need to get approval from the author of the Occitan traineddata.

**Comment by jeromewu** [comment]
I have added it to tessdata repo and you can check it here: https://github.com/naptha/tessdata/commit/8667756e44b09d8e6f2a504f61173354fe4e25ca
