### ISSUE TITLE
ionic4

### ISSUE THREAD

**Issue by zhuqiyun** [naptha/tesseract.js#396]
error TS2591: Cannot find name 'Buffer'

**Comment by jeromewu** [comment]
Can you provide a sample code to reproduce the issue? Thanks.

**Comment by keremh** [comment]
hi @zhuqiyun ,
I hope, This steps will help you:

- npm i @types/node

- add **"types": ["node"]** in src/tsconfig.app.json

Resource -> https://github.com/aws/aws-sdk-js/issues/2515

**Comment by jeromewu** [comment]
Close due to inactivity.
