### ISSUE TITLE
Error opening data file ./eng.traineddata

### ISSUE THREAD

**Issue by carey4756** [naptha/tesseract.js#398]
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.

**Comment by MacroChip** [comment]
@carey4756 The fix for me was to remove your existing traineddata files.

I started getting this as well today. I cannot figure out what changed between when it worked 2 days ago and now. I haven't updated or reinstalled anything. There must be some component that loads from the internet but doesn't necessarily reload the traineddata.

**Comment by jeromewu** [comment]
One way to fix the problem like this is to change the cacheMethod to not to read from the existing cache, there 2 useful methods to use:

```javascript
const { createWorker } = Tesseract;
const worker = createWorker({
  cacheMehod: 'refresh',  // not to read cache and write back
// cacheMethod: 'none',  // not to read cache and not to write back
});
```

Hope it helps and you can check details here: https://github.com/naptha/tesseract.js/blob/master/docs/api.md#createworkeroptions-worker

**Comment by innerop** [comment]
your workaround doesn't work ... @jeromewu 

Error opening data file ./osd.traineddata
put_char @ tesseract-core.wasm.js:8
write @ tesseract-core.wasm.js:8
write @ tesseract-core.wasm.js:8
doWritev @ tesseract-core.wasm.js:8
_fd_write @ tesseract-core.wasm.js:8
___wasi_fd_write @ tesseract-core.wasm.js:8
(anonymous) @ VM6-4274 wasm-010df0a6-4274:1
(anonymous) @ VM6-2481 wasm-010df0a6-2481:1
(anonymous) @ VM6-155 wasm-010df0a6-155:1
(anonymous) @ VM6-1000 wasm-010df0a6-1000:1
(anonymous) @ VM6-71 wasm-010df0a6-71:1
(anonymous) @ VM6-2839 wasm-010df0a6-2839:1
(anonymous) @ VM6-5522 wasm-010df0a6-5522:1
(anonymous) @ VM6-2045 wasm-010df0a6-2045:1
(anonymous) @ VM6-1674 wasm-010df0a6-1674:1
(anonymous) @ VM6-703 wasm-010df0a6-703:1
(anonymous) @ VM6-6814 wasm-010df0a6-6814:1
Module._emscripten_bind_TessBaseAPI_Recognize_1 @ tesseract-core.wasm.js:8
TessBaseAPI.Recognize.TessBaseAPI.Recognize @ tesseract-core.wasm.js:8
T @ worker.min.js:8
e.dispatchHandlers @ worker.min.js:8
(anonymous) @ worker.min.js:8
tesseract-core.wasm.js:8 Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
put_char @ tesseract-core.wasm.js:8
write @ tesseract-core.wasm.js:8
write @ tesseract-core.wasm.js:8
doWritev @ tesseract-core.wasm.js:8
_fd_write @ tesseract-core.wasm.js:8
___wasi_fd_write @ tesseract-core.wasm.js:8
(anonymous) @ VM6-4274 wasm-010df0a6-4274:1
(anonymous) @ VM6-2481 wasm-010df0a6-2481:1
(anonymous) @ VM6-155 wasm-010df0a6-155:1
(anonymous) @ VM6-1000 wasm-010df0a6-1000:1
(anonymous) @ VM6-71 wasm-010df0a6-71:1
(anonymous) @ VM6-2839 wasm-010df0a6-2839:1
(anonymous) @ VM6-5522 wasm-010df0a6-5522:1
(anonymous) @ VM6-2045 wasm-010df0a6-2045:1
(anonymous) @ VM6-1674 wasm-010df0a6-1674:1
(anonymous) @ VM6-703 wasm-010df0a6-703:1
(anonymous) @ VM6-6814 wasm-010df0a6-6814:1
Module._emscripten_bind_TessBaseAPI_Recognize_1 @ tesseract-core.wasm.js:8
TessBaseAPI.Recognize.TessBaseAPI.Recognize @ tesseract-core.wasm.js:8
T @ worker.min.js:8
e.dispatchHandlers @ worker.min.js:8
(anonymous) @ worker.min.js:8
tesseract-core.wasm.js:8 Failed loading language 'osd'
put_char @ tesseract-core.wasm.js:8
write @ tesseract-core.wasm.js:8
write @ tesseract-core.wasm.js:8
doWritev @ tesseract-core.wasm.js:8
_fd_write @ tesseract-core.wasm.js:8
___wasi_fd_write @ tesseract-core.wasm.js:8
(anonymous) @ VM6-4274 wasm-010df0a6-4274:1
(anonymous) @ VM6-2481 wasm-010df0a6-2481:1
(anonymous) @ VM6-155 wasm-010df0a6-155:1
(anonymous) @ VM6-1000 wasm-010df0a6-1000:1
(anonymous) @ VM6-71 wasm-010df0a6-71:1
(anonymous) @ VM6-2045 wasm-010df0a6-2045:1
(anonymous) @ VM6-1674 wasm-010df0a6-1674:1
(anonymous) @ VM6-703 wasm-010df0a6-703:1
(anonymous) @ VM6-6814 wasm-010df0a6-6814:1
Module._emscripten_bind_TessBaseAPI_Recognize_1 @ tesseract-core.wasm.js:8
TessBaseAPI.Recognize.TessBaseAPI.Recognize @ tesseract-core.wasm.js:8
T @ worker.min.js:8
e.dispatchHandlers @ worker.min.js:8
(anonymous) @ worker.min.js:8
tesseract-core.wasm.js:8 Tesseract couldn't load any languages!
put_char @ tesseract-core.wasm.js:8
write @ tesseract-core.wasm.js:8
write @ tesseract-core.wasm.js:8
doWritev @ tesseract-core.wasm.js:8
_fd_write @ tesseract-core.wasm.js:8
___wasi_fd_write @ tesseract-core.wasm.js:8
(anonymous) @ VM6-4274 wasm-010df0a6-4274:1
(anonymous) @ VM6-2481 wasm-010df0a6-2481:1
(anonymous) @ VM6-155 wasm-010df0a6-155:1
(anonymous) @ VM6-1000 wasm-010df0a6-1000:1
(anonymous) @ VM6-71 wasm-010df0a6-71:1
(anonymous) @ VM6-2045 wasm-010df0a6-2045:1
(anonymous) @ VM6-1674 wasm-010df0a6-1674:1
(anonymous) @ VM6-703 wasm-010df0a6-703:1
(anonymous) @ VM6-6814 wasm-010df0a6-6814:1
Module._emscripten_bind_TessBaseAPI_Recognize_1 @ tesseract-core.wasm.js:8
TessBaseAPI.Recognize.TessBaseAPI.Recognize @ tesseract-core.wasm.js:8
T @ worker.min.js:8
e.dispatchHandlers @ worker.min.js:8
(anonymous) @ worker.min.js:8
tesseract-core.wasm.js:8 Warning: Auto orientation and script detection requested, but osd language failed to load

**Comment by innerop** [comment]
Why don't you share a fully tested example? 

Anyone able to get this thing to work with OSD without the Error message?
