### ISSUE TITLE
typescript inferface definition for RecognizeOptions still uses rectangles[] rather than rectangle

### ISSUE THREAD

**Issue by MatthewSbar** [naptha/tesseract.js#401]
From what I gather there was a change from supporting multiple rectangles to only supporting one per job, but the type definition for the parameter where the rectangle is provided, RecognizeOptions, hasn't been updated, so typescript throws a fit when attempting to provide one rectangle as a parameter

This fix worked for me

In the file 

\tesseract.js\src\index.d.ts

change

  interface RecognizeOptions {
    rectangles: Rectangle[]
  }

to  

interface RecognizeOptions {
    rectangle: Rectangle
  }

**Comment by jeromewu** [comment]
Fixed, thanks for reporting the issue!
