### ISSUE TITLE
Failed loading language 'chi_tra'

### ISSUE THREAD

**Issue by merons** [naptha/tesseract.js#402]
![log](https://user-images.githubusercontent.com/20228882/73620683-5850d880-4676-11ea-8a8b-3fd452a72249.png)

When CDN 2.+ used in Chrome, the corresponding log options appear.
Requests the ability to hide this option.
This option is required only for offline users.

**Comment by jeromewu** [comment]
Can you provide a sample code to produce this issue?
BTW, from the warning you got, it means that you are unable to load the traineddata, which will make tesseract.js unable to execute.

**Comment by jeromewu** [comment]
Close due to inactivity.
