### ISSUE TITLE
.detect() : "Invalid resolution 0 dpi" despite EXIF data on image.

### ISSUE THREAD

**Issue by nightfire445** [naptha/tesseract.js#408]
**I'm running into an issue when using .detect() on this [ JPEG image ](https://ibb.co/ScPL4Zx) with the following EXIF metadata;**

EXIF data:
ImageWidth | 1336
ImageHeight | 200
Orientation | Horizontal (normal)
XResolution | 76
YResolution | 76
ResolutionUnit | inches
Software | Piexifjs
ExifImageWidth | 1336
ExifImageHeight | 200

**Here is my code for the detection. Note that .recognize() works as expected.**

       const { createWorker } = Tesseract;
        const { setLogging } = Tesseract;

        const worker = createWorker({
          tessedit_char_whitelist: ' 0123456789',
          logger: m => console.log(m), // Add logger here
        });

        (async () => {

         await worker.load();
         await worker.loadLanguage('eng+osd');
         await worker.initialize('osd');

         const { skew } = await worker.detect(image);
         console.table(skew);

         await worker.initialize('eng');
         
          
          const { data  } = await worker.recognize(image);

          await worker.terminate();
          return data;

        })()

**Here is the associated Error Stack:**

> tesseract-core.wasm.js:8 Warning. Invalid resolution 0 dpi. Using 70 instead.
> 
> put_char @ tesseract-core.wasm.js:8
> write @ tesseract-core.wasm.js:8
> write @ tesseract-core.wasm.js:8
> doWritev @ tesseract-core.wasm.js:8
> _fd_write @ tesseract-core.wasm.js:8
> ___wasi_fd_write @ tesseract-core.wasm.js:8
> (anonymous) @ wasm-010df0a6-4274:1
> (anonymous) @ wasm-010df0a6-2481:1
> (anonymous) @ wasm-010df0a6-155:1
> (anonymous) @ wasm-010df0a6-1000:1
> (anonymous) @ wasm-010df0a6-71:1
> (anonymous) @ wasm-010df0a6-5380:1
> (anonymous) @ wasm-010df0a6-5382:1
> (anonymous) @ wasm-010df0a6-2787:1
> (anonymous) @ wasm-010df0a6-6696:1
> Module._emscripten_bind_TessBaseAPI_DetectOS_1 @ tesseract-core.wasm.js:8
> TessBaseAPI.DetectOS.TessBaseAPI.DetectOS @ tesseract-core.wasm.js:8
> O @ index.js:219
> e.dispatchHandlers @ index.js:290
> (anonymous) @ index.js:20
> tesseract-core.wasm.js:8 Too few characters. Skipping this page
> put_char @ tesseract-core.wasm.js:8
> write @ tesseract-core.wasm.js:8
> write @ tesseract-core.wasm.js:8
> doWritev @ tesseract-core.wasm.js:8
> _fd_write @ tesseract-core.wasm.js:8
> ___wasi_fd_write @ tesseract-core.wasm.js:8
> (anonymous) @ wasm-010df0a6-4274:1
> (anonymous) @ wasm-010df0a6-2481:1
> (anonymous) @ wasm-010df0a6-155:1
> (anonymous) @ wasm-010df0a6-1000:1
> (anonymous) @ wasm-010df0a6-71:1
> (anonymous) @ wasm-010df0a6-2865:1
> (anonymous) @ wasm-010df0a6-5379:1
> (anonymous) @ wasm-010df0a6-5382:1
> (anonymous) @ wasm-010df0a6-2787:1
> (anonymous) @ wasm-010df0a6-6696:1
> Module._emscripten_bind_TessBaseAPI_DetectOS_1 @ tesseract-core.wasm.js:8
> TessBaseAPI.DetectOS.TessBaseAPI.DetectOS @ tesseract-core.wasm.js:8
> O @ index.js:219
> e.dispatchHandlers @ index.js:290
> (anonymous) @ index.js:20
> createWorker.js:141 Uncaught Error: Failed to detect OS
>     at createWorker.js:141
>     at Worker.e.onmessage (onMessage.js:3)
> (anonymous) @ createWorker.js:141
> e.onmessage @ onMessage.js:3
> index.html:1 Uncaught (in promise) Failed to detect OS

**Any guidance on next steps would be greatly appreciated.**

**Comment by jeromewu** [comment]
Hi,
As "Invalid resolution 0 dpi" is not an Error, but a Warning, so it is not the root cause of the Error.

The real root cause is this statement:

```
tesseract-core.wasm.js:8 Too few characters. Skipping this page
```
When the characters inside your image is too few, it will be impossible for tesseract to detect the OS and thus fail.

**Comment by nightfire445** [comment]
Thank you for the response! Is there a guideline on how many characters is too few? The image I used features 13.

**Comment by jeromewu** [comment]
The default value is 50, you can try to modify parameter `min_characters_to_try` to change this behavior.

```javascript
worker.setParameter('min_characters_to_try', 10); // lower the number of characters needed.
```

I haven't tried if it works or causes any side effect, just for your reference.
