### ISSUE TITLE
Prevent small text recognized as superscript text

### ISSUE THREAD

**Issue by bentinata** [naptha/tesseract.js#409]
**Is your feature request related to a problem? Please describe.**
A smaller text would always assumed as superscript. 

**Describe the solution you'd like**
Have an option to let text baseline not lower than bounding box.

**Additional context**

Image:
![120200213145235](https://user-images.githubusercontent.com/3183661/74413973-07f62980-4e73-11ea-82f3-396b480fe5d3.png)

[Homepage](http://tesseract.projectnaptha.com/) result:
![120200213150613](https://user-images.githubusercontent.com/3183661/74413975-088ec000-4e73-11ea-97f7-f24f2fbe1d5f.png)

Local run resulting text:
![120200213150637](https://user-images.githubusercontent.com/3183661/74413978-09bfed00-4e73-11ea-833c-786bcc542427.png)

**Comment by jeromewu** [comment]
Unless you create your own traineddata for this specific cases, or it is kind of normal for tesseract to have poor result for small text inside an image.
Another possible work around is to have bigger image and use rectangle to recognize only small text part of the image to get a better result.

Key snippet:
```javascript
  const { data: { text } } = await worker.recognize(image, {
    rectangle: {
      top: 0, left: 0, width: 30, height: 100,
    },
  });
```
