### ISSUE TITLE
Bypassing otsu internal binarization preprocessing by providing an 1-bit image for performance purpose

### ISSUE THREAD

**Issue by olivierpascal** [naptha/tesseract.js#410]
See https://groups.google.com/forum/#!searchin/tesseract-ocr/Disable$20image$20pre-processing/tesseract-ocr/beouvbCprNU/6xu7hgWgGP8J

> The only image preprocessing action that is performed is the adaptive image threshold (Otsu).
> If the provided image already is monochrome, it isn't applied, so you don't have to disable it manually.

See https://github.com/tesseract-ocr/tesseract/blob/2a37f5dd6226156bf32e60d1ae0209a383af4843/src/ccmain/thresholder.cpp#L185

```c
if (pix_channels_ == 0) {
  // We have a binary image, but it still has to be copied, as this API
  // allows the caller to modify the output.
  Pix* original = GetPixRect();
  *pix = pixCopy(nullptr, original);
  pixDestroy(&original);
} else {
  OtsuThresholdRectToPix(pix_, pix);
}
```

**Comment by olivierpascal** [comment]
See https://groups.google.com/forum/#!searchin/tesseract-ocr/Disable$20image$20pre-processing/tesseract-ocr/beouvbCprNU/6xu7hgWgGP8J

"The only image preprocessing action that is performed is the adaptive image threshold (Otsu).
If the provided image already is monochrome, it isn't applied, so you don't have to disable it manually."

**Comment by jeromewu** [comment]
No clue to fix this, close for now.
