### ISSUE TITLE
Doc update: Chrome extension demo example.

### ISSUE THREAD

**Issue by fxnoob** [naptha/tesseract.js#411]
I have created a chrome extension using this library. so by using that one can extract text from an image available on any webpage just by hovering over the image and selecting an option from the context menu of chrome.
demo video: https://www.youtube.com/watch?v=27vNfF-K52c
source code: https://github.com/fxnoob/image-to-text
I would like to mention this link into the chrome extension example section.

**Comment by jeromewu** [comment]
Looks great! Let me add it to the README.md
