### ISSUE TITLE
Comparison of diagnostic accuracy between local path and Html Input File

### ISSUE THREAD

**Issue by hamedkhorasani** [naptha/tesseract.js#412]
When the file is selected from INPUT HTML, it recognizes the file more precisely and accurately when the file is selected from the local path.

Screenshot:
[https://filebin.net/jyvmax1090qo22bt/Rec-0062.gif?t=p0zsd1pz](https://filebin.net/jyvmax1090qo22bt/Rec-0062.gif?t=p0zsd1pz)

**Desktop:**
 - OS: [Windows]
 - Browser [chrome]
 - Version [80]

**Comment by jeromewu** [comment]
Hi, sadly the link you provided is not working anymore, can you provide the link again? thanks.

**Comment by jeromewu** [comment]
Close due to inactivity.
