### ISSUE TITLE
Words array not correctly generated for Japanese/Korean/Chinese

### ISSUE THREAD

**Issue by rigelglen** [naptha/tesseract.js#413]
I'm trying to use tesseract js to detect some Korean text, but the tesseract output for words has one character per word.

![20200224_144821](https://user-images.githubusercontent.com/844778/75144229-8cbb3000-571c-11ea-9852-913294b12280.jpg)

<img width="1308" alt="Screenshot 2020-02-24 at 4 22 34 PM" src="https://user-images.githubusercontent.com/844778/75146891-0e618c80-5722-11ea-97f5-3ab7c9430497.png">

The value of text property is correctly recognised as 안녕하세요! without spaces between the characters, however the words array has single characters in it. 

The worker parameters I am setting are:

```
tessedit_pageseg_mode: PSM.AUTO,
tessedit_ocr_engine_mode: OEM.LSTM_ONLY,
preserve_interword_spaces: '1'
```

I am using tesseract.js: "^2.0.2".

**Comment by jeromewu** [comment]
After some quick research, I have to say there is no good way to solve this issue, so we won't fix this issue for now.

**Comment by kazupon** [comment]
Hi!
I have same issue.

I found this issue on tesseract.
https://github.com/tesseract-ocr/tesseract/issues/991

In this issue, it seems to be possible to work around it with parameters.

If tesseract.js-core can also be controlled by parameters, it would seem to solve this issue, but is it hard?
