### ISSUE TITLE
Some image recognition results are null

### ISSUE THREAD

**Issue by iori2882** [naptha/tesseract.js#416]
The pictures below are some special cases in some pictures.The recognition results of these 2 pictures are empty, not a wrong value.However, I Retake screenshots of these 2 pictures, tesseract.js can recognize the value, why is this? Can you help test these 2 pictures, thank you very much!

![0985_20200227_022458](https://user-images.githubusercontent.com/1480587/75376788-98b91480-590b-11ea-9d40-e3a3cec511dc.png)

![0985_20200227_021523](https://user-images.githubusercontent.com/1480587/75376795-9bb40500-590b-11ea-94ee-92eb36910ce9.png)

**Comment by jeromewu** [comment]
I think the root cause is the size of the image as the original one is too small (44x20) for tesseract.js to recognize.

**Comment by iori2882** [comment]
> I think the root cause is the size of the image as the original one is too small (44x20) for tesseract.js to recognize.

It is not the reason that the picture is too small, because 100 pictures of the same type and size, only 1/10 of the pictures read null
