### ISSUE TITLE
Is handwritten supported?

### ISSUE THREAD

**Issue by franciscop** [naptha/tesseract.js#42]
I didn't see it anywhere so I tried it with an online random note and the results were... quite bad:

![hand](https://cloud.githubusercontent.com/assets/2801252/19415435/48ac0854-93ab-11e6-8a59-920eb876ac3e.png)

So I suggest adding a disclaimer stating that it doesn't work with handwritten text

**Comment by bijection** [comment]
Where would you expect to see such a note?

**Comment by ChristopherA334** [comment]
At the family of the kidnapped victims home/mailbox with the details of their demands/ransom.

**Comment by ArnoM** [comment]
I chuckled. But a cleaver kidnapper would use cut out letters of the newspaper. Kidnapping 101

**Comment by Blaccexican** [comment]
https://cloud.githubusercontent.com/assets/2801252/19415435/48ac0854-93ab-11e6-8a59-920eb876ac3e.png

**Comment by bijection** [comment]
Closing this. Feel free to add comments if you have thoughts about disclaimer placement.

**Comment by franciscop** [comment]
I think it was just a misunderstanding on my side and most people wouldn't expect "OCR" to include reading handwritten notes, so never mind. Thanks for the laughts though (:
