### ISSUE TITLE
Partial text recognition

### ISSUE THREAD

**Issue by alizahid** [naptha/tesseract.js#423]
**Is your feature request related to a problem? Please describe.**
I'm trying to run Tesseract.js on a screenshot of a video game. I'm only interested in a few words at a time, which mostly appear towards the top and middle of the screen. Is there any way to do a partial OCR? If a specific word(s) is found, just stop and return the data. I've tried cropping the image to get what I want, but depending on what's on-screen, it can take between 1-8s and time is a critical factor for my use case.

**Describe the solution you'd like**
An optional parameter `string[]` to `recognize` checks for any of those and exists recognition immediately.

**Describe alternatives you've considered**
Cropping the image, but due to the regions I'm looking for, it's not ideal.

**Comment by jeromewu** [comment]
You can check `recognize()` api to see how to recognize only part of the image.

https://github.com/naptha/tesseract.js/blob/master/docs/api.md#worker-recognize
