### ISSUE TITLE
Error Opening Data File ./eng.traineddata

### ISSUE THREAD

**Issue by nereolopez** [naptha/tesseract.js#424]
Hi, 

first of all, thanks for the great work being done with Tesseract.js. I discovered it few months ago and I am testing it offline on phones. I followed [this example](https://github.com/jeromewu/tesseract.js-offline) (and also [this one](https://itnext.io/offline-ocr-with-tesseractjs-and-ionic-5054fc7eef86), but is using v1x). I am using Angular and Capacitor and I have the tesseractjs files inside `assests/lib`  and the language files inside `assets/lib/lang-path`. Below is the code for the `worker` creation: 

```ts
private createOfflineWorker() {
    return createWorker({
      workerPath: '../assets/lib/worker.min.js',
      langPath: '../assets/lib/lang-data/',
      corePath: '../assets/lib/tesseract-core.wasm.js',
      logger: m => this.logProgress(m),
    });
}
```

Here is how I read the image:
```ts
public async readImage(image, selectedLanguage): Promise<Tesseract.RecognizeResult> {
    const worker = this.createOfflineWorker();

    await worker.load();
    await worker.loadLanguage(selectedLanguage);
    await worker.initialize(selectedLanguage);
    
    const result = await worker.recognize(image);
    await worker.terminate();

    this.initializeProgress();    
    
    return result;
}
```

When I run it on the browser with `ng serve` it works perfectly, and the strange thing is that it works perfectly **regardless what I write in the langPath**

When I run it on Android, I get the following errors: 
```
Capacitor/Console: File: http://localhost/assets/lib/tesseract-core.wasm.js - Line 8 - Msg: Error opening data file ./eng.traineddata
Capacitor/Console: File: http://localhost/assets/lib/tesseract-core.wasm.js - Line 8 - Msg: Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
```

Initially I thought it would be an issue with the Android relative paths, but, again, no matter which path I set, the message is always the same. I even tried setting the languages relative to the worker file in case it is looking for it in the same folder, but without luck.

I  saw some threads speaking about the TESSDATA_PREFIX (which I am not using), but all of them were related to other Tesseract flavors (not js), and did not manage to find anything in that sense for `tesseract.js 2.0.2`.

Any idea on how can I use it so that it loads the languages? (I also tried with the comppressed and the uncomprressed language files).

Thanks!

**Comment by jeromewu** [comment]
I think the issue is related to how Capacitor manages storage in Android, it might not be that straight forward to just use the relative path to access the files you need. I would suggest you raise the issue in Capacitor github/community instead of here (as I have no experience in Capacitor).

**Comment by nereolopez** [comment]
Hi @jeromewu, thanks for the answer, but what about the case I mentioned that in the Browser, with Angular, I have a similar behavior but the other way around? (meaning that it works regardless what I assign to the `langPath`)

Thanks

**Comment by jeromewu** [comment]
Well, the root cause might be the cache of the traineddata.
In tesseract.js, the worker will first check the cache to see if the traineddata exists, the worker won't download from langPath if the cache exists, you can try to use "incognito window" in Chrome (or private window in Firefox) to see if it still works with the wrong langPath.

You can find more information here for the cache part: https://github.com/naptha/tesseract.js/blob/master/docs/api.md#createworkeroptions-worker

**Comment by nereolopez** [comment]
Somehow what you say makes sense because I just cloned my repo at home (in my laptop I initially used the `createWorker()` online, so it might have cached it), and now, where there is no cache, the code above is not working either on the browser. I removed the '/'  at the end of the 'langPath' and does not work either. I also tried making that path relative to the worker, and does not work. 
I will try to have it working first offline in the Browser, and then check with the Capacitor team. If you have any hint on why it does not work like that in the Browser, is more than welcome.

Thanks again for your help and the awesome job you guys are doing!

**Comment by pieterdb4477** [comment]
> 
> 
> Well, the root cause might be the cache of the traineddata.
> In tesseract.js, the worker will first check the cache to see if the traineddata exists, the worker won't download from langPath if the cache exists, you can try to use "incognito window" in Chrome (or private window in Firefox) to see if it still works with the wrong langPath.
> 
> You can find more information here for the cache part: https://github.com/naptha/tesseract.js/blob/master/docs/api.md#createworkeroptions-worker

This fixed my issue with finding my custom traineddata. Is there an option to tell tesseract to look in langPath if the cache exists but doesn't contain a language?
