### ISSUE TITLE
Syntax Error in Internet Explorer 11 (Angular)

### ISSUE THREAD

**Issue by PLPatrick** [naptha/tesseract.js#425]
Hi Jerome,

I have a problem with Tesseract, let me explain it: 

I use `Tesseract.js` in an Angular App.
And when I open it on  : `http://localhost:4200/` in **Internet Explorer 11**, I have a white page and a syntax error _(I see it in the developer tools)_.
On other browsers I have no problem.

It seems that Tesseract is not transpiled.
I expect Tesseract to be transpiled and work on IE 11.

Some details: 
 - OS: Windows
 - Browser: Internet Explorer 
 - Browser version: 11

The syntax error points to:
```js
const recognize = async (image, langs, options) => {
  const worker = createWorker(options);
  await worker.load();
  await worker.loadLanguage(langs);
  await worker.initialize(langs);
  return worker.recognize(image)
    .finally(async () => {
  await worker.terminate();
});

```
I target `es5` in my `tsconfig.json` :
```json
"target": "es5",
"lib": [
  "es2017",
  "es6",
  "dom"
 ]
```
I opened the same issue here : [tesseract.js-angular-app/issues/6](https://github.com/jeromewu/tesseract.js-angular-app/issues/6).

Thank you in advance for taking the time to answer my problem.
Cheers, Patrick.

**Comment by jeromewu** [comment]
To use tesseract.js, you need to use browser that at least support asm.js.
As IE 11 doesn't support asm.js, it is impossible to make it work.
Ref: https://caniuse.com/#feat=asmjs

**Comment by crayolakat** [comment]
@PLPatrick I am using Tesseract v1.0.10 for compatibility with IE
