### ISSUE TITLE
Use camera feed to read text

### ISSUE THREAD

**Issue by netgfx** [naptha/tesseract.js#426]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
When user is using their mobile phone with a camera, be able to identify the text (e.g: from a book) and send it to a server.

**Describe alternatives you've considered**
User can always take subsequent pictures and feed them to Tesseract.

**Additional context**

**Comment by jeromewu** [comment]
Hi, I would suggest you check APIs of webcam and reference the example of video to achieve your goal: https://github.com/jeromewu/tesseract.js-video

Feel free to let me know if you have further questions.

**Comment by netgfx** [comment]
Thank you that was awesome example!
