### ISSUE TITLE
Detect text, but not full OCR

### ISSUE THREAD

**Issue by camhart** [naptha/tesseract.js#428]
Can tesseract.js be used to detect where text is in an image, but not do full on OCR?

My hope would be that this would improve the performance, as I don't actually need the text itself, just the location of text.

**Comment by jeromewu** [comment]
Hi, for tesseract.js I don't think it is possible as its model already trained for recognizing text and bounding box at the same time, so it is unlikely to speed up by only doing one of the tasks.
