### ISSUE TITLE
Ability to load, init, download, unzip & load before calling .recognize?

### ISSUE THREAD

**Issue by astopo** [naptha/tesseract.js#43]
Would be awesome to be able to init before invoking `.recognize`

**Comment by thatsmekaustubh** [comment]
its about a year by now
are there any developments w.r.t.  this

**Comment by jeromewu** [comment]
We have enabled this capability in tesseract.js v2, please check below for example:

https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-preload-language-data
