### ISSUE TITLE
Add from_cache in progress

### ISSUE THREAD

**Issue by ThomasKientz** [naptha/tesseract.js#430]
Hi,

First, thanks for the great work.

With v2 there is no way to know if the language is loaded from cache or downloaded, isn't it ? 

https://github.com/naptha/tesseract.js/tree/support/1.x#tesseractjobprogresscallback-function---tesseractjob

**Comment by jeromewu** [comment]
You can use log feature to see more information, including whether it reads from cache.

```javascript
const worker = createWorker({ logging: true });
```

And you will see some extra information:
![image](https://user-images.githubusercontent.com/5723124/77521239-4ee92d00-6ebd-11ea-9119-d64ad9e85f3f.png)

**Comment by ThomasKientz** [comment]
@jeromewu I want to show this inside the UI, so I need to process the output. I have tried :

```
createWorker({
  logger: m => console.log(m),
})
```

But it is missing infos about cache : 

<img width="820" alt="Capture d’écran 2020-03-25 à 10 30 00" src="https://user-images.githubusercontent.com/10157845/77521881-a4a0e380-6e83-11ea-957c-d8bd7dde42a9.png">

**Comment by jeromewu** [comment]
Added in v2.1.1, feel free to try.

![image](https://user-images.githubusercontent.com/5723124/77529158-169c1b80-6eca-11ea-9e62-823599a5eaac.png)

**Comment by ThomasKientz** [comment]
Awesome, thanks !
