### ISSUE TITLE
Rectangle seems to be ignored

### ISSUE THREAD

**Issue by aniljbhatia** [naptha/tesseract.js#432]
**Describe the bug**
Hi,

I am trying to set a rectangle so only a section of the image is being analysed but it seems to be ignored and the whole image is still processed.

What am I doing wrong? Or is there an issue?

Thanks!

**To Reproduce**
I used the example https://github.com/jeromewu/tesseract.js-react-app as a base and added the rectangle code as below:

```
import React, { useEffect, useState, useCallback } from 'react';
import { createWorker, PSM } from 'tesseract.js';
import './App.css';

function App() {
  const [ocr, setOcr] = useState('Recognizing...');

  const doOCR = useCallback(async () => {
    const rectangle = { left: 100, top: 300, width: 350, height: 400 };
    const worker = createWorker({
      logger: m => console.log(m),
    });

    await worker.load();
    await worker.loadLanguage('eng');
    await worker.initialize('eng');
    const result = await worker.recognize('http://localhost:3000/Screenshot_20200327-114025.jpg', { rectangle });
    setOcr(result.data.text);
    await worker.terminate();
  }, []);

  useEffect(() => {
    doOCR();
  }, [doOCR]);

  return (
    <div className="App">
      <p>{ocr}</p>
    </div>
  );
}

export default App;
```

**Expected behavior**
Expecting only the text in the defined rectangle to be processed.

**Comment by jeromewu** [comment]
The issue should be caused by using the old version of tesseract.js, please upgrade to the latest version of tesseract.js and try again.

```
$ npm install tesseract.js@latest
```

**Comment by aniljbhatia** [comment]
Ah ah! Don't know why I didn't think to try upgrading! Thanks.
