### ISSUE TITLE
Lambda layer access complication

### ISSUE THREAD

**Issue by lajpatshah** [naptha/tesseract.js#433]
I created 2 Lambda layers 

1. containing node_modules including tessearct which is loaded as /opt/nodejs/node_modules
2. containing tessearct lang gz data files which is loaded as /opt/nodejs/lang

Lang files are not loaded at the time of creating worker. I tried different options even giving absolute path yet it gives error. My code could successfully check existence of gz file in lang folder. But the same gives error when passed to createWorker.

I am sorry if I am out of line here.

**Comment by jeromewu** [comment]
Can you paste any error message here? It is pretty hard to guess from your description.

**Comment by lajpatshah** [comment]
Hello @jeromewu will recreate Lambda and send you the error. Will close this issue as it would unnecessarily appear unresolved. Thank you for your time.
