### ISSUE TITLE
in electron, I give a File object (from a file <input>)

### ISSUE THREAD

**Issue by lk0606** [naptha/tesseract.js#437]
![image](https://user-images.githubusercontent.com/43233310/78554094-13474f00-783d-11ea-84fd-c2a093475da0.png)

**Comment by jeromewu** [comment]
Can you provide the full code to reproduce this issue? Thanks.

**Comment by lk0606** [comment]
> Can you provide the full code to reproduce this issue? Thanks.

[my github](https://github.com/lk0606/ocr-electron-react/blob/dev/src/components/upload.jsx),thanks

**Comment by jeromewu** [comment]
As your code failed right after the `loading language traineddata` log, I think you are having the Network issue, please try to use offline version: https://github.com/jeromewu/tesseract.js-offline

**Comment by lk0606** [comment]
> https://github.com/jeromewu/tesseract.js-offline

but, in Browser, it worked. in electron, got this

**Comment by jeromewu** [comment]
If that is the case, I am afraid there is nothing I can help as I cannot reproduce your issue and you don't consider my suggestion.
