### ISSUE TITLE
support more unicode symbols

### ISSUE THREAD

**Issue by escapiststupor** [naptha/tesseract.js#442]
I am trying to recognize something like this
<img width="232" alt="Screen Shot 2020-05-01 at 9 31 08 PM" src="https://user-images.githubusercontent.com/8017959/80810387-4db2ca80-8bf6-11ea-8117-ea3e9c8a1952.png">

Is there any way to support these symbols (♥♢♧♡♤♦♣♠) ?

I tried to set `tessedit_char_whitelist` but it doesn't recognize those symbols.

I am using it as a client-side app so can't really train it.

**Comment by Balearica** [comment]
These symbols are not included in the existing .traineddata files for any language.  You could make a new .traineddata file that supports these symbols, however doing so is outside the scope of this repository (as this must be done using the desktop version of Tesseract).  Users interested in this should consult the documentation from the [main Tesseract project](https://github.com/tesseract-ocr/tessdoc/blob/main/OldVersionDocs.md).
