### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by BrunoiTandel1996** [naptha/tesseract.js#445]

**Comment by BrunoiTandel1996** [comment]
<script src="/dist/tesseract.dev.js"></script>
I downloaded the source code and tried to run the file. But here it says failed to load resource for the above script.
Can you please help me out with this?

**Comment by Balearica** [comment]
If `tesseract.dev.js` does not exist either (1) no build was run (2) the production version of the build was run (which creates `tesseract.min.js` instead).  

Anybody encountering this should either switch the `src` tag to use the production version (`tesseract.min.js`) or build the development version as explained in the instructions [here](https://github.com/naptha/tesseract.js#development).
