### ISSUE TITLE
Slow recognition, randomly stops and 10gb+ RAM usage.

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [naptha/tesseract.js#446]
I was trying to do text recognition on this image
![test](https://user-images.githubusercontent.com/32597776/81866461-7002fb80-9599-11ea-8741-a1c46bf44d2f.jpg)

And it took  more than 3 minutes until it randomly stopped at  ` progress: 0.8285714285714286` , and used up to 10gb+ of RAM (probably more if i have free memory left)

![image](https://user-images.githubusercontent.com/32597776/81866552-8c069d00-9599-11ea-9291-80c835dec370.png)

Is this normal..?

The code:
```js
import Tesseract from "tesseract.js";

Tesseract.recognize(
	"D:/test/test.jpg",
	"eng",
	{ logger: m => console.log(m) }
).then(({ data: { text } }) => {
	console.log(text);
});
```

I'm using v2.1.1

**Comment by chriszhou1017** [comment]
I also encountered with this issue, it takes about 7GB ram and stop. The code is just like yours.

**Comment by chriszhou1017** [comment]
I`ve ran some test and find out a solution to this issue, you should split the picture to several segments, and do ocr to these segments one by one.

It seems that long text with noise will make the app to crash.

**Comment by sasukecodes** [comment]
The weird thing is that this doesn't happen in their web demo even when offline. There's definitely something wrong.

**Comment by SuspiciousLookingOwl** [comment]
Btw I ended up using [node-tesseract-ocr](https://www.npmjs.com/package/node-tesseract-ocr) which is way way faster for my use case

**Comment by Balearica** [comment]
The performance-related issues should be solved the latest version (v3).  I recognized this image as a test, and it took <7 seconds to run.
