### ISSUE TITLE
Giving Firefox extensions some love too

### ISSUE THREAD

**Issue by gnonio** [naptha/tesseract.js#447]
I recently published [korporize over at AMO](https://addons.mozilla.org/en-GB/firefox/addon/korporize/), allowing Firefox access to this great library on the browser extension side, and have included *very* basic Tesseract.js functionality. Currently in a very experimental state (v0.9.2) I invite everyone to try it out.

korporize will be part of a more ambitious extension and there are some features I need to include before declaring v1.0 but I am open to suggestions and issues anyone may find. Feel free to drop by the [github repository](https://github.com/gnonio/korporize). And if it helps anyone in their projects I'll be happy too.

This is neither an Bug or exaclty a Tesseract.js issue, obviously if this announcement should be seen as inappropriate, please close it down. In any case look at korporize as my giving back for the great Tesseract.js project. Much appreciated.

**Comment by jeromewu** [comment]
Interesting, I will add this addon to the README.md, let me know if you don't want to it. :smile:

**Comment by jeromewu** [comment]
Commit here: https://github.com/naptha/tesseract.js/commit/fcd01ceb325ef8c63ae126586521205848269c2d
