### ISSUE TITLE
can't load 'https://cdn.rawgit.com/naptha/tessdata/gh-pages/3.02/'

### ISSUE THREAD

**Issue by lxp521125** [naptha/tesseract.js#45]
dear,
the 'langPath' I can't open, location is not work.
maybe need another CDN path.
in china

**Comment by bijection** [comment]
Can you include a screenshot of your console showing the error you're getting?

**Comment by rowasc** [comment]
In addition to adding a console error log, maybe you can try downloading this trained data set from the browser . If you can download it, the CDN access itself is not the problem.
https://cdn.rawgit.com/naptha/tessdata/gh-pages/3.02/en.traineddata.gz

**Comment by lxp521125** [comment]
![image](https://cloud.githubusercontent.com/assets/13718014/19422512/3a03b002-9448-11e6-91ba-d1f8b29ceab0.png)

**Comment by jessemortenson** [comment]
I am currently getting the same "404: Not Found" at that URL. Firefox and Chromium. Location: Minnesota, USA.

**Comment by lxp521125** [comment]
![image](https://cloud.githubusercontent.com/assets/13718014/19422687/edfa3a02-944a-11e6-9305-2141ffa23d93.png)

good news, now I'm OK!

**Comment by bijection** [comment]
@rowasc you have a type in that url. It should be https://cdn.rawgit.com/naptha/tessdata/gh-pages/3.02/eng.traineddata.gz

**Comment by bijection** [comment]
Closing this because @lxp521125 has figured it out.
