### ISSUE TITLE
Could we have built-in pre-processing filters that might help with accuracy?

### ISSUE THREAD

**Issue by geoyws** [naptha/tesseract.js#451]
**Is your feature request related to a problem? Please describe.**
![mr bean](https://user-images.githubusercontent.com/1738396/82642250-33419f00-9c40-11ea-836e-6368874e3124.jpg)
When the picture has a lot of background noise, colour or when the picture is pixelated, like the picture above, Tesseract oftentimes returns nothing. Google's Vision API however has no problems accurately returning the strings. Could it be pre-processing filters? Or some form of machine learning we're not applying?

**Describe the solution you'd like**
I wonder if Tesseract could get up to Google Vision API's level of accuracy.

**Comment by jeromewu** [comment]
Right now we don't have plan for that, but you can use other libraries to do preprocessing.
Some people suggest to use this one: http://manuels.github.io/unix-toolbox.js/
