### ISSUE TITLE
Tesseract example is not working?

### ISSUE THREAD

**Issue by phamvanlinh20111993** [naptha/tesseract.js#453]
I am trying to use tesseract to translate images. When I use the example given on git it doesn't work. Photo below:
- In the browser nothing text console.
![image](https://user-images.githubusercontent.com/26922207/83948657-d4d40d80-a848-11ea-884f-c2c376ec2bd1.png)
- Here is my code: 
![image](https://user-images.githubusercontent.com/26922207/83948675-ee755500-a848-11ea-858d-4465b1de1b13.png)
Am I missing anything? thanks

**Comment by jeromewu** [comment]
It should be working, maybe you just got a slow network or hardware, judge from your log.

**Comment by phamvanlinh20111993** [comment]
I don't think so, because I visit websites like facebook or instagram and even play games and everything is normal. I have tried to run the program many times but it still looks like the picture. :(.

**Comment by nav1-code** [comment]
try his code:
```
Tesseract.recognize(
  "https://tesseract.projectnaptha.com/img/eng_bw.png",
  "eng",
  {
    logger: (m) => console.log(m),
  }
).then((text) => {
  console.log("get  text", text.text);
});
```
for me it works :)

**Comment by phamvanlinh20111993** [comment]
I tried it but nothing changed :( :( @nav1-code

**Comment by Balearica** [comment]
Closing as this issue is >2 years old and we don't have a reproducible example to follow up on.  Given that other users were able to run identical code, my guess is that OP's language data cache was corrupted (see ##666).
