### ISSUE TITLE
OCR of white text appears to not work very well, but inverting solves the issue.

### ISSUE THREAD

**Issue by andrewkfiedler** [naptha/tesseract.js#454]
I'm trying to use the ocr on some Japanese text images, but not getting very good results.  I've attached a codepen example.

Maybe it's a configuration issue?

https://codepen.io/andrewkfiedler/pen/BajNYBR?editors=1010

![Screen Shot 2020-06-06 at 8 05 34 PM](https://user-images.githubusercontent.com/11984853/83959362-1c4e9f80-a831-11ea-877a-2cfb265b88fa.png)

**Comment by andrewkfiedler** [comment]
So I decided to run an experiment today where I inverted the whites / blacks on that image, thinking that maybe tesseract is expecting black text.  

https://codepen.io/andrewkfiedler/pen/vYLNZgW?editors=1010

It appears to work perfectly if I do that 🎉 

![Screen Shot 2020-06-08 at 11 46 39 AM](https://user-images.githubusercontent.com/11984853/84068398-bb80ad80-a97d-11ea-9189-c972a9eb8c31.png)

Is this solvable by configuration?  Or would changes need to be made to tesseract to handle white text instead of black text?

**Comment by jeromewu** [comment]
I am glad you have find the solution. :smile: 
It is not solvable by configuration, so image processing is the right way to do.

**Comment by andrewkfiedler** [comment]
Yeah, I'm glad it turned out to be a relatively simple fix 😌 

In case anyone stumbles across this in the future, here's function you might find useful:

```
async function toDataURL(url) {
  return new Promise((resolve, reject) => {
    var xhr = new XMLHttpRequest();
    xhr.onload = function () {
      var reader = new FileReader();
      reader.onloadend = function () {
        const canvas = document.createElement("canvas");

        const ctx = canvas.getContext("2d");
        var image = new Image();
        image.onload = function () {
          canvas.width = image.width;
          canvas.height = image.height;
          ctx.globalCompositeOperation = "difference";
          ctx.fillStyle = "#fff";
          ctx.fillRect(0, 0, canvas.width, canvas.height);
          ctx.drawImage(image, 0, 0);
          resolve(canvas.toDataURL("image/jpeg", 1));
        };
        image.src = reader.result as string;
      };
      reader.readAsDataURL(xhr.response);
    };
    xhr.open("GET", url);
    xhr.responseType = "blob";
    xhr.send();
  });
}
```

The important parts (where the inverting is done) are in the img `onload` function.  Order of operations there does matter, since you need to specify the inverting function before you draw to the canvas.  Hope that helps!
