### ISSUE TITLE
Bundler tesseract.js with @zeit/ncc in AWS lambda function

### ISSUE THREAD

**Issue by samuv** [naptha/tesseract.js#458]
Hello,

I'm trying to bundle tesseract.js that I'm using with nodejs in a lambda, right now I'm including the node_modules folder in the zip, usually, I will use [@zeit/ncc](https://github.com/vercel/ncc) and bundling everything in a single file js.

My problem when I used ncc is the worker-script is exported in a separate file without resolving his dependencies, what file a need to target for bundling the worker-script?

creating a separate file and in createWorker config target that file.

Does it make sense?

**Comment by samuv** [comment]
I want to put an update on this; maybe it can help someone with my same necessities.

- I have used the eng.traineddata not zipped, so the lambda doesn't need to unzip
- I have targeted my lambda code with tessseract.js as dependency with ncc
- I have targeted this path for the node worker `./node_modules/tesseract.js/src/worker-script/node/index.js` with ncc and put it in the worker folder.
- But for working correctly, I had to copy the wasm file too `./node_modules/tesseract.js-core/tesseract-core.wasm` that I put in the worker folder.
- the config for the `createWorker` is something like this 
```
{
  langPath: path.join(__dirname, 'lang'),
  cachePath: path.join(__dirname, 'lang'),
  workerPath: path.join(__dirname, '/worker/index.js'),
  cacheMethod: 'readOnly',
  gzip: false,
}
```

This work as intended, I'm creating for each lambda a worker, I don't know if this is the best way, I need to make some further test.
The final lambda with other stuff in it is 13MB, that is not bad at all.

**Comment by ferrygun** [comment]
@samuv Could you provide the detailed steps how to bundle with ncc?

**Comment by samuv** [comment]
> @samuv Could you provide the detailed steps how to bundle with ncc?

I had to retrieve the test folder where I developed this. If it can help here is how I was declaring the scripts on my package.json

```json
    "boundleWorker": "npx @zeit/ncc build ./node_modules/tesseract.js/src/worker-script/node/index.js -o ./dist/worker",
    "bundle": "npx @zeit/ncc build index.js -o ./dist/ ",
    "build": "npm run bundle && npm run boundleWorker"
```

logic inside the index.js

```javascript
import { createWorker, OEM } from 'tesseract.js'

const tesseractWorker = createWorker({
  langPath: path.join(__dirname, 'lang'),
  cachePath: path.join(__dirname, 'lang'),
  workerPath: './worker/index.js',
  cacheMethod: 'readOnly',
  gzip: false,
  errorHandler: (err) => console.log('error', err),
})
```

It was Jun of 2020, so I don't remember anything else about this 🤣 sorry for the late answer @ferrygun 

I think I can close this
