### ISSUE TITLE
Standalone HTML with offline tessaract is not working

### ISSUE THREAD

**Issue by javadevelopment4** [naptha/tesseract.js#459]
I would like to have a standalone HTML file which accepts image as well as language. Process the file without any web server. 

I have created the HTML withe all libraries in a local folder. However it is failed to work. 

Can you please kindly help me with the HTML code so that i can use it standalone?

why can't run without a server ? I want to have my offline conversion in my local laptop which should not expects a server..

**Comment by Osmiogrzesznik** [comment]
from what i see it progressively downloads worker scripts

**Comment by Osmiogrzesznik** [comment]
try this https://github.com/naptha/tesseract.js/blob/master/docs/local-installation.md

**Comment by yaswanthsvist** [comment]
@Osmiogrzesznik  Thank u, 
I have fixed this issue using webpack.
``` js
const MergeIntoSingleFilePlugin = require("webpack-merge-and-include-globally");
```

``` js
plugins: [
    new MergeIntoSingleFilePlugin({
      files: {
        "tesseract-worker.min.js": [
          "./node_modules/tesseract.js/dist/worker.min.js",
        ],
        "tesseract-core.wasm.js": [
          "./node_modules/tesseract.js-core/tesseract-core.wasm.js",
        ],
      },
    })
   ]
```
while creating worker some where
``` js
const worker = createWorker({
  workerPath: location.href + "/tesseract-worker.min.js",
  langPath: "./lang-data", // downloaded trained data files.
  corePath: location.href + "/tesseract-core.wasm.js"
});
```

**Comment by brightinnovator** [comment]
@yaswanthsvist can you please attach the full HTML file for reference and testing. Thank you

**Comment by yaswanthsvist** [comment]
@brightinnovator  Unfortunately my tesseract processing code is not inside index.html.

copy the bellow files from node_modules to the directory where ur index.html file is located and refer these files from your code

```
cp ./node_modules/tesseract.js/dist/worker.min.js  ./path_where_index.html_is_present/
cp ./node_modules/tesseract.js-core/tesseract-core.wasm.js  ./path_where_index.html_is_present/
```
in ur index.html
```
<script>
 (async ()=>{
  const worker = createWorker({
    workerPath: "./worker.min.js",
    langPath: "./lang-data", // downloaded trained data files.
    corePath: "./tesseract-core.wasm.js"
  });
  await worker.load();
  await worker.loadLanguage("eng");
  await worker.initialize("eng");
  
 })()
</script>
```

mostly this should work for you to up and running it in offline.

**Comment by brightinnovator** [comment]
can you please attach one sample HTML as well for the above for testing and implement in the website?

**Comment by Balearica** [comment]
Let me know if this issue is still active, and if so, what the use-case for an offline .html version would be.  A standalone/offline .html file seems entirely possible from a technical perspective, however as the base [Tesseract program](https://github.com/tesseract-ocr/tesseract) can be compiled to run on almost any device (and run faster), it's unclear to me what the utility of an offline version of the wasm port would be.

**Comment by Balearica** [comment]
Closing as stale.  Feel free to reopen if you believe there is a compelling use case for a fully offline .html version.
