### ISSUE TITLE
TesseractWorker is not a constructor with new version

### ISSUE THREAD

**Issue by DM-Aburumman** [naptha/tesseract.js#460]
I installed the latest version of Tesseract but still give me the same error " TesseractWorker is not a constructor"

version used "tesseract.js": "^2.0.0-beta.2"

**Comment by DM-Aburumman** [comment]
<img width="397" alt="error" src="https://user-images.githubusercontent.com/57400853/85230192-92d9c880-b3ff-11ea-988d-2f8f10f5d95a.PNG">

**Comment by dht6903** [comment]
I also ran into this issue using 2.1.1 with vue

**Comment by somya339** [comment]
$ npm install tesseract.js@next

In the latest version (2.0.0-beta.1), TesseractWorker has deprecated and you need to use createWorker instead. Check README.md for details.

**Comment by Balearica** [comment]
Closing as this was a intended/documented change in a major release.
