### ISSUE TITLE
Tesseract couldn't load any languages

### ISSUE THREAD

**Issue by cheeck97** [naptha/tesseract.js#462]
Hello, I recently encountered such a problem that a tesseract cannot load / initialize * .traineddata. 
![image](https://user-images.githubusercontent.com/30501031/85364931-f31a5880-b52c-11ea-957b-5130c7d6ce21.png)
But by the time I start receiving this message, the tesseract already recognized about 50 iterations in 1-2 hours. *.traineddata is in two places: in the root of the launch and in the TESSDATA_PREFIX environment (/usr/local/share/tessdata). 
![image](https://user-images.githubusercontent.com/30501031/85365434-0548c680-b52e-11ea-9350-78b18504c0aa.png)
If I reload * .traineddata, the problem will be solved only temporarily
Help me solve the problem please

_OS : Ubuntu 18.04.3
NodeJS: 13.8.0
NPM: 6.13.6
Tesseract.js: 2.1.1_

**Comment by Balearica** [comment]
If this issue is still active, can you post a snippet of the code your were running and/or confirm whether or not you were using a scheduler? There seems to be an issue stemming from multiple processes writing to the same `.trainneddata` file, so I'm wondering if this is caused by that.

**Comment by Balearica** [comment]
@herecy I was able to reproduce this bug in version 2, but not the current version (v3).  If this issue is still active, please confirm you still encounter this bug in the latest version and provide a reproducible example.

**Comment by Balearica** [comment]
I implemented changes that should resolve this in [Version 4](https://github.com/naptha/tesseract.js/releases/tag/v4.0.0).  Specifically, the cache used to be overwritten with each `recognize` job, which I believe lead to it being randomly corrupted seemingly at random (often after hours of recognition jobs).  If anybody encounters this error using v4, please open a new issue.
