### ISSUE TITLE
Any method to  make  ’recognize‘  faster？

### ISSUE THREAD

**Issue by ThenMorning** [naptha/tesseract.js#463]
As the title.
Thanks!

**Comment by miguelm3** [comment]
I just found on the readme the section, that speeded up a lot the recognition. I don't know exactly how or why multiple workers work better.
https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-multiple-workers-to-speed-up-200-beta1

**Comment by ThenMorning** [comment]
> I just found on the readme the section, that speeded up a lot the recognition. I don't know exactly how or why multiple workers work better.
> https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-multiple-workers-to-speed-up-200-beta1

Thanks.

**Comment by Balearica** [comment]
Closing as the significant performance disparity between C++ and wasm was resolved in the latest release 3.0.0. Feel free to open another issue if you encounter outrageous runtimes, but everything should now feel much faster.

Note: anything run on Safari will continue to be significantly slower as Apple has not yet implemented SIMD support. If you're reading this in the future, the following link should show if that has changed yet.

https://webassembly.org/roadmap/
