### ISSUE TITLE
Cannot read property 'arrayBuffer' of undefined ( Electron.js + Vue.js)

### ISSUE THREAD

**Issue by marcoippolito** [naptha/tesseract.js#465]
With this simple vue file taken from: https://raw.githubusercontent.com/jeromewu/tesseract.js-electron/master/index.html : 

    <template>
      <div>
      </div>
    </template>

    <script>

    // https://github.com/jeromewu/tesseract.js-electron/blob/master/index.html

    import { createWorker } from 'tesseract.js';
    import path from 'path';

    let __dirname = "";

    export default {
      mounted () {
          const worker = createWorker({
            cachePath: path.join(__dirname, "lang-data"),
            logger: m => console.log(m),
          });

          (async () => {
            // await worker.load();
            await worker.loadLanguage('eng');
            //await worker.initialize('eng');
            //const { data: { text } } = await worker.recognize(path.join(__dirname, 'images', 'testocr.png'));
            //console.log(text);
            //await worker.terminate();
          })();
      }
    }

    </script>

I get this error:
"Uncaught Error: TypeError: Cannot read property 'arrayBuffer' of undefined createWorker.js:173 at Worker.worker.onMessage"
![image](https://user-images.githubusercontent.com/3073209/87558480-7278f300-c6b9-11ea-9d67-1feea127f12e.png)

How to solve the problem?

Marco

**Comment by ColorfulHorse** [comment]
version 2.0.0 is ok

**Comment by marcoippolito** [comment]
@ColorfulHorse Thank you! Yes. With version 2.0.0. is ok.
So it means that the vuersion 2.0.1 has a bug

**Comment by jeromewu** [comment]
Please check v2.1.4 for the fix of this issue. :smile:
