### ISSUE TITLE
langpath to use custom .trainneddata 

### ISSUE THREAD

**Issue by alkoow** [naptha/tesseract.js#467]
Hello!
I've used the v2 CDN to integrate Tesseract to my index.php file, but I want to use only digits...

As I used PHP for my project, I've imported it on a free web server, WebHost, to test it more easily.
So, I've created this tree into it :
/
├── public_html/
│   ├── index.js
│   ├── index.php
│   └── tessdata/
│        └── digits.traineddata

Here is my reference in my PHP file :
```php
<script src='https://unpkg.com/tesseract.js@v2.1.0/dist/tesseract.min.js'></script>
```

And here is my js createWorker :

```js
// OCR
const { createWorker } = Tesseract;

const worker = createWorker({ 
    langPath: "./tessdata/",
    gzip: false,  
    logger: m => console.log(m)
});
(async () => {
await worker.load();
await worker.loadLanguage('digits');
await worker.initialize('digits');
const { data: { text } } = await worker.recognize(canvas);
// When we get the text, we test it
testCaractere(text);
})();
```
I'm out of idea for making work this path, I've done so many different tries, the code above is only my last attempt.

To be honest, I think it's the first time I'm going so far in a project, and I'm a bit overwhelmed by a few things.

I will try to make it as localhost but is something gets any idea in order to make it work?

Have a nice day,
Az'

**Comment by 3epnm** [comment]
In NodeJS environment, custom .trainneddata can be loaded, if the cachePath option is set to the same path as langPath. In a Browser enviroment, [idb-keyval](https://github.com/jakearchibald/idb-keyval) is used to cache language data. Perhaps, changing/adding custom langdata directly into the indexdb is worth a try.

**Comment by Balearica** [comment]
Closing as stale given this doesn't appear to be a bug report and it's been a couple of years since this was asked.  Feel free to reopen if still active.
