### ISSUE TITLE
Not getting Clear Output..Few symbols and unknown characters are coming in output..Can someone please help

### ISSUE THREAD

**Issue by aditya0salaria** [naptha/tesseract.js#470]
Hi Guys,

I need help regarding tesseract functionality. I am using below code, Output is coming but not getting clear output. Is there any way, we can get clear output. Below is the code:

Library used below:

<script src='https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js'></script>
function used below:
setTimeout(function(){
var myImage= document.getElementById('ImageId');
Tesseract.recognize(myImage).then(function(result){
$('#Output').val(result.text);
});
},1000);

I have attached few images as an example which i need to convert to text
![75985eb8-8299-4139-80dd-ea3826b5d104](https://user-images.githubusercontent.com/68499895/87873033-a87ce680-c9db-11ea-83c9-c9d849b6286a.JPG)

**Comment by Balearica** [comment]
Closing as stale and not a bug/feature request.
