### ISSUE TITLE
Alternative Symbol Choices?

### ISSUE THREAD

**Issue by ishkena** [naptha/tesseract.js#472]
I was looking for a way to access the alternative symbol results from the OCR engine. I noticed that confidence for alternative symbol choices was included in the documentation for the original Tesseract project at https://tesseract-ocr.github.io/, but I couldn't find a similar solution in JavaScript. Any ideas?

**Comment by Balearica** [comment]
Tesseract.js reports this at present.  If `ret` is the object returned by `worker.recognize`, the following would extract alternative symbol choices for the first letter in the first word.

```
ret.data.blocks[0].paragraphs[0].lines[0].words[0].symbols[0].choices
```

**Comment by Balearica** [comment]
Closing as answered.
