### ISSUE TITLE
ERR_IPC_CHANNEL_CLOSED: Channel closed 

### ISSUE THREAD

**Issue by marcoippolito** [naptha/tesseract.js#475]
When I try to call an async function from dialog.showOpenDialog I get this error and the window crashes:

![image](https://user-images.githubusercontent.com/3073209/89738184-08b0f680-da77-11ea-98dc-3e46cb579da5.png)

called function:

    import { createWorker } from 'tesseract.js'
    const path = require('path')

    const worker = createWorker();

    export default async function imgToText(imgFilePath: string): Promise<void> {
      const image = path.resolve(__dirname, imgFilePath)
      await worker.load();
      //await worker.loadLanguage('eng');
      //await worker.initialize('eng');
      //const { data: { text } } = await worker.recognize(image);
      //console.log(text);
      //await worker.terminate();
    }

This is the calling function :  

    async function loadFile() {
      dialog.showOpenDialog({
        properties: ['openFile', 'multiSelections'],
      }).then(result => {
        result.filePaths.forEach((filepath: string) => {
          imgToText(filepath);
        })
      }).catch(err => {
        console.log(err)
      })
    }

Other info:

    Electron version: 9.0.0
    Typescript version: 3.9.7
    tesseract.js version: 2.1.1
    System:
      OS: Linux 5.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    Browsers:
      Chrome: 84.0.4147.105
      Firefox: 79.0

How to solve the problem?
Looking forward to your kind help.
Marco

**Comment by Ganeshjadhav221b** [comment]
Any updates/workarounds on this? Im facing same issue.

**Comment by crohit92** [comment]
I am also getting the same error.

**Comment by Balearica** [comment]
Closing this issue as the master branch now uses `worker_threads` rather than `child_process` (per #630).  Therefore, you should not encounter this particular error again.  If you encounter a new error, feel free to open a new issue.
