### ISSUE TITLE
pdf support

### ISSUE THREAD

**Issue by jmsilcom** [naptha/tesseract.js#479]
**Describe the solution you'd like**

I'd like to know if tesseract js support pdf format ?

**Comment by idmyn** [comment]
Hi @jmsilcom, there's an example of converting png to pdf [here](https://github.com/naptha/tesseract.js/blob/6021eca27a03bd74c5bac7ca5732d75ec1d8f20b/examples/browser/download-pdf.html) - hope that helps

**Comment by kumailraza-4kites** [comment]
![image](https://user-images.githubusercontent.com/99461943/163326096-2a6ec45d-c2ce-4cf3-bcac-bf7c0f75a480.png)

**Comment by Balearica** [comment]
Tesseract does not support .pdf directly, so .pdfs must be converted to images first.  .pdf libraries are quite large, so it's best that users who need this functionality add a .pdf library to their project and do this step themselves.  

Good js/wasm .pdf libraries that can convert .pdf -> images are:
1. [PDF.js](https://github.com/mozilla/pdf.js/) (Apache-2.0 license)
2. [muPDF](https://github.com/ArtifexSoftware/mupdf) (AGPL-3.0 license)

**Comment by 993620475** [comment]
> 嗨@jmsilcom，[这里有](https://github.com/naptha/tesseract.js/blob/6021eca27a03bd74c5bac7ca5732d75ec1d8f20b/examples/browser/download-pdf.html)一个将 png 转换为 pdf 的示例 - 希望有帮助

Error in pixReadStream: Pdf reading is not supported
