### ISSUE TITLE
Large images cause a delay

### ISSUE THREAD

**Issue by tim-krieger** [naptha/tesseract.js#490]
If I use a photo (~5 M) it takes a long time (~15 sec) before the text recognition starts. The browser console shows me` [Violation] 'load' handler took`. Same issue with https://github.com/naptha/tesseract.js/blob/master/examples/browser/basic.html. 

Is this a normal behavior or should I resize the image? Smaller pictures (~1 M) are no problem.

**Comment by WintrySnowman** [comment]
This may be related to [this line](https://github.com/naptha/tesseract.js/blob/adcb5b875986ebe61d7235e64d956d648c53c1dd/src/worker-script/utils/setImage.js#L12), which is causing a hang depending on how many bytes it needs to process. I've made a patch in #610 whilst adding support for `ImageData`.

**Comment by Balearica** [comment]
Closing as this should be resolved with the release of version 3.0.0.  Feel free to open another issue if that is not the case.
