### ISSUE TITLE
worker.recognize() works in node.js environment, but not in chrome browser environment.

### ISSUE THREAD

**Issue by elrion018** [naptha/tesseract.js#495]
**Describe the bug**
worker.recognize() works in node.js environment, but not in chrome browser environment.

**To Reproduce**
1. create-react-app
2. yarn start
3. see error

**Expected behavior**
I wanted to recognize text in image files normally.

**code**

```
import { createWorker } from "tesseract.js";
const worker = createWorker({
  logger: (m) => console.log(m),
});

async function getTextFromImage() {
  await worker.load();
  await worker.loadLanguage("eng");
  await worker.initialize("eng");

  const {
    data: { text },
  } = await worker.recognize("./test.png");
  await worker.terminate();

  return text;
}
getTextFromImage().then(console.log);
```

**Screenshots**
![캡처](https://user-images.githubusercontent.com/41279460/98711743-bb6f5880-23c8-11eb-813c-a5dd5b0f3d3a.PNG)
![캡처](https://user-images.githubusercontent.com/41279460/98711890-f1acd800-23c8-11eb-9ce8-25628715f17a.PNG)
![캡처](https://user-images.githubusercontent.com/41279460/98932909-50866480-2523-11eb-8c27-ab5a87841f4a.PNG)

There is code with error at the line 26 of https://github.com/naptha/tesseract.js/blob/master/src/worker/browser/loadImage.js
Local images are recognized properly in the node.js environment, but chrome browsers do not.

**Desktop (please complete the following information):**
 - OS: window
 - Browser : chrome  86.0.4240.193

**Comment by falktan** [comment]
It is a general limitation, that local files cannot directly be accessed from the browser. This is a security measure. Otherwise any website could simply access local files.
However, if a user explicitly allows access to a file (by selecting it from a dialog for instance), you can access this file. For more details on how to do this, see e.g.:
https://stackoverflow.com/questions/371875/local-file-access-with-javascript

**Comment by Balearica** [comment]
@falktan is correct regarding local files not being directly accessible from the browser due to security.  Closing the issue.
