### ISSUE TITLE
Reading Gifs throws an exception: "function signature mismatch"

### ISSUE THREAD

**Issue by thiagoperes** [naptha/tesseract.js#499]
**Describe the bug**
I'm trying to run Tesseract the following way on Node.js:
```
Tesseract.recognize(url, 'eng').then(({ data: { text } }) => {
    console.log(text);
  });
```
Everything runs smoothly until I get a gif image ([link](https://dl.airtable.com/.attachments/6ece760f3cd97411dceb10fe64a05d40/c1c845d9/5679e171f26b8954209daeae81f4266c0f6e9c82.gif)), which throws the error below:
```
Error in pixReadMemGif: function not present
Error in pixReadMem: gif: no pix returned
Error in pixGetSpp: pix not defined
Error in pixGetDimensions: pix not defined
Error in pixGetColormap: pix not defined
Error in pixCopy: pixs not defined
Error in pixGetDepth: pix not defined
Error in pixGetWpl: pix not defined
Error in pixGetYRes: pix not defined
Error in pixClone: pixs not defined
Please call SetImage before attempting recognition.
/Users/thiagoperes/house/node_modules/tesseract.js/src/createWorker.js:173
        throw Error(data);
        ^

Error: RuntimeError: function signature mismatch
    at ChildProcess.<anonymous> (/Users/thiagoperes/house/node_modules/tesseract.js/src/createWorker.js:173:15)
    at ChildProcess.emit (events.js:314:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

**To Reproduce**
1. Use Tesseract.js in node 
2. Try requesting a gif image
3. See error

**Expected behavior**
Detection to work successfully

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.0.1
 - Browser N/A
 - tesseract.js@^2.1.4
 - Node Version v12.19.0

**Additional context**
No additional context

**Comment by aarmora** [comment]
This happens to me as well with tiff files.

`Error in pixReadMem: Unknown format: no pix returned
Error in pixGetSpp: pix not defined
Error in pixGetDimensions: pix not defined
Error in pixGetColormap: pix not defined
Error in pixCopy: pixs not defined
Error in pixGetDepth: pix not defined
Error in pixGetWpl: pix not defined
Error in pixGetYRes: pix not defined
Error in pixClone: pixs not defined
Please call SetImage before attempting recognition.
C:\Users\jbhan\jsScripts\viewing-tif-king-county-properties\node_modules\tesseract.js\src\createWorker.js:173
        throw Error(data);
        ^

Error: RuntimeError: function signature mismatch
    at ChildProcess.<anonymous> (C:\Users\jbhan\jsScripts\viewing-tif-king-county-properties\node_modules\tesseract.js\src\createWorker.js:173:15)`

**Comment by Daiestai** [comment]
I've seen this before while testing a continual OCR read/output loop, the issue there was relating to the time required to create the image vs when the tesseract tries to pick up the image to process it. First experiences using bmp files, this was reduced in frequency when using png. Does this still occur if you add a small wait between setting the image and executing the OCR read?

**Comment by oasis1992** [comment]
> He visto esto antes mientras probaba un bucle continuo de lectura / salida de OCR, el problema estaba relacionado con el tiempo requerido para crear la imagen frente a cuando tesseract intenta tomar la imagen para procesarla. Experimenté por primera vez usando archivos bmp, esto se redujo en frecuencia al usar png. ¿Sigue ocurriendo esto si agrega una pequeña espera entre la configuración de la imagen y la ejecución de la lectura de OCR?

this work for me, I added a setTimeout function with 200 ms

**Comment by Balearica** [comment]
I'm closing this issue as I confirmed that .gif files (including the file linked above) are recognized as expected using the current version.  I'm adding a .gif test to confirm this does not change in any future version.  With regards to the subsequent commenters, the error "Please call SetImage before attempting recognition" is fairly generic, so if you are experiencing this for reasons unrelated to gif compatibility, please open a separate issue.
