### ISSUE TITLE
the chinese language package need improvement

### ISSUE THREAD

**Issue by lxp521125** [naptha/tesseract.js#50]
![image](https://cloud.githubusercontent.com/assets/13718014/19429345/ccf4bcb0-9481-11e6-9530-ef23865cf9cb.png)
![image](https://cloud.githubusercontent.com/assets/13718014/19429517/b44a183a-9482-11e6-975e-46f4823b85f5.png)

maybe I can do something.

**Comment by Kruemmelmonster** [comment]
this is git! so please go ahead and help whenever you can :+1: 
i would think improving chinese support would help alot, and any help is appreciated :smile:

**Comment by jeromewu** [comment]
In tesseract.js v2, the Chinese recognition accuracy is highly improved, please check if it works and feel free to reopen with more information
