### ISSUE TITLE
How to set job id manually?

### ISSUE THREAD

**Issue by Engywook2005** [naptha/tesseract.js#501]
Hi there!

On this page:
https://github.com/naptha/tesseract.js/blob/master/docs/api.md

it says:
"jobId is generated by Tesseract.js, but you can put your own when calling any of the function above."

But I don't see where it says exactly _how_ to set job id.

Ideally with the promise based approach rather than await, would be much appreciative:

```
Tesserect.recognize(el, 'eng', {options}).then((data) => {...})
```

**Comment by stonefruit** [comment]
The instruction refers to functions for Workers. `Worker.recognize(image, options, jobId)`.

`Tesserect.recognize(...)` is using `recognize(image, langs, options)`.

You will need to create a worker and use that if you want to set jobId

**Comment by Balearica** [comment]
stonefruit is correct.  `jobId` is a unique identifier passed to a worker, which is in turn passed back to the main thread when the job is completed.  The functions that accept `jobId` as an argument are shown below. 

https://github.com/naptha/tesseract.js/blob/0e368c69d61056d8420a2fcc0e0a8ca9a5620f33/src/index.d.ts#L16-L28
