### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by ohchangmin** [naptha/tesseract.js#502]
What's the problem?

 

import { createWorker,createScheduler} from 'tesseract.js';

          const worker = createWorker({
            logger: m => console.log(m),
          }); 

          await worker.load();
          await worker.loadLanguage('eng');
          await worker.initialize('eng');
          const { data: { text } } = await worker.recognize(....);
          
          console.log(text);
          await worker.terminate();

error 
 
![error](https://user-images.githubusercontent.com/33721829/101437703-24100d80-3954-11eb-9168-b55f27a05991.png)

 
 NodeJS            : v14.15.1  
 npm               : 6.14.8
 OS                : Windows 10

tesseract.js version 2.1.1

There's no problem with the code.
Two days ago, it wasn't a problem
Suddenly, there was a problem. 
I think there's a problem with the processing department. 
Looks like the server's in trouble.??

**Comment by cxcorp** [comment]
I got the "Error opening data file ./eng.traineddata" after accidentally serving an 404 error page for the path where Tesseract.js was trying to load eng.traineddata. I fixed it by clearing out the traineddata from IndexedDB and letting it re-download the traineddata file. On Chrome, you can clear out IndexedDB from DevTools -> Application -> IndexedDB.

**Comment by Balearica** [comment]
Closing issue as this should be resolved by #585.  Feel free to reopen if this is not the case.
