### ISSUE TITLE
Use custom *.traineddata for ocr

### ISSUE THREAD

**Issue by alekhranjan75** [naptha/tesseract.js#504]
I want to know how I can use my own *.traineddata for improving the OCR. I tried using `datapath`, `langpath` but it doesn't seems to be working.
I'm using it in my reactjs project.

**Comment by cxcorp** [comment]
I managed to do this by setting `langPath` to some subpath, e.g. `/ocr`, then serving my *.traineddata files from that folder, e.g `/ocr/eng.traineddata`. Remember to clear the old *.traineddata from IndexedDB (in Chrome, open devtools and go to Application -> IndexedDB).

**Comment by Balearica** [comment]
Closing issue as it looks like this question was answered.
