### ISSUE TITLE
One of the Tesseract source must be a html file instead of the expected JS type file, getting console errors no matter what.

### ISSUE THREAD

**Issue by Explosion-Scratch** [naptha/tesseract.js#511]
**Describe the bug**
Easiest with a screenshot:
The error:
![image](https://user-images.githubusercontent.com/61319150/103448386-91b30f00-4c5e-11eb-8592-38c03a2971f5.png)
My console:
![image](https://user-images.githubusercontent.com/61319150/103448398-abeced00-4c5e-11eb-83ef-099d9bd701b7.png)
The code I copy pasted:
https://github.com/naptha/tesseract.js/blob/90466c3b5504a9220ba0ff91ccec22003f72cbd2/examples/browser/basic.html

### WITH ONE EXCEPTION
I tried this with both the unpkg version:
and this from cdnjs:
```html
<!-- v2 -->
<script src='https://unpkg.com/tesseract.js@v2.1.0/dist/tesseract.min.js'></script>
```
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/tesseract.js/2.1.4/tesseract.min.js"></script>
```

**To Reproduce**
Copy paste the example code OR go to [the sandbox I made with my exact code I'm using](https://codesandbox.io/s/funny-kilby-uoji2?file=/index.html:251-267), (Not you'll have to open it in a new tab and go to console to see the error as the platform I am using (codesandbox) doesn't catch errors in the built in console.)
**Expected behavior**

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome 87 (Latest)
 - Version: Latest

**Smartphone (please complete the following information):**
_N/A_

**Comment by Balearica** [comment]
The example file you linked specifies a non-default `corePath`, which evidently is not valid in the server environment where you are hosting the page.  Deleting the `corePath` argument will resolve (as tesseract.js downloads tesseract.js-core from the CDN by default). 

https://github.com/naptha/tesseract.js/blob/90466c3b5504a9220ba0ff91ccec22003f72cbd2/examples/browser/basic.html#L10

I may edit the examples to do this by default, as I don't see much of a downside.

**Comment by Explosion-Scratch** [comment]
I was a coding noob back then, closing this. Your solution worked, many thanks.
