### ISSUE TITLE
Firefox does not  get any results. 

### ISSUE THREAD

**Issue by obiwan1337** [naptha/tesseract.js#513]
**Describe the bug**
After initialization of the worker, it stops with 'loading language traindata'.
not sure if it is something i need to unlock in the browser or not so i leave this here. 
Maybe it helps.

**To Reproduce**
1. Go to 'https://obiwan1337.github.io/distancePlay/'
2. enable the cam.
3. click on the video
4. open debug console
5. wait for firefox to not finish. (i waited 15mins)

**Expected behavior**
I expected to have the worker interpret the letters on the image.

**Screenshots**
![tessbug](https://user-images.githubusercontent.com/43846856/105769090-33273b00-5f55-11eb-8257-6a8852b80a2f.png)

**Desktop (please complete the following information):**
 - OS: endeaverOS
 -  Browser Firefox
 - Version 84.0.2

**Smartphone (please complete the following information):**
 not tested on SM

**Comment by Balearica** [comment]
Let me know if this issue is still active.  I went to this URL but did not se Tesseract.js being used.

**Comment by Balearica** [comment]
Closing as stale.
