### ISSUE TITLE
tesseract.js@^2.1.4 in React App: loadImage.js:34 Failed to execute 'toBlob' on 'HTMLCanvasElement'

### ISSUE THREAD

**Issue by fauzialz** [naptha/tesseract.js#514]
**Describe the bug**
I try to run tesseract.js in React by following the example from [tesseract.js-react-app](https://github.com/jeromewu/tesseract.js-react-app). I clone the repo and run it locally. Everything work perfectly, so I install the latest version with `npm i tesseract.js` to my project and try to follow the example. Unfortunately, tesseract can't give me the result because in **loadImage.js:34** this error happens:
```
Uncaught DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.
```
**To Reproduce**
1. You can clone this project [tesseract.js-react-app](https://github.com/jeromewu/tesseract.js-react-app)
2. In packege.json, change ` "tesseract.js": "^2.0.0-beta.1"` to `"tesseract.js": "^2.1.4"` which is the tesseract.js version that I found have the issue
3. `npm i` and then `npm start`
4. See the console

**Expected behavior**
I expect no error just like when the example project using` "tesseract.js": "^2.0.0-beta.1"`

**Screenshots**
![tesseractjs](https://user-images.githubusercontent.com/42629134/107249240-c0928100-6a65-11eb-804f-294f7ab98b41.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Version 88.0.4324.150 (Official Build) (64-bit)
 - tesseract.js@^2.1.4

**Comment by tabrezdn1** [comment]
Same issue please let me know if you come up with some solution. Thanks

**Comment by fauzialz** [comment]
> Same issue please let me know if you come up with some solution. Thanks

While waiting for the fix, I try to use Tesseract.js v2.0.0 and it works well in my project (except for dependencies vulnerability issues in npm audit). You can uninstall the current Tesseract.js version and if you use npm, you can install v2.0.0 by running this command:

`npm install tesseract.js@2.0.0`

**Comment by ansnoussi** [comment]
same issue here with version 2.1.4
downgrading to 2.0.0 seems to work for me, hope they fix this soon.

**Comment by watashite** [comment]
The issue seems to be exactly in `2.1.4`, downgrading to `2.1.3` is enough and doesn't undo security fixes.

**Comment by JiRadu** [comment]
I get a similar error but for the 'fixOrientationFromUrlOrBlobOrFile' function.

I did a little bit of digging and the problem seems to reproduce from v2.1.2, by this commit: https://github.com/naptha/tesseract.js/commit/a54dbc345b8d4cb22fca039b5e42da1c2ad77af8

Looking in Javascript-Load-Image package, I can see the dependency is a bit outdated( v5 vs v3.0.0 ). 
I couldn't get Javascript-Load-Image v5 to work with the v2.1.2 of the tesseract.js though, this needs more investigation.

Also, this only happens if the image has crossOrigin set to true, so it's an edge case.


Hope this should give you a head start in solving this issue.

I will remain at v2.1.1 until this is resolved.

**Comment by afermon** [comment]
Same issue here, for me it works on v2.1.1, other versions experience the issue.

**Comment by kaisian97** [comment]
Using in Nextjs, tesseract v2.1.5 still having the same issue.

**Comment by fauzialz** [comment]
I upgrade the library to v2.1.5 and my previous issue seems fixed. I will close the issue. If anyone still facing this issue after upgrading to v2.1.5, maybe you can try the method above.

> Using in Nextjs, tesseract v2.1.5 still having the same issue. Only local images works. For remote images, try to convert to base64 before process [https://stackoverflow.com/questions/22172604/convert-image-url-to-base64](url)

**Comment by aorborc** [comment]
> I upgrade the library to v2.1.5 and my previous issue seems fixed. I will close the issue. If anyone still facing this issue after upgrading to v2.1.5, maybe you can try the method above.
> 
> > Using in Nextjs, tesseract v2.1.5 still having the same issue. Only local images works. For remote images, try to convert to base64 before process [https://stackoverflow.com/questions/22172604/convert-image-url-to-base64](url)

Downgrading to v2.0.0 brought some other issue. v2.1.5 is still throwing the same error for me.

**Comment by nihirv** [comment]
Having this issue in v2.1.5 using svelte 3.46.

I think the bug was introduced in 2.1.2 because downgrading to 2.1.2 didn't work but 2.1.1 did
