### ISSUE TITLE
Tesseract.js not accuracy to OCR Thai and English picture.

### ISSUE THREAD

**Issue by doanga2007** [naptha/tesseract.js#515]
**Describe the bug**
I am coding with Tesseract.js library , Tesseract.js not accuracy to OCR Thai and English picture (have not correct OCR to **“8300ธ5ทกขคงจฉ** instead correct OCR to **ABCDEF กขคงจฉ**).

**To Reproduce**
1. Code snippet with Tesseract.js library :

```
<!doctype html>
<html>
<head>
  <title>ทดสอบ Tesseract.js 4</title>
</head>
<body>
<p id="status"></p>
<script src="http://localhost:90/ocrtest2021/tesseract.min.js"></script>
<script>
	var sta = document.getElementById("status");
    
    /* Code to crossOrigin = anonymous */
    var recogImage = new Image;
	recogImage.crossOrigin = "anonymous"; /* THIS WILL MAKE THE IMAGE CROSS-ORIGIN */
	recogImage.src = "http://localhost:90/ocrtest2021/test-ocr-2021.jpg";

    const worker = Tesseract.createWorker({
      logger: m => sta.innerHTML = m.status
    });
    Tesseract.setLogging(true);
    work();

    async function work() {
      await worker.load();
      await worker.loadLanguage('eng+tha');
      await worker.initialize('eng+tha');

      //let result = await worker.detect(recogImage);
      //console.log(result.data);

      let result = await worker.recognize(recogImage);
      sta.innerHTML = result.data.text.replaceAll(' ','');  // remove literal spaces

      await worker.terminate();
    }
    
// https://www.thaicreate.com/php/forum/135293.html
</script>
</body>
</html>
```

2. See to Tesseract.js not accuracy to OCR Thai and English picture (have not correct OCR to **“8300ธ5ทกขคงจฉ** instead correct OCR to **ABCDEF กขคงจฉ**).

**Expected behavior**
After coding with Tesseract.js library , Tesseract.js not accuracy to OCR Thai and English picture (have not correct OCR to **“8300ธ5ทกขคงจฉ** instead correct OCR to **ABCDEF กขคงจฉ**).

**Screenshots**
- Picture to describe Tesseract.js not accuracy to OCR Thai and English picture (have not correct OCR to **“8300ธ5ทกขคงจฉ** instead correct OCR to **ABCDEF กขคงจฉ**) : [https://i.postimg.cc/qMbj6Qz0/ocr-test-error-3.png](https://i.postimg.cc/qMbj6Qz0/ocr-test-error-3.png)
- Picture to test OCR Thai and English picture : [https://i.postimg.cc/htLqR6MV/test-ocr-2021.jpg](https://i.postimg.cc/htLqR6MV/test-ocr-2021.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Edge
 - Version : 88.0.705.63

**Additional context**
- All file coding to describe Tesseract.js not accuracy to OCR Thai and English picture (have not correct OCR to **“8300ธ5ทกขคงจฉ** instead correct OCR to **ABCDEF กขคงจฉ**) : [https://drive.google.com/file/d/1TLgwqHh4NEpUVWRnLfM0BijXwQo36r8k/view?usp=sharing](https://drive.google.com/file/d/1TLgwqHh4NEpUVWRnLfM0BijXwQo36r8k/view?usp=sharing)

**Comment by Balearica** [comment]
Tesseract.js is the Javascript/Webassembly port of Tesseract.  We do not make any edits to the recognition engine, so any accuracy issues with the Tesseract engine are outside of the scope of this project.  If you would like to pursue further, you should (1) check whether the issue is present when using the main (CLI) [Tesseract project](https://github.com/tesseract-ocr/tesseract) and (2) if so, and you believe this constitutes a bug, raise the issue with that project.  If you believe the issue is specific to Tesseract.js, you can reopen this issue.
