### ISSUE TITLE
Unable to detect the local file

### ISSUE THREAD

**Issue by sdembele** [naptha/tesseract.js#519]
Hi,
Thank you for your fascinating work, 
I tried to create a project locally, 
the objective is to recognize a local image,
but I have this error :

> Fetch API cannot load file:///Users/mac/mytesseract/1_klTODXvF6Zjh3SRpOdIpbA.png. URL scheme must be "http" or "https" for CORS request.

Any solution to recognize images locally 

the used code :

`const jobID = 'SD-77858OT';
    const { createWorker } = Tesseract;
    const exampleImage = '1_klTODXvF6Zjh3SRpOdIpbA.png';

    const worker = createWorker({
      logger: m => {
        console.log(m.progress);
        console.log(m)
      },
    });
    
    (async () => {
      await worker.load(jobID);
      await worker.loadLanguage('eng',jobID);
      await worker.initialize('eng',jobID);
      const { data: { text } } = await worker.recognize(exampleImage,jobID);
      console.log(text);
      await worker.terminate(jobID);
    })();`

**Comment by Balearica** [comment]
Browsers do not allow for http/https sites to access local resources.  This is explained by a link below, and is not specific to Tesseract.js.  For a file on your users' computers to be accessible via Javascript in a browser, it will need to go through an "upload" button first.  Alternatively, if you are just trying to use a test image, it should be added as a resource within the folder you are running the http server out of. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
https://www.w3schools.com/HOWTO/howto_html_file_upload_button.asp

**Comment by viba98** [comment]
I have been trying to do the same thing. I tried testing with the default tesseract image ("https://tesseract.projectnaptha.com/img/eng_bw.png")and it works fine. But when I change to a local image, i get the errors in the image below. 

Here is my code: 
```
const { createWorker } = require('tesseract.js');

const worker = createWorker({
  logger: m => console.log(m), // Add logger here
});

(async () => {
  await worker.load();
  await worker.loadLanguage('eng');
  await worker.initialize('eng');
  const { data: { text } } = await worker.recognize('test.jpg');
  console.log(text);
  await worker.terminate();
})();
```

<img width="463" alt="Screenshot 2022-08-12 at 11 03 27" src="https://user-images.githubusercontent.com/32447352/184291045-e783c189-ed9c-44be-9e71-5cba0021d8ee.png">
 a local image

**Comment by Balearica** [comment]
@viba98 What directory did you put `test.jpg` in and what directory are you running your http server out of?

**Comment by viba98** [comment]
They are in the same file. It is a folder called Slicer. And i'm using a local host server from here (https://www.digitalocean.com/community/tutorials/js-axios-vanilla-js)

**Comment by viba98** [comment]
I think this might be the problem. But I'm not sure if any of these modules are available for JS? https://stackoverflow.com/questions/38149512/tesseract-runtime-error-error-in-pixreadmempng-function-not-present

**Comment by Balearica** [comment]
Closing as answered, given that the original poster was trying to access their local file directly from the browser, and browsers do not allow this (see response above).  It looks like @viba98 is having a different problem--if still outstanding a new/separate issue should be opened.
