### ISSUE TITLE
Language / Config for MRZ reading

### ISSUE THREAD

**Issue by noamyg** [naptha/tesseract.js#520]
Hi, I'm trying to read a MRZ and I get some unexpected results. I'm assuming I should pass some options for MRZ

![image](https://user-images.githubusercontent.com/34273570/109934907-aef37080-7cd5-11eb-9671-f9fb75734b05.png)

Result:
P**L**PRYDE<ASSIS<MOREIRA<**S**RONALDO<<<**LLLLLLLLLLL**Q568928<<4PRY8003214M2501073<<<<<<<<<<<<<<08**— —**

I've marked the incorrect characters.

Here's my code:

```
const imgBuffer = Buffer.from(this.croppedImage.split(',')[1], 'base64');
const tsResult = await Tesseract.recognize(imgBuffer, 'eng');
const parsedText = tsResult.data.text.replace(/(\r\n|\n|\r)/gm, '');
console.log(parsedText);
```

I'm using v2.0.0.
Thanks!

**Comment by Balearica** [comment]
Let me know if this question is still outstanding.  If you've moved on I will close since this isn't a bug report or feature request.

**Comment by pepperav** [comment]
Did you try loading OCR B fonts traineddata? [check here](https://github.com/Shreeshrii/tessdata_ocrb)
