### ISSUE TITLE
how to recognized image in <canvas>?

### ISSUE THREAD

**Issue by simonaaba** [naptha/tesseract.js#524]
**Describe the bug**
when the image in a canvas tags in html ,the function recognize will not work ,how to resolve it ?

> <canvas id="s-canvas" width="100" height="30"></canvas>
veryCode1_imgObj = document.getElementById("s-canvas");
Tesseract.recognize(veryCode1_imgObj, {
		lang: 'eng'
	}).then(function(result){})
![recoge](https://user-images.githubusercontent.com/10238686/111281478-eec43b80-8677-11eb-8571-5d650eb1ac1a.png)

**Comment by IggWeb** [comment]
You need to actually get the image:
canvas.toDataURL() or canvas.toBlob()

**Comment by Balearica** [comment]
@IggWeb is correct, you need to get the image content of the canvas as either a data URL or blob.  Closing issue.
