### ISSUE TITLE
the Chinese result is not correct enough

### ISSUE THREAD

**Issue by wormtql** [naptha/tesseract.js#525]
**Describe the bug**
actually it's not a bug, just I think the result is not good enough
I put this image on the website 
![image](https://user-images.githubusercontent.com/42363449/112166429-94ece400-8c2a-11eb-8f81-9ab99c7e84dc.png)
but it ended up with this result:
![image](https://user-images.githubusercontent.com/42363449/112166374-87cff500-8c2a-11eb-9443-3e18b441b0a7.png)
which I believe is actually bad to be honest.

of course this image is not very normalized, if images like this is not supported by design, is there any open source solutions that support this?

**Comment by piscopancer** [comment]
@wormtql hi, having similar situation here, have you figured out how to improve the inference for chinese? (after 3 years xd)
![image](https://github.com/naptha/tesseract.js/assets/109352196/c4c0cb2c-c4d4-4668-856d-9c09335d8367)

**Comment by wormtql** [comment]
Use a Chinese targeted solution works for me, like [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)

**Comment by piscopancer** [comment]
@wormtql does it actually work in nodejs? I have not found an appropriate package neither on GitHub, nor on npm. Also, did you consider training your own model with Chinese handwriting datasets? if you tried, did it work out and could you further integrate it with your tesseractjs application? I have no idea how to integrate paddleocr with my nodejs app, unlike tesseractjs that does work smoothly. Even though trained data... is not hot handwriting. Can you please share a link to the exact paddleOCR package?

**Comment by wormtql** [comment]
PaddleOCR can be deployed [with onnx](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/deploy/paddle2onnx/readme.md), which can be run in [js environment](https://onnxruntime.ai/docs/tutorials/web/) (though I didn't try it). Maybe you can try the handwritten image in [PaddleOCR online example](https://aistudio.baidu.com/application/detail/7658)
