### ISSUE TITLE
How do I access the logger's progress property ?

### ISSUE THREAD

**Issue by ayush-work** [naptha/tesseract.js#530]
I am  creating a react project where I want the logger's progress property, so that I can store the property into a state which can be used to create a progress bar. Basically I want to create a progress bar using the logger's progress property.

**Comment by GhostDog98** [comment]
Having the exact same problem here, let me know if you come up with a solution please :)

**Comment by ayush-work** [comment]
> Having the exact same problem here, let me know if you come up with a solution please :)

### This is what I did


**_Storing the progress data in a state_**
```
const [log, setLog] = useState({});

 const worker = createWorker({
    logger: (m) => {
      setLog({
        status: m.status,
        progress: m.progress,
      });
    },
  });

```
**_Then simply used this state to render a progress bar_**

```
 <ProgressBar 
    label={`${Math.floor(log.progress.toFixed(2) * 100)}%`} 
    now={Math.floor(log.progress.toFixed(2) * 100)} >          
</ProgressBar>
```
