### ISSUE TITLE
Error: Error: UNKNOWN: unknown error, open '\eng.traineddata' CRASH

### ISSUE THREAD

**Issue by soulus98** [naptha/tesseract.js#536]
**Describe the bug**
I'm not sure what is causing this or how to fix it, I have worker.load, initialise and loadlanguage in a try-catch, but it is ignored and just crashes.
This is the Error data:
```
\node_modules\tesseract.js\src\createWorker.js:173
        throw Error(data);
        ^

Error: Error: UNKNOWN: unknown error, open '\eng.traineddata'
    at ChildProcess.<anonymous> (\node_modules\tesseract.js\src\createWorker.js:173:15)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```
This is where I am when it happens
```
{
  workerId: 'Worker-1-fa91e',
  status: 'loading language traineddata',
  progress: 0
}
{
  workerId: 'Worker-1-fa91e',
  status: 'loading language traineddata (from cache)',
  progress: 0.5
}
```

**To Reproduce**
The only thing I can think of is that I sometimes call two of these simultaneously, but it still happens with only one, just less frequently.

**Expected behavior**
Not a crash

**Desktop (please complete the following information):**
 - OS: Win10
 - Node: v14.16.0
 - Tess @2.1.4

Is there at least a way that I can handle this? So I can retry it when it fails.

**Comment by soulus98** [comment]
Happens 10% of the time when I call it once, 50% of the time if I am simultaneously calling multiple

**Comment by animosi** [comment]
I have the same issue. I deleted the trainer file and re-run the program. I've also download the file from other sources and still get the same issue.  The occurrence is quite high for me.

**Comment by soulus98** [comment]
@animosi 
Do you still have this issue? It seems to occur for me if I am performing another task synchronously, like writing the file to disk.
I would still like to know a proper workaround or at least what causes it.

**Comment by Balearica** [comment]
@herecy I was able to reproduce this bug in version 2, but not the current version (v3).  If this issue is still active, please confirm you still encounter this bug in the latest version and provide a reproducible example.

**Comment by Balearica** [comment]
Many users reported similar errors (see #666) in Tesseract.js v2 and we implemented fixes to significantly reduce if not eliminate them in both v3 and v4.  If you encounter this error using the latest version (v4 or above) please open a new issue.
