### ISSUE TITLE
Error npm install BAS

### ISSUE THREAD

**Issue by nahprog** [naptha/tesseract.js#541]
When installing, swears at
Adding a module to browser automation studio
...
npm info lifecycle tesseract.js@2.1.4~postinstall: tesseract.js@2.1.4
"opencollective-postinstall" ?? ?????? ???????? ??? ?????
????????, ??????? ?????? ??? ???????? ????.
"true" ?? ?????? ???????? ??? ?????
????????, ??????? ?????? ??? ???????? ????.
npm verb lifecycle tesseract.js@2.1.4~postinstall: unsafe-perm in lifecycle true
...
npm verb node v12.18.3
npm verb npm  v6.14.6
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tesseract.js@2.1.4 postinstall: `opencollective-postinstall || true`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tesseract.js@2.1.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

How to fix it?

**Comment by Balearica** [comment]
I am not familiar with BAS.  If this issue is still active, please add a reproducible example and we can follow up.

**Comment by Balearica** [comment]
Closing as stale.  If somebody encounters this with the current version and can provide a reproducible example, feel free to reopen.
