### ISSUE TITLE
react-native support?

### ISSUE THREAD

**Issue by jonathanpalma** [naptha/tesseract.js#55]
Hey guys!! I wonder if you have considered bringing support for frameworks like react-native through node. I was working on a [tesseract wrapper for react-native](https://github.com/jonathanpalma/react-native-tesseract-ocr) but your lib looks much better. (Considering that now the wrapper is only implemented on android)

So, I tryed to create a test using yours but I'm getting this error

![rsz_14632600_1552933568054084_273631139_o](https://cloud.githubusercontent.com/assets/12414771/19465558/54b900da-94c2-11e6-94c0-e0de45b331ae.png)

**Comment by bartvanremortele** [comment]
The packager goes out of memory when importing tesseract.js-core
<img width="376" alt="schermafbeelding 2016-10-18 om 12 30 35" src="https://cloud.githubusercontent.com/assets/424370/19474166/b7a4494a-952e-11e6-9ca6-e411ce323058.png">
<img width="1437" alt="schermafbeelding 2016-10-18 om 12 29 15" src="https://cloud.githubusercontent.com/assets/424370/19474165/b79e2e0c-952e-11e6-8ff4-88b8f077ef8d.png">

**Comment by bartvanremortele** [comment]
So I ran some more tests:
- I bumped the memory limit of the packager by changing the following line:
`node "$THIS_DIR/../local-cli/cli.js" start "$@"`
to
`node --max_old_space_size=4096 "$THIS_DIR/../local-cli/cli.js" start "$@"`
in file:
`node_modules/react-native/packager/packager.sh`

and 
```
$NODE_BINARY "$REACT_NATIVE_DIR/local-cli/cli.js" bundle \
  --entry-file "$ENTRY_FILE" \
  --platform ios \
  --dev $DEV \
  --reset-cache \
  --bundle-output "$BUNDLE_FILE" \
  --assets-dest "$DEST"
```
to
```
$NODE_BINARY \
  --expose-gc \
  --max_old_space_size=4096 \
"$REACT_NATIVE_DIR/local-cli/cli.js" bundle \
  --entry-file "$ENTRY_FILE" \
  --platform ios \
  --dev $DEV \
  --reset-cache true \
  --bundle-output "$BUNDLE_FILE" \
  --assets-dest "$DEST"
```
in file: 
`node_modules/react-native/packager/react-native-xcode.sh`

which resulted in:
<img width="1318" alt="schermafbeelding 2016-10-18 om 13 25 55" src="https://cloud.githubusercontent.com/assets/424370/19475946/e6a63084-9536-11e6-8b04-436c26edc5fb.png">

**Comment by bijection** [comment]
have you tried adjusting the timeout as the error suggests?

**Comment by enapupe** [comment]
Considering `Tesseract.js currently requires node v6.8.0 or greater.`, I suppose there's no support for it on react native, since rn runs JavaScriptCore..

**Comment by rgoldiez** [comment]
Anyone get this to work with React Native?

**Comment by enapupe** [comment]
So, I went through this a little bit more and aside from the `location` dependency, which is easy to workaround, tesseract heavily depends on `workers` (which I managed to polyfill) (https://www.w3.org/TR/workers/) and some `Image` api to get the binary image data - which seems impossible to do in react-native.

For the people interested in continuing this quest: there's currently 2  "drivers"  implementations  of this package: browser and node. Ideally you would start one from scratch, calling it react-native and linking it on `package.json` under `react-native` section (there's a similar thing going on with `browser`). The gotcha now is finding a way to load image binary data and forward it to tesseract.

**Comment by enapupe** [comment]
BTW. I tried to make it work by adapting the current `browser` implementation. But there's really no good starting point. Both implementation (node & browser) heavily use their own APIS which are NOT available in react-native context.

**Comment by arheom** [comment]
+1 for react-native support.

**Comment by AlexisLeon** [comment]
Hi everyone, I'm currently working to add support for react native.
I already fixed the JavaScript workers issue and I'm working on how to implement the HTML Image API.

Will be very helpful to know what's the flow in loadImage for node and browser.

**Comment by mikasjoman** [comment]
@AlexisLeon keep us updated with the progress :) Looking forward to implement this in my RN app!

**Comment by alburdette619** [comment]
@AlexisLeon How's it going?  Do you have anything published yet or need any help?

**Comment by sanchezzzhak** [comment]
can it help?
https://medium.com/@aakashns/using-core-node-js-modules-in-react-native-apps-64acd4d07140

**Comment by AlexisLeon** [comment]
@mikasjoman @alburdette619 Almost there..
<img width="540" alt="screen shot 2017-11-04 at 12 17 59 am" src="https://user-images.githubusercontent.com/10150214/32402986-2110856e-c0fe-11e7-8bc2-0f4967baa38f.png">

- [x] JS Worker

**Comment by nikita-pankratov** [comment]
@AlexisLeon +1 looking forward to it. what is the status? do you need any help?

**Comment by AlexisLeon** [comment]
@nikita-pankratov I'll publish my code soon.
I implemented the `Worker`s in RN via Native Modules, now I'm looking for a way to implement the `Image` API, but it's getting tough. Any ideas?

**Comment by jonathanpalma** [comment]
I would like to know if somebody could help us to have a look at @daominhsangvn's [fork](https://github.com/newoceaninfosys/react-native-tesseract-ocr) and provide some feedback about it. @AlexisLeon @nikita-pankratov @sanchezzzhak @alburdette619 @mikasjoman @arheom @enapupe @rgoldiez @bijection @bartvanremortele

**Comment by alburdette619** [comment]
@jonathanpalma oh looks like they got iOS implementation in, that's what was holding me up. I'll take a further look asap.

**Comment by jpicornell** [comment]
Hey @AlexisLeon, where is your code published? I'm interested in working on this allowing us to not depend on node/browser native apis without having to eject. Let's see if it's possible!

**Comment by MeKyleH** [comment]
Any update on the RN support?

**Comment by mradziwon** [comment]
@AlexisLeon Any updates on workers? Maybe you can find solution for Image here [expo/browser-polyfill](https://github.com/expo/browser-polyfill).

**Comment by devgunyogesh** [comment]
@AlexisLeon Any update if it supports React Native now?

**Comment by AlexisLeon** [comment]
@mradziwon @devgunyogesh Nope, still looking for Image api solution, Workers are "working" as native modules

**Comment by Talalisi** [comment]
@AlexisLeon did you find a solution for React Native support ?

**Comment by AlexisLeon** [comment]
@Talalisi no 😞
Sadly for us there is not support for the js `Image` API
To implement OCR I decided to send the image to an API (Node.js) and return the extracted text

**Comment by callmejm** [comment]
any update for this awesome library use in react-native ?

**Comment by broros** [comment]
maybe use WebAssembly

**Comment by jeromewu** [comment]
I would like to close this issue for now as it is not possible for tesseract.js to support react-native now.

The key issue we faced is that react-native have a poor support for asm.js and no support for webassembly now, so it is impossible to use tesseract.js in react-native (of course tesseract.js works in WebView, but it is not "native").

Cross our finger and hope one day we can reopen this issue with more support from react-native.

**Comment by broros** [comment]
@jeromewu do you have an example of how this should work with webView?

**Comment by jeromewu** [comment]
@broros I tried to use webview and sadly there is a out of memory error... (just like in Cordova)

I think it is a dead end for using tesseract.js in webview, I would recommend to use the native one in Android or iOS, here is a library that leverages native tesseract-ocr in react-native: https://github.com/jonathanpalma/react-native-tesseract-ocr

**Comment by wilson0x4d** [comment]
bummer.
