### ISSUE TITLE
Error with example code. Error at createWorker.js:173

### ISSUE THREAD

**Issue by 737325** [naptha/tesseract.js#555]
**I'm trying to use OCR to read an image, however, when i try to create the worker, i received a runtime error.**
I'm working with Angular

My Tesseract version is: "tesseract.js": "^2.1.4",
 
My code is the next:

I had this two imports
`import { ImageLike, Rectangle } from 'tesseract.js'; 
import * as Tesseract from 'tesseract.js';`

`   public encontrarProveedor(foto: ImageLike): string{
    
    let resultada = '';
    const { createWorker } = Tesseract;

    const worker = createWorker();
    (async () => { 
      await worker.load(); 
      await worker.loadLanguage('eng'); 
      await worker.initialize('eng');

      try{
        const { data: { text } } = await worker.recognize(foto);       
        console.log(text);
        resultada = text.toString();

      } catch(err){
        await worker.terminate();
      }     
     })();
     return resultada;
    }
`

The exact error is the following:

**ERROR Error: RuntimeError: null function or function signature mismatch
    at createWorker.js:173**

![image](https://user-images.githubusercontent.com/83501094/126959424-29b656fd-3280-4c5a-9c40-ac44c16d107d.png)

Any idea?

Thanks

**Comment by ceverard9** [comment]
Dealing with the same error as well. I am using scheduler.addJob("recognize", ...

**Comment by Balearica** [comment]
Closing since this relates to version 2, which is no longer supported and contains many bugs that have been resolved in subsequent versions.  Please open a new issue if this is encountered using version 4.
