### ISSUE TITLE
Memory problem in version 2.1.3 comparing to version 2.1.2

### ISSUE THREAD

**Issue by hieunguyen2211** [naptha/tesseract.js#556]
**Describe the bug**
After upgrading to version **2.1.3** from version **2.1.2**, there is a significant increase in memory while recognizing the text in the image.
For details, in version **2.1.2**, the memory consumption was **~120 mb** while in version **2.1.3**, it increases to **> 700 mb**.
Are there any reasons why this happens in version **2.1.3** and are there any solutions that I could try to optimize the memory?

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version: 91.0.4472.164

**Comment by nghiaviettran** [comment]
Any update on this issue? I also facing with this issue on my project. :(

**Comment by Balearica** [comment]
@hieunguyen2211 Thanks for raising this issue, as well as being specific with regards to the update that caused it.  The problematic commits have been reverted in the master branch, so this should be resolved.
