### ISSUE TITLE
CDN Tesseract 1.0.8 not found

### ISSUE THREAD

**Issue by lsrom** [naptha/tesseract.js#56]
I copied the `<script src='https://cdn.rawgit.com/naptha/tesseract.js/1.0.8/dist/tesseract.js'></script>` from the README but it threw error 404. I couldn't access the file neither via wget or my browser.

What helps is if you change the `1.0.8` part to `0.2.0` which should be correct version of tesseract.js according to your releases. So to fix this issue I propose either add correct file so the url works or change the readme to `0.2.0` url.

Working URL: `https://cdn.rawgit.com/naptha/tesseract.js/0.2.0/dist/tesseract.js`

**Comment by JensDebergh** [comment]
I guess the latest available version is: 

`https://cdn.rawgit.com/naptha/tesseract.js/1.0.7/dist/tesseract.js`

I've stumbled across the same problem and it seems 1.0.8 has not been deployed to the cdn yet.

**Comment by bijection** [comment]
Fixed, the url is now https://cdn.rawgit.com/naptha/tesseract.js/1.0.9/dist/tesseract.js
