### ISSUE TITLE
Question: Does this work with Chrome Extension built with Manifest 3?

### ISSUE THREAD

**Issue by Fried-Chicken** [naptha/tesseract.js#560]
Hello, 

I just have a quick question which I’ve already spent days Googling and trying to answer to no avail. 

Does Tesseract.js work with Chrome Extension  Manifest 3?

I’ve noticed that even with CSP defined and scrips embedded creating workers is still blocked.

I’d be grateful if anyone had an answer to my question.

Thanks

Fried Chicken

**Comment by ForeverAT** [comment]
May I ask is there any answer for this issue? As I am also concern on this question. Thank you

**Comment by datvm** [comment]
@ForeverAT I was able to, explained here: https://stackoverflow.com/a/76604454/653457. No idea why there is no documentation/mention of this anywhere though.
