### ISSUE TITLE
Trouble recognizing text with edge

### ISSUE THREAD

**Issue by Ozoto** [naptha/tesseract.js#562]
Hello guys, 

I'm working on a recognition of a specified ref number on somes boxes from a picture.
I've implemented Tesseract and I'm using a regex to find the letters REF to extact the subsequent numbers. 

Sometimes REF is surrounded by edges, Tesseract will not recognizes any letters then. Do you guys have any idea on how I could improve my algorythm ? 
I found that with the simplified chinese traineddata, it worked better but it can't be a solution and it's definitely not satisying enough. 

The kind of picture I'm having trouble with : 

![IMG_20210831_175430](https://user-images.githubusercontent.com/26707523/131542787-dde893f2-8061-4f4a-8251-d3d904936c1d.jpg)

Thank you in advance!

**Comment by AndreV2890** [comment]
Hi

I've more or less the same problem when I try to extract OCR from industrial machine label
have you achieved any results on this topic?

**Comment by Balearica** [comment]
Let me know if this question is still outstanding. If you've moved on I will close since this isn't a bug report or feature request.

**Comment by Balearica** [comment]
Closing as stale.
