### ISSUE TITLE
Tesseract read `6` as `é` even when language is set to `eng`

### ISSUE THREAD

**Issue by mostafa-raafat** [naptha/tesseract.js#563]
when I try this code
```
  const worker = createWorker({
    logger: (m) => console.log(m),
  });

  await worker.load();
  await worker.loadLanguage("eng");
  await worker.initialize("eng");
  const {
    data: { text },
  } = await worker.recognize("./img/captcha_image.png");
  console.log(text);
  await worker.terminate();
  ```
I should get the number `cbfd6` rather than `cbfdé`

**Screenshots**
![captcha-image](https://user-images.githubusercontent.com/43439787/132205789-0a967fc0-5230-4a02-b2f2-2cee26b7fd7b.jpeg)

**Comment by ericksonnascimento** [comment]
tried with _por_ and _eng+por_

```
const { createWorker} = require('tesseract.js');

const worker = createWorker({
    logger: m => console.log(m),
});

const lang = 'eng+por'; //por

(async() =>{
    await worker.load();
    await worker.loadLanguage(lang);
    await worker.initialize(lang);
    const { data: {text} } = await worker.recognize(urlImage);
    console.log(text);
    await worker.terminate();
})()
```
result was `cbfd6`

**Comment by Balearica** [comment]
I confirmed that, for whatever reason, "é" is listed as an English character in the default Tesseract traineddata.  Tesseract.js inherits its default traineddata files from the main [Tesseract project](https://github.com/tesseract-ocr/tesseract), so changing that is outside of the scope of this repo.  However, you can prevent Tesseract from recognizing "é" (or any other character) by using the `tessedit_char_blacklist` config argument. 

`w.setParameters({tessedit_char_blacklist: "é"})`

https://github.com/tesseract-ocr/langdata/blob/main/eng/desired_characters#L102
