### ISSUE TITLE
Not recognizing number

### ISSUE THREAD

**Issue by RupamShaw** [naptha/tesseract.js#568]
**Describe the bug**
Its not recongnising number in image

**Expected behavior**
It should recognize number in uploaded image
**Screenshots**
here is the image attached
<img width="36" alt="212" src="https://user-images.githubusercontent.com/4842454/136142998-3ad7bc15-2ee7-4dea-b711-90abd1e14749.png">

![21](https://user-images.githubusercontent.com/4842454/136143340-5f8663ee-df3e-4312-b64c-92fd8ec820eb.JPG)

 - OS: [e.g. iOS] Mac
  - Version-     "tesseract.js": "^2.1.5"

here is my node js code

```

 Tesseract.recognize(
    '212.png',
    'eng',
    {
      logger: m => console.log(m),
      'psm': 6
    }
  ).then(({ data: { text } }) => {
    console.log(text);
  })
````
text output should show 21
but showing fas

**Comment by Balearica** [comment]
If you want to recognize only numbers, you can set a whitelist.  See the following example:

https://github.com/naptha/tesseract.js/blob/90466c3b5504a9220ba0ff91ccec22003f72cbd2/docs/examples.md#with-whitelist-char-200-beta1

In general, note that this repo is only for the webassembly port of Tesseract.  We do not modify the Tesseract engine in any way.  Therefore, any issues with Tesseract's recognition quality are outside of the scope of this repo.
