### ISSUE TITLE
Where is the "Empty page!!" error message located?

### ISSUE THREAD

**Issue by soulus98** [naptha/tesseract.js#571]
**Is your feature request related to a problem? Please describe.**
I have no need to know whether a page is empty, but my use case of tesseract.js has many empty pages fed into it. The message floods an otherwise useful error log I have for other messages.

**Describe the solution you'd like**
I would like an option to turn off the `Empty page!!` message, or, if someone could tell me where it is located, I will just delete it myself.

**Describe alternatives you've considered**
In the original tesseract-ocr it is found in `/src/textord/colfind.cpp` but I cannot find an equivalent file or folder for tesseract.js.
I've also tried commenting **every single instance* of `console` in both `/node_modules/tesseract.js` and `/node_modules/tesseract.js-core`, but while that causes other issues, the `Empty page!!` message *still* appears.
I just can't get rid of the thing.
Also, I've considered having a script intercept the `Empty page!!` message and remove it from the `error.log` file, but I don't think that should be necessary, and probably wouldn't work for cleaning up a terminal window.

**Additional context**
![empty page](https://user-images.githubusercontent.com/73259768/137423342-368e4a00-7321-4fad-8a57-64911392ef82.png)

**Comment by soulus98** [comment]
I just discovered and read about the wasm stuff. I guess it is in the huge binary string somewhere.
If nobody knows where it is, can someone point me towards a decompiler so I can find it myself?

**Comment by Balearica** [comment]
I agree the "empty page" message is unnecessary and annoying.  I will remove in the next version.

**Comment by Balearica** [comment]
Closing as this message has been removed in tesseract.js-core ([a7c4cd5](https://github.com/naptha/tesseract.js-core/pull/18)).
