### ISSUE TITLE
DOMException: The operation is insecure.

### ISSUE THREAD

**Issue by KekOnTheWorld** [naptha/tesseract.js#572]
Just copied the example:

`
import { createWorker } from 'tesseract.js';

const w = createWorker({
  logger: m => console.log(m)
});

(async () => {
  await w.load();
  await w.loadLanguage('eng');
  await w.initialize('eng');
  const { data: { text } } = await w.recognize('https://tesseract.projectnaptha.com/img/eng_bw.png');
  console.log(text);
  await w.terminate();
})();
`

with version 1 it seams to work but with 2 it throws this error:
`
Uncaught DOMException: The operation is insecure. loadImage.js:26
    fixOrientationFromUrlOrBlobOrFile loadImage.js:26
    transform load-image.js:122
    transform load-image-scale.js:31
    transform load-image-meta.js:194
    onload load-image.js:135
    onload load-image.js:54
`

**Comment by KekOnTheWorld** [comment]
EDIT: Seams to work with local images so im ok with it.

**Comment by ThatOneCalculator** [comment]
I'm getting this issue too, however, my application needs to read images on a remote S3 bucket.
