### ISSUE TITLE
How to assign a custom JobId to the scheduler?

### ISSUE THREAD

**Issue by Allatir** [naptha/tesseract.js#577]
Hi, 

Is it possible to assign a custom JobId to the scheduler? I need to be able to assign the correct logging events to the correct image before it is finished. After finishing i get it back, but thats already to late then. 

Is this possible?

with kind regards

**Comment by oleg-andreyev** [comment]
Pass 4th argument.

```
scheduler.addJob('recognize', img, {}, scan.id);
```

https://github.com/naptha/tesseract.js/blob/90466c3b5504a9220ba0ff91ccec22003f72cbd2/docs/api.md#workerrecognizeimage-options-jobid-promise

**Comment by Allatir** [comment]
Alright, that fixes it, had to use 2.1.5 as well! Thank you very much.
