### ISSUE TITLE
No getPDF function in type definitions.

### ISSUE THREAD

**Issue by MohanVaddi** [naptha/tesseract.js#580]
**No getPDF function in the type definitions provided.**

![image](https://user-images.githubusercontent.com/58596948/142669452-67663b51-991d-46a3-8528-6898e342d367.png)

**but the function is available in: [worker-script/index.js](https://github.com/naptha/tesseract.js/blob/master/src/worker-script/index.js)**

![image](https://user-images.githubusercontent.com/58596948/142670021-e29e33a8-d24a-45be-9de0-c55a09c7aaa1.png)

**Comment by Balearica** [comment]
Thanks for flagging, this has been added in the master branch.
