### ISSUE TITLE
Numeric-only OCR

### ISSUE THREAD

**Issue by XfedeX** [naptha/tesseract.js#587]
**Is your feature request related to a problem? Please describe.**
Add an option to only search for numbers.

**Comment by dl-cy** [comment]
same demand

**Comment by kamiro** [comment]
Just wandering by, however can this be done by setting the tessedit_char_whitelist in worker.setParameters?

```
(async () => {
  await worker.setParameters({
    tessedit_char_whitelist: '0123456789',
  });
})
```
https://github.com/naptha/tesseract.js/blob/master/docs/api.md#workersetparametersparams-jobid-promise

**Comment by Balearica** [comment]
@kamiro's response is correct.  Closing.
