### ISSUE TITLE
Is it possible to obtain the Thresholded Image from tesseract?

### ISSUE THREAD

**Issue by diogoalmiro** [naptha/tesseract.js#588]
I would like to have access to the thresholded image created by tesseract. (See function: [GetThresholdedImage](https://github.com/jeromewu/tesseract/blob/be451c7fdeab7b335f08f2f4c83cc17cafc73056/src/api/baseapi.cpp#L646))

This feature is implemented by the tesseract wrapper library for pyton as a function: https://github.com/sirfz/tesserocr/blob/master/tesserocr.pyx#L1737
There is also a parameter that writes the thresholded image to the file "tessinput.tif": "tessedit_write_images".

I am using win10 and NodeJS with some tiff files, setting the parameter "tessedit_write_images" to "T" or "1" does nothing.

**Comment by Balearica** [comment]
This library does not currently include an interface for retrieving the thresholded image.  It's theoretically possible to do so using low-level functions to read the contents of the wasm filesystem and/or memory--but not something we currently support with high-level functions. 

Feel free to thumbs up this issue if you're reading this and would use this feature if added--can probably add in a future release if there's enough demand.

**Comment by Balearica** [comment]
@diogoalmiro This feature has been added in the development branch for version 4 and will be included in that release.  That branch is functional at present if you would like to try it out, and is described in more detail in #662.  An [example](https://github.com/naptha/tesseract.js/blob/dev/v4/examples/browser/image-processing.html) has also been included to demonstrate usage.

**Comment by Balearica** [comment]
It looks like there is a bug where setting `imageColor: true` causes a filesystem error when used with a black and white image.  Will need to implement a fix before version 4 is released.

**Comment by Balearica** [comment]
Closing as this was added in [Version 4](https://github.com/naptha/tesseract.js/releases/tag/v4.0.0).

**Comment by GitMurf** [comment]
@Balearica I see the example is for browser but can you retrieve the created "threshold" images with Node as well? Thanks

**Comment by Balearica** [comment]
@GitMurf Yes, you can also do this on Node.  You should be able to adapt the browser example fairly easily.

**Comment by Balearica** [comment]
@GitMurf I added an example for retrieving processed images using Node, which can be found [here](https://github.com/naptha/tesseract.js/blob/master/examples/node/image-processing.js).

**Comment by GitMurf** [comment]
@Balearica thanks a ton! This is exactly what I needed :) Much appreciated!
