### ISSUE TITLE
FetchError: request to https://tessdata.projectnaptha.com/4.0.0/eng.traineddata.gz failed, reason: certificate has expired using electron

### ISSUE THREAD

**Issue by BThiebaut** [naptha/tesseract.js#589]
**Describe the bug**
I got the error "FetchError: request to https://tessdata.projectnaptha.com/4.0.0/eng.traineddata.gz failed, reason: certificate has expired" using typescript example in an electron app (in the electron main process, not rendered window)

**To Reproduce**
1. Copy https://github.com/jeromewu/tesseract.js-typescript/blob/master/index.ts
2. Run in electron main process using typescript.
3. Get the error

**Expected behavior**
Be able to read the given png text

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chromium (electron)
 - Version : latest

**Additional context**

My code : 

```
private processOcr()
    {
        (async () => {
            await this.worker.load();
            await this.worker.loadLanguage('eng');
            await this.worker.initialize('eng');
            const { data: { text } } = await this.worker.recognize(this.PngPath);
            console.log(text);
            await this.worker.terminate();
          })();
    }
```
PngPath contain the local png file as an absolute path.

Complete error : 

```
(node:12380) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:12380) UnhandledPromiseRejectionWarning: FetchError: request to https://tessdata.projectnaptha.com/4.0.0/eng.traineddata.gz failed, reason: certificate has expired
```

**Comment by RimashMohomed** [comment]
@BThiebaut Did you able to figure this out?

**Comment by Sectaur** [comment]
Has anyone resolved this issue ? I'm also experiencing the same issue.

The code example works on MacOs (V12) using html and "nodeIntegration: true" (webpreferences in Main.js), however, the same error is seen when running the code in either Main.js or the renderer (after injecting using pre-load script, as recommended).

<img width="786" alt="Screen Shot 2022-08-13 at 2 06 03 PM" src="https://user-images.githubusercontent.com/75922852/184465856-4145ae8f-ff72-4b5e-a645-4a9006f8505e.png">

 Why is it working for one and not the other ?

**Comment by Balearica** [comment]
I believe this only occurs when using an old version of Electron.  The error does not appear to occur when using the latest stable version as of this writing (v20).

**Comment by Sectaur** [comment]
Many thanks !

 will give it a go and let you know if it works.

Also, how do I extract the bbox positions using recognise() ?

**Comment by Balearica** [comment]
@Sectaur can you confirm if this works so we can close the issue? 

The only way I've personally retrieved character/word bounding box positions is through parsing the HOCR output (an xml format).  There are almost certainly easier ways to get bounding boxes, but I only use the HOCR output in my application personally.

**Comment by Sectaur** [comment]
Hi,

Sorry for the late reply.

Yes, It worked, thanks !

The images are pretty complex so am getting variable results but your
suggestions did work.

I’ll try your method and see how it goes,

Regards,

Hament
