### ISSUE TITLE
does support uyghur language?

### ISSUE THREAD

**Issue by ttormahiri** [naptha/tesseract.js#59]
i'm excited about the project ,this project does support uyghur language?

**Comment by rowasc** [comment]
Doesn't look like it is supported.. this is the list of supported languages
https://github.com/naptha/tesseract.js/blob/master/docs/tesseract_lang_list.md

**Comment by bijection** [comment]
Right! We only support languages supported by https://github.com/tesseract-ocr/tesseract that do not need the cube engine.

**Comment by ttormahiri** [comment]
i'm looking that list ,uyghur language not listed ,  have you heard uyghur language ?,uyghur language is very import language so many people need for support this language and this language looks like arabic and persian
