### ISSUE TITLE
Tesseractjs recognize Error: abort(undefined). Build with -s ASSERTIONS=1 for more info on IOS version 15.2

### ISSUE THREAD

**Issue by WahajAutoLeap** [naptha/tesseract.js#590]
**Describe the bug**
when recognize method is run, worker is created and job is completed but at time of output it says Tesseract JS recognize Error: abort(undefined). Build with -s ASSERTIONS=1 for more info, doesn't output result.

**To Reproduce**
I am sending a canvas frame which is being captured from a video so. 
1. Go to 'start scanning'
2. Frames are being sent to recognize method which should return output  
3. but instead in console it shows worker created then job done(cannot be seen is screenshot  but after enable logging I found it)

**Expected behavior**
should read and display parsed result

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - iPhone 11 and up
 - OS: 15.2
 - Browser [ chrome ]
 - Version [ 94 ]

**Additional context**
this is only happening in IOS v15.2 its working fine on lower versions, it also works fine on android.I am passing only image on recognize so that everything is default.
 
![990f7852-0253-41e2-aaa1-bae70b4cc691](https://user-images.githubusercontent.com/94890365/147823580-2b5b5ae0-3315-4af1-af97-415aaaedaecc.jpg)

**Comment by smuaq** [comment]
Not working on iOS 15.2 at all

**Comment by WahajAutoLeap** [comment]
every time iOS updates this error occurs now it appears on iOS 15.2.1 it was resolved on iOS 15.2

**Comment by Balearica** [comment]
I ran a basic test using iOS 15.2 and it worked.  Therefore, this problem presumably only occurs under specific circumstances.  If this issue is still active, please add a reproducible example we can easily run to produce this error.

**Comment by Balearica** [comment]
Closing as stale.  Feel free to reopen if somebody can create a reproducible example using the current version of Tesseract.js.
