### ISSUE TITLE
Request for adding Santali language tessdata

### ISSUE THREAD

**Issue by Prasanta-Hembram** [naptha/tesseract.js#592]
**Is your feature request related to a problem? Please describe.**
Only a feature for the addition of Santali language request. It is absent from official source. I have manually trained this tess data for Santali language and added to my respository (https://github.com/Prasanta-Hembram/Santali-tessdata) . 

**Describe the solution you'd like**
Adding Santali tessdata to this project from my respository (https://github.com/Prasanta-Hembram/Santali-tessdata) .

**Describe alternatives you've considered**
-

**Additional context**
 there is a another tessdata (https://github.com/indic-ocr/tessdata/tree/master/sat) but it's version is not mentioned.

**Comment by Balearica** [comment]
To clarify, did you test your training data with this project and confirm it works?  Your repo states this is version 3 training data, however I was under the impression that the LSTM model (the default) is only compatible with version 4 data and above.

**Comment by Balearica** [comment]
Closing as stale and because I do not believe the data provided is compatible with the default model.
