### ISSUE TITLE
Performance improvement when using rectangle with image node in browser

### ISSUE THREAD

**Issue by aaronsgiles** [naptha/tesseract.js#593]
I have a web application that displays an image to the user and lets them select a region for recognition. I noticed when doing the naive approach:
```
const rectangle = { left:x0, top:y0, width:x1-x0, height:y1-y0 };
const { data: { text } } = await cacheEntry.worker.recognize(imageNode, rectangle);
```
that the `recognize` call was taking quite a long time before even beginning recognition. I suspected this was due to image decoding, so I changed my approach to use a temporary canvas, which pushes all the decoding work onto the native browser code:
```
const rectangle = { left:x0, top:y0, width:x1-x0, height:y1-y0 };
var tempCanvas = document.createElement('canvas');
tempCanvas.width = rectangle.width;
tempCanvas.height = rectangle.height;
var context = tempCanvas.getContext('2d');
context.drawImage(imageNode, -rectangle.left, -rectangle.top);
const { data: { text } } = await cacheEntry.worker.recognize(tempCanvas);
```
and it made a huge difference. This is on Firefox latest. YMMV on other browsers. 

I haven't experimented to see if in general it is better to use a temporary canvas in all cases, but I recommend at least mentioning this in the docs when it comes to performance in the browser, because in my experience it is quite a boost. This approach probably doesn't play well outside the browser, but maybe it could be intelligently applied in the `recognize` glue.

**Comment by gabzim** [comment]
Hey excellent catch, I'm not doing this on the browser yet but this is definitely good advice.

**Comment by hammad-umar** [comment]
I am making an application where user upload an image and on the image he/she draw a bounding box around the text. I want to remove extra whitespaces from the bounding box soon after user draw a bounding box. So the bounding box shrinks according to the text can anyone helps. I am using annotorious for drawing bounding boxes and tesseractjs OCR.

**Comment by Balearica** [comment]
Thanks for the tip.  Note that Tesseract.js v2 had significant performance issues setting large images--so it makes sense that cropping first would help.  These issues have been resolved in Tesseract.js v3 (the current version), so I would expect the difference this makes to be comparatively minor (if any) now.
