### ISSUE TITLE
Memory leakage error for only one scan! - nodejs

### ISSUE THREAD

**Issue by alienorder** [naptha/tesseract.js#595]
Wrapped port fails in nodejs for pages of moderate complexity. Issue is not directly bound to the size of an image but to the number of words to be recognized.
For a fill factor of above 30% of 11 text size on one A4 sized picture the process using workers exactly as to the example is permanently causing
——- memory leakage errors ——-
after taking almost all of the available 8 GB RAM very slowly processing. (One scan!)

Tested with some of the most actual versions of nodejs this date (2022/01)
and also different number of workers and jobs

for some simple file it was still factor 100! slower than the Port’s original tesseract of same version. (Nodejs Around 3 minutes.) (the example png was the fastest - 15 sec)

1. go to the examples
2. copy the example using a worker or multiple
3. select a different image (png or jpg) (A4) with some dense text in good quality b&w of around 2 mb size
4. see the process take 100% CPU and all RAM for a couple of minutes until it fails. With memory leakage error!
5. the same process works fine for the image 
in the example.

**Expected behavior**
It should work with decent comparison to the port‘s origin and not produce leakage errors

**Desktop**
 - OS: win10
 - tesseract.js Version v2 (as of now default)
 - Nodejs different of the latest tested (2022/01)

**Comment by Balearica** [comment]
This issue should be resolved in the master branch.  Please let me know if still an issue.

**Comment by Balearica** [comment]
Closing as stale and because I believe this was resolved.  Feel free to reopen if you encounter again.
