### ISSUE TITLE
Does this JS library implement Tesseract Word Font Attributes function

### ISSUE THREAD

**Issue by ken4ward** [naptha/tesseract.js#599]
**Is your feature request related to a problem? Please describe.**
I have used a feature that's only available in Tesseract 3.0.5 which allows getting the font attributes. I'll like to confirm if this JS library has an. implementation for that as well?

**Describe the solution you'd like**
I need to be able to extract font-size information (font names aren't so useful) - is there any way at all of doing so with LSTM/v4? Which implementation of Tesseract OCR version does this library support?
If I use OcrEngineMode 0 to be able to get this info, will that be removed from v4 at a later date?
Is there any advantage to using v4 with OcrEngineMode 0 vs v3.05?

**Comment by Balearica** [comment]
Tesseract.js does provide this information the same as the main Tesseract library.  For example, if `ret` is the object returned by `worker.recognize`, the following would extract the font_size attribute of the first word.

```
ret.data.blocks[0].paragraphs[0].lines[0].words[0].font_size
```

Note that font size information is not always reliable.  In my own projects I ended up just calculating font size manually using the height of letters.  However, this is an issue with Tesseract (not something specific to Tesseract.js).  

I do not believe there is any significant difference between using v3.05 and the current version with OEM mode 0.  The legacy model + features are not going anywhere (they will not be removed at a later date) however do not seem to be actively maintained/improved either.

**Comment by Balearica** [comment]
Closing as answered.
