### ISSUE TITLE
DIdnt work for me

### ISSUE THREAD

**Issue by benag** [naptha/tesseract.js#6]
<html>
    <head>

    </head>
    <body>
    <img src="dream.jpg" class="to_ocr">
    <div class="prog"><div>
    <canvas class="display"></canvas>
    <script src="http://tenso.rs/tesseract.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>

    <script>
        var img = $('body').find(".to_ocr");
        Tesseract.recognize( img, { progress: 'prog', lang: 'eng'} )
            .then( 'display' );
    </script>
    </body>
    </html>

getting:
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': An object could not be cloned.

**Comment by austinmorgan** [comment]
Hi there, combined your code with some stuff from the example.htm file in the tesseract.js repo and this worked for me, give it a shot:

```html
<html>
<head>

</head>
<body>
<img src="dream.jpg" id="ocr" />
<div id="display"></div>
<script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>
<script src="http://tenso.rs/tesseract.js"></script>
<script>
    var img = new Image();
    img.src = document.getElementById('ocr').src;

    img.onload = function() {
    	Tesseract.recognize(img,{
			progress: function(e){
				console.log(e)
			}
		}).then( function(d){ document.getElementById('display').innerHTML+=d.text } )
	}
</script>
</body>
</html>
```

I didn't use your canvas or JQuery, but you could put those back in, just wanted to show how I passed the image into Tesseract.recognize. The progress log will show up in the console.

**Comment by intergleam** [comment]
it's an error now 
```
<html>
<head>

</head>
<body>
<img src="dream.jpg" id="ocr" />
<div id="display"></div>
<script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>
<script src='https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js'></script>
<script>
    var img = new Image();
    img.src = document.getElementById('ocr').src;

    img.onload = function() {
        Tesseract.recognize(img,{
            progress: function(e){
                console.log(e)
            }
        }).then( function(d){ document.getElementById('display').innerHTML+=d.text } )
    }
</script>
</body>
</html>
```
gives 
```
tesseract.js:356 Uncaught DataCloneError: Failed to execute 'postMessage' on 'Worker': An object could not be cloned.
```

**Comment by bijection** [comment]
The API has changed, check out the new API in the readme.
