### ISSUE TITLE
Reopen the question: will tesseract.js support chrome extension build with MV3

### ISSUE THREAD

**Issue by ForeverAT** [naptha/tesseract.js#601]
The problem now of using tesseract.js in chrome extension with manifestV3 is the unsafe-eval issue. As MV3 separate the CSP for extension page and sandboxed page, the extension page is no longer allow to use unsafe-eval in script-src. May I ask is there any example or method to implement tesseract.js in chrome extension with manifestV3?

**Comment by clarodanesh** [comment]
Any updates on this issue? Looks like chrome are allowing us to set worker-src in the csp for extension_pages. According to this bug here [Chrome allowing worker-src link](https://bugs.chromium.org/p/chromium/issues/detail?id=1173354) however when using this with tesseract.js in the extension csp throws an error relating to loading blob url's in the worker. This bug can be seen here [Blob: url bug with mv3 and tesseract](https://bugs.chromium.org/p/chromium/issues/detail?id=1319380&q=&can=2) 

@jeromewu @ForeverAT

**Comment by ForeverAT** [comment]
currently no, I have changed to other OCR for my project in this moment.
@clarodanesh

**Comment by sanjeev07** [comment]
Hello! any update on this issue . any idea how to make this work using manifest version 3 ?

**Comment by Balearica** [comment]
I'm the only active maintainer at the moment, and have no experience with developing Chrome extensions.  Therefore, I think this would take somebody else developing a fix, or at the very least, providing a detailed description of what part of tesseract.js is problematic and how it would need to be changed.

**Comment by ForeverAT** [comment]
Actually I find a method ( and tried) these days, you may inject the file into the website you are browsing and build worker in the website. Most websites are fine but like GitHub, it does not allowed us to create worker (which does not required by other OCR technology). Hope this help you guys.
@sanjeev07 @clarodanesh

**Comment by RobertJGabriel** [comment]
Hey @Balearica,

At @ForeverAT  is correct. That is the way i'm able to get it to work.

The more detailed issue is that the Manifest v3 switches the backend script to the serverworker standard and you no longer have access to the document api.

Let me know if I can do anything, as it would be amazing to have the tesseract in the serverworker.

**Comment by datvm** [comment]
@ForeverAT  I was able to add it to Chrome Extension (running in an extension popup page), explained here: https://stackoverflow.com/a/76604454/653457. No idea why there is no documentation/mention of this anywhere though.

**Comment by felri** [comment]
@datvm thank you, at least I'm getting a new error now:

> Refused to compile or instantiate WebAssembly module because neither 'wasm-eval' nor 'unsafe-eval' is an allowed source of script in the following Content Security Policy directive: "script-src 'self'"). Build with -s ASSERTIONS=1 for more info.

**Comment by datvm** [comment]
@felri You need to [add a CSP declaration for wasm](https://developer.chrome.com/docs/extensions/reference/manifest/content-security-policy).

**Comment by ngntriminh** [comment]
> @ForeverAT I was able to add it to Chrome Extension (running in an extension popup page), explained here: https://stackoverflow.com/a/76604454/653457. No idea why there is no documentation/mention of this anywhere though.

Thank you. Your solution saved my life!

**Comment by jzhao846** [comment]
Hi, after setting workerBlobURL to false, I am getting this issue, even on websites that worked before:

`Uncaught (in promise) SecurityError: Failed to construct 'Worker': Script at 'chrome-extension://adgbmjocepadpogbpkcfjlenomopilfo/vendor/tesseractjs/tesseract.js@v5.0.4_dist_worker.min.js' cannot be accessed from origin 'https://www.google.com'.`

Any idea why that is and how to fix it? Thanks!

**Comment by ngntriminh** [comment]
> Hi, after setting workerBlobURL to false, I am getting this issue, even on websites that worked before:
> 
> `Uncaught (in promise) SecurityError: Failed to construct 'Worker': Script at 'chrome-extension://adgbmjocepadpogbpkcfjlenomopilfo/vendor/tesseractjs/tesseract.js@v5.0.4_dist_worker.min.js' cannot be accessed from origin 'https://www.google.com'.`
> 
> Any idea why that is and how to fix it? Thanks!

Have you also added `tesseract-core.wasm.js`? 
After adding it, try to add this in your `manifest.json` (replace `[path to your worker.min.js]` and `[path to your tesseract-core.wasm.js]` with your actual paths:
```
 "web_accessible_resources": [
    {
      "resources": ["[path to your worker.min.js]", "[path to your tesseract-core.wasm.js]"],
      "matches": ["<all_urls>"]
    }
  ]
```
If you still face the CSP error, add this:
```
  "content_security_policy": {
    "extension_pages": "script-src 'self' 'wasm-unsafe-eval'; object-src 'self';"
  },
```

**Comment by jzhao846** [comment]
@ngntriminh Thanks for the reply. Unfortunately, I am still facing the same error. I am relatively new to JS and developing chrome extensions, but my interpretation of the error message is that it is incorrectly constructing the worker from the webpage instead of the extension itself? I don't have a popup or any html, so I've been including Tesseract using `chrome.scripting.executeScript({files: ['libs/tesseract.min.js'], target: {tabId: tab.id}})` in my `background.js`. Maybe this is an incorrect way to load it? Again, it works perfectly fine without `workerBlobURL: false` as long as the website doesn't have interfering CSP restrictions, so the blob's role in constructing the worker might be relevant to the overall issue.

**Comment by ngntriminh** [comment]
> @ngntriminh Thanks for the reply. Unfortunately, I am still facing the same error. I am relatively new to JS and developing chrome extensions, but my interpretation of the error message is that it is incorrectly constructing the worker from the webpage instead of the extension itself? I don't have a popup or any html, so I've been including Tesseract using `chrome.scripting.executeScript({files: ['libs/tesseract.min.js'], target: {tabId: tab.id}})` in my `background.js`. Maybe this is an incorrect way to load it? Again, it works perfectly fine without `workerBlobURL: false` as long as the website doesn't have interfering CSP restrictions, so the blob's role in constructing the worker might be relevant to the overall issue.

@jzhao846 Thank you. Here is how I initiate Tesseract for my Chrome extension and it works fine. In my case, I don't use `background.js`, it's just a normal `.js` file so maybe you can take it as a reference:
```
const { createWorker } = Tesseract;
const worker = await createWorker("eng", 1, {corePath: chrome.runtime.getURL("/libs/tesseract-core.wasm.js"), workerPath: chrome.runtime.getURL("/libs/worker.min.js"), workerBlobURL: false, });
```

**Comment by jzhao846** [comment]
@ngntriminh Thanks for the help. In the end, I was able to resolve the origin issue by constructing the worker in an [Offscreen Doc](https://developer.chrome.com/docs/extensions/reference/api/offscreen).

Based on my understanding, the workerURL needs to be of the same origin as where it is called from (e.g. google.com). The workerURL lives in the extension's origin, so this has to be bypassed using a blob url. However, this blob url can also cause problems with the webpage's CSP. Constructing the worker in an offscreen doc or an iframe would ensure that the worker is called from the extension's origin to begin with, thus no longer running into origin problems. I assume calling the worker from a popup would also solve the issue.

Hopefully this helps anyone else who has the same problem!
