### ISSUE TITLE
Can we read only specific text from image based on text size ?

### ISSUE THREAD

**Issue by Utsaww** [naptha/tesseract.js#605]
**I am trying to read text from an image based on image size!**
 
I have some specific text sizes so I am trying to do that if text or font size is greater than 2px it will read only those texts, but could not find any solution and I guess this feature is also not available in this tesseract.js?

is there any solution or method please enlightened me.

**Comment by Balearica** [comment]
While I do not believe this is a built-in feature in the tesseract.js API, it can likely be achieved without too much work.  There are various config options in the main (desktop) version of Tesseract that deal with size thresholds for text vs. noise.  Therefore, I would start by seeing if you can achieve what you're looking for using the desktop version of Tesseract.  Once you figure that out what config options are necessary, the relevant config options could be exposed in the tesseract.js API.

**Comment by Utsav-upadhyay** [comment]
@Balearica Thank you for this amazing idea, I am surely going to explore this but broadly I need to say I am looking for a solution where it picks the biggest font size text only or any option like Naptha where I select the text from image and copy

**Comment by Balearica** [comment]
While perhaps you can engineer a solution, there is no built-in option that does what you describe.  Closing as answered.
