### ISSUE TITLE
PSM.RAW_LINE is missing in type file

### ISSUE THREAD

**Issue by Dullson** [naptha/tesseract.js#606]
[Current typescript definition of PSM enum](https://github.com/naptha/tesseract.js/blob/adcb5b875986ebe61d7235e64d956d648c53c1dd/src/index.d.ts#L88) is missing RAW_LINE (13) flag.
I believe it's a type file error since [the underlying library files](https://github.com/jeromewu/tesseract/blob/349d42f04a0aed88b5f37983ba66f12c673eb987/src/ccmain/tesseractclass.cpp#L73) include the raw_line flag

**Comment by Balearica** [comment]
Thanks for flagging, this has been added in the master branch.
