### ISSUE TITLE
Tesseract fails when running in Firefox incognito browser

### ISSUE THREAD

**Issue by ronbarbosa** [naptha/tesseract.js#609]
**Describe the bug**
When running Firefox in an incognito browser window/tab, Tesseract image scans do not function. This does not seem to impact Chromium based browsers.

**To Reproduce**
1. In a Firefox incognito/private browser window visit https://tesseract.projectnaptha.com/
2. Notice the demo at the bottom hangs
3. This error is thrown in the console: 
Uncaught Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.
    exports createWorker.js:139
    onmessage onMessage.js:3
    exports onMessage.js:2
    exports createWorker.js:122
    <anonymous> demo.js:28
createWorker.js:139:14

**Expected behavior**
No error should be shown and the OCR process should complete.

**Screenshots**
![image](https://user-images.githubusercontent.com/1733836/163716054-54a56167-0ffb-4604-b17a-1c403d05b7df.png)

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Browser: Firefox
 - Version: 99.0.1

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
A failure occurs in my own project as well, both in online mode and offline mode, but I do not see the same error message. In my project, online mode fails during Tesseract.recognize() and neither returns nor throws an exception (the worker is created internally by Tesseract.recognize()). Offline mode fails during createWorker() and throws a "type error" exception indicating "r is null." 

In my project, both online and offline methods work properly outside incognito mode. The offline version functions properly when disconnected from the internet as well (as long as the browser is not in incognito mode). The problem only seems to be present in incognito mode regardless of whether the browser has an active connection to the internet.

I have noticed that in a Firefox incognito browser window, the demo on the Tesseract.js homepage also fails.

**Comment by WintrySnowman** [comment]
Tesseract stores the training data inside IndexedDB after it's loaded it for the first time. Firefox's private browsing mode explicitly disables IndexedDB, [as per this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=781982). There does not appear to be a fallback in place, but in the worst case you should be able to check for support and alert the user as to why.

**Comment by Balearica** [comment]
Thanks to @ronbarbosa for reporting and @WintrySnowman for explaining the core issue.  I reviewed the code, and believe this can be easily resolved.  At present, it looks like the language data is successfully retrieved from the remote server, however there is an error writing to cache (as modifications to IndexedDB are disabled) that causes the entire function to fail/throw an error.  Therefore, it should simply be a matter of wrapping this line in a "try" block.  Will implement a fix shortly.

https://github.com/naptha/tesseract.js/blob/263dbb87b11871eb29887b68ef2253ec0dca120c/src/worker-script/index.js#L134-L136

**Comment by Balearica** [comment]
Closing as this was resolved in [Version 4](https://github.com/naptha/tesseract.js/releases/tag/v4.0.0).
