### ISSUE TITLE
How to increase the speed of ocr using tesseract.js in mobile app

### ISSUE THREAD

**Issue by Mas-Y** [naptha/tesseract.js#611]
Hi,
I am using tesseract.js in a mobile app built using ionic, OCR using tesseract.js is taking long time. Is there a way to decrease the time taken and make the ocr faster in the mobile app.
Any suggestions are welcomed.

**Comment by Balearica** [comment]
Using the Legacy engine rather than the LSTM engine (the default) will reduce runtime considerably.

**Comment by Balearica** [comment]
Additionally, if you are open to performance optimizations that are not implemented in the master branch, see #604 and https://github.com/naptha/tesseract.js-core/pull/18.

**Comment by abhishek-hingne** [comment]
When I tried using Legacy Engine, I am getting following error:
TesseractError: (1, "Error: Tesseract (legacy) engine requested, but components are not present in /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata!! Failed loading language 'eng' Tesseract couldn't load any languages! Could not initialize tesseract.")
But when I use Default OEM then it works perfectly.

Do you have any suggestion on how to solve this issue

**Comment by abhishekhingne** [comment]
When I tried using Legacy Engine, I am getting below error
TesseractError: (1, "Error: Tesseract (legacy) engine requested, but components are not present in /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata!! Failed loading language 'eng' Tesseract couldn't load any languages! Could not initialize tesseract.")
But when I use Default OEM then it works perfectly.

Do you have any suggestion on how to solve this issue

**Comment by Balearica** [comment]
Please post the code you used that resulted in this error.

**Comment by abhishekhingne** [comment]
tesseract input.tiff output --oem 0 -l eng

**Comment by Balearica** [comment]
Are you using the Tesseract desktop app?  If so this is the wrong place to ask for support.

**Comment by Mas-Y** [comment]
@Balearica Thank you so much for the support. Using Legacy engine didn't make a big difference, but the optimised branch you shared was really helpful. There was a significant decrease in time. Do you have any suggestions for further decreasing the time?

**Comment by Mas-Y** [comment]
Thank you @Balearica for the support. Would continue using the optimised branch.
