### ISSUE TITLE
Tesseract.js can't load language files on deployed server

### ISSUE THREAD

**Issue by danisss9** [naptha/tesseract.js#618]
**Describe the bug**
Tesseract throws error when running in a deployed VM (ex: "https://vmdev-01:1000/DocScanner").

But works when running on localhost (ex: "https://localhost/DocScanner").

The code and deployment is the same. Both servers are running windows 10, IIS and ASP.NET Core 3.1 and for Frontend i'm using Angular 12.

**To Reproduce**
1. Setup Tesseract.js to run on browser (see code bellow)
2. Deploy WebApp on a VPS or Docker
3. Shows error loading languages

**Expected behavior**
Should work the same as in localhost.

**Screenshots**
Error Message:
![image](https://user-images.githubusercontent.com/36733433/175570488-2cf400b8-0699-4215-8f9e-c1329ce3af71.png)

"assets/scripts/tesseract" folder: 
![image](https://user-images.githubusercontent.com/36733433/175570744-73cbeb45-ae53-4433-961c-f29375451bbd.png)

"assets/scripts/tesseract/lang-data" folder:
![image](https://user-images.githubusercontent.com/36733433/175570844-c07c7476-be12-4bba-adb5-71d864247bfe.png)

Package.json tesseract versions:
![image](https://user-images.githubusercontent.com/36733433/175571365-4300d258-208f-4070-9651-94bd1318fd92.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 102.0.5005.115 (Official Build) (64-bit)

**Additional context**

Tesseract.js setup code:
```
import { createWorker } from 'tesseract.js';

private async OcrImage(img: string) {
    const worker = createWorker({
      corePath:
        (this.baseUrl ?? '/') +
        'assets/scripts/tesseract/tesseract-core.wasm.js',
      workerPath:
        (this.baseUrl ?? '/') + 'assets/scripts/tesseract/worker.min.js',
      langPath:
        location.origin +
        (this.baseUrl ?? '/') +
        'assets/scripts/tesseract/lang-data',
      cacheMethod: 'none'
    });

    await worker.load();
    await worker.loadLanguage('eng');
    await worker.initialize('eng');
    await worker.setParameters({
      tessedit_char_whitelist: '0123456789',
    });

    const data = await worker.recognize(img);
    await worker.terminate();
    return data;
  }
```

**Comment by zerosdev** [comment]
I have this problem too, I have 2 VPS with Ubuntu 20.04, 1 server is working fine and the other sometimes get this error even though eng.traineddata already exists. I don't know what happened. Both servers have the same code

**Comment by Balearica** [comment]
@zerosdev As your issue only occurs "sometimes" it is probably related to the caching error discussed in #666.  This should be fixed or significantly mitigated in version 4.  In short, it looks like `eng.traineddata` can be corrupted, so when this happens you should either delete this file, or disable caching entirely (by setting `cacheMethod` to "none") although this may increase network use.

**Comment by 314513535** [comment]
I have same issue. I guess this component can only work by running on node.js but not pure javascript.

**Comment by Balearica** [comment]
@314513535 It is entirely possible to load custom traineddata files using JavaScript in browser.  If you are having trouble doing so and want support please provide a reproducible example of your issue in the form of a code snippet (that can be run without additional dependencies) or repository. 

Here is an example of a program using custom training data in browser: https://github.com/scribeocr/scribeocr/blob/master/main.js#L758

**Comment by danisss9** [comment]
This seems to be fixed in version 4.
