### ISSUE TITLE
.EXE or Solution File in the downloads folder please

### ISSUE THREAD

**Issue by conetopia** [naptha/tesseract.js#619]
Downloaded like 17 versions from 2.15 and below, and none of the folders had a .exe in them.
No instructions were given.
Did some research and downloaded Visual Studios 2022. 
Build Button was missing, because I was opening Folder instead of Solution.
No Solution File included Either.

Please Update/Fix

Also: Downloaded Tesseract OCR 
https://github.com/UB-Mannheim/tesseract/wiki -64 bit
However Once installed, nothing opens. Opened Folder C:\Program Files\Tesseract-OCR
There is nothing really to launch besides the tesseract Application, How ever Clicking it doesn't do anything.
Text to image just does a quick flash of command prompt in a tiny window, and thats it, 

Not sure If this was supposed to be a Dependency/Requirement to run Tesseract.js
Would really like a guide.

**Comment by Balearica** [comment]
Tesseract.js is the webassembly port of Tesseract (for web developers to integrate into websites).  For the desktop version see the [main Tesseract project](https://github.com/tesseract-ocr/tesseract).
