### ISSUE TITLE
Fetch Failed (Broken on Node 18)

### ISSUE THREAD

**Issue by IkeVoodoo** [naptha/tesseract.js#620]
**Describe the bug**
Whenever I try to use Tesseract.js, wherever I am passing in a Buffer or a URL, I get `RuntimeError: abort(TypeError: fetch failed). Build with -s ASSERTIONS=1 for more info.`

**To Reproduce**
1. Install Tesseract.js (npm install tesseract.js)
2. Go to https://github.com/naptha/tesseract.js/ scroll down until you find the second code block
3. Paste it into your code

**Expected behavior**
I expected some text to be printed to console

**Screenshots**
![Code](https://user-images.githubusercontent.com/55694349/178295956-941ddad7-c034-42da-80e4-2a1d6f8e5428.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser None, Using Node
 - Version 18.4.0

**Smartphone (please complete the following information):**
Not using a smartphone

**Additional context**
No additional context

**Comment by adriangzz** [comment]
This is solved by downgrading node version to 16.16.0.

**Comment by Balearica** [comment]
Thanks for flagging--will have to update such that it is not broken in Node 18 in the next release.

**Comment by Balearica** [comment]
Root cause ended up being in tesseract.js-core.  Fixed in that repo, and so Node.js 18 will be supported in the next release.
