### ISSUE TITLE
Add additional repository maintainers

### ISSUE THREAD

**Issue by ryanbarr** [naptha/tesseract.js#623]
**Is your feature request related to a problem? Please describe.**
Come August 2nd, this repository will have not have seen a release in one year. The only change made since that release was to update the `FUNDING.yml`. Tesseract.js is also relying on Tesseract v4, when Tesseract v5 is available.

With nearly 150,000 monthly downloads and millions in total, this library has become a crucial part of many other projects. It deserves active maintenance and support.

**Describe the solution you'd like**

1. Merge @Balearica's PR at naptha/tesseract.js-core#18 and do a release to adopt the performance gains of Tesseract v5.
2. Open a call for new maintainers.
3. Consider implementing the [badges from "Is it maintained?"](https://isitmaintained.com/project/naptha/tesseract.js).

**Describe alternatives you've considered**
The only alternatives are to replicate the functionality Tesseract.js offers in a new library or rely on forks.

**Additional context**
N/A

**Comment by Balearica** [comment]
I've been added and will be working on a new release with Tesseract 5 along with other features/fixes.

**Comment by Balearica** [comment]
Closing as I've released version 3.0.0, which contains significant performance improvements including the PR you link to above.
