### ISSUE TITLE
Has the author stopped maintenance?

### ISSUE THREAD

**Issue by SilurianYang** [naptha/tesseract.js#624]
**Is your feature request related to an issue? Please describe.**
The code update on the master branch is the same as 2 years ago, I checked that [tesseract](https://github.com/tesseract-ocr/tesseract) has been updated to v5.2.0 version

**Describe your desired solution**
Continue maintenance or join more active developers?

**Describe the alternatives you have considered**
Is there an alternate version?

**Additional context**
no

**Comment by Balearica** [comment]
I've been added and will be working on a new release with Tesseract 5 along with other features/fixes.

**Comment by Balearica** [comment]
Closing as I've released version 3.0.0.  As always, additional contributors are welcome if folks have an interest in improving the library.
