### ISSUE TITLE
Incorrect return result

### ISSUE THREAD

**Issue by hieuemmm** [naptha/tesseract.js#627]
**Data get in here :** https://www.tratencongty.com/company/115db8798-cong-ty-tnhh-mtv-dau-tu-xay-dung-vuong-phat/
**Here is image URL :** [data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEkAAAANCAIAAABq2NTxAAADX0lEQVRIid2WTUgqYRSGj9cG+0Eky341JMlNZAuhhoEwsjAqMoIiiDZRu9BVQov2Q0ubFuHCRdGiIPrBRAqDaBVBVAxDuFAIpkbqG4Jw4DrBXXw21+sdBeWu7ll9vJ7z8L7j8XM0CCH4T+tHuQOyLP/8roKP9vb2rFarKIr/yFt58L+N/c52dnbW3t4+MzNzcXGBFVEUl5aW7Ha7yWTy+/1YtNlsLd/l9XqVcUEQ1tbWvF5vfX19CWZl+t9wWZYHBwctFktDQ8Pq6qq6MYQQQojn+cbGRrfbHQ6HtVptOBxGCKXT6ampqe3t7d3dXQDY2tpCCN3c3Jyfn4dCIQDweDzou+bn5/V6fSKRUBRVZgW6KjyVShEEUVdXNzIyQtO0qrFcNoZhNBoNy7IIIZfL5XK5UF5NTk4CAMMwikLTtJIWIcRxHEEQPp8vf6oYs1xdFU7TdE1NTTKZRH9WvrHcTh4fH/f29ra2tgJAT0/P4+Mj1jOZzOLi4snJicPhmJ6eVpYkFotptdqxsTHlx5DNZjc3NwcGBuLxeGlmuboqfGdnp6Oj4+PjA/6sfGO5bHd3d93d3fhcVVWFZwRB6OvrOzo60mq1DMNUV1fjhs/Pz+vra4qiDAYDVqLRqNFoPDg48Hg8CwsLz8/PxZgV6KpwgiCenp6cTif+olSN5bKJomgymfBZEITa2loAkCSJ53mdTvf19TU3N/f+/o4bLi8vs9ns6OioAuU4bnx8fGhoKBAISJIUjUaLMSvQVeHxeDyZTPr9/o2NDeXiKTCWy2YwGGRZxueHh4euri4AsFqt9/f3Ly8vV1dXPM/v7+/jBrwYbrdbySbLcnNzMwDghy1JUjFmBboqHPf7fD4AULa3wFguW39/P8uyAJBKpViWHR4exrrFYgEA/KiampqweHt7azab7Xa7kq2zszOTyQBAJBIBAKfTWYJZrq4Kx4UXkiRJdWP4eolEIgRBMAxDUZROp8OXVSKRODw8nJ2dBQCKotLpNG7W6XTLy8v5t9P6+rrNZguFQkajkSTJEswK9GJwbCz//iwwBsopGAy2tLQYjUblj+X09FSv15vN5kAg8Pr6qnQ6HI5YLJaf7e3tbWVlRa/XkyTJcVwJZgW6KnxiYqKtrS0YDOaPFxjToP/3ffIXqS27QEtWZCUAAAAASUVORK5CYII=](url)

**Result:**
![image](https://user-images.githubusercontent.com/76985151/182952634-ff5553c2-ea91-46f6-966f-458622ef3395.png)
This is incorrect with me

**Comment by Balearica** [comment]
I was not able to reproduce this result.  I ran the code below in the debug console of the sample size (link also below), and the result was correct. 

http://tesseract.projectnaptha.com/

```
worker.recognize("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEkAAAANCAIAAABq2NTxAAADX0lEQVRIid2WTUgqYRSGj9cG+0Eky341JMlNZAuhhoEwsjAqMoIiiDZRu9BVQov2Q0ubFuHCRdGiIPrBRAqDaBVBVAxDuFAIpkbqG4Jw4DrBXXw21+sdBeWu7ll9vJ7z8L7j8XM0CCH4T+tHuQOyLP/8roKP9vb2rFarKIr/yFt58L+N/c52dnbW3t4+MzNzcXGBFVEUl5aW7Ha7yWTy+/1YtNlsLd/l9XqVcUEQ1tbWvF5vfX19CWZl+t9wWZYHBwctFktDQ8Pq6qq6MYQQQojn+cbGRrfbHQ6HtVptOBxGCKXT6ampqe3t7d3dXQDY2tpCCN3c3Jyfn4dCIQDweDzou+bn5/V6fSKRUBRVZgW6KjyVShEEUVdXNzIyQtO0qrFcNoZhNBoNy7IIIZfL5XK5UF5NTk4CAMMwikLTtJIWIcRxHEEQPp8vf6oYs1xdFU7TdE1NTTKZRH9WvrHcTh4fH/f29ra2tgJAT0/P4+Mj1jOZzOLi4snJicPhmJ6eVpYkFotptdqxsTHlx5DNZjc3NwcGBuLxeGlmuboqfGdnp6Oj4+PjA/6sfGO5bHd3d93d3fhcVVWFZwRB6OvrOzo60mq1DMNUV1fjhs/Pz+vra4qiDAYDVqLRqNFoPDg48Hg8CwsLz8/PxZgV6KpwgiCenp6cTif+olSN5bKJomgymfBZEITa2loAkCSJ53mdTvf19TU3N/f+/o4bLi8vs9ns6OioAuU4bnx8fGhoKBAISJIUjUaLMSvQVeHxeDyZTPr9/o2NDeXiKTCWy2YwGGRZxueHh4euri4AsFqt9/f3Ly8vV1dXPM/v7+/jBrwYbrdbySbLcnNzMwDghy1JUjFmBboqHPf7fD4AULa3wFguW39/P8uyAJBKpViWHR4exrrFYgEA/KiampqweHt7azab7Xa7kq2zszOTyQBAJBIBAKfTWYJZrq4Kx4UXkiRJdWP4eolEIgRBMAxDUZROp8OXVSKRODw8nJ2dBQCKotLpNG7W6XTLy8v5t9P6+rrNZguFQkajkSTJEswK9GJwbCz//iwwBsopGAy2tLQYjUblj+X09FSv15vN5kAg8Pr6qnQ6HI5YLJaf7e3tbWVlRa/XkyTJcVwJZgW6KnxiYqKtrS0YDOaPFxjToP/3ffIXqS27QEtWZCUAAAAASUVORK5CYII=").then((x) => console.log(x.data.text))

```

**Comment by hieuemmm** [comment]
> Tôi đã không thể tái tạo kết quả này. Tôi đã chạy mã bên dưới trong bảng điều khiển gỡ lỗi có kích thước mẫu (liên kết bên dưới) và kết quả là chính xác.
> 
> http://tesseract.projectnaptha.com/
> 
> ```
> worker.recognize("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEkAAAANCAIAAABq2NTxAAADX0lEQVRIid2WTUgqYRSGj9cG+0Eky341JMlNZAuhhoEwsjAqMoIiiDZRu9BVQov2Q0ubFuHCRdGiIPrBRAqDaBVBVAxDuFAIpkbqG4Jw4DrBXXw21+sdBeWu7ll9vJ7z8L7j8XM0CCH4T+tHuQOyLP/8roKP9vb2rFarKIr/yFt58L+N/c52dnbW3t4+MzNzcXGBFVEUl5aW7Ha7yWTy+/1YtNlsLd/l9XqVcUEQ1tbWvF5vfX19CWZl+t9wWZYHBwctFktDQ8Pq6qq6MYQQQojn+cbGRrfbHQ6HtVptOBxGCKXT6ampqe3t7d3dXQDY2tpCCN3c3Jyfn4dCIQDweDzou+bn5/V6fSKRUBRVZgW6KjyVShEEUVdXNzIyQtO0qrFcNoZhNBoNy7IIIZfL5XK5UF5NTk4CAMMwikLTtJIWIcRxHEEQPp8vf6oYs1xdFU7TdE1NTTKZRH9WvrHcTh4fH/f29ra2tgJAT0/P4+Mj1jOZzOLi4snJicPhmJ6eVpYkFotptdqxsTHlx5DNZjc3NwcGBuLxeGlmuboqfGdnp6Oj4+PjA/6sfGO5bHd3d93d3fhcVVWFZwRB6OvrOzo60mq1DMNUV1fjhs/Pz+vra4qiDAYDVqLRqNFoPDg48Hg8CwsLz8/PxZgV6KpwgiCenp6cTif+olSN5bKJomgymfBZEITa2loAkCSJ53mdTvf19TU3N/f+/o4bLi8vs9ns6OioAuU4bnx8fGhoKBAISJIUjUaLMSvQVeHxeDyZTPr9/o2NDeXiKTCWy2YwGGRZxueHh4euri4AsFqt9/f3Ly8vV1dXPM/v7+/jBrwYbrdbySbLcnNzMwDghy1JUjFmBboqHPf7fD4AULa3wFguW39/P8uyAJBKpViWHR4exrrFYgEA/KiampqweHt7azab7Xa7kq2zszOTyQBAJBIBAKfTWYJZrq4Kx4UXkiRJdWP4eolEIgRBMAxDUZROp8OXVSKRODw8nJ2dBQCKotLpNG7W6XTLy8v5t9P6+rrNZguFQkajkSTJEswK9GJwbCz//iwwBsopGAy2tLQYjUblj+X09FSv15vN5kAg8Pr6qnQ6HI5YLJaf7e3tbWVlRa/XkyTJcVwJZgW6KnxiYqKtrS0YDOaPFxjToP/3ffIXqS27QEtWZCUAAAAASUVORK5CYII=").then((x) => console.log(x.data.text))
> ```

I changed the image to x10 size. And it works very well. Thank you
