### ISSUE TITLE
Assign char whitelist to specific rectangles

### ISSUE THREAD

**Issue by BrunoAkune** [naptha/tesseract.js#635]
Hi, I wanted to ask if it is possible to assign Tesseract to read specific chars from each rectangle.
Example:
Rectangle 1 = just read the letters
Rectangle 2 = just read the numbers

**Comment by Balearica** [comment]
tesseract.js supports both a `tessedit_char_whitelist` config option (only recognizing whitelisted characters) as well as the ability to only recognize text within a specific rectangle.  Both are explained in [examples](https://github.com/naptha/tesseract.js/blob/master/docs/examples.md).  Therefore, you should be able to read only whitelisted characters within a specific rectangle by using these options together.

**Comment by Balearica** [comment]
Closing as answered.
