### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by AnotherAnkor** [naptha/tesseract.js#64]
http://www.djvu-soft.narod.ru/scan/twd06.jpg

**Comment by bijection** [comment]
What error are you getting?

**Comment by AnotherAnkor** [comment]
something like this:

пювпшш ь тку Лпи шепни доснгачпо ш „Щ шт, ,„ „мы. грохпчп „ пш- п и-
идиша ют. т ь... пецшчпепсп „шнш ш. 11“ т щшщ .„, „к умри ‚шип эб—
щ идиш непшчп прошпкатвж Теперь} „шик. и. ш бмппышаэ шт...
пени шпиц им. „шиши конина. пусть „и. Ф„,‚„‚‚„ „аи. обл-трлшнпст им.
очень щшю мидиями-ш. ш пижам ш- „щ, и шиш ребенок ибпшорпжпи‘т
ш.“ нише наженбмнилщсьашш. у.» „и. дом» нощно. Ниле улыбпжи ‚о
‘ „мы ышпиии „ш. „мы пихали-кия „„„_з..‚.‚„..ш..‚„ „ими. шт
‘ нм шиш ними. и мы» друзья приказ)"
но т Мглы Зепп „ лад Фиф, мм, а“
.. 0п:\ь.— на м юмрпшп, „ним: мьБ-г н.. ищите то у мшя пищи.
„шиш„натр—„империю. Наип Господи Ушли: ищи и "одним. Пли-ку
лшут ..›югд‚.с„.„одуш.„...щ на. как": ш- д ...‚.. .. “(то я даю мини ш нашили
лишь! Большим пни наймит мшщ пп- км": 1. „ шум, вы" к шунт
ют- и щит. плит, и тира-таи. мы .‚.
‘1 шпал.
в шиш.“ ищ- претшш ибшпшппп .
Поспешит ‚ш. т. п ту мемсхрпитъ „и. „ш ‚. „м при „тиши ппгпий—
Темам ‚шт атшмгпшп. плиоцене-чтит ш лиги-папу. Гении. “и но им при
пива на не „мы ‚ш силою „ шднмош. .‚ „ш ха „ю "пышно „Миш.
Ила/типпспштьраймМПшусхитнппшйн— ЕД???“ „„„‚ „д. и, „типы над ее
ли‚мнительны,путы!работы—плывяншй „им. Тпк как „по о супшцпмпщш
цшыпшъ „ш. Нуд- бы ни пришли. мюпэ' „титр... и, Быев то. шпинпип. .. ною
„и, .. то же. тип Радиации. ищут? тюль шбпющшпшх и „ш, .. „шт
Не „не в ими ‚и „к. .. ионнтщшшшь и. мрпйщ астр/‚кпд.
ш шатре? да. югпл ноне-“ш... хь столь в „они „мы. пппршшпющпп „ем чи-
щдмое обнищание—болиды мм“, „шт; типа шсппшш Туши раскупили
1 "пыли и пили. т тебя.- на прпхпшкки прп— ипртц. м нужен нахацптшшм и. ‚щит.—
шшш и мам Учппшс. Мм щ аира-„ель пои мяты. щтцтшп кит-“списывай
пи. кант пщпршпюыеш'нхбпппптшх „и. инокини“ ‚ю „ш. тмина о нем
кати. сии-томно устал-я. добирать не до— ‚.‚....ь и. “и о.. пчппьамрппчещ „тмин,
и Нет: годами. 0... на сюит Больших „т „мы иеиосюею прибитым. петь
на: в хиам'пиныпшй сущ. ч„‚ стадии „. „ „шт. в „и та... скупит с „мы:
ужпк? Миши шить ‚т. н....„‚. шью юю- „мы могущим им на ш щ» - м—
пм ищи. к“ он: атм. М бит-п в или пыпшшп я и ш.» его. "опиши „щит.
инмпулпсьзд т драил. пппьпппая уж‘ и» ‚и. т. „нуждам... что ‚им. жили,
гит Тибш у-иош обувь Прпшш т. е... пдшщди от: пькпьубежпщ-у ими.
и 55
How you can see it's more different with image.

**Comment by bijection** [comment]
Have you tried increasing your image's resolution?

**Comment by AnotherAnkor** [comment]
What's prefered resolution for image?
I tryed it in your demo random image from network.

**Comment by bijection** [comment]
It works best around 300 dpi.
