### ISSUE TITLE
Use with video element

### ISSUE THREAD

**Issue by trouba** [naptha/tesseract.js#647]
**Describe the bug**
Documentation states [here](https://github.com/naptha/tesseract.js/blob/master/docs/image-format.md) that you can use a video element but the video implementation example uses a canvas. 
I think I saw an implementation with a video source, but I couldn't find it again and every video implementation I saw online uses the frame in canvas approach.

**Expected behavior**
If it's possible to use directly a video element like this for example`worker.recognize(videoElement, {})`, a code example could be added, if not the documentation could be more clear.

**Comment by Balearica** [comment]
It looks like for video inputs the [poster](https://www.w3schools.com/tags/att_video_poster.asp) attribute of the video is recognized, which per W3 is either "an image to be shown while the video is downloading, or until the user hits the play button" or "the first frame of the video".  I don't think this is an intuitive behavior (probably not what most users trying to recognize frames from videos want), and agree that it's misleading to say we support video elements.  Therefore, I think we should remove all claims that tesseract.js supports recognizing video elements from the documentation. 

https://github.com/naptha/tesseract.js/blob/b419e45114dce2719f8e26b188faefd86caca2a1/src/worker/browser/loadImage.js#L50-L52

**Comment by Balearica** [comment]
Closing issue as documentation was edited to remove claim of video element support in #652.
