### ISSUE TITLE
Incorrectly work recognize function in polish language

### ISSUE THREAD

**Issue by I-n-d-e-r** [naptha/tesseract.js#65]
Incorrectly work recognize function in polish language.

**My test image:**

![tess](https://cloud.githubusercontent.com/assets/18102267/19625503/d667722c-991a-11e6-944c-3782528ec2cd.png)

**Tesseract-text (marked with bad words, only a few of the beginning)**

Śród **_takrcn_** pól **_pned_** raty nad brzegrem **_ruczaru_**
Na pagórku _mewrerkrm_, we brzozowym _garu_
**_Sial_** dwór szlachecki, z **_dnewa_**, **_recz_** podmurawany
Śwrecrny się z daleka panrelane ściany
Tym brelsze ze odbrte od cremner zrelem
Tupoh, co gu bronią od wiatrów Jesrem
**Dom mreszkalny ruewrelkr` lecz zewsząd cnęaogrI stodołę mar wrerka` r plzy me] trzy stogr\n\n**

**Tesseract recognize, differs significantly from the text in the image. The letters are converted to the other by what words does unintelligible string.**

![zrzut ekranu z 2016-10-23 12-30-38](https://cloud.githubusercontent.com/assets/18102267/19625573/ab6ef840-991c-11e6-93c3-6d4c735cd7a2.png)

**Comment by bijection** [comment]
You should try increasing the resolution of the image (by scaling it up for example). See the note at https://github.com/naptha/tesseract.js#tesseractrecognizeimage-imagelike-options---tesseractjob
