### ISSUE TITLE
Recent changes are incompatible with NodeJS v12

### ISSUE THREAD

**Issue by storm42** [naptha/tesseract.js#651]
**Describe the bug**
Basic example script execution crashes on NodeJS version 12.18.1

**To Reproduce**
1. Write a script with the first example of the repository's README and load any external image URL
2. Run the script, and it immediately crashes

**Expected behavior**
The result should be the parsed / read strings of the image

**Screenshots**
https://i.imgur.com/wM0jWF8.png

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
The file setImage.js contains this writing : https://i.imgur.com/7bdICSz.png
Which is invalid in nodeJS version 12

**Comment by Balearica** [comment]
Version 3 is incompatible with Node.js v12--this is noted in the [Major Changes in v3](https://github.com/naptha/tesseract.js#major-changes-in-v3) section of the readme as well as the release notes.  Tesseract.js should work on all [supported releases](https://nodejs.org/en/about/releases/) (v12 reached end of life in April 2022).  That being said, if you want to create a PR to make Tesseract.js run on v12 without impacting other versions, I will merge it in.

**Comment by Balearica** [comment]
Closing as this is a documented change rather than a bug.  I am still willing to merge in changes to improve compatibility with other Node.js versions if others are motivated to write them.
