### ISSUE TITLE
Circular references in result

### ISSUE THREAD

**Issue by FranzZemen** [naptha/tesseract.js#67]
Would be awesome if you removed the circular references in the result object.  The references make it impossible to easily convert to a JSON object.

**Comment by FranzZemen** [comment]
This is probably not a tesseract.js itself as its a general forking issue with the child process taking on the parent process arguments, but how do you debug?

**Comment by bijection** [comment]
What part of the response are you trying to convert to json?

**Comment by bijection** [comment]
In general, you can convert serialize parts of the response like this:

```javascript
Tesseract.recognize(img)
.then(function (res){
    var myString = JSON.stringify( res.words.map( function(word){return word.text} ) )
    doSomethingWith( myString )
})
```

or in es6:

```javascript
Tesseract.recognize(img)
.then( res =>
    doSomethingWith( JSON.stringify( res.words.map( word => word.text ) ) ) 
)
```

**Comment by bijection** [comment]
Debugging discussion continues in #66
