### ISSUE TITLE
Trouble distinguishing between `I`s, `l`s, and `|`s.

### ISSUE THREAD

**Issue by buneeIsSlo** [naptha/tesseract.js#674]
On the landing page, the resulting text isn't accurate(`I`s, `l`s, and `|`s specifically) when the image has youtube's font(the font used for comments). Check the screenshots below, the differences have been marked with a red dot.

**Input:** 
![iLight](https://user-images.githubusercontent.com/79749200/192524800-f5781c98-e535-49e0-9993-0a9188dbb306.png) 

**Output:** 
![resLight](https://user-images.githubusercontent.com/79749200/192526176-1cc41e1e-7e82-4bec-b6f0-3002d8fa62c8.png)

The result is even more inaccurate if the screenshot was captured in dark mode.

**Input:**
![iDark](https://user-images.githubusercontent.com/79749200/192530364-d59777ac-b9f2-4647-8eaf-e77cbd47bb67.png)

**Output:**
![resDark](https://user-images.githubusercontent.com/79749200/192530680-8056fdc2-0f76-46ca-a880-6a50d9aef037.png)

**To Reproduce**
1. Screenshot any comment consisting `I, l, |`s on youtube and try it out on the [landing page](https://tesseract.projectnaptha.com/).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 105.0.5195.127

P.S. I don't know how this library works. I apologize if I've missed something.

**Comment by Balearica** [comment]
In your example image all 3 glyphs are virtually identical, and in several cases there is not enough linguistic context to make an educated guess.  For several of these I am not sure which glyphs are which--so it is unsurprising that Tesseract has a hard time telling them apart.  

If you want a quick fix to improve accuracy, I would add `|` to the blacklist given how uncommon that character is. 

`w.setParameters({tessedit_char_blacklist: "|"})`

If you are confident you'll only be using a single font, you can look into creating custom training data using that font.  Documentation would be found from the main Tesseract projects docs--we do not have a guide for how to do this here.

**Comment by buneeIsSlo** [comment]
Thank you for the clarification. I have no personal use case for this at the moment, I just thought I should point it out.
