### ISSUE TITLE
TesseractJS could not load language sometimes and application stops running

### ISSUE THREAD

**Issue by engageaffli** [naptha/tesseract.js#676]
Sometimes tesseract fails to load the worker with the following error "Error opening data file ./eng.traineddata".
If I try to not use woker.terminate , the memory keeps increasing.
Atleast if you provide some function to clear the cache or automatically clear, I can keep the worker running in my server.

I tried to make consecutive requests to the server, but I was not able to replicate. It happens once a while in a day and the server stops since the exception cannot be caught even with try catch block due to issues with tesseract library.
I don't know why this exception occurs since I can't replicate just like that by running a loop. If there a problem reading from harddisk or reading the same data multiple times at the same harddisk location does it occur?
Any async/await not provided in the code?
The exception does not clearly specify when this happens.

Is it possible to clear the cache after recognizing the image since I do not wish to load the worker for every request.
It is fast if I load the worker only once during the application startup but the memory keeps increasing since the worker does not clear cache.

I am using the following code for tesseract in nodejs app

app.post('/ocr', (req, res) => {
    const image_url = req.body.url;
    const worker = createWorker();
    (async () => {
        await worker.load();
        await worker.loadLanguage('eng');
        await worker.initialize('eng');
        const {
            data: {
                text
            }
        } = await worker.recognize(image_url);
        await worker.terminate();
        res.send(text.trim()).end();
    })();
})

Environment
Tesseract Version: 3.0.3
Commit Number:
Platform: Heroku server: Nodejs
Current Behavior:
2022-09-27T07:49:41.746323+00:00 app[web.1]: Error opening data file ./eng.traineddata
2022-09-27T07:49:41.751276+00:00 app[web.1]: Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
2022-09-27T07:49:41.751340+00:00 app[web.1]: Failed loading language 'eng'
2022-09-27T07:49:41.751586+00:00 app[web.1]: Tesseract couldn't load any languages!
2022-09-27T07:49:41.789088+00:00 app[web.1]: node:internal/event_target:969
2022-09-27T07:49:41.789090+00:00 app[web.1]: process.nextTick(() => { throw err; });
2022-09-27T07:49:41.789091+00:00 app[web.1]: ^
2022-09-27T07:49:41.789092+00:00 app[web.1]:
2022-09-27T07:49:41.789092+00:00 app[web.1]: Error: initialization failed
2022-09-27T07:49:41.789092+00:00 app[web.1]: at Worker. (/app/node_modules/tesseract.js/src/createWorker.js:173:15)
2022-09-27T07:49:41.789093+00:00 app[web.1]: at Worker.emit (node:events:513:28)
2022-09-27T07:49:41.789094+00:00 app[web.1]: at MessagePort. (node:internal/worker:233:53)
2022-09-27T07:49:41.789094+00:00 app[web.1]: at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
2022-09-27T07:49:41.789094+00:00 app[web.1]: at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)

Expected Behavior:
There should not be any errors and memory should be as it is when it was initialized after it completes the job. This is a general use case for any application that runs. I don't understand how quality tests are accomplished without this.

Suggested Fix:
Please provide option to clear the cache or automatically free the memory after the recognition is completed.
Try catch block does not work during exceptions due to tesseract and the application stops.

**Comment by rtzm** [comment]
I ran into the same issue with initialization and changing the `cacheMethod` as specified [here](https://github.com/naptha/tesseract.js/issues/398#issuecomment-581127075) prevented the initialization error from appearing for me.

**Comment by engageaffli** [comment]
Thank you cacheMethod "none" works as of now but one of the user mentioned that it did not work for him.  
The issue which I was seeing is intermittent so the exact reason is not known when it occurs and cannot guarantee on the solution. I would like to start the worker only once and keep it running.
The memory in NodeJs App keeps increasing. Does it not automatically clear the memory after the recognize method?
Is there a way to clear the worker memory after it recognizes the image?

**Comment by Balearica** [comment]
@engageaffli It sounds like there are 2 unrelated bugs being discussed here.  First, there is a bug with the language data cache being corrupted, which is reported in many other issues (see #666).  As @rtzm states, this can by bypassed by disabling caching, however doing so will result in the language data being re-downloaded every time it is loaded, which may be undesirable for other reasons.  This bug should be resolved in an upcoming release. 

Second, it sounds like you've experienced a memory leak (i.e. memory not being entirely cleared after each `recognize` operation).  I do not believe there is an open issue for this, however if it does exist we should be able to create a reproducible example (as I have no reason to believe a memory leak would be non-deterministic or dependent on race conditions like the cache issue).  I will look into this now.

**Comment by Balearica** [comment]
@engageaffli I was able to replicate the memory leak issue, and created an issue for that with a reproducible example (see #678).  Users looking to follow progress on the caching bug and memory leak should therefore follow #666 and #678, respectively.

**Comment by Balearica** [comment]
Closing this issue as duplicate (see https://github.com/naptha/tesseract.js/issues/666 and https://github.com/naptha/tesseract.js/issues/678).
