### ISSUE TITLE
Memory leak - Out of memory issue after page refresh

### ISSUE THREAD

**Issue by priamaniv** [naptha/tesseract.js#677]
**Describe the bug**
Noticing a memory leak after OCR is finished and workers are terminated using Tessaract 3.0.3

**To Reproduce**
1. Install tessaract js on your browser
2. After it recognizes the text, terminate the scheduler without await
3. Refresh the page
4. Try step 2- step 3 (x4)
5. Notice it throwing "Out of memory" error

**Expected behavior**
Allow recognizing the text after multiple refreshes

**Screenshots**
<img width="811" alt="image" src="https://user-images.githubusercontent.com/20426542/193921137-067ec264-2327-45d8-a28c-1bb5a716bc78.png"> 

**Smartphone (please complete the following information):**
 - Device iPhone 13 Pro / iOS 16 / Browser Safari version 15.1 (17612.2.9.1.20)

**Comment by priamaniv** [comment]
This is probably what is happening but awaiting a worker to terminate takes a long time and our app refreshes to show refreshed user status 
https://github.com/naptha/tesseract.js/issues/476#issuecomment-775112787

**Comment by Balearica** [comment]
`scheduler.terminate()` is an async method.  Therefore, unless you are waiting for it to run using await (or using some equivalent method to confirm it finished running), it is inaccurate to say that the "workers are terminated".  You should adapt your code to wait until `scheduler.terminate()` finishes running.
