### ISSUE TITLE
worker.recognize memory leak

### ISSUE THREAD

**Issue by Balearica** [naptha/tesseract.js#678]
A memory leak exists in `worker.recognize`.  When the same worker is used for recognizing many files, memory slowly increases, and eventually the program crashes.  To replicate this issue, run the [benchmark.js](https://github.com/naptha/tesseract.js/blob/master/examples/node/benchmark.js) example, except with `i < 10` changed to `i < 100`.  On my system this fails on the 84th recognition job.

**Comment by Balearica** [comment]
I investigated the cause of the memory leak and confirmed that leak is caused by the [setImage](https://github.com/naptha/tesseract.js/blob/master/src/worker-script/utils/setImage.js) function.  Repeatedly running image recognition *without* `setImage` does not cause a memory leak, and repeatedly running `setImage` without recognition does cause a memory leak. 

I was unable to figure out how to adapt the existing code (which creates the image object on the Javascript side) to not have this issue.  However, writing the image to the filesystem and then reading it to a `pix` object on the C++/Webassembly side resolved the issue entirely.  Therefore, pending another user figuring out how to patch the current code, I plan to use this solution.

**Comment by engageaffli** [comment]
@Balearica . Thank you for the update. Could you please let me know if there is any way I can update the code in nodejs server.

Thank you

**Comment by Balearica** [comment]
Closing as this should be resolved in [Version 4](https://github.com/naptha/tesseract.js/releases/tag/v4.0.0).
