### ISSUE TITLE
Bump file-type from 12.4.1 to 16.5.4

### ISSUE THREAD

**Issue by ewrayjohnson** [naptha/tesseract.js#679]
This was never completed merged:  [Bump file-type from 12.4.1 to 16.5.4](https://github.com/naptha/tesseract.js/pull/625)
file-type@13.0.0 introduced breaking changes.

**Comment by Balearica** [comment]
@ewrayjohnson Can you explain this further?  It's not immediately clear what the benefit is, and it looks like you commented on the linked PR that simply bumping the version number is not possible (as it would break Tesseract.js).

**Comment by Balearica** [comment]
Closing as stale.
