### ISSUE TITLE
is it support in expo mobile 

### ISSUE THREAD

**Issue by maksha19** [naptha/tesseract.js#683]
**Is your feature request related to a problem? Please describe.**
i was tried this with exco mobile development.. its throwing error `Can't find variable: document`

**Describe the solution you'd like**
better to support mobile js versions 

**Describe alternatives you've considered**

**Additional context**

**Comment by Balearica** [comment]
Please fill out the entire issue template for bug reports.  This issue does not contain sufficient information for us to do anything.

**Comment by Balearica** [comment]
Closing as incomplete/stale.
