### ISSUE TITLE
Can't recognize text on iPhone, while can on Android phone and Laptop windows 11 

### ISSUE THREAD

**Issue by hotmzc1977** [naptha/tesseract.js#687]
Hi, I built an APP with tesseract.js to recognize the selected area of the camera stream, and it works very well on my OPPO phone and Dell laptop, windows 11 installed. But it can't on my iPhone 11, and the error message is abort(trap!). Build with -s Assertions =1 for more info.

tesseract.js version is the latest, and I am using NPM run start with SSL cert. So I can access the web app from my phone.

below is some of my code written in react.js:
1. get picture from video stream
ctx!.drawImage(videoRef.current,left, top, width, height,                0,                0,                width,                height            );
let newimgUri = previewCanvasRef.current.toDataURL();

2. initialize worker
workerRef.current = Tesseract.createWorker({
            logger: m => {
                console.log(m);
            },
        });
        await workerRef.current.load();
        await workerRef.current.loadLanguage(language);
        await workerRef.current.initialize(language);
3. recognize text from image(base64)
workerRef.current!.recognize(image)
            .then(result => {
                console.log("result", result);
                return { success: true, result };
            })
            .catch(err => {
                console.error("recognize", err);
                return { success: false, error: err };
            });

**Comment by Balearica** [comment]
Can you provide a full reproducible example?  Tesseract.js appears to work (at least sometimes) on iPhone, and the above code snippets are insufficient for allowing us to reproduce this specific error.

**Comment by hotmzc1977** [comment]
It worked after I published it to GitHub pages. thanks for your reply.
this is my repo: https://github.com/hotmzc1977/React-Tesseract-OCR

**Comment by Balearica** [comment]
> It worked after I published it to GitHub pages. 

To clarify, it *does* run when published on GitHub pages?  If this issue is specific to running on your local network, then I don't think I can do anything.  I don't actually own an iPhone, so when I test on different devices it is by publishing to the web using GitHub pages (or similar service), and then accessing through a virtual device on Browserstack.

**Comment by Balearica** [comment]
Closing as it appears this issue was resolved when publishing to web.
