### ISSUE TITLE
Do I need to train / download a training data file or does tesseract.js come with default training data for English out of the box?

### ISSUE THREAD

**Issue by GitMurf** [naptha/tesseract.js#689]
Hi sorry as I know that GH Issues is probably not the best place for this but I spent a ton of time trying to figure out a better place to ask this question or get clarity and have not been able to so I apologize and **thank you in advance** for answers / suggestions to my question here.

The TLDR of my question is whether I need to do anything with training data or downloading some default trained data or if it already comes out of the box with the suggested default training data (for English)?

I saw here (https://github.com/naptha/tesseract.js/blob/master/docs/faq.md#how-does-tesseractjs-download-and-keep-traineddata) the following and wondering if this is required / recommended for node.js implementation? Should I download one of these trained data files manually and include in my project?

> During the downloading of language model, Tesseract.js will first check if *.traineddata already exists. (browser: IndexedDB, Node.js: fs, in the folder you execute the command) If the *.traineddata doesn't exist, it will fetch *.traineddata.gz from tessdata, ungzip and store in IndexedDB or fs, you can delete it manually and it will download again for you.

I read the following from here (https://github.com/tesseract-ocr/tessdoc/blob/main/ImproveQuality.md#improving-the-quality-of-the-output) which sounds like it implies that out of the box tesseract already comes with training data that is going to be better than what you would train yourself?

> There are a variety of reasons you might not get good quality output from Tesseract. It's important to note that, unless you're using a very unusual font or a new language, retraining Tesseract is unlikely to help.

I also came across trained data files listed by the Google team from 2017 like this one and am wondering if this is needed / recommended to add something like this? https://github.com/tesseract-ocr/tessdata_fast

Thanks in advance!

**Comment by Balearica** [comment]
Tesseract.js automatically downloads the appropriate `.traineddata` file from a CDN.  You do not need to download your own.

**Comment by Balearica** [comment]
Closing as answered.
