### ISSUE TITLE
about tesseract.js

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [naptha/tesseract.js#690]
can i understand tesseract.js  is about about its source code.or oter Use tesseract.js the way you like! under contend is use tesseract.js library,because i npm run build in tesseract.js  no about index.html, i don't know how to use in Brower

**Comment by Balearica** [comment]
I don't understand what this means.  Please read our documentation and try the [examples](https://github.com/naptha/tesseract.js/tree/master/examples) to learn how to use Tesseract.js.  If you have a bug report or feature request please fill out the entire issue template.
