### ISSUE TITLE
[Urgent] Responses are shuffled during load when worker is not terminated

### ISSUE THREAD

**Issue by engageaffli** [naptha/tesseract.js#699]
**Describe the bug**

The response for one request goes to the other request. This is a nightmare when doing business in production.
I am using the same worker without terminating it, in order to get the response faster.
I usually use post request in the backend to get the response and was not aware until I made a get request 
through the UI during the load. 
The responses for post request which are different images came to the get request for a complete different type of image. 
This does not happen all the time, so it looks to me it happens during load or during timeout when the image is not retrieved from internet for the existing request.  Something related to asynchronous caching. 

**To Reproduce**
Please find the glitch code, I am using.
You may clone the code to send bulk request to post api and then make a get request from the url.

https://glitch.com/edit/#!/bustling-aeolian-gourd

**Expected behavior**
Every request is unique and has to get the response for that request.

**Additional context**

**Comment by Balearica** [comment]
Thanks you for reporting this issue.  As this was not something encountered in testing, the idea that the previous image is used when an image fails to be retrieved does sound the most plausible.  I will investigate.

**Comment by Balearica** [comment]
I investigated the issue, and was able to replicate.  Whenever you (1) run `worker.recognize` on a valid image and then (2) run `worker.recognize` on an invalid image, it will return the same output both times.  The core issue is that attempting to set an invalid image is not throwing an error.  

I will prioritize implementing a patch, as I agree this is an important issue.

**Comment by Balearica** [comment]
This should be resolved in the latest version (4.0.1).  Starting in that version, running `recognize` or `detect` with an invalid `image` argument will throw an error.  Please let me know if you encounter a similar issue in the latest release.
