### ISSUE TITLE
Cannot work on IOS version 14.4

### ISSUE THREAD

**Issue by hieunguyen2211** [naptha/tesseract.js#701]
**Describe the bug**
After upgrading tesseract.js to version 4.0.0, it cannot work as expected on IOS version 14.4. The system throws an error, which is described below:

_Unhandled Promise Rejection: RuntimeError: Aborted(CompileError: WebAssembly.Module doesn't parse at byte 11942: invalid section). Build with -sASSERTIONS for more info. (evaluating 'new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.")')_ 

We tried to use the latest version (4.0.1) but the issue is still there.

**To Reproduce**
1. Run tesseract.js on IOS version 14.4
2. See the error on console tab

**Expected behavior**
Everything should work as expected and there is no error occurred.

**Screenshots**
<img width="1048" alt="Screen Shot 2022-12-14 at 17 15 09" src="https://user-images.githubusercontent.com/52429592/208016980-e2ac2fb4-1a3a-495f-8cd3-3568a7c983c3.png">

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: IOS 14.4
 - Browser: Safari, Chrome
 - Version: Safari version 14.4, Chrome version 108.0.5359.52

**Comment by hieunguyen2211** [comment]
After debugging, the error is thrown when trying to use `createWorker` function.

**Comment by hieunguyen2211** [comment]
Besides that, the error handling cannot work to catch this error. I found the root cause is that inside `worker-script/index.js`, the function `load` has not been implemented with any try-catch blocks.

![Screen Shot 2022-12-16 at 14 13 33](https://user-images.githubusercontent.com/52429592/208043287-38006e5b-98fd-4cad-a74d-314d17c71e6c.png)

**Comment by Balearica** [comment]
Thank you for this bug report.  I was able to replicate this error on iOS 14.  It does not appear to occur on iOS 15 or 16.  I will investigate what could be causing this. 

One follow-up question:  you mentioned that you updated to Tesseract.js v4.  What was the version you were previously running (that presumably did not have this issue)?

**Comment by Balearica** [comment]
This should be resolved by the latest release (4.0.2).  Let me know if you continue to experience this issue.

**Comment by hieunguyen2211** [comment]
I used tesseract.js version 2.1.2 before upgrading to v4. Thanks a lot for considering this bug.
