### ISSUE TITLE
Getting TypeError while executing a simple text recognition script using Node.js

### ISSUE THREAD

**Issue by mykola-mokhnach** [naptha/tesseract.js#702]
**Describe the bug**
The module always throws a cryptic error message that looks like 

```
RuntimeError: abort(TypeError: Failed to parse URL from /Users/elf/code/appium/packages/ocr-plugin/node_modules/tesseract.js-core/tesseract-core.wasm). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/Users/elf/code/appium/packages/ocr-plugin/node_modules/tesseract.js-core/tesseract-core.js:9:14685)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

when I try to perform a standard image recognition flow. 
I can observe the exception happens right on `await worker.load()` call. The logs show:
```
>>> before load
dbug Plugin [OcrPlugin] {"status":"loading tesseract core","progress":0}
dbug Plugin [OcrPlugin] {"status":"loaded tesseract core","progress":1}
dbug Plugin [OcrPlugin] {"workerId":"Worker-0-03313","status":"initializing tesseract","progress":0}
(node:41790) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Failed to parse URL from /Users/elf/code/appium/packages/ocr-plugin/node_modules/tesseract.js-core/tesseract-core.wasm
TypeError: Failed to parse URL from /Users/elf/code/appium/packages/ocr-plugin/node_modules/tesseract.js-core/tesseract-core.wasm
/Users/elf/code/appium/packages/ocr-plugin/node_modules/tesseract.js-core/tesseract-core.js:9
var Module=typeof TesseractCoreWASM!=="undefined"...
```
Perhaps, this happens because I run it on M1 Mac?

**To Reproduce**
1. Check out https://github.com/mykola-mokhnach/appium/tree/ocr_plugin
2. Run `npm i` in the root folder
3. Open `cd packages/ocr-plugin`
4. Start `npm run test:unit` to execute the unit test https://github.com/mykola-mokhnach/appium/blob/ocr_plugin/packages/ocr-plugin/test/unit/plugin.spec.js

**Expected behavior**
The test should pass.

**Desktop (please complete the following information):**
 - OS: macOS 13.0
 - Browser Node.js 
 - Version 18.11.0

**Comment by mykola-mokhnach** [comment]
It looks like the issue lies in node.js version. After downgrading to node v16.19.0 the problem is gone.

**Comment by Balearica** [comment]
I confirmed that all of our tests run properly using Node 18.  Let me know if you can provide a standalone snippet that runs in Node 16 but not Node 18, however otherwise I'm going to assume the issue is specific to your project or a dependency you using.

If the issue is specific to a dependency you are using, I am open to merging in changes to improve compatibility, however that's outside the scope of things I can investigate personally.

**Comment by mykola-mokhnach** [comment]
Thanks for checking it.
Unfortunately I cannot provide more insights on this issue. Maybe it's really specific to my env 🤷

**Comment by bilalabesat** [comment]
i am having same issue. using node 18 i get below error. but with node 16 i don't see any error and it works fine
TypeError: Failed to parse URL from /app/node_modules/tesseract.js-core/tesseract-core.wasm
TypeError: Failed to parse URL from /app/node_modules/tesseract.js-core/tesseract-core.wasm
details error in  [tesseract_log.txt](https://github.com/naptha/tesseract.js/files/10727450/tesseract_log.txt)
