### ISSUE TITLE
Exposing the character classifier 

### ISSUE THREAD

**Issue by Nomlax** [naptha/tesseract.js#703]
I have a very niche use case where I want to recognize one-letter characters or symbols. 

As my understanding of OCR goes, once lines are isolated, characters are isolated and then the isolated characters are passed through a character classifier. 

Right now, passing the single characters through normal Tesseract mistakes a single isolated character for multiple different characters in the same image, or detect lines in a way that breaks the character classifier. 

Example:
![chrome_37q8KBt02d](https://user-images.githubusercontent.com/73515313/209300167-0400f939-c48e-4096-b413-e8f4f48050ca.png): gives the correct result of "testing, testing,"
![chrome_YAkhaSuTpv](https://user-images.githubusercontent.com/73515313/209300311-d7241097-ab0a-45b5-9219-0c63cfdb88e4.png): gives the result "Bl" presumably from the line detection or character isolation

![image](https://user-images.githubusercontent.com/73515313/209300540-7bc0c548-4f05-4847-b5b1-8225998d60d0.png)

Would it be possible to expose the character classification portion of Tesseract and skip the other portions?

**Comment by Balearica** [comment]
If you want Tesseract tell you "what single character does this image look closest to" you can do that by setting `oem` to `0` (enabling the legacy model) and `psm` to `10` (assume single character).  

```
      const worker = await Tesseract.createWorker();
      await worker.loadLanguage('eng');
      await worker.initialize('eng', "0");
      await worker.setParameters({tessedit_pageseg_mode: "10"});
      const ret = await worker.recognize(files[0]);
      console.log(ret.data.text);
```

Note that this still results in an incorrect result for your sample image: the comma is misidentified as `)`.  This is to be expected.  Single character identification is poor with ambiguous characters as Tesseract relies on context to get these right (e.g.  `,` vs `’` vs `)`, `l` vs `1`, `O` vs `0`).

**Comment by Balearica** [comment]
Closing as answered.
