### ISSUE TITLE
Error in PixCreateNoInit: pixdata_malloc fail for data

### ISSUE THREAD

**Issue by jasondalycan** [naptha/tesseract.js#704]
When processing an image of 3k x 4k pixels I'm receiving the following error: 

```
Error in pixCreateNoInit: pixdata_malloc fail for data
node:internal/event_target:1011
   process.nextTick(()=> { throw err; });

Error: RuntimeError: null function or function signature mismatch
   at Worker.<anonymous> (/usr/src/app/node_modules/tesseract.js/src/createWorker.js:173:15)
...
```

This occurs with Tesseract.js 3.0.2 on Node.js 16.15.1 on Debian 11 inside Docker.  This only appears to happen for large images.  Do you know how to resolve this?

**Comment by jasondalycan** [comment]
I just tried on Windows 10 (same Node version) and got the same error:

```
Error in pixCreateNoInit: pixdata_malloc fail for data
Error in pixCreateTemplateNoInit: pixd not made
Error in pixCreateTemplate: pixd not made
Error in pixCopy: pixd not made
Error in pixGetData: pix not defined
Error in pixGetWpl: pix not defined
Error in pixSetSpp: pix not defined
Error in pixCopy: pixs not defined
Error in pixCreateNoInit: pixdata_malloc fail for data
node:internal/event_target:912
  process.nextTick(() => { throw err; });
                           ^
Error: RuntimeError: memory access out of bounds
    at Worker.<anonymous> (C:\development\app\node_modules\tesseract.js\src\createWorker.js:173:15)
```

**Comment by jasondalycan** [comment]
More info, this seems to happen when the same `Worker `is reused multiple times.  Perhaps there is memory cleanup that's required to avoid this issue?

**Comment by Balearica** [comment]
Given your messages above, it sounds like this bug only occurs under certain circumstances (i.e. simply recognizing a single 3000x4000 image may not cause this bug).  Can you please add reproducible example code that can be run to reproduce this error message? 

Additionally, can you confirm whether this bug exists using the latest version of Tesseract.js (currently `4.0.2`)?

**Comment by Balearica** [comment]
Closing as stale.
