### ISSUE TITLE
Can't correctly read simple text

### ISSUE THREAD

**Issue by ohenepee** [naptha/tesseract.js#705]
**Describe the bug**
Its either I am doing something wrong or tesseract can't correctly read some simple things. I can't seem to read the number 9 if its the starting character in a text/line. I also can't seem to read the text 5.11x. I've been banging my on this issue for days now.

**To Reproduce**
Take these images and use in the code below
![LessThanOne-2022-12-01T03:43:40 920Z](https://user-images.githubusercontent.com/15159487/210194667-6776a037-ade3-4dbf-a0eb-749616ea430d.png)
![LessThanOne-2022-12-01T06:50:20 185Z](https://user-images.githubusercontent.com/15159487/210194670-16e4ac2d-44cd-46ed-86a5-945a50ced4fc.png)
![LessThanOne-2022-12-01T03:27:51 137Z](https://user-images.githubusercontent.com/15159487/210194671-56fef039-67fd-4197-ac2a-aa7e8d3f0839.png)
![123](https://user-images.githubusercontent.com/15159487/210194741-b81bc8b5-580b-4061-a8b7-f888fb630d7e.png)

```js
const sharp = require("sharp");
const { createWorker } = require("tesseract.js");

(async () => {
  const worker = await createWorker();
  await worker.loadLanguage("eng");
  await worker.initialize("eng");
  await worker.setParameters({
    tessedit_ocr_engine_mode: 1, 
    tessedit_pageseg_mode: 13, 
    tessedit_char_whitelist: "0123456789x"
  });

  let buf = await sharp(file).toBuffer();
  let result = await worker.recognize(buf);
  console.log(result.data.text.trim());
})();
```
9.69x read as 0.69x
9.50x reads as 0.50x
9.24x reads as 0.24x
5.11x reads as 511x

**Desktop:**
 - OS: Linux Mint 21
 - Node Version: 18.10.0
- Tesseract.js Version: 4.0.2

**Additional context**
I've tried downscaling the images to no avail.

**Comment by Balearica** [comment]
Running with different settings should resolve.  The Legacy model (oem 0) is going to outperform the LSTM model (oem 1) here, as you have high-quality characters but non-dictionary words.  (The Legacy model works by recognizing the shape of each individual letter--the results it produces are generally more intuitive [although not necessarily correct]).  Using the settings below Tesseract correctly identified all of your examples. 

```
(async () => {
  const worker = await createWorker();
  await worker.loadLanguage("eng");
  await worker.initialize("eng", 0);
  await worker.setParameters({
    tessedit_char_whitelist: "0123456789x."
  });

  let result = await worker.recognize(file);
  console.log(result.data.text.trim());
})();

```

**Comment by ohenepee** [comment]
Thanks a lot, that worked... but now my app is behaving funny, freezing here and there, wasn't so without the legacy model. But as long as I can read tye texts I consider this issue solved. However if you have any solution for the hangings and freezing I'd help.

**Comment by Balearica** [comment]
I am not aware of any issue with the legacy model freezing (in fact, in my experience it was almost always faster).  If you have a specific image that consistently causes this issue we can look into it, however if it truly is caused by the internals of the recognition model that is probably outside of the scope of this repo.

**Comment by ohenepee** [comment]
Thanks a lot @Balearica, I've fixed it, it was a bug in my code which I introduced around the same time I changed to the legacy mode.
