### ISSUE TITLE
Font type not recognized?

### ISSUE THREAD

**Issue by tahayassine** [naptha/tesseract.js#715]
I made several tests to recognize the text and the font in several images.  The text is well recognized, but the type of the font never has any. I would like to know if I did something wrong or it is normal. Here is my code:

```
async (rectangle: Rectangle, image: string): Promise<Font[]> => {
  const worker = await createWorker();

  await worker.loadLanguage('eng');
  await worker.initialize('eng');
  const result = await worker.recognize(image, { rectangle });

  let fonts: Array<Font> = [];
  if (
    result &&
    result.data &&
    result.data.blocks &&
    result.data.blocks.length > 0
  ) {
    if (result.data.words) {
      for (const word of result.data.words) {
        console.log('word', word);

        let font: Font = {
          id: word.font_id,
          name: word.font_name,
          size: word.font_size,
          isSmallcamps: word.is_smallcaps,
          isBold: word.is_bold,
          isItalic: word.is_italic,
          isUnderline: word.is_underlined,
          isMonospace: word.is_monospace,
          isSerif: word.is_serif,
        };
        fonts = [...fonts, font];
      }
    }

    console.log(fonts);
    return fonts;
  }
```

**Comment by Balearica** [comment]
Font identification only exists for the legacy model (oem mode 0).
  
```
await worker.initialize("eng", 0);
```

Unfortunately, even within the legacy model, the feature returns completely inaccurate results, especially when using default settings.  I have gotten Tesseract to correctly identify sans vs. serif fonts with different configuration settings, however if you're hoping to identify specific fonts (e.g. Georgia vs. Times New Roman) that isn't something Tesseract is capable of.

**Comment by Balearica** [comment]
Closing as answered.
