### ISSUE TITLE
Regression after 1.0.10

### ISSUE THREAD

**Issue by ckuetbach** [naptha/tesseract.js#72]
If I use the HTML #68 and change the version to 1.0.10 everything works.

If I change it to the actual buildversion (from HEAD), I get the message "tesseract.dev.js:89 Uncaught DataCloneError: Failed to execute 'postMessage' on 'Worker': An object could not be cloned."

I had to change the buildfiles because of #70 and #71, but I think this issue is not be a problem in the buildprocess. Neither dev nor release builds are working.

**Comment by bijection** [comment]
Should be working now
