### ISSUE TITLE
/dist/tesseract.dev.js

### ISSUE THREAD

**Issue by Roboxkin** [naptha/tesseract.js#720]
In the examples, the path to this script is everywhere, where can I get it?

**Comment by Balearica** [comment]
To create the development versions of the scripts (suffix `.dev.js`), please follow the instructions in the readme on [running a development server](https://github.com/naptha/tesseract.js#development).  If you wish to use the non-development versions (suffix `.min.js`), including those hosted on CDNs, you should change the file paths.
