### ISSUE TITLE
Deprecated dependencies warning

### ISSUE THREAD

**Issue by rr3khan** [naptha/tesseract.js#725]
**Describe the bug**
Some packages that are used are deprecated.
Specifically:
- resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
- babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.

**To Reproduce**
1. Run 'npm install tesseract.js'
2. Observe terminal output

**Expected behavior**
No deprecation warnings

**Screenshots**
<img width="901" alt="Screenshot 2023-04-01 at 11 13 57 AM" src="https://user-images.githubusercontent.com/65298773/229297693-963bca3d-389a-43cc-a915-376b5b5d6e9c.png">

**Desktop**
 - OS: MacOS Ventura 13.2.1

**Comment by Balearica** [comment]
Both of these dependencies were removed in the [v4.1.0](https://github.com/naptha/tesseract.js/releases/tag/v4.1.0) release.
