### ISSUE TITLE
Alternative CDN or self hosting

### ISSUE THREAD

**Issue by CodingPeak** [naptha/tesseract.js#727]
Yesterday unpkg CDN was down. Can you provide a version that doesn't rely on unpkg's availability? Is it possible to host the javascript files ourselves?

**Comment by Peyman-Borhani** [comment]
@CodingPeak   I tried multiple ways of importing, it all works, so I download the latest ".min.js" file mentioned in Installation - CDN, and directly use it in my code.

**Comment by Balearica** [comment]
The use of `unpkg` is just a result of using the default arguments.  You can host everything yourself--this is explained [here](https://github.com/naptha/tesseract.js/blob/master/docs/local-installation.md).  

In short, the 3 relevant arguments are `workerPath`, `langPath`, and `corePath`.  By default these are set to fetch code/data from `unpkg`, however you can change them to anything else (including a location on your site you are hosting them).

**Comment by CodingPeak** [comment]
I believe this requires having a nodejs environment, which I don't want to set up. Is the re no way to just download the required files? A built version of the files? Most projects have a dist folder, but can't find that here. I don't want to be dependent on the availability of a CDN.

**Comment by Balearica** [comment]
You can just download the files once from the CDN (the paths are specified in the article I linked) and host them yourself.  For example the current version of `worker.min.js` is here: https://unpkg.com/tesseract.js@v4.0.3/dist/worker.min.js.
