### ISSUE TITLE
Warning: Parameter not found: textord_tabfind_vertical_horizontal_mix

### ISSUE THREAD

**Issue by dawadam** [naptha/tesseract.js#728]
**Describe the bug**
I'm using **jpn** language and a warning appear.
How to configure this parameter to specify the direction of the lines?
Because this warning appears :

`Warning: Parameter not found: textord_tabfind_vertical_horizontal_mix`

**To Reproduce**
```
import fs from 'fs'
import { createWorker } from 'tesseract.js';

// in async function [...]

const sourceFolder = './resources/jpn-book/'

const worker = await createWorker();
await worker.loadLanguage('jpn');
await worker.initialize('jpn');
// parametres
await worker.setParameters({
    // 'textord_tabfind_vertical_horizontal_mix': '?'
})

const sourcePageNum = 2

const buf = fs.readFileSync(sourceFolder + sourcePageNum)
const result = await worker.recognize(buf);
```

**Expected behavior**
The warning appears, how to hide?
How to configure the direction of the line, specific in Japanese?

**Desktop (please complete the following information):**
 - OS: linux
 - Browser : node
 - Version 4.0.3

**Comment by Balearica** [comment]
It looks like the `textord_tabfind_vertical_horizontal_mix` parameter you are trying to set does not exist.  Searching in the repo for Tesseract shows this option was [depreciated in 2015](https://github.com/tesseract-ocr/tesseract/commit/0e868ef377103c448cfe58d873957f966a53ce28) and [removed in 2018](https://github.com/tesseract-ocr/tesseract/pull/1418).  The current version of Tesseract.js uses Tesseract 5.3.0, which was released in 2022. 

I do not know what configuration options accomplish what you are trying to do, but would advise checking the documentation for the [main Tesseract project](https://github.com/tesseract-ocr/tesseract).  This repo is strictly for the web port of Tesseract, so we do not maintain documentation on the options that Tesseract supports.

**Comment by dawadam** [comment]
I am not trying to use this parameter, the message appears even though I am not using any parameter.
I am just implementing the Japanese data.
Okay, I will check the other repository, the main one.

**Comment by Balearica** [comment]
Gotcha.  In general, whenever users report bugs of this nature we need to confirm whether this behavior is specific to Tesseract.js or it is a bug with the desktop/CLI version of Tesseract.  Therefore, you should confirm whether the behavior you describe occurs using the desktop version of Tesseract (when run with an equivalent version + configuration settings).  If the bug only occurs with Tesseract.js, then it may be a bug in this repo and we should investigate further.  If the bug also occurs with Tesseract, then fixing is outside of the scope of this repo (as we do not edit the Tesseract recognition engine).

**Comment by Balearica** [comment]
Closing this issue on the presumption that this behavior is not specific to Tesseract.js.  If you investigate further and find that this only occurs in Tesseract.js (and not Tesseract) we can re-open.

**Comment by ve3** [comment]
I have error like this: _Parameter not found: segsearch_max_futile_classifications_ but it's come from **tesseract-core-simd-lstm.wasm.js:31:307**

So, it isn't from Tesseract.js correct?
