### ISSUE TITLE
How can I mark/highlight/get coordinates of the recognized text? 

### ISSUE THREAD

**Issue by ararTP** [naptha/tesseract.js#738]
I don't know if it's a feature request or this feature exists, because it seems possible here:
![image](https://user-images.githubusercontent.com/77303253/232592599-f4ccc948-d1ec-411d-a8ef-27507e0503bf.png) [src](https://github.com/naptha/tesseract.js)
Is there a way to get the recognized words coordinates in an image like shown?  (I want to be able to know their coordinates and highlight them)

Thanks.

**Comment by Balearica** [comment]
Tesseract.js supports many formats of output data.  Multiple output formats that include coordinates.  How to specify output formats is described [here](https://github.com/naptha/tesseract.js/blob/master/docs/api.md#workerrecognizeimage-options-jobid-promise).  A full list of output formats can be found [here](https://github.com/naptha/tesseract.js/blob/9e074655e25505f0cd88bb3eeb0561cae88752bc/src/index.d.ts#L70-L83).  

If you are writing a JavaScript program from scratch, the `blocks` format is likely the most useful.  It returns a JavaScript object with word text, coordinates, confidence scores, and other information.

**Comment by ararTP** [comment]
Thanks @Balearica  

For any reader in the future, I have made this simple function to convert an `hocr` to easy to use array:

**`hocr_to_array.mjs`**
```
import fs from 'fs';
import * as cheerio from 'cheerio';

function hocrFileToArray(path){
    return hocrTextToArray(fs.readFileSync(path, 'utf-8'));
}

function hocrTextToArray(hocr){
    const output = [];

    // parse the HOCR file using Cheerio
    const $ = cheerio.load(hocr);

    // extract the line elements from the HOCR file and iterate through them
    const lines = $('span.ocr_line');

    lines.each((i, line) => {
        var lineText = "";
        
        // extract the bounding box coordinates
        const bbox = $(line).attr('title').split(';')[0].split('bbox ')[1].split(' ');
        const [x0, y0, x1, y1] = bbox.map(Number);
        
        // extract the word elements from the line and iterate through them
        const wordsInLine = [];
        const words = $(line).find('span.ocrx_word');
        
        words.each((j, word) => {
            
            // extract the word text
            const wordText = $(word).text().trim();

            lineText+=wordText;
            if (j === words.length - 1) lineText+='\n';
            else lineText+=' ';

            // extract the word bounding box coordinates
            const wordBbox = $(word).attr('title').split(';')[0].split('bbox ')[1].split(' ');
            const [wordX0, wordY0, wordX1, wordY1] = wordBbox.map(Number);
            wordsInLine.push({
                text:wordText,
                box: {left:wordX0, top:wordY0, right:wordX1, bottom:wordY1,width:(wordX1-wordX0),height:(wordY1-wordY0) }
            })
            
        });
        output.push({
            text:lineText,
            box: { left:x0, top:y0, right:x1, bottom:y1,width:(x1-x0),height:(y1-y0) },
            words:wordsInLine
        });
    });
    return output;
}
export {hocrFileToArray,hocrTextToArray}
 
```

usage:

```
import { hocrTextToArray,hocrFileToArray } from './hocr_to_array.mjs'

console.log(hocrFileToArray(filePath));
console.log(hocrTextToArray(hocrText));
```

**Comment by Balearica** [comment]
Thanks for explaining how you were able to resolve.  Closing as completed.
