### ISSUE TITLE
NOT an issue: Custom fonts question

### ISSUE THREAD

**Issue by kabus202** [naptha/tesseract.js#75]
I was wondering if it is possible to use this with custom font's.

For example.  

I have image with this font: 

http://www.dafont.com/kenteken.font

so the 1 looks almost like an I,  is it possible to customize the font, so it will recognize it completly?

**Comment by oscarjlep** [comment]
I'm also interested on hearing how this could be accomplished. I'm having a problem reading numbers from car's driving panel, as the digits have small spaces between parts of font (as is common in matrix-style displays). I could create example jpg/tif etc of those digits for Tesseract, but how can I use that file for matching?

**Comment by NoobDoesMC** [comment]
I'd also like to know. I'm trying to OCR minecraft screenshots.

I saw [this](https://github.com/tesseract-ocr/tesseract/wiki/Fonts) on the tesseract-our repository, can we use something like that in tesseract.js?

**Comment by jeromewu** [comment]
tesseract.js can use traineddata from tesseract-ocr directly without any modification, as long as you can have the right traineddata, I think you can achieve recognition for custom fonts.

And right now we don't add any support for the training phase, please use tesseract-ocr to do the training.
