### ISSUE TITLE
tesseract.js not recognizing picture in an PWA App

### ISSUE THREAD

**Issue by nickcernean** [naptha/tesseract.js#755]
I have a SAPUI5 web application I'm currently working on, the app requires an OCR feature.
The basic flow is:
1. Choose picture:
   a) From gallery (PNG, JPG, JPEG, HEIF)
   b) Take a picture (PNG, JPG, JPEG, HEIF)
2. Analyses the picture and returns the text.
The flow 1.b does not work at all on both iPhone and Android devices
And the flow 1.a seems to fail whenever I'm choosing a photo from gallery that is in HEIF format.
However, as I was debugging , I noticed that the HEIF format picture seems to work whenever I run the app in browser and trying to retrieve the text from a picture.

This is my implementation, including some potential solutions found on stackoverflow and github issues.

```
 that.getView()
  .getController()
  .readOcr(imageData)
  .then(function (result) {
      onDeviceReadySuccess(result);
   })
  .catch(function (error) {
      onDeviceReadyFail(error);
   });
```

The "**imagedata**" argument is the value that "**readFile**" function resolves.

```
readOcr: function (imageUrl) {
          return new Promise(async function (resolve, reject) {
            const { createWorker } = Tesseract;

            const worker = await createWorker({
              langPath: "../libs/assets",
              logger: (m) => console.log(m)
            });
            worker
              .loadLanguage("eng")
              .then(() => worker.initialize("eng"))
              .then(() => worker.recognize(imageUrl))
              .then(({ data: { text } }) => {
                resolve(text);
                worker.terminate();
              })
              .catch((error) => {
                reject(error);
                worker.terminate();
              });
          });
        }

```

[The result the readOcr is the following one, some random text:](https://i.stack.imgur.com/U0ael.png). </br>
[The tesseract debugger when processing the image returns this message. ](https://i.stack.imgur.com/J1W58.png)

```
readFile: function (file) {
          return new Promise(function (resolve, reject) {
            var reader = new FileReader();
            
            var img = new Image();

            reader.onload = function () {
              resolve(reader.result);
              img.onload = function () {

                const canvas = document.createElement("canvas");
                const ctx = canvas.getContext("2d");

                ctx.imageSmoothingQuality = "high";

                canvas.width = img.width;
                canvas.height = img.height;

                ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

                const pngDataUrl = canvas.toDataURL("image/png");
                resolve(pngDataUrl);
              };
              img.onerror = function () {
                reject(new Error("Failed to load image"));
              };
              img.src = reader.result;
            };
            reader.onerror = function () {
              reject(reader.error);
            };
            reader.readAsDataURL(file);
          });
        },
```

Tried to convert the image to base64 / png image, did not give any result.

```
var reader = new FileReader();
var img = new Image();

reader.onload = function () {
 resolve(reader.result);
 img.onload = function () {

 const canvas = document.createElement("canvas");
 const ctx = canvas.getContext("2d");

 ctx.imageSmoothingQuality = "high";

 canvas.width = img.width;
 canvas.height = img.height;

 ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

 const pngDataUrl = canvas.toDataURL("image/png");
 resolve(pngDataUrl);
};
 img.onerror = function () {
 reject(new Error("Failed to load image"));
};
 img.src = reader.result;
};

```
So at this point I am considering any help, since could not found a solution that will suit me. It is either the library which causes these issues or there is something wrong in my code. And, yes this issue is posted stackoverflow.

**Comment by Balearica** [comment]
Please provide the version of Tesseract.js you are using in any bug reports. 

From your description, it is unclear whether this is an issue with Tesseract.js or some other aspect of your app.  To clarify, are you able to provide an example image that fails to be recognized properly when run in the browser (whether on a desktop or mobile device)?

**Comment by nickcernean** [comment]
The version I am using is "tesseract.js": "^4.0.3".
The photo I was using is
![Ids](https://github.com/naptha/tesseract.js/assets/38768779/b9b8475a-b803-49f5-b190-58ef5e1a5b5d)
Perhaps, none of the photos seem to work.
The only one that worked was this one, the one from the main page of the library.
![Main ](https://github.com/naptha/tesseract.js/assets/38768779/02685c9d-d006-4905-a855-a5b63805d2c1)

**Comment by Balearica** [comment]
I ran the first image you provided in one of our [examples](https://github.com/naptha/tesseract.js/blob/master/examples/browser/basic-efficient.html), and it produced the following. 

```
MRX-5312-SA1241
KRL-2137-SQ7753

APD-4122-SL9755|
```

Unless there is a valid image you can provide that does not function with our minimal example code, I do not think the issue is with Tesseract.js but with some other aspect of your project.
