### ISSUE TITLE
Update to latest tesseract then V8 platform used by this instance of Node does not support creating Workers

### ISSUE THREAD

**Issue by lincdh** [naptha/tesseract.js#756]
**Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)**
v4.0.5

**Describe the bug**
On tesseract v2.1.5 everything works correctly. Once updated to v4.0.5 this error happens.

![Screenshot 2023-05-10 at 21 58 33](https://github.com/naptha/tesseract.js/assets/21136244/894454a0-e48f-4bbd-9cbf-6e10f62d4ddc)

**To Reproduce**

Try this code:

```
const worker = await createWorker({
  logger: m => console.log(m)
});
```

**Expected behavior**
Latest version should work without error just like the v2.1.5 version.

**Device Version:**
 - OS + Version: Macbook Pro 14 2021 + MacOS 13
 - ElectronJS v21.4.4, NodeJS v14.16.1

**Comment by Balearica** [comment]
It sounds like you are trying to use the Node version of Tesseract.js for Electron, which will not work.  You should use the browser version of Tesseract.js.

**Comment by lincdh** [comment]
I'm thinking of using the browser version.

Can I set a local lang traineddata path like the node version?

I don't the doc and example having it specified?

**Comment by Balearica** [comment]
For the browser version, to avoid using any remote CDN you would need to specify `langPath`, `workerPath`, and `corePath`.  This is explained [here](https://github.com/naptha/tesseract.js/blob/master/docs/local-installation.md).  This is different from the Node version where you only need to specify `langPath` (as `Tesseract.js-core` is automatically installed by npm and all code is run from `node_modules`).

In general, the browser version will not have direct access to the local filesystem (this is true of all browser-based code), so running the browser examples locally still requires using a local http server.  I have not used Electron personally, so am not immediately sure what that would look like within an Electron context.

**Comment by Balearica** [comment]
Thinking about this more, presumably to have everything local in Electron it would be read from the local filesystem from some Electron-provided function, and then passed to Tesseract.js as an arraybuffer.  Let me know if that sounds right.  I would need to think about whether that is currently possible or if it would require an update to Tesseract.js.

**Comment by Balearica** [comment]
@lincdh I found it was possible to use Tesseract.js fully offline (including local `.traineddata`) in Electron.  I added an example to [this repo](https://github.com/Balearica/tesseract.js-electron).

**Comment by Balearica** [comment]
Closing as completed, as a fully offline example of Tesseract.js v4.0.5 running on Electron has been provided.
