### ISSUE TITLE
Running tesseract.js in Next.js 13 ?

### ISSUE THREAD

**Issue by Cliff-R-K** [naptha/tesseract.js#772]
I tried the examplecode in a regular node.js app without problems. But when trying the same in a next.js 13 app I get this error using the same code:

`error uncaughtException: Error: Cannot find module 'C:\Dev\waterflow\.next\worker-script\node\index.js'`

How do I fix this ?

**Comment by Balearica** [comment]
Please provide a reproducible example repo along with any instructions required to run.

**Comment by Balearica** [comment]
Closing for now, will reopen if a reproducible example is provided.
