### ISSUE TITLE
npm fails in windows

### ISSUE THREAD

**Issue by hanzichi** [naptha/tesseract.js#78]
The errors:

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\R
oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "tesseract.js" "--sav
e"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.5

npm ERR! shasum check failed for C:\Users\username\AppData\Local\Temp\npm-21224-988b
a5b0\registry.npmjs.org\tesseract.js-core\-\tesseract.js-core-1.0.2.tgz
npm ERR! Expected: 1ce33a29dc812357b8356a30ededf8b188043b37
npm ERR! Actual:   02453a5ef70f2ef3ec37af6e3467cd5c351e77e6
npm ERR! From:     https://registry.npmjs.org/tesseract.js-core/-/tesseract.js-c
ore-1.0.2.tgz
```

and my Node.js is v7.0.0

**Comment by hanzichi** [comment]
errr, anyone?

**Comment by wanipook** [comment]
me too, my Node.js is v6.9.1 and my npm is v3.10.8 
error is 
 `45 error Windows_NT 6.1.7601
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "tesseract.js" "--save"
47 error node v6.9.1
48 error npm  v3.10.8
49 error code ENOSELF
50 error Refusing to install tesseract.js as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>`

**Comment by hanzichi** [comment]
@wanipook I think `npm install tesseract.js` is enough

**Comment by eterna2** [comment]
might wanna clear ur npm cache and reinstall again.

it is a checksum mismatch = corrupted download or trojon

**Comment by hanzichi** [comment]
@eterna2 when I run `npm cache clean`, I come across almost the same problem, what's the matter?

**Comment by hanzichi** [comment]
@eterna2 well, it's Ok to install when run `npm cache clean`! Thanks a lot!

@wanipook FYI
