### ISSUE TITLE
tesseract using all of the browser memory

### ISSUE THREAD

**Issue by TricksterCode210** [naptha/tesseract.js#780]
**Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)**
Tesseract.js version: 4.1.0

**Describe the bug**
I have an issue with tesseract that it is using all of the browser memory. Every time I upload an image to my program, it is going to consume at least 1GB RAM, but when I reload the page all of that usage will be gone. How can i prevent that? I'm new to React but I don't know if I'm using it incorrectly or that's a bug. Please help me with that issue.

**To Reproduce**
1. Press 'Töltse fel a fájlt' button (It is in hungarian)
2. Wait until it is showing the ocr result
3. Take a look at the browser RAM usage

Please attach any input image required to replicate this behavior.
Watch the localhost:3000
1st picture
![image](https://github.com/naptha/tesseract.js/assets/84982671/42b14ec9-39ef-4b91-8516-5d08c74daf22)
2nd picture
![image](https://github.com/naptha/tesseract.js/assets/84982671/528bd642-736a-4198-8382-095d4839376a)
3rd picture
![image](https://github.com/naptha/tesseract.js/assets/84982671/11376b18-ec5a-420f-a72c-54cba0e06d3d)

**Expected behavior**
It should not use that much RAM all the time

**Device Version:**
 - Windows11
 - Edge, Chrome, OperaGx

**Additional context**
HomePage.js
```
import {useEffect, useState} from 'react'
import InputFields from "./InputFields";
import {createWorker} from "tesseract.js";

const HomePage = () => {

	const [imageData1, setImageData1] = useState()
	const [imageData2, setImageData2] = useState()
	const [imageData3, setImageData3] = useState()
	const [imageData4, setImageData4] = useState()

	const [ocr1, setOcr1] = useState('')
	const [ocr2, setOcr2] = useState('')
	const [ocr3, setOcr3] = useState('')
	const [ocr4, setOcr4] = useState('')

	const worker = createWorker()

	const convertImageToText = async (imageData, setOcr) => {
		if (!imageData) {
			return
		}
		await (await worker).loadLanguage("hun") // Ide kéne a language
		await (await worker).initialize("hun")
		const {
			data: {text}
		} = await (await worker).recognize(imageData, {rotateAuto: true})
		setOcr(text)
                await (await worker).terminate()
	}

	useEffect(()=>{
		convertImageToText(imageData1, setOcr1)
	}, [imageData1])

	useEffect(()=>{
		convertImageToText(imageData2, setOcr2)
	}, [imageData2])

	useEffect(()=>{
		convertImageToText(imageData3, setOcr3)
	}, [imageData3])

	useEffect(()=>{
		convertImageToText(imageData4, setOcr4)
	}, [imageData4])


	return (
		<div className={'container-fluid scanners'}>
			<div className={'row'}>
				<div className={'col-3'}>
					<p>Input gomb</p>
				</div>
				<div className={'col-3'}>
					<p>Kép</p>
				</div>
				<div className={'col-6'}>
					<p>OCR eredmény</p>
				</div>

			</div>
			<InputFields id={"elso"} ocr={ocr1} imageData={imageData1} setImageData={setImageData1}/>
			<InputFields id={"masodik"} ocr={ocr2} imageData={imageData2} setImageData={setImageData2}/>
			<InputFields id={"harmadik"} ocr={ocr3} imageData={imageData3} setImageData={setImageData3}/>
			<InputFields id={"negyedik"} ocr={ocr4} imageData={imageData4} setImageData={setImageData4}/>
		</div>
	)
}

export default HomePage
```
InputFields.js
```
import {HStack} from "@chakra-ui/react";
import {useState} from "react";

const InputFields = ({
    id,
    ocr,
    imageData,
    setImageData
}) => {

    function handleImageChange(e) {
        const file = e.target.files[0]
        if (!file) {
            return
        }
        const reader = new FileReader()
        reader.onloadend = () => {
            const imageDataUri = reader.result
            setImageData(imageDataUri)
        }
        reader.readAsDataURL(file)
    }

    return(
        <div className="container-fluid mt-5 mb-5 border border-info rounded-4">
            <div className={'row'}>
                <HStack>
                    <div className={'col-3 '}>
                        <label htmlFor={`file_upload_${id}`} className={'custom-file-upload'}>Töltse fel a fájlt</label>
                        <input
                            type="file"
                            id={`file_upload_${id}`}
                            onChange={(e) => {handleImageChange(e)}}
                            accept="image/*"
                        />
                    </div>
                    <div className={'col-3'}>
                        <img src={imageData} hidden={!imageData} height={"100%"} width={"100%"} alt="Kép"/>
                    </div>
                    <div className={'col-6'}>
                        <p className={"ocr-result"}>{ocr}</p>
                    </div>
                </HStack>
            </div>
        </div>
    )
}

export default InputFields;
```

**Comment by Balearica** [comment]
Please add the Tesseract.js version number to your Issue.  The very first field in the template is `Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)`.

**Comment by TricksterCode210** [comment]
I've added to the issue, but I write it down here to. Tesseract version: 4.1.0

**Comment by Balearica** [comment]
It looks like you are initializing a new instance of Tesseract and loading language data every time an image is being recognized.  You should edit your code to set up your worker **once** using `createWorker`, `initialize`, and `loadLanguage`.  Then, you can use this worker object to recognize any text.  Finally, when you are done recognizing text you can terminate the worker. 

In other words, the only Tesseract.js function that should be inside `convertImageToText` is `worker.recognize`.

**Comment by Balearica** [comment]
> All I had to do is to delete the worker stuff and replace it with the Tesseract.recognize() method. It looks like it is working fine and it is less code than the previous version

Yes, the `Tesseract.recognize` function is designed to be extremely easy to use.  One word of caution is that `Tesseract.recognize` can be less performant compared to managing workers directly as it creates and destroys a worker every time it is run.  The pros/cons of each approach is explained in the [intro guide](https://github.com/naptha/tesseract.js/blob/master/docs/intro.md).
