### ISSUE TITLE
Handwriting recognition

### ISSUE THREAD

**Issue by drabanus** [naptha/tesseract.js#785]
**Is your feature request related to a problem? Please describe.**
I have a very little success with recognition of handwriting. 

**Describe the solution you'd like**
A solution would be an interface that allows to upload handwritten examples and train the algorithm specifically on those examples. 

**Describe alternatives you've considered**
1) Alternative 1: Training the algorithm for handwriting recognition 
2) Alternative 2 (better): As handwriting styles are vastly different, it may be impossible, or at least onerous, to train the algorithm to recognize ANY handwriting. Therefore, user-based training may be the way to go 

**Additional context**
n/a

**Comment by Balearica** [comment]
Tesseract.js is a JavaScript/Webassembly version of the [Tesseract OCR engine](https://github.com/tesseract-ocr/tesseract).  We do not make any changes to the Tesseract OCR engine here (or the default language data), so issues of this nature are outside of the scope of this repo. 

You should investigate whether recognizing handwriting is possible in the main Tesseract project documentation/issues/etc.  Any information you find will carry over to Tesseract.js.  Based on the [FAQ page](https://tesseract-ocr.github.io/tessdoc/FAQ.html#can-i-use-tesseract-for-handwriting-recognition), recognizing handwriting with high accuracy does not appear to be possible.

> You can [use Tesseract for handwriting recognition], but it won’t work very well, as Tesseract is designed for printed text. Look for projects focused on handwriting recognition.
