### ISSUE TITLE
No download on `langpath` just fail

### ISSUE THREAD

**Issue by TheHellTower** [naptha/tesseract.js#786]
NPM: *4.1.1*

**Describe the bug**
[Here](https://github.com/naptha/tesseract.js/blob/master/docs/api.md#create-worker) I seen that if you give `langPath` it's supposed to download the `.traineddata` but it doens't it's talking about a not found `<file>.traineddata.gz`

**To Reproduce**
1. `npm i tesseract.js`
2. 
```js
const worker = await createWorker({
      logger: m => {},//console.log(m),
      langPath: path.join(__dirname, "..\\..\\..\\tesseractlangs") //modify according to you obviously
    });

    var lang = "afr+amh+ara+asm+aze+aze_cyrl+bel+ben+bod+bos+bul+cat+ceb+ces+chi_sim+chi_tra+chr+cym+dan+deu+dzo+ell+eng+enm+epo+est+eus+fas+fin+fra+frk+frm+gle+glg+grc+guj+hat+heb+hin+hrv+hun+iku+ind+isl+ita+ita_old+jav+jpn+kan+kat+kat_old+kaz+khm+kir+kor+kur+lao+lat+lav+lit+mal+mar+mkd+mlt+msa+mya+nep+nld+nor+ori+pan+pol+por+pus+ron+rus+san+sin+slk+slv+spa+spa_old+sqi+srp+srp_latn+swa+swe+syr+tam+tel+tgk+tgl+tha+tir+tur+uig+ukr+urd+uzb+uzb_cyrl+vie+yid";
    await worker.loadLanguage(lang);
    await worker.initialize(lang);
```
3. Execute & Enjoy

No image needed since it's not scanning related.

**Expected behavior**
Downloading and extracting in the `langPath` path

**Device Version:**
 - Windows `10` (Build `19045.3086`)
 - Node v`19.8.1`

**Additional context**
None required.

**Comment by Balearica** [comment]
`langPath` specifies a URL or (for Node.js version only) local path where the language data files should be retrieved from.  Presumably these files are not found in the folder that you specified.  Unless you want to provide custom language data (`.traineddata`) files, you should remove the `langPath` argument and just use the default.

**Comment by TheHellTower** [comment]
> `langPath` specifies a URL or (for Node.js version only) local path where the language data files should be retrieved from. Presumably these files are not found in the folder that you specified. Unless you want to provide custom language data (`.traineddata`) files, you should remove the `langPath` argument and just use the default.

But if I leave the default it will download literally next to my `package.json`, etc.. so It's literally broken in my opinion..

**Comment by Balearica** [comment]
The `langPath` argument specifies the path the files are retrieved **from**.  The `cachePath` argument specifies the path that the files are saved **to**.  If you want to manually specify a folder for the `.traineddata` files to be saved, set `cachePath`.

**Comment by TheHellTower** [comment]
> The `langPath` argument specifies the path the files are retrieved **from**. The `cachePath` argument specifies the path that the files are saved **to**. If you want to manually specify a folder for the `.traineddata` files to be saved, set `cachePath`.

You solved my problem thank you for everything !
