### ISSUE TITLE
output format and jobId

### ISSUE THREAD

**Issue by sm2017** [naptha/tesseract.js#787]
See https://github.com/naptha/tesseract.js/blob/master/src/index.d.ts#L5 and https://github.com/naptha/tesseract.js/blob/master/src/index.d.ts#L27

Why  for the workers we can define `output` and `jobId` and for `recognize` we cannot?

**Comment by Balearica** [comment]
`Tesseract.recognize` is intended to be an extremely simple function for new users experimenting with Tesseract.js.  That function intentionally sacrifices both performance and control to be as simple as possible. 

The performance of `Tesseract.recognize` is poor, and we do not recommend it for most production applications (we instead recommend using `worker` objects directly).  This is explained in the [intro guide](https://github.com/naptha/tesseract.js/blob/master/docs/intro.md).

**Comment by sm2017** [comment]
@Balearica I followed the guide, but I get the following error

```
node:internal/event_target:1037
  process.nextTick(() => { throw err; });
                           ^

Error: RuntimeError: null function or function signature mismatch
    at Worker.<anonymous> (C:\Project\node_modules\tesseract.js\src\createWorker.js:191:15)
    at Worker.emit (node:events:511:28)
    at MessagePort.<anonymous> (node:internal/worker:263:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:762:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v20.3.0

```
