### ISSUE TITLE
Why CLI do better job than tesseract.js

### ISSUE THREAD

**Issue by sm2017** [naptha/tesseract.js#790]
Why does CLI detect more accurate than js library? 80% better with same image 

```bash
 tesseract input.png  output pdf
```

```js
import { createWorker } from 'tesseract.js';

const worker = await createWorker({
  logger: m => console.log(m)
});

(async () => {
  await worker.loadLanguage('eng');
  await worker.initialize('eng');
  const { data: { text } } = await worker.recognize('input.png');
  console.log(text);
  await worker.terminate();
})();
```

**Comment by Balearica** [comment]
Please update  this issue to add (1) the input image, (2) the output text you are getting [both for the CLI and Tesseract.js versions], and (3) the version numbers [both for the CLI and Tesseract.js]. 

Tesseract.js runs a webassembly port of the Tesseract OCR engine.  The results should be completely identical between Tesseract.js and the Tesseract API.  There are some slight differences in default settings between the Tesseract API and Tesseract CLI, and occasionally those can produce meaningful differences in results (see e.g. https://github.com/naptha/tesseract.js/issues/730#issuecomment-1542927581).

**Comment by Balearica** [comment]
Closing, will reopen if the information requested above is provided.
