### ISSUE TITLE
Add ability to load language from a File (Blob/Stream etc)

### ISSUE THREAD

**Issue by datvm** [naptha/tesseract.js#794]
**Is your feature request related to a problem? Please describe.**
Right now in order to load a language, the URL has to be specified at the beginning and it must be available already. This does not apply to Chrome extension (offline). Say I can download a user-selected file (they download when they are online) and store it in IndexedDB. Now I want to feed it to TesseractJs but currently this is impossible because the file does not really have an URL.

**Describe the solution you'd like**
The `loadLanguage` can accept an optional second parameter, `content` where the content is provided, maybe through a `Blob`, `Stream` or `ArrayBuffer`. Alternatively, a `string` or `URL` object can be provided to override the default behavior (`langPath` + `langCode` + `<magic string>`) to tell Tesseract to just download from that URL. I think another parameter to specify if it's `gzip` or not would be nice as well.

**Describe alternatives you've considered**
Right now the only way to do it is to require users to be online and download the files from the server/a server.

**Additional context**
N/A

**Comment by datvm** [comment]
Thanks that would be helpful. It will take me a few days until I go back to this project again but just to confirm, simply have the file exists there is all it needs? Does it detect all `*.traineddata` files?

**Comment by Balearica** [comment]
If you initialize Tesseract with language `eng` (for example) a file named `eng.traineddata` must exist on the filesystem.  As long as it exists (through whatever method) Tesseract will run.

**Comment by Balearica** [comment]
Closing as answered.
