### ISSUE TITLE
TypeError: r.slice(0,500).join is not a function

### ISSUE THREAD

**Issue by jiabochao** [naptha/tesseract.js#797]
**Tesseract.js version ("tesseract.js": "^4.1.1",)**

**Describe the bug**

The following error occurs when running in a CapacitorJS iOS application, but it works fine in a PC browser.
```
Error: TypeError: r.slice(0,500).join is not a function. (In 'r.slice(0,500).join(" ")', 'r.slice(0,500).join' is undefined)
```

**To Reproduce**

```
const ret = await worker.value.recognize(blob);
```

Please attach any input image required to replicate this behavior.

**Expected behavior**

**Device Version:**
 - OS + Version: iOS 16.2
 - Browser "@capacitor/ios": "^5.0.2",

**Additional context**

**Comment by Balearica** [comment]
Were you able to use CapacitorJS with another version and experienced this when updating Tesseract.js, or was this the only version tested on?

**Comment by jiabochao** [comment]
I had been using the File object provided by @capawesome/capacitor-file-picker plugin API, but it appears to be incompatible with the browser’s File object, so I switched to use the browser’s input file upload and now it’s working fine on the iOS app as well.
