### ISSUE TITLE
Console Debug

### ISSUE THREAD

**Issue by D3sTeptu** [naptha/tesseract.js#799]
Hello! I am using Tesseract.js v 4.0.4, and when I initialize a tesseract worker, I get this message: Estimating resolution as 386 (https://cdn.jsdelivr.net/npm/tesseract.js-core@v4.0.4/tesseract-core-simd.wasm.js:33). How can I disable this output?

**Comment by Balearica** [comment]
All messages produced by Tesseract during `worker.recognize` can be sent to the output object (rather than printed to the console) by setting `debug: true` in the recognition output options.  

```
worker.recognize(img1, undefined, {debug: true})
```

**Comment by D3sTeptu** [comment]
I understand, but how can I disable it?

**Comment by Balearica** [comment]
As stated above, if you do not want debugging messages printed to the console, you need to set `debug: true` output option so they are sent to the output object instead.  This is the only way to avoid these messages being printed to the console.

**Comment by D3sTeptu** [comment]
Oh, okay! Thank you!
