### ISSUE TITLE
Add API to provide custom job identifier to `scheduler.addJob`

### ISSUE THREAD

**Issue by jbaiter** [naptha/tesseract.js#800]
**Is your feature request related to a problem? Please describe.**
For tracking progress it would be very helpful if we were able to pass a `jobId` parameter to the `scheduler.createJob` method.

**Describe the solution you'd like**
This API is supported on the `Worker` objects, and the scheduler does call `addJob`, which can take a custom job identifier as a parameter. The only problem is that it's not exposed in the scheduler's `addJob` and `queue` functions.
However, adding the job id as a third parameter to the `addJob` function would be a breaking API change, since the second `payload` argument is currently variadic :-/

I propose the following API:

```typescript
addJob(action: "recognize" | "detect", payload: any[], jobId?: string)
```

**Comment by Balearica** [comment]
This should be possible at present.  The scheduler code is completely generic--it simply identifies a free worker and calls the specified function, passing through all other arguments.  In fact, schedulers can even be used for managing workers created by the user for other functions (unrelated to Tesseract).  In the case of calling `recognize` and setting the `jobId` argument using a scheduler, that would look like this:

```
scheduler.addJob('recognize', 'https://tesseract.projectnaptha.com/img/eng_bw.png', undefined, undefined, "myjob")
```

**Comment by jbaiter** [comment]
🤦🏾  of course, thank you! :-)
