### ISSUE TITLE
What is the state about browser extensions?

### ISSUE THREAD

**Issue by rugk** [naptha/tesseract.js#807]
The Firefox extension linked in the Readme is apparently not maintained/not on AMO anymore, see https://github.com/gnonio/korporize/issues/14  (note you may remove the link if that turns out to be true).

Otherwise, is there any Chrome/Chromium extension that could be ported to Firefox as nowadays WebExtensions are quite cross-browser compatible?

**Comment by rugk** [comment]
Oh overlooked https://github.com/Tshetrim/Image-To-Text-OCR-extension-for-ChatGPT :see_no_evil:

**Comment by Balearica** [comment]
Closing as it looks like this was resolved.
