### ISSUE TITLE
tessedit_ocr_engine_mode in recognize options does not work

### ISSUE THREAD

**Issue by eyaler** [naptha/tesseract.js#808]
in version 4.1.1, setting tessedit_ocr_engine_mode in recognize options does not work, and you must set it in worker initialize

does not work:
`r = await Tesseract.recognize(im, 'eng', {tessedit_ocr_engine_mode: 0})`

works:
```
w = await Tesseract.createWorker()
await w.loadLanguage('eng')
await w.initialize('eng', 0)
r = await w.recognize(im)
```

**Comment by Balearica** [comment]
I do not believe this behavior itself is a bug, as the [Tesseract source code](https://github.com/tesseract-ocr/tesseract/blob/8b4284d28bc5fb04afd744bbadbe10ffc3c79040/src/ccmain/tesseractclass.cpp#L119-L123) indicates that the `tessedit_ocr_engine_mode` is a parameter set at initialization.  However, a types file in this repo does incorrectly indicate that this parameter can be set after initialization, so I think the actionable change here is to remove that. 

https://github.com/naptha/tesseract.js/blob/4a63a8e28cebf740baeb4d44c9a72d27f3fc71dc/src/index.d.ts#L68

**Comment by Balearica** [comment]
I removed the misleading option, so there should no longer be any indication that `tessedit_ocr_engine_mode` can be changed after initialization.

**Comment by eyaler** [comment]
@Balearica thanks! ideally, trying to set init_only args after initialization should raise a warning or an exception instead of silently failing.

**Comment by Balearica** [comment]
I think a warning could be helpful.  I would not want to throw an exception since I do not think this is worth breaking existing code over--other users likely have this option set under the mistaken belief that it does something.

**Comment by Balearica** [comment]
I added a warning message when users attempt to use `setParameters` to set an init-only parameter.  Closing the issue as resolved.
