### ISSUE TITLE
Current CDN Example Not Working

### ISSUE THREAD

**Issue by darth-cheney** [naptha/tesseract.js#81]
Hi. I'm trying to conduct a very simple test using just a single HTML file and by including the `tesseract.js` script using the CDN source in the documentation:
  ```html
<script src='https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js'></script>
```
  
My HTML file is simple:
```html
<html>
    <head>
        <script src='https://cdn.rawgit.com/naptha/tesseract.js/1.0.10/dist/tesseract.js'></script>
        <title>Tesseract Test</title>
    </head>
    <body>
        <label for="fileInput">Choose File to OCR:</label>
        <input type="file" id="fileInput" name="fileInput"/>
        <br />
        <br />
        <div id="document-content">
        </div>
    </body>
    <script>
        document.addEventListener('DOMContentLoaded', function(){
            var fileInput = document.getElementById('fileInput');
            fileInput.addEventListener('change', handleInputChange);
        });

        function handleInputChange(event){
            var input = event.target;
            var file = input.files[0];
            console.log(file);
            Tesseract.recognize(file)
                .progress(function(message){
                    console.log(message);
                })
                .then(function(result){
                    var contentArea = document.getElementById('document-content');
                    console.log(result);
                })
                .catch(function(err){
                    console.error(err);
                });
        }
    </script>
</html>
```
But if I try to add an image, nothing happens in the console or anywhere else. This is also true if I clone the repository and instead load `tesseract.js` from the `dist` directory.
  
I see that the main (non-github) website for the project uses the CDN version `1.0.7`, so I tried using that source instead. It came to life and started reporting back progress, but then threw the following error:

```javascript
tesseract_example.html:27 Object {status: "loading tesseract core", progress: 0}
tesseract_example.html:27 Object {status: "loading tesseract core", progress: 1}
tesseract_example.html:27 Object {status: "initializing tesseract", progress: 0}
index.js:10 pre-main prep time: 65 ms
tesseract_example.html:27 Object {status: "initializing tesseract", progress: 1}
worker.js:11953 Uncaught DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An object could not be cloned.(…)

(anonymous function)	@	worker.js:11953
respond	@	worker.js:12185
dispatchHandlers	@	worker.js:12205
(anonymous function)	@	worker.js:11952

```
  
Am I just doing this wrong somehow?
  
(Using Chrome 54 in OSX 10.11.)

**Comment by antimatter15** [comment]
I just tried running your exact code snippet and it worked for me. Have you tried clearing your browser cache?

**Comment by darth-cheney** [comment]
Clearing browser data seems to have improved things, but now I'm still getting the latter error I did when trying to use `1.0.7`:
  
```javascript
worker.js:8474 Uncaught DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An object could not be cloned.(…)(anonymous function) @ worker.js:8474respond @ worker.js:8706dispatchHandlers @ worker.js:8726(anonymous function) @ worker.js:8473
```
  
Additionally, it would be good to understand just why clearing browser data made a difference at all

**Comment by iwollmann** [comment]
Appearantly this happens only when you trying access the page directly without a webserver.

**Comment by MacroChip** [comment]
I am accessing the page directly without a webserver and am having the same issue.
Chrome on Linux Mint
Version 55.0.2883.75 (64-bit)
```
Object {status: "initializing tesseract", progress: 1}
worker.js:11953 Uncaught DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An object could not be cloned.
```

**Comment by iwollmann** [comment]
Exactly @MacroChip, that's what i said, you need to access through a web server.

**Comment by MacroChip** [comment]
@iwollmann Is that really the solution for Chrome? It works fine in Firefox without a web server.

**Comment by iwollmann** [comment]
I really don't know, here I am using with chrome in this scenario... =(

**Comment by Giusti** [comment]
Hey I have exactly the same problem but I am getting another error.

`XMLHttpRequest cannot load . Can't create DocumentThreadableLoader`

And 

`cdn.rawgit.com/naptha/tesseract.js/8b915dc/dist/tesseract.worker.js:1 Uncaught DataCloneError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An object could not be cloned.`

**Comment by lgcagithub** [comment]
Maybe you should try to request tesseract.js from web server. For example, Apache, Tomcat.

**Comment by lgcagithub** [comment]
Maybe you should try to request all the files from web server. For example, Apache, Tomcat.

**Comment by a4027971** [comment]
I meet the same error by using local file. 
Finally, the problem can be solved for me by using Chrome Extension ([Web Server for Chrome]).(https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb/related)

**Comment by TingHsi** [comment]
worker.js:8475 Uncaught DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': Error: Uncaught ReferenceError: require is not defined could not be cloned.
    at http://10.0.6.49/naptha/tesseract.js/1.0.9/dist/worker.js:8475:16
    at Object.respond (http://10.0.6.49/naptha/tesseract.js/1.0.9/dist/worker.js:8707:9)
    at Object.dispatchHandlers (http://10.0.6.49/naptha/tesseract.js/1.0.9/dist/worker.js:8729:17)
    at http://10.0.6.49/naptha/tesseract.js/1.0.9/dist/worker.js:8474:17
(anonymous) @ worker.js:8475
respond @ worker.js:8707
dispatchHandlers @ worker.js:8729
(anonymous) @ worker.js:8474


My trouble is same to you, @darth-cheney .
Your program is OK now?

**Comment by HuubSmit** [comment]
Did anyone find a solution regarding all the files locally? I cannot seem to get it to work, in different circumstances. Using the index.js from the CDN seems to me that nothing is loaded locally.

**Comment by brendanwilding** [comment]
This is so sad that it doesn't work in chrome. It works in FF.

**Comment by jeromewu** [comment]
Should be working with latest example. Feel free to reopen with more information. :smile:
