### ISSUE TITLE
Is it possible to resolve number captchas but puzzled

### ISSUE THREAD

**Issue by mnsrulz** [naptha/tesseract.js#811]
I am trying to crack the captcha from the image below but it's not returning the results at all. I am imagining it's something to do with the way image is, but is it possible to crack these kind of captchas using this lib?

![image](https://github.com/naptha/tesseract.js/assets/1809086/681aeac1-0c80-4995-ab78-ad075d7bd04e)

Have tried the below code with no success

```

import { createWorker } from 'tesseract.js';

const worker = await createWorker({
    logger: m => console.log(m),
});

const lang = 'eng+por'; //por

(async () => {
    // await worker.load();
    await worker.loadLanguage(lang);
    await worker.initialize(lang);
    await worker.setParameters({
        tessedit_char_whitelist: '0123456789',
    });


    const { data: { text } } = await worker.recognize(urlImage);
    console.log(text);
    await worker.terminate();
})()
```

**Comment by Balearica** [comment]
Tesseract is not able to read captchas (unless the captchas are unbelievably poorly implemented).  The purpose of a captcha is to be readable to humans but unreadable to OCR programs (like Tesseract).  While some libraries are built to be robust to these types of image manipulations, Tesseract is not one of them--it will struggle with any image with lots of noise/distortion.

**Comment by mnsrulz** [comment]
thanks for the quick reply! After reading a bit around I was able to get that working. Next step, I wanted to host it in netlify platform, and it looks it's failing there with the below error message

```
{
  "errorType": "Error",
  "errorMessage": "Cannot find module '/var/worker-script/node/index.js'",
  "trace": [
    "Error: Cannot find module '/var/worker-script/node/index.js'",
    "    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)",
    "    at Function.Module._load (node:internal/modules/cjs/loader:873:27)",
    "    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)",
    "    at MessagePort.<anonymous> (node:internal/main/worker_thread:197:24)",
    "    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)",
    "    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)"
  ]
}
```

Curious if you have any insights on running this library in netlify platform?
