### ISSUE TITLE
tesseract.projectnaptha.com demo site has some bugs

### ISSUE THREAD

**Issue by JayMartMedia** [naptha/tesseract.js#818]
**Tesseract.js version 4.1.1**

**Describe the bug**
The demo site https://tesseract.projectnaptha.com/ doesn't extract and display text when image is initially dropped onto the page.

**To Reproduce**
1. Navigate to https://tesseract.projectnaptha.com/
2. Wait for tesseract.js to initialize and extract the text from the "mild splendour" demo image
3. Open your browser dev tools
4. Open your file explorer
5. Drag an image containing text from the file explorer onto the demo web page
6. View the error in the dev tools console
7. Notice that the text is not extracted from the image

**Test Image**
![test-image](https://github.com/naptha/tesseract.js/assets/43322309/338d1ba4-dac9-418e-86fd-7b350b838398)

**Expected behavior**
The text extraction will occur when you drop the image from your file explorer onto the page

**Device Version:**
 - OS + Version: Windows 10
 - Browser Chrome

**Additional context**
The text extraction is performed successfully if you drag and drop an image from file explorer onto the webpage before tesseract.js is initialized.

The text extraction is performed successfully if you switch to the Chinese Demo then back to the English Demo and then drag and drop an image form file explorer onto the webpage.

I'm happy to dig through and resolve this issue. So far I have not been able to find the repo for the tesseract.projectnaptha.com page.

**Comment by JayMartMedia** [comment]
Ahh, I see the gh-pages branch now: https://github.com/naptha/tesseract.js/tree/gh-pages

**Comment by JayMartMedia** [comment]
Just tossed a PR up for this: https://github.com/naptha/tesseract.js/pull/819

**Comment by Balearica** [comment]
Thanks for contributing a fix for this.  Merged.
