### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Hongbo-Miao** [naptha/tesseract.js#82]
First thanks for the great library!

Just a suggestion, it would be great to provide typings for TypeScript.

**Comment by joarb** [comment]
It seems as though DefinetlyTyped already did that. Check out: 

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/tesseract.js

Add to your project by simply do `npm install --save-dev @types/tesseract.js`.

**Comment by leaving123** [comment]
How to set the "Local Installation" with the Typescript?
