### ISSUE TITLE
Need help with recognition

### ISSUE THREAD

**Issue by AnotherAnkor** [naptha/tesseract.js#83]
https://pp.vk.me/c637324/v637324787/16eaf/IkAlENWwG90.jpg
https://pp.vk.me/c637324/v637324787/16e8b/6RzPDEjGrWE.jpg
http://astronaut.ru/bookcase/books/kamanin1/foto/forz1.gif
http://ic.pics.livejournal.com/silent_gluk/12280813/5849088/5849088_original.jpg
With my test image doesn't work.
With biggest test image need to set more memory (where in code??). With smaller and images from cam I get nothing.
And I need to use it with cam. What's can be needed cam resolution?

**Comment by iwollmann** [comment]
@AnotherAnkor, i don't know if you already viewed this, but this helped me a lot: https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality

**Comment by jeromewu** [comment]
Tested your image, and works with tesseract.js v2, please try it again and feel free to reopen if it still doesn't work.
