### ISSUE TITLE
Nothing happens on demo site

### ISSUE THREAD

**Issue by stumpykilo** [naptha/tesseract.js#833]
I am trying to run the demo on https://tesseract.projectnaptha.com/ and I get an error in the console. This seems to be blocking any processing of the image dropped onto the page regardless of language.

```
send.js:9 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': function progressUpdate(packet){
	var log = document.getElementById('log');

	const statusLabel = {"initialized...<omitted>...
} could not be cloned.
```

**Comment by Balearica** [comment]
Thank you for reporting.  The demo site was written for Tesseract.js v4, however Tesseract.js v5 was being loaded, resulting in the error. 

I've updated the site to use Tesseract.js v4 for now, as that is the quickest fix, so the issue should be resolved.  (You may have to clear your cache for the site for the change to take effect.)

**Comment by Balearica** [comment]
I updated the demo to use Tesseract.js v5, so everything should now be up to date.  Closing this issue as resolved.

**Comment by farwish** [comment]
a new demo try here, [imageocr](https://tool.offso.com/imageocr)
