### ISSUE TITLE
Can I understand how this work?

### ISSUE THREAD

**Issue by Pnlvfx** [naptha/tesseract.js#837]
If I'll try to recognize an image without any text I'll get this and honestly idk if it's a bug, or an invisible text, maybe someone could explain it to me?

'"\n' +
    'A y 3 Vo —\n' +
    '“Wl |.\n' +
    'ul! ni | ; / =\n' +
    'i I |\n' +
    'If HJ |\n' +
    '] I\n' +
    '< as IE - LE - |\n' +
    '47 COSI EE ([ | B\n' +
    'a : 4 Ec Ee .\n' +
    '—— pee y 5 Sr) Py WS “ ne\n' +
    'mn : a 1 V7 5 Novum — >» 2 fe %\n' +
    'So —— HET aE\n' +
    '= a . — Ee —\n' +
    'HEE = g |\n' +
    'p—l | g=mrr2 % DE\n' +
    '\\ ral nh = “NY\n' +
    '___ J) a\n' +
    'PD I | ( [\n' +
    'I UTE | .\n' +
    '| mil wpe | pe\n' +
    'RY we | JH | Sv a il rb\n' +
    'TREE | J =e\n' +
    '0, 5 =uBg5"= 2 ill\n' +
    '| I | & wv\n' +
    '— |\n' +
    '| EN)\n' +
    '> | { |\n' +
    'IH | ¥B nid\n' +
    '“ | 1 A= | ke : & Ey oN\n' +
    'a Ly | PY\n' +
    'Ly —eee— = Seosor | <o eo — 4 a = -\n' +
    'CEA CL  ——— a Sa Rete 5, po ~\n' +
    'a —— es = dia\n'
}

**Comment by Balearica** [comment]
Please post a reproducible example including the image and code.

**Comment by Balearica** [comment]
It does not sounds like Tesseract.js is suited for your application.  Tesseract assumes what you are showing it is text, and does its best to recognize it as such.

**Comment by Pnlvfx** [comment]
Ok sorry, can I ask if someone know what package can I use to achieve this?
