### ISSUE TITLE
interpret currency symbols

### ISSUE THREAD

**Issue by guntercn** [naptha/tesseract.js#838]
In the Spanish ('spa') tereract interpretation, the currency symbol ₡ is interpreted as a number 2.

Tesseract interprets a character as a number.

English language, Tesseract interprets well as a character, but it is in 'spa' the need.

Any way to improve or correct this "error"?

**Additional context**
Number with a currency simbol
![Cajas2](https://github.com/naptha/tesseract.js/assets/16024623/fd92c23f-3d43-4947-a5d8-cb455c915120) 

thanks

**Comment by Balearica** [comment]
The words and symbols that are seen as valid are determined by the language data loaded (`spa.traineddata` in this instance).  By default, Tesseract.js loads `.traineddata` files provided by the [main Tesseract project](https://github.com/tesseract-ocr/tesseract)--we use integerized versions of the [tessdata_best](https://github.com/tesseract-ocr/tessdata_best) data.  If you were to find or create a `.traineddata` file that does not have this issue, you can use it by setting the `langPath` argument. 

Issues related to language data are outside of the scope of this repo.  The goal of Tesseract.js is to bring the Tesseract OCR engine to the browser--we do not make any edits to the recognition engine or `.traineddata` provided by Tesseract.  If you are interested in learning more about how language data works, and what tools exist to modify it, you should look at the documentation provided by the main Tesseract project.  Their website is [here](https://tesseract-ocr.github.io) and repo is [here](https://github.com/tesseract-ocr/tesseract).
