### ISSUE TITLE
Preload tar.gz data

### ISSUE THREAD

**Issue by elmarti** [naptha/tesseract.js#84]
I'm writing an app for Chinese and I've noticed that on the first call it loads the training file and uses it for all of the following calls. Is there a way to do this on page load so that the data is available after the first call to Tesseract?

**Comment by ztz0223** [comment]
The readme said you can use the Tess data locally, by using create API with options.

**Comment by Inglebard** [comment]
Hi,
Any news about that ?

**Comment by jeromewu** [comment]
Please reference: #43
