### ISSUE TITLE
"Failed to fetch version info for @tesseract.js-data/fr."

### ISSUE THREAD

**Issue by ChrisJeamme** [naptha/tesseract.js#840]
**Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)**
5.0.2

**Describe the bug**
I just launched a recognition after setting it to French, and the GET of "fr.traineddata.gz" returns a 404 error

**To Reproduce**
Request **_GET_** `https://cdn.jsdelivr.net/npm/@tesseract.js-data/fr/4.0.0_best_int/fr.traineddata.gz`
or
Execute code :
```
const worker = await createWorker('fr');
const { data: { text } } = await worker.recognize('randomdatabecausenomatter');
```

![image](https://github.com/naptha/tesseract.js/assets/8880170/f4b74896-b495-4cd8-a674-06e77a2c3def)

**Expected behavior**
GET status 200 of this file and continue recognition

**Device Version:**
 - OS + Version: Windows 11
 - Browser : Chrome 118.0.5993.71

**Additional context**
Worked very well in version 4.

**Comment by Balearica** [comment]
The code for French is `fra` not `fr`.  Language codes can be found in [this file](https://github.com/naptha/tesseract.js/blob/778aa00a11ea086a0b3a138ab520b38524b1ec10/src/constants/languages.js#L37).

**Comment by ChrisJeamme** [comment]
Oh yes ! My bad
It might be good to have a little check, I had absolutely no idea that I had entered the value incorrectly
Thank you for the quick reply
