### ISSUE TITLE
Image from iframe

### ISSUE THREAD

**Issue by enemali** [naptha/tesseract.js#841]
Does it work if the image is coming from an iframe ? ( different domain from parent page )

**Comment by Balearica** [comment]
This is more a general question about HTML/iframes than Tesseract.js, as the answer comes down to whether you can access the contents of an image (`img.src`) in an iframe.  If you can access `img.src` from the context where Tesseract.js is loaded, then Tesseract.js can recognize it. 

I would expect the answer is no.  My understanding of iframes is that if you embed an iframe that is (1) a different domain and (2) not a website you control (so you cannot set the CORS policy), then you do not have access to the contents of the iframe.  In this situation, I believe the iframe is almost like a separate browser tab.
