### ISSUE TITLE
About v1.0.1

### ISSUE THREAD

**Issue by x09326** [naptha/tesseract.js#85]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

I found that the files of v1.0.1 in github are different from npm released.
Which one is better to be hosted?
Please help me solve it, thanks.
https://github.com/cdnjs/cdnjs/pull/9717

**Comment by extend1994** [comment]
Hi @bijection @antimatter15 Do you know about this? It would be very helpful for me to add the files to CDNJS! 😄

**Comment by jeromewu** [comment]
On CDNs now, close the issue for now.
