### ISSUE TITLE
How to get the micr value when reading a bank cheque?

### ISSUE THREAD

**Issue by ErsinMandaci** [naptha/tesseract.js#857]
I am scanning a bank cheque in the Flutter application. I could not get the expression in the micr field on the cheque with ocr. How do I do this?

**Comment by Balearica** [comment]
Closing as off topic, as this does not appear to be a bug report or feature request for Tesseract.js.  If you do have a bug report or feature request for the Tesseract.js JavaScript library, please fill out the entire issue template.
