### ISSUE TITLE
Network error while fetching

### ISSUE THREAD

**Issue by daniellwdb** [naptha/tesseract.js#858]
**Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)**
"tesseract.js": "^5.0.3"

**Describe the bug**
Call to `createWorker` results in:
```
Error: Error: Network error while fetching https://cdn.jsdelivr.net/npm/@tesseract.js-data/en/4.0.0/en.traineddata.gz. Response code: 404
```

**To Reproduce**
`npm i tesseract.js@latest`
```typescript
import { createWorker } from "tesseract.js";

createWorker("en", 4)
```

**Expected behavior**
Language data should be downloaded.

**Device Version:**
 - Windows 11
 - Node v18.16.0

**Additional context**
Manually adding the `eng.traineddata` file to my project root (like how it was downloaded in the past) does not work either

**Comment by Balearica** [comment]
`en` is not a valid language code.  Presumably you mean `eng` for English.  A full list of language codes can be found [here](https://github.com/naptha/tesseract.js/blob/master/src/constants/languages.js).

**Comment by daniellwdb** [comment]
Thanks!
