### ISSUE TITLE
rotateRadians and osd output are incorrect

### ISSUE THREAD

**Issue by wvanrensburg** [naptha/tesseract.js#859]
**Version 5.03**

When asking for `rotateRadians` from the recognize api, the radians returned are incorrect. See attached image for example. The correct text is pulled, and the image is clearly 90 degrees (or 270, or -90 however you put it), but the radians value returned is `-0.010256410576403141`, which converting back to degrees, comes out to roughly `-0.58` degrees.

Tested the below with both PSM modes of `PSM.SPARSE_TEXT_OSD` and `PSM.AUTO_OSD`

**Example to reproduce**
```
const { data: { tsv, imageBinary, rotateRadians } } = await scheduler.addJob(
           'recognize',
          `data:image/png;base64,${imagebase64}`,
          {rotateAuto: true}, {imageBinary: true, rotateRadians: true, tsv: true}
);
```

When calling it directly on tesseract, Tesseract reports correct orientation
```
tesseract /path/to/image.png /path/to/reportout --psm 0

Page number: 0
Orientation in degrees: 90
Rotate: 270
Orientation confidence: 10.40
Script: Latin
Script confidence: 5.40
```

![rotatedimage](https://github.com/naptha/tesseract.js/assets/2231975/67af973f-11cf-4426-8e3a-34580774c233)

**Comment by wvanrensburg** [comment]
Adding to this.... when adding the `odd: true` to the options payload, the OSD result comes out incorrect as well.

Example
```
const { data: { tsv, imageBinary, rotateRadians } } = await scheduler.addJob(
           'recognize',
          `data:image/png;base64,${imagebase64}`,
          {rotateAuto: true}, {imageBinary: true, rotateRadians: true, tsv: true, osd: true}
);
```
Results in..
```
Page number: 0
Orientation in degrees: 0
Rotate: 0
Orientation confidence: 0.00
Script: Latin
Script confidence: 2.00
```
which is the incorrect output.

**Comment by Balearica** [comment]
Thanks for reporting.  It sounds like we need to improve documentation and/or recognition output for auto-rotate and orientation detection, and perhaps adding an output field for total page angle. 

The reason why `rotateRadians` is reported as `-0.58` degrees is that `rotateRadians` is only reporting the angle used by the auto-rotate feature (enabled by `rotateAuto: true`).  The auto-rotate code is distinct from the orientation detection code, with both adjustments being calculated independently at different points in the recognition process.  

Orientation detection detects how the page is oriented, with 4 discrete options:  0/90/180/270.  The angle used by auto-rotate is calculated using the slope of the lines of text Tesseract identifies just prior to recognition (after orientation has been corrected).  Auto-rotate is intended to adjust the image +/- 10 degrees and improves results for pages that have been photographed/scanned at an angle. To calculate the total angle of the page, as it stands, both the angle reported by orientation detection and auto-rotate would need to be combined.

**Comment by Balearica** [comment]
> Adding to this.... when adding the osd: true to the options payload, the OSD result comes out incorrect as well running with modes PSM.SPARSE_TEXT_OSD and PSM.AUTO_OSD

I was able to replicate the incorrect `osd` results you are describing when using the Tesseract.js default `oem` value of `1` (`LSTM_ONLY`).  However, changing this value to `2` (`TESSERACT_LSTM_COMBINED`) produce the correct result.  `oem` is the 2nd argument in `createWorker`, so that looks like the following:

```
const worker = await Tesseract.createWorker("eng", 2);
```

I believe that the `tesseract` CLI application uses a default `oem` value of `2`.  Therefore, this would explain why you got different results using Tesseract.js compared to the `tesseract` CLI program.

**Comment by Balearica** [comment]
The following snippet contains a minimal test site that reports the total angle of the page, including both orientation and page rotation.  

```
<!DOCTYPE HTML>
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js"></script>
  </head>
  <body>
    <input type="file" id="uploader" multiple>
    <script type="module">

      const worker = await Tesseract.createWorker("eng", 2);
      worker.setParameters({tessedit_pageseg_mode: '3'})

      const recognize = async function(evt){
        const files = evt.target.files;
        
        for (let i=0; i<files.length; i++) {
          const ret = await worker.recognize(files[i], {rotateAuto: true}, {osd: true});

          const osdAngle = parseFloat(ret.data.osd.match(/Orientation in degrees: (\d+)/)?.[1]) || 0;
          const autoRotateAngle = ret.data.rotateRadians * (180 / Math.PI) * -1;
          const totalAngle = osdAngle + autoRotateAngle;
          console.log("osdAngle: " + osdAngle + " (degrees)");
          console.log("autoRotateAngle: " + autoRotateAngle + " (degrees)");
          console.log("totalAngle: " + totalAngle + " (degrees)");

          console.log(ret.data.text);
        }
      }
      const elm = document.getElementById('uploader');
      elm.addEventListener('change', recognize);
    </script>
  </body>
</html>

```

This test image is rotated exactly 95 degrees clockwise.

![rotate_95_clock](https://github.com/naptha/tesseract.js/assets/100809261/4c434c05-a705-452f-8369-5f1ff3de97d9)

Results:
```
osdAngle: 90 (degrees)
autoRotateAngle: 5.017756638841202 (degrees)
totalAngle: 95.0177566388412 (degrees)
```

**Comment by matsklevstad** [comment]
Hi! I tried to use your code in a plain .html file and run it in the browser, but i get this error. Any suggestions why? 

![Screenshot 2024-07-26 at 08 33 04](https://github.com/user-attachments/assets/45f7eee1-583b-4ac9-a9bb-04dc77434db0)

**Comment by Balearica** [comment]
@matsklevstad Modify the `createWorker` line to the following and it should run.

```js
const worker = await Tesseract.createWorker("eng", 2, {legacyCore: true, legacyLang: true});
```

This forces the Legacy code and language data to be downloaded, which is required for `oem` mode `2` (LSTM + Legacy fallback).  This should happen automatically, so the fact that this is not happening is a bug.  I will open a separate issue to track this.

**Comment by matsklevstad** [comment]
Thank you, it worked! I tried reading the documentation, but I couldn't find what I was looking for. Is it possible to calculate the angle and then rotate the image so that OCR can read it correctly? Specifically, if the image is upside down, can the system detect this, rotate the image, and then perform OCR?

**Comment by Balearica** [comment]
@matsklevstad Tesseract.js should be capable of detecting and automatically accounting for various orientations and angles when performing recognition.  However, the scope of this Git Issue is specific to Tesseract.js *reporting* correct angle information, which it looks like is not at issue here.  Therefore, if you are having general issues with orientation detection, please create a new Git Discussion with a reproducible example (code + image) of the image rotated at 270 degrees that you are working with, and I can take a look.

**Comment by matsklevstad** [comment]
@Balearica Can you check out #940  ? :)
