### ISSUE TITLE
How to use the library locally via nodejs?

### ISSUE THREAD

**Issue by ztz0223** [naptha/tesseract.js#87]
I just want to use local tessdata in the server end, I got the way:
Tesseract = require('tesseract.js'),
Tesseract.recognize(serverImgs[i], {
      lang: ‘eng’,
      langPath: path.resolve('../tessdata')
    })
to set the local tessdata path, but for the first time, the remote tessdata must be downloaded from the CDN.

Who can tell me how to set the options to use the local tessdata?

Thanks very much.

**Comment by ztz0223** [comment]
After read the tesseract.js' codes, I found that, the lang.js will read the trainded datas from the root directory of the depot, so copy the trained data at the root directory, will be OK.

Any other better solutions?
Thanks.

**Comment by jeromewu** [comment]
Please check here for local installation guide: https://github.com/naptha/tesseract.js/blob/master/docs/local-installation.md
