### ISSUE TITLE
chinese don't support

### ISSUE THREAD

**Issue by wq57wq57** [naptha/tesseract.js#872]
chinese don't support,,chi_sim.traineddata have been download,put it in the directory  assert.

**Comment by wq57wq57** [comment]
only localhost:3000 can visit the wen address,127.0.01:300,ip:3000 all can't visit,why

**Comment by Balearica** [comment]
I don't understand what is being asked.  Tesseract.js definitely supports Chinese, and this is one of the languages in the [demo site](https://tesseract.projectnaptha.com/).  You should review the documentation and examples if you are having trouble getting a site set up.
