### ISSUE TITLE
How to exit after recognition?

### ISSUE THREAD

**Issue by Andiedie** [naptha/tesseract.js#88]
After recognition, the program did not exit.
Only after I press `Ctrl+C`, the program closed.
How to deal with it?
![image](https://cloud.githubusercontent.com/assets/21376471/21585643/8cd1052a-d0ff-11e6-85be-fb1e91415a4a.png)

![image](https://cloud.githubusercontent.com/assets/21376471/21585573/05117ca6-d0fe-11e6-9d6c-ae81b3e8a835.png)

**Comment by emarthinsen** [comment]
@Andiedie Did you ever come up with a solution to this?

**Comment by emarthinsen** [comment]
@Andiedie You've probably already found a solution or moved on, but I just figured out how to get it to close. When you are done with all of your processing, call `terminate()`. Here's an example from my code:

```
'use strict';

const Tesseract = require('tesseract.js');

Tesseract
  .recognize(PATH)
  .then((result) => {
    console.log(result.text);
  })
  .catch((err) => {
    throw err;
  });

Tesseract.terminate();
```

**Comment by Andiedie** [comment]
@emarthinsen  Thank you.
