### ISSUE TITLE
How to hide 'pre-main prep time: ...ms'

### ISSUE THREAD

**Issue by Andiedie** [naptha/tesseract.js#89]
I don't want to show this : )

**Comment by vincentjames501** [comment]
+1

**Comment by mylamour** [comment]
Just remove `"pre-main prep time: "`  in the `tesseract.js-core\index.js` line 505 
![image](https://cloud.githubusercontent.com/assets/12653147/25225698/f6eae990-25f4-11e7-9881-2589139e2fa0.png)

**Comment by menushka** [comment]
How is this the accepted solution?

**Comment by dir** [comment]
Any updates on this? Just gonna restate what @menushka said, how is this the accepted solution?

**Comment by jeromewu** [comment]
In the latest version (2.0.0-beta.1), this issue has resolved, please upgrade and check.

**Comment by dir** [comment]
So sorry about that, new to this project. Will check the beta out. Love what you’re doing @jeromewu.
