### ISSUE TITLE
Pure Javascript? (ie no workers or web dependencies)

### ISSUE THREAD

**Issue by trevorwat** [naptha/tesseract.js#9]
Hi.
first, good work!

second: is it possible to use tesseract.js directly from javascript without a web worker?  Perhaps an earlier build output gives that prior to being web-worker-ified(?)

Thanks.

**Comment by antimatter15** [comment]
It's certainly possible but it's slow enough that I can't recommend it

**Comment by trevorwat** [comment]
Hi Kevin

Thanks & good to meet you.  Any pointers on getting a pure JS version going?  .. madeline.js perhaps?

 

 

 

 

Best regards,
Trevor

Trevor Watkins
____________________________
www.thoriumds.com <http://www.thoriumds.com/> 
trevor.watkins@thoriumds.com <mailto:trevor.watkins@thoriumds.com> 



 

  

‘The information in this e-mail (which includes any files transmitted with it) is confidential.  It is intended for the addressee only.  If this e-mail has been received by you and you are not the addressee please inform the sender and erase the e-mail from your system immediately.  Any use, re-transmission, forwarding or copying of this e-mail by anyone other than the addressee is prohibited. Copyright in this e-mail and any document created by us will be and remains our property and this e-mail does not transfer any rights to you. This e-mail and its contents may not be relied on for any purpose whatsoever by anyone other than the addressee and no liability will be accepted for any loss however arising caused by misuse of or unauthorised reliance on this e-mail.'
