### ISSUE TITLE
Limit output to just numbers

### ISSUE THREAD

**Issue by honkskillet** [naptha/tesseract.js#91]
Is it possible to limit the matches characters to just numbers (or a subset of characters) to improve accuracy?

**Comment by AchrefGamos** [comment]
No.

**Comment by iwollmann** [comment]
@honkskillet I don't know if is the right way, but I got this behavior with this configuration option:

`tessedit_char_whitelist: ':/-0123456789'`

**Comment by jeromewu** [comment]
Please check here for whitelist chars in tesseract.js v2: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-whitelist-char-200-alpha5
