### ISSUE TITLE
Focusing area

### ISSUE THREAD

**Issue by matayo-ayo** [naptha/tesseract.js#910]
It really does a good job but when it comes to output it gives out too many lines which more of them are not useful (trash to programmer) that make it to keep program use long time to load while the data needed might be two or three lines 
ie. You want only a names and id number

It may be more useful if you add a feature to allow user to relocate where to get certain data ie using line numbers and cursor position, and if you would go more to get something like user image from id

**Comment by Balearica** [comment]
> It may be more useful if you add a feature to allow user to relocate where to get certain data ie using line numbers and cursor position

It is already possible to recognize a specific region by using the `rectangle` argument.  This can be seen in the documentation for [worker.recognize](https://github.com/naptha/tesseract.js/blob/master/docs/api.md#workerrecognizeimage-options-output-jobid-promise).

This can be used to recognize a specific area using cursor position.  For example, in [ScribeOCR](https://scribeocr.com/) you can select `Edit -> Recognize Word` and then use the cursor to select a specific word missed by the initial recognition pass.  This was implemented using the `rectangle` argument of `worker.recognize`.
