### ISSUE TITLE
Detect templates

### ISSUE THREAD

**Issue by marsanla** [naptha/tesseract.js#92]
Hi, i am new with this library and OCR, and i would like to know if its possible to scan a picture like here ([http://minhaj.io/nodejs/tesseract-nodejs-heroku-ocr-app/](http://minhaj.io/nodejs/tesseract-nodejs-heroku-ocr-app/)) base on a template?

Thanks :)

**Comment by jeromewu** [comment]
In the latest (2.0.0-beta.1) version, you can assign rectangles on the image to recognize only certain parts of image, you can check example here: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-only-part-of-the-image-200-beta1
