### ISSUE TITLE
how to use installed tessercat lib on windows for tesseract.js?

### ISSUE THREAD

**Issue by orange-jacky** [naptha/tesseract.js#924]
how to use installed tessercat lib on windows for tesseract.js

using cdn sometimes can't not loadload this wasm and it's too slow, i need to install tesseract package in my window or macos sytem and use tesseract.js to call it. how to realize it

**Comment by Balearica** [comment]
If the core issue is that you do not like the CDNs Tesseract.js uses by default, it is already possible to bypass the CDNs and use your own copy of all files.  See [this page](https://github.com/naptha/tesseract.js/blob/master/docs/local-installation.md) for details.

It is not possible to use Tesseract.js with a non-webassembly version of Tesseract that you installed separately.  The purpose of Tesseract.js is to provide a portable webassembly version of Tesseract that can be run in the browser or Node.js.  If you want to use a version of Tesseract installed on your local system, you should use the [main Tesseract project](https://github.com/tesseract-ocr/tesseract), not Tesseract.js.
