### ISSUE TITLE
TesseractJob.cancel()

### ISSUE THREAD

**Issue by ytiurin** [naptha/tesseract.js#93]
Hi! Thank you for an amazing port!

I just wanted to ask if it is possible to cancel active tesseract job, so that promise would not resolve?
I use `TesseractJob._instance.terminate()` to cut the currect operation but it seem to destroy tesseract worker and it doesn't initialize the next time I do `Tesseract.recognize()`

Is there a painless way to stop tesseract job and reject the promise?

**Comment by antimatter15** [comment]
I've added a fix in b99bf1cee53929d9dad7fe25d86492d2eb262495

**Comment by ianrose14** [comment]
@antimatter15 Can you give a little more color on this?  I'm not sure what the right API is to use to cancel a running operation.  I looked at the commit you linked above but as a newbie unfamiliar with the code I'm afraid it isn't obvious to me...

**Comment by bowersj** [comment]
@ianrose14 I don't know if you're still interested but here's a solution I stumbled on to.

Disclaimer, I am still learning and there might be a  better approach but this is what worked for me.

Note: I am running on windows 7 node version 8.11.2

```javascript
const Tesseract = require('tesseract.js');

const imgPath = "D:\\some\\path\\to\\an\\image.PNG";

Tesseract.recognize( imgPath )
    .catch( err => console.error( err ) )
    .then( function( res ){ console.log( res ) } )
    .catch( err => console.error( err ) )
    .finally( msg => {
        // console.log( msg );
       Tesseract.terminate();
    });
```

The key is the `Tesseract.terminate();` statement on the finally event. 

Hope this helps.

On a side note, if anyone has a better approach, do share!
