### ISSUE TITLE
How to suppress console logs?

### ISSUE THREAD

**Issue by archasek** [naptha/tesseract.js#942]
**Is your feature request related to a problem? Please describe.**
Can I disable logging / debug / console output like:
```
Warning: TT: undefined function: 32
Estimating resolution as 189
Warning: decodeScan - unexpected MCU data, current marker is: ffff
```

**Describe the solution you'd like**
Option to disable logging warnings.

**Comment by Balearica** [comment]
Closing as duplicate of the discussion you opened in #941, instructions for suppressing logs are provided there.
