### ISSUE TITLE
Configuring to run from LOCALHOST

### ISSUE THREAD

**Issue by tetrahydra** [naptha/tesseract.js#95]
Hello,

I have download all the files and set them all properly, but receiving this error:

> worker.js:8474 Uncaught DataCloneError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An object could not be cloned.

I have downloaded https://github.com/naptha/tesseract.js-core and languages.

This is a working settings,

```
var defaultOptions = {
    workerPath : 'http://192.168.1.20/tesslocal/tesseract.js-master/dist/worker.js',
    corePath   : 'https://cdn.rawgit.com/naptha/tesseract.js-core/0.1.0/index.js',
    langPath   : 'http://192.168.1.20/tesslocal/lang/'
};
```

but when changed to this,

```
var defaultOptions = {
    workerPath : 'http://192.168.1.20/tesslocal/tesseract.js-master/dist/worker.js',
    corePath   : 'http://192.168.1.20/tesslocal/tesseract.js-core/index.js',
    langPath   : 'http://192.168.1.20/tesslocal/lang/'
};
```

the above error appears.

How can I solve this?

Thanks.

**Comment by krsyoung** [comment]
@tetrahydra any chance you ever figured this out?

**Comment by jeromewu** [comment]
Please check here: https://github.com/naptha/tesseract.js/blob/master/docs/local-installation.md

If you try the latest version of tesseract.js and the issue still exists, feel free to reopen the issue with more information :smile:
