### ISSUE TITLE
repo broken by design

### ISSUE THREAD

**Issue by kyle-wendling** [naptha/tesseract.js#953]
come on. you know what you did. the example are broken by default. they reference a '/dist' folder looking for tesseract.js, you know, the thing 99.9% of people are look at this repo for. and you didn't even include tesseract.js in the repo. there isn't even a dist folder. seriously.

just include in the repo please.
/dist/worker.min.js
/dist/tesseract.min.js

 I'm sure you have some reason this wasn't done initially, but trust me, but having broken examples, the cardinal sin in any repo, overrides any possible reason you're forcing people to figure out why it's broken, then figure out whatever js build system you used to compile, there's no need for this.

**Comment by Balearica** [comment]
The fact that users are required to run a build command after cloning from GitHub is a standard (near universal) practice in JavaScript development for a number of reasons, and the `npm run build` command is the same for virtually every JavaScript project (in addition to being [documented in our readme](https://github.com/naptha/tesseract.js?tab=readme-ov-file#building-static-files)).  If you look up Git repos for the top 20 JavaScript libraries globally per JSDelivr, you'll find they do things similarly (ex. [1](https://github.com/video-dev/hls.js/blob/master/demo/index.html), [2](https://github.com/videojs/video.js/blob/main/sandbox/descriptions.html.example), [3](https://github.com/nolimits4web/swiper/blob/master/demos/040-pagination-dynamic.html)).  Additionally, I am not aware of any non-JavaScript language with a build step where it is a standard practice to distribute builds in the GitHub repo.

When developing with JavaScript libraries in general, if you do not want to build the library yourself, you should download from `npm` (or use a CDN).  The released [npm version](https://www.npmjs.com/package/tesseract.js) of a package will have a `dist` directory containing the built version that can be used immediately.
