### ISSUE TITLE
Broken character not recognizable

### ISSUE THREAD

**Issue by wazidchoudhary** [naptha/tesseract.js#955]
### Discussed in https://github.com/naptha/tesseract.js/discussions/954

<div type='discussions-op-text'>

<sup>Originally posted by **wazidchoudhary** September 17, 2024</sup>
Hey guyz can someone help on extract text from ocr images of broken character like 
![downloaded_image - 2024-09-17T000722 019](https://github.com/user-attachments/assets/5ed03ac5-9c38-435a-9e72-d3706f234c0d)
![downloaded_image - 2024-09-17T003654 506](https://github.com/user-attachments/assets/4ce1f2b4-2ab2-4bc5-8933-193e88df8fda)
</div>

**Comment by wazidchoudhary** [comment]
please help I tried everything it read p as F and mismatch many characters

**Comment by Balearica** [comment]
This was already posted as discussion #954, which is the appropriate place to post it, as it is neither a bug report nor feature request.  Please do not open duplicative threads.
