### ISSUE TITLE
About traineddata...

### ISSUE THREAD

**Issue by lgcagithub** [naptha/tesseract.js#96]
I want to know how you generate the traineddata. Does it can be made by us? Or how to improve the accuracy of the recognition. For example, the Vietnamese.

**Comment by nicolas-zozol** [comment]
I would add another exemple. Is it possible to add to english some trainings about smileys. I would consider a given set of emojis and their signification ( 😀 => smile ), and the result would be 'smile'. It could be the same for game cards (poker,  hearthstone...) inside a classic english text.

**Comment by jeromewu** [comment]
Please check here for training your own trained data: https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00
