### ISSUE TITLE
Trainneddata

### ISSUE THREAD

**Issue by christangga** [naptha/tesseract.js#97]
Hi, is it possible to tesseract.js to implement this feature?

http://stackoverflow.com/questions/11681309/how-to-merge-traindata-file-in-tesseract

please help! thank you so much!

**Comment by hoffmanjon** [comment]
Did you find an answer to your question?  I am looking at the possibility of training tesseract for a specific font but not sure if I can use it with tesseract.js

**Comment by tugend** [comment]
I don't know about merging, but if you want to traning Tesseract for a specific font - you should be able to use regular Tesseract to produce training data. https://github.com/naptha/tesseract.js/issues/176

**Comment by jeromewu** [comment]
Mission completes! Check here for the example: https://github.com/naptha/tesseract.js/blob/master/docs/examples.md#with-multiple-languages-separate-by-
